### ISSUE TITLE
Font change option

### ISSUE THREAD

**Issue by mjuzikfrik** [FooSoft/yomichan#101]
Hello,

Latest update of Windows 10 has included a new Japanese font which look much better then the default one.  Do you think you could make an option to choose the font one wants to use. Example of what I'm talking about. 
![screenshot_4](https://user-images.githubusercontent.com/16630872/33428103-f105447a-d5c7-11e7-9c4a-2e8de059e18a.png)

**Comment by toasted-nutbread** [comment]
You can change the fonts by using the **Custom popup CSS** option under the "General Options" header after "Show advanced options" has been enabled. Once PR #253 has been merged, you will be able to see the style changes in real time.

I'm not sure what font is being used in that image, but you may be able to find out by inspecting element using the browser. Alternatively, it may be a font from [this list](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#japanese-supplemental-fonts).

The style you would want to add is:
```css
.expression { font-family: "FONT NAME"; }
```
