### ISSUE TITLE
Settings import not working

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1019]
Just built a new PC and am setting up yomichan again; importing settings doesn't seem to do anything. File select dialogue pops up but nothing happens after selection. Not sure if I'm doing something wrong or maybe the importer broke with a recent change? Here is my export: 
[yomichan-settings-2020-11-10-01-13-55.zip](https://github.com/FooSoft/yomichan/files/5516816/yomichan-settings-2020-11-10-01-13-55.zip)

I was on win 8.1 before and now I'm on 10, if that matters

Very much appreciated!
-Tyler

edit: should note this is with Chrome

_Originally posted by @Thermospore_

**Comment by toasted-nutbread** [comment]
There was a bug in the previous release which caused settings imports to not always work correctly. If you open up the JSON file and add the line "fieldTemplates": null, to the "anki": {...} block, that should allow it to be imported.

(Moved to a separate issue; probably should have locked the other issue since it's a placeholder)

**Comment by Thermospore** [comment]
> open up the JSON file and add the line `"fieldTemplates": null,` to the "anki": {...} block

Worked like a charm, much appreciated! <3

> (Moved to a separate issue; probably should have locked the other issue since it's a placeholder)

Ah, I take it the v2 settings page isn't public yet, then?

**Comment by toasted-nutbread** [comment]
It's "public" in that there is a pull request up with it, but it's not merged into the main branch or in a release yet. I'm hoping to get it available for beta testing soon.
