### ISSUE TITLE
Can't scroll in settings window, Chrome Canary

### ISSUE THREAD

**Issue by ghost** [FooSoft/yomichan#104]
Hi. When I reinstalled Yomichan today and tried to install the dictionaries, I noticed that I can't scroll down the settings window. See the screenshot of how it looks in Canary (very long) as opposed to how it looks in Chrome (with a scrollable scroll-bar). 

![image](https://user-images.githubusercontent.com/28154244/34275991-d4579006-e69f-11e7-8fb1-d84ead4299df.png)

Chrome:
![image](https://user-images.githubusercontent.com/28154244/34276016-e6b68cca-e69f-11e7-8978-9e86a364131b.png)

Windows 10, if that matters, just freshly installed, thus the re-configuration of Yomichan.

I never did a bug-report on github before, so if I do anything wrong, please tell me.

**Comment by aquinzi** [comment]
I can confirm this using Windows 7.

**Comment by marcodallagatta** [comment]
Can confirm this is still an issue, Windows 10, latest stable Chrome, latest extension from the Chrome store.

**Comment by toasted-nutbread** [comment]
Closing since this should hopefully no longer be an issue. Yomichan now shows settings in a standalone tab.
