### ISSUE TITLE
Collapsible Dictionaries+Words

### ISSUE THREAD

**Issue by wwly23** [FooSoft/yomichan#1051]
It would be super nice to have them. Some dictionary entries from Kenkyusha take a long time to scroll past. One might want to have collapsed J-E dictionaries by default to reveal only when the J-J definition is unclear or has too many new words.

Collapsible word entries would be cool too. First result not what you wanted? Click a button to hide instead of scrolling through several dictionary entries of a different word.

Being able to collapse right in the middle of a long entry seems important too. You may not realize how long the entry is until midway.

**Comment by wwly23** [comment]
Oh, I think it would be cool also have expandable dictionaries. Have it show only a configurable number of lines by default, and allow you to expand if you want more.

**Comment by shadiow6** [comment]
Hi I would like to know whether this function has been implemented yet or is it still being considered? I find myself avoiding dictionary with long definitions just because I hate scrolling forever to the next definition. I think this option would be really helpful to everybody. A checkbox that says "hide this dictionary on default" and having it show only the dictionary name in the result would be really nice.

**Comment by toasted-nutbread** [comment]
It has not been implemented yet, but I am considering when/how to best fit it in. User feedback helps drive what I work on (to a certain extent), so your additional comment helps boost the priority I'll have for it.

**Comment by Thermospore** [comment]
> Collapsible word entries would be cool too. First result not what you wanted? Click a button to hide instead of scrolling through several dictionary entries of a different word.
> 
> Being able to collapse right in the middle of a long entry seems important too. You may not realize how long the entry is until midway.

you can use alt+arrow key or alt+scroll wheel (by default) to jump from entry to entry

I almost always use that since I have like 15 dictionaries haha

**Comment by Ceynou** [comment]
Has "completely collapsed entry from a certain dictionary" been talked about?
Sometimes you still want to keep a bilingual dictionary in case you don't understand the definition in the monolingual one, but with the current set up you just see the definition because it's all in the first line

**Comment by Thermospore** [comment]
On mobile right now so I can't give screenshots, but here is what I do. My default profile has jmdict disabled. I have another identical profile but with jmdict enabled, and a condition set so it is used when the popup level is greater than 1 (something like that). So effectively I only see jmdict when I look up a word in a monolingual def (including the headword itself of course)

**Comment by Ceynou** [comment]
Just tried, that's smart thanks you!
