### ISSUE TITLE
Frequency Lists now "undefined"

### ISSUE THREAD

**Issue by agamemenon** [FooSoft/yomichan#1058]
Hello,

Thank you for all your hard work on Yomichan. With the new update, basic frequency lists still work fine.
For example, a frequency list with the format of ["認める","freq",714] works.

However, frequency lists that contain extra fields such as "reading" now show up as "undefined", when they would display properly before.
For example, a frequency list with the format of ["炊爨", "freq", {"reading": "すいさん", "frequency": 44019}] does not display properly anymore.

Could this issue be investigated and fixed? Thank you.

**Comment by Thermospore** [comment]
I have the same issue

![image](https://user-images.githubusercontent.com/35350819/100086017-443eb900-2df9-11eb-964d-5852897250a5.png)

**Comment by Thermospore** [comment]
Nice, thanks for the fix! I'm not too familiar with the update process; I assume Chrome will automatically update the extension at some point to reflect the change?

**Comment by toasted-nutbread** [comment]
Chrome will auto-update when a new release is out. Is this a usage impediment for either of you that would merit a patch release sooner, or would it be fine to wait until the next full release? (next full testing release ~1 week; stable ~2 weeks)

**Comment by Thermospore** [comment]
If it's not too much trouble I would appreciate a patch release :^)

**Comment by agamemenon** [comment]
Seconded for the patch release if possible 👍

**Comment by shadiow6** [comment]
> I have the same issue
> 
> ![image](https://user-images.githubusercontent.com/35350819/100086017-443eb900-2df9-11eb-964d-5852897250a5.png)

Hello, unrelated question but where did you get that wikipedia freq list ? How useful do you find it ? Can I have the download as well? Thanks

**Comment by heitorvrb** [comment]
Same issue here, waiting for patch release 🙏

**Comment by toasted-nutbread** [comment]
Fix is queued for 20.11.1.1 patch release; I believe @FooSoft has been busy recently, and I don't handle official release deployment. Apologies for any issues; I can create an unofficial temporary standalone build that you might be able to manually install depending on your browser, if that's helpful. (It would require dictionary/settings reinstallation though.)

**Comment by Thermospore** [comment]
No worries, I understand!

[Looking at the fix](https://github.com/FooSoft/yomichan/pull/1059/commits/6bcb8d801c4c8e75d9a821d6743702a1e6602c62), could I just temporarily recompile the dictionary with the field name changed?

as in change change this:
`    [
        "当流",
        "freq",
        {
            "reading": "とうりゅう",
            "frequency": 56142
        }
    ],`

to this?
`
    [
        "当流",
        "freq",
        {
            "reading": "とうりゅう",
            "frequency2": 56142
        }
    ],`

Otherwise, I assume the patch release will get posted any day now. For me it might be simpler to just keep manually looking up that freq list as needed, rather than worrying about uninstalling/reinstalling/etc

**Comment by toasted-nutbread** [comment]
The validation process will probably disallow the `frequency2` variant, so I don't think that would work.

**Comment by Thermospore** [comment]
ah, yep
`Error: Dictionary has invalid data in 'term_meta_bank_1.json' for value 'dictionary[0][2][1]', validated against 'schema.additionalItems.oneOf[0].items[2][1].items': 0 oneOf schemas matched`

**Comment by FooSoft** [comment]
Sorry for the delay! I've been drowning in emails and did not notice this earlier. Patched version has been queued for release.
