### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#106]
Firefox for Android has now also updated to WebExtensions only, so [this](https://github.com/ispedals/Rikachan-Android) doesn't work anymore. I tried to run Yomichan on my phone and it installed fine, I was able to import a dictionary but because the scanning is implemented for mouse only, I wasn't able to use it.

I tried adding `onClick` and `onTouchStart` and the corresponding `window.addEventListener` to `ext/fg/js/frontend.js`, but they didn't work for some reason. Does anybody have any ideas how to make Firefox for Android extensions listen to touch (click) events or is the problem somewhere else?

**Comment by FooSoft** [comment]
I'd definitely like to have things working on Android, but I can't even figure out how to bring up the extension settings window for Yomichan when I install it on a test android device, heh.

**Comment by siikamiika** [comment]
After installing the extension, this worked for me:
<img src="https://xmppimg.eddykk.com/upload/w1bh3jL_FS0DzT6q/oc5vcfy9TkC-fNBBysDcJQ.jpg" width="300"> <img src="https://xmppimg.eddykk.com/upload/-dmPGOtY3Na_gVhw/7qwO8iCgSxeG998nkn8AaA.jpg" width="300">

The small menu where you can toggle Yomichan on and off is at the bottom of menu under Help but it opens itself as a new tab.

**Comment by siikamiika** [comment]
Tried this again, and after 4 hours of cryptic errors:
![](https://xmppimg.eddykk.com/upload/Nu-rjSQkkvZ1JDiF/15tAPTKSRj2aCIHe3hNs7Q.jpg)
I'll try to make the changes compatible with the existing desktop browser support and send a pull request.

**Comment by FooSoft** [comment]
That looks sweet! I've wanted to have Android support for a while, so your efforts in making this happen are very much appreciated :+1:

**Comment by ignacy0109** [comment]
@siikamiika 
How are you grouping kanji-reading pairs with the same reading together?
Some setting I'm too retarded to find or a new feature not available in 1.5.1?

**Comment by siikamiika** [comment]
@ignacy0109 Should be available in 1.5.1. General Options --> Result Grouping --> Group results by main dictionary entry. If you have multiple dictionaries, set Dictionaries --> Main dictionary for merged mode to the dictionary you want to group by.

---

My Android branch is still in the same state as it was when taking that screenshot. The reason I haven't sent a pull request yet is that it interferes with normal use of the browser but I haven't figured out how to do it properly. Maybe I should add a floating button that toggles scanning mode and freezes everything but the popup until tapped again? I don't know.

Anyway, in the current state it listens to touchmove and touchend. touchmove highlights the current character (or the character nearest to the current position if there is no text under the finger, unlike search popup) and touchend searches starting from the current character. This is annoying when scrolling around a page that has lots of Japanese text because there will be unwanted touchend events on words. The advantage over Rikaichan-Android is that you can also search text in links if you move your finger before ending the touch event, making the browser not recognize the touch as a click on the link. I've also noticed that some input fields don't work when scanning is enabled even when there's no Japanese text in the input.

I've added a fix for #107 in the branch because the problem was more apparent on Android, but it could be a good idea to  send it separately because nothing's happened on the Android branch for a while.

**Comment by pierreduf** [comment]
Dear all,

I see that this issue is still so everything is not probably solved for an android working version.

But I'm event stuck at the 1st step :) _"I tried to run Yomichan on my phone and it installed fine"_,
==> not for me, I can't even install it on the most up-to-date firefox installed from the Play Store. It says that it's not available for my platform and the install button is greyed out. Any idea?

I even tried with Firefox 52 but it's the same thing.

**Comment by siikamiika** [comment]
Android support was merged to Yomichan in #160 (thank you @toasted-nutbread!), so I'll close this issue.

@pierreduf Try installing Yomichan from here: https://foosoft.net/projects/yomichan/index.html#installation The version at https://addons.mozilla.org is quite old and doesn't work with touch devices.

On a side note I wonder what happened to my screenshots in this issue :thinking:
