### ISSUE TITLE
[Anki] Adding kanji suddenly broken: cannot read property length of undefined

### ISSUE THREAD

**Issue by sschmidTU** [FooSoft/yomichan#1068]
Clicking on the plus leads to a js error and nothing happens, see below.

This used to work, now it doesn't, and i don't think i changed any settings in Yomichan.
Adding vocabulary still works, curiously.

![image](https://user-images.githubusercontent.com/33069673/100397478-2caa3f00-304a-11eb-9997-2efc5b66ce07.png)

```sh
Yomichan v20.11.1.0 has encountered a problem.
Originating URL: chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/fg/float.html?type=kanji&query=%E6%BD%B0&wildcards=off
TypeError: Cannot read property 'length' of undefined
    at DisplayFloat._getDefinitionPrimaryExpressionAndReading (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/mixed/js/display.js:1430:46)
    at DisplayFloat._createNote (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/mixed/js/display.js:1389:48)
    at DisplayFloat._addDefinition (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/mixed/js/display.js:1350:33)
    at async DisplayFloat._noteAdd (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/mixed/js/display.js:1066:28)
```
Disregard the first type error with noUiSlider, that was before using Yomichan.

My Kanji export settings are pretty simple:
![image](https://user-images.githubusercontent.com/33069673/100397775-d8a05a00-304b-11eb-988e-1169a05d7496.png)

Thanks! <3

**Comment by toasted-nutbread** [comment]
Queued for [20.11.1.1 patch release](https://github.com/FooSoft/yomichan/issues/980#issuecomment-733785189), whenever FooSoft has time.

**Comment by patoniilista** [comment]
It was working fine until a couple hours ago. 
![2021-04-21 18_33_59-Window](https://user-images.githubusercontent.com/72221896/115624037-6cf7ab80-a2d0-11eb-9200-974ab6973ec7.png)
I can't create any card at all, can only see the ones I already have in my deck.
![2021-04-21 18_37_45-Window](https://user-images.githubusercontent.com/72221896/115624296-d24b9c80-a2d0-11eb-8e78-3e6b0d01732d.png)

**Comment by toasted-nutbread** [comment]
(Migrated to #1622 since it looks like a new issue)
