### ISSUE TITLE
Yomichan popup can disappear in Firefox's fullscreen mode

### ISSUE THREAD

**Issue by kuchitsu** [FooSoft/yomichan#107]
So in Firefox's fullscreen (F11) mode you can bring up or hide the top bar (the one with tabs, etc) by moving the mouse closer of further away from it. It seems like doing that always results in the Yomichan popup disappearing. For a split second I can see it changing its position but then it vanishes. Is this possible to fix?

**Comment by siikamiika** [comment]
I can confirm this behavior. Seems like peeking the tabs fires a resize event that gets handled here:
https://github.com/FooSoft/yomichan/blob/7a6e2925bdf94cf93c858323587d24e156d8b7ac/ext/fg/js/frontend.js#L133
(if you can enable add-on debugging and install Yomichan from its `manifest.json` just comment this line out and it's fixed)

I was not able to reliably distinguish between resize events generated by actual resize and peeking tabs so it's probably best to add a setting for ignoring all resize events that include drag-resizing, toggling between maximized and floating mode and such. Some guesswork with `screen.height` vs. `window.height` (or maybe even popup size vs. `window.height/width`?) could also work.
