### ISSUE TITLE
Transferring frequency with ankiconnect

### ISSUE THREAD

**Issue by rajlego** [FooSoft/yomichan#1073]
![image](https://user-images.githubusercontent.com/5921902/100494519-cf1b0d00-3185-11eb-8420-deab3212fa79.png)
I have my cards set like this (needs a bit of messing around with still). Glossary entry results in this: 
(n, hon, JMdict (English))
teacher
master
doctor

while original yomichan looks like this:
![image](https://user-images.githubusercontent.com/5921902/100494539-1c977a00-3186-11eb-85a8-2c05ec3959fd.png)
Is there a way to make the card and have it also copy frequency (e.g. innocent corpus green number thing) into glossary?

**Comment by toasted-nutbread** [comment]
`{frequencies}` marker added in #1074 for the next release.
