### ISSUE TITLE
November 2020 Release

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1079]
https://github.com/FooSoft/yomichan/releases/tag/20.12.6.0

**Comment by FooSoft** [comment]
@toasted-nutbread sorry it has taken me forever to get to this. Work related things have mostly settled down, so I should have more cycles for Yomichan and other GitHub related things :+1: 

The settings UI in general looks pretty amazing and I love what you've done with it. I think it will be a huge visibility win for Yomichan users. Some points to consider:

* The "Show popup preview"  toggle jumps to top of the screen when enabled and returns to screen center when disabled. Not sure if it's supposed to do this or if it is a bug (I am getting this on Chromium). When expanded, there is also a lot of vertical white space inserted between the elements. We should probably have the preview contents be right below the toggle and not have the toggle jump around depending on its state. Also, would there ever be a time where the user would not want to display the preview at all?
* The link for "Top" which appears after you scroll downwards appears in an area which is already pretty busy and this make it hard to notice. I'm wondering if it would look better in bottom right corner of the screen, as there is nothing currently there and it would be easy to spot. I get that having "top" be at the top of the page makes sense, but in its current form I think a lot of people will not notice it.
* The popups (Profiles, Dictionaries, etc.) have headings which do not stand out enough IMO. I'm not sure if there's a better style to use here, but there should be something to make them stand out a little better. The popups always open in full-height which can seem to be a bit overkill if there is not a lot of info to display.
* We can probably get rid of the whole About/Donate/whatever thing. There's really not really a lot that needs to be said "about" Yomichan and considering that this is a more distributed development effort at this point, having a "donation" thing there is strange too, especially considering that project has no direct monetary expenses at this point.
* ...with that being said, maybe have some sort of "Help" or "Report a bug" or something link that sends the user to GitHub?

**Comment by toasted-nutbread** [comment]
Sounds good. For the purposes of the current release, I'll go ahead and merge the current PR and address feedback in new PRs.

I'll address your feedback more directly in #1000, which I've reserved for this purpose. I'll add info/link to the settings pages about this, and then the release changes will be ready.

**Comment by toasted-nutbread** [comment]
@FooSoft New tag/branch should be ready for testing release: https://github.com/FooSoft/yomichan/tree/20.12.6.0.

#1084 updates the settings pages with temporary info about the settings v2.

**Comment by FooSoft** [comment]
Firefox and Chrome dev builds submitted!

**Comment by toasted-nutbread** [comment]
Issues queued for patching before the full release:
#1104

**Comment by toasted-nutbread** [comment]
New release tag created for stable release, which should be ready.
https://github.com/FooSoft/yomichan/releases/tag/20.12.6.1

**Comment by FooSoft** [comment]
Shipped!

**Comment by FirionHope** [comment]
Any easy way to disable the blue coloring that got added in the latest update? I find it a bit distracting

**Comment by Pintliz** [comment]
can we have the latest version on dev stream too 🙏 
so that the test version users don't have to switch extension each time a new stable version is released

**Comment by Aridow** [comment]
Is there a way to disable the blue color on words, the blue bar on the left on selected entry, and switch to the old back/forward arrows display ? I find these changes superfluous and the new "arrows bar" less convenient

**Comment by Pintliz** [comment]
@Aridow @FirionHope 
add this line to your popup custom css
:root{--accent-color: inherit !important;}

**Comment by toasted-nutbread** [comment]
> Any easy way to disable the blue coloring that got added in the latest update? I find it a bit distracting

There are several parts with blue coloring; are you mentioning the left indicator? [image](https://user-images.githubusercontent.com/11037431/76166413-bde02b00-6134-11ea-9496-f692e9d01a5e.png)


> can we have the latest version on dev stream too 🙏
> so that the test version users won't have to switch extension each time a new stable version is released

@FooSoft I was going to mention this as well for the same reason.


> Is there a way to disable the blue color on words, the blue bar on the left on selected entry, and switch to the old back/forward arrows display ? I find these changes superfluous and the new "arrows bar" less convenient

For the blue color on words, I think this is partially a mistake on my part. This style shouldn't have been used for all display modes; only when the option **Result grouping** = *Group results by main dictionary entry*. I will fix this.

For the selection indicator, I can try some other things. So I can better judge how to address this: in your view, what do you dislike about it + what would you prefer?
I am trying to move away from an indicator that affects layout of the entry content (i.e. the old `＊`), as that sometimes causes scrolling or undesirable layout issues. I can add it back if necessary, but that's the motivation behind the change.

For the back/forward buttons, this layout has been changed in order to support more features people have requested, and to make the UI easier to use on touch-based devices. Is your disagreement related to the new positioning of the buttons, the visual style, or both?


> add this line to your popup custom css
> :root{--accent-color: inherit !important;}

This will affect other parts of the UI that use this color for other reasons, including future changes. Note that as mentioned above, the text color is a bug on my part, so I will fix that. For now, a better custom CSS rule would be the following:
```css
:root {
    --kanji-popular-text-color: var(--default-text-color) !important;
    --kanji-rare-text-color: var(--default-text-color) !important;
}
```

**Comment by Aridow** [comment]
> For the selection indicator, I can try some other things. So I can better judge how to address this: in your view, what do you dislike about it + what would you prefer?

I think it catches the eye too much (whether it be the color or the "spread" animation when the popup displays). I would prefer if we could choose to disable it, since I don't really have the need for it (I didn't use the star either, but it was unobtrusive)
> For the back/forward buttons, this layout has been changed in order to support more features people have requested, and to make the UI easier to use on touch-based devices. Is your disagreement related to the new positioning of the buttons, the visual style, or both?

The visual style don't bother me. I just think it's less convenient to have the arrows at the right and vertically. Maybe that's because the words/kanji and definitions are on the left (so my cursor was closer to the old arrows, with a mouse I found it more useful), or because on my browser the arrows are horizontally on the left so I'm more used to it

**Comment by toasted-nutbread** [comment]
Thanks for the feedback, I'll do some reworking of the design and see if I can come up with some good options.

**Comment by seanblue** [comment]
> For the blue color on words, I think this is partially a mistake on my part. This style shouldn't have been used for all display modes; only when the option Result grouping = Group results by main dictionary entry. I will fix this.

This is good to know. I use "Group results by term-reading pairs" and I'm finding the colors to be distracting. When listed individually (as is the case with this setting), showing the word in blue as well as showing the blue bar on the left side serves no purpose. Having the blue P is already sufficient to know what is popular and what isn't.

How it looks to me, for reference:
![image](https://user-images.githubusercontent.com/5884067/102694663-84bf0600-41f0-11eb-8044-51288a2e18b8.png)

**Comment by seanblue** [comment]
Regarding the back/forward style, I rarely drill into a kanji, so it probably doesn't matter *that* much to me. However, I do think the new buttons are a little too big. Maybe that's largely to make it more user friendly on touch devices, but it does take up a lot of space using my laptop screen or monitor.

I also have mixed feelings on the buttons only appearing when you first drill into a kanji. On one hand, this means more space for the main content until you actually need the back buttons. On the other hand, it's weird to me that clicking a kanji and then clicking the back button would result in the view being different from how it was originally.

By the way, what are some of the features that this design change enables?

**Comment by toasted-nutbread** [comment]
> EDIT: There was some kind of "currently selected entry" indicator before, right? I can't remember how it looked, but the new version definitely feels different and much more prominent than before.

Correct, it used to be the asterisk:
https://github.com/FooSoft/yomichan/blob/5021ed9f831a394a7145db58375a0c80994d123a/ext/mixed/img/entry-current.svg

> EDIT 2: I also noticed that the blue bar indicating that the first entry is selected does some kind of "fade in" effect when first opening the popover, which is contributing to it being distracting.

Yes, I will be looking into fixing that. The old `＊` did a similar thing, but it wasn't an animation.

> Regarding the back/forward style, I rarely drill into a kanji, so it probably doesn't matter that much to me. However, I do think the new buttons are a little too big. Maybe that's largely to make it more user friendly on touch devices, but it does take up a lot of space using my laptop screen or monitor.

I may add some sizing options as I test some other design changes.

> I also have mixed feelings on the buttons only appearing when you first drill into a kanji. On one hand, this means more space for the main content until you actually need the back buttons. On the other hand, it's weird to me that clicking a kanji and then clicking the back button would result in the view being different from how it was originally.

I will likely be adding an option to make the sidebar persistent, but in the current release, there wasn't any reason to do so. The old forward/back buttons also caused the view to be different, but maybe it was more natural when it was at the top (no layout change due to horizontal space change).

> By the way, what are some of the features that this design change enables?

One example is a button to change profiles directly in the popup, which some people have asked for.
![image](https://user-images.githubusercontent.com/11037431/102695390-07e25b00-41f5-11eb-9969-081876546183.png)

Beyond that, it just adds some additional room to add buttons if necessary. I still have to decide on how to best fit in some of the requests.

**Comment by toasted-nutbread** [comment]
Update: some changes have been made to address the feedback received so far.

* Added some options to control the display of the current entry indicator, and make it show up instantly.
  ![indicator](https://user-images.githubusercontent.com/11037431/102703105-cc698000-4238-11eb-8f22-7052ffd60cdb.gif)

* Added some options to change the location of the action bar.
  ![action-bar](https://user-images.githubusercontent.com/11037431/102703104-ca072600-4238-11eb-9a22-9bef77d7a65f.gif)

**Comment by 0x766F6964** [comment]
Maybe I'm mistaken but didn't the Yomichan search page (the one with the clipboard monitor) remove spaces between words in sentences? Was it an option or something? It was really convenient since I use that page to add cards to Anki.

I might have just copied a weird batch of sentences. Otherwise keep up the good work. This add-on is fantastic. Without it I would have to actually use the disaster that is qolibri instead of just pretending.

**Comment by Thermospore** [comment]
(For the record, I like the blue 🙂)

**Comment by toasted-nutbread** [comment]
The coloring is useful for merged mode, but not so much for other modes, since there are tags displayed by default which convey the same info. In merged mode, you need to mouseover the terms to see tags and such, hence why the coloring is helpful.

It can be enabled for all modes using custom CSS, but I'll be reverting the default behaviour to what it was previously.

**Comment by toasted-nutbread** [comment]
@FooSoft Patch release 20.12.6.2 is ready, which includes the following:

* [x] #1132
* [x] #1135
* [x] #1137
* [x] #1139
* [x] a9303197a9cd2308f2cf168b2191fe3fb1927094 (partial revert of #1044)

**Comment by FooSoft** [comment]
Got it -- shipped update to both stable and testing

**Comment by Pintliz** [comment]
![image](https://user-images.githubusercontent.com/24824399/102744510-ef10ab80-4394-11eb-865e-9c6ef3b9d726.png)
I'm having this error when trying to install the FF testing ver

**Comment by toasted-nutbread** [comment]
For Firefox, I believe you need to:
1. Open `about:config` and set `xpinstall.signatures.required` to `false`.
2. Use Firefox Beta/Developer/Nightly, not regular Firefox.

It's annoying that they made it so difficult, but I believe it's been that way for quite some time.

**Comment by Pintliz** [comment]
This is the first time this happened on my end.
I'll try the other Firefox builds
