### ISSUE TITLE
Anki integration failed to fetch on edge

### ISSUE THREAD

**Issue by elwendyr** [FooSoft/yomichan#1085]
When i try to activate anki integration it says failed to fetch, it worked a few days ago so it might be due to edge being updated.

**Comment by toasted-nutbread** [comment]
* Do you have Anki running in the background, with AnkiConnect installed?
* Can you check which version of Edge you're on? (edge://settings/help)
* Can you export your settings and share them here? (from the Yomichan settings page, at the bottom)

**Comment by elwendyr** [comment]
just restarted my computer and for some really it solved the problem, thanks.
