### ISSUE TITLE
Cloze-suffix not importing to Anki cards

### ISSUE THREAD

**Issue by Dapizzaman** [FooSoft/yomichan#1094]
I'm having trouble with cloze-suffix failing to import to Anki. Cloze-body and cloze-prefix transfer over fine, but the suffix field always ends up empty in the cards. 

I've tried uninstalling Yomichan and Ankiconnect, as well as making a new deck to import cards into without success.

Any other suggestions would be appreciated. Thank you!

**Comment by toasted-nutbread** [comment]
What version of Yomichan are you using?
What browser are you on?
Can you export and share your settings file and an example sentence that exhibits the issue?

**Comment by Dapizzaman** [comment]
I'm using 20.11.1.1 on Firefox 83.0. I see there's a new release but it seems it hasn't been updated for Firefox yet. I've attached the settings file as a .txt because Github doesn't like .json. Hopefully that doesn't break anything... Let me know if you need it uploaded a different way. I can zip it or something.

Here's an example from this page with the term bolded: https://www3.nhk.or.jp/news/easy/k10012756431000/k10012756431000.html

女性は、近所の母親に頼んで、**消毒**に使うアルコールやゴムの手袋、紙の皿、割り箸、レトルト食品を買ってきてもらいました。

And a screenshot of the resulting card in browser view:
![image](https://user-images.githubusercontent.com/13431548/101971574-4928a880-3c00-11eb-9651-d79111353c17.png)

[yomichan-settings-2020-12-12-03-21-37.txt](https://github.com/FooSoft/yomichan/files/5682418/yomichan-settings-2020-12-12-03-21-37.txt)

**Comment by toasted-nutbread** [comment]
Check your Anki card field config; one of the field names is incorrect ("clo**s**e-suffix" instead of "clo**z**e-suffix")

**Comment by Dapizzaman** [comment]
Yep, that was it. I would have never figured that out by myself. I remember realizing I misspelled it in Anki, changed the field name, but never regenerated the card config in Yomichan's settings.

Thanks very much for the help.
