### ISSUE TITLE
[Feature Request] Import & Export Settings

### ISSUE THREAD

**Issue by Pluige** [FooSoft/yomichan#112]
It would be cool if it were possible to export my current settings, so that I can use them on different devices without having to reconfigure everything (importing the dictionaries + setting up anki).
Perhaps just pointing out in the "README" where these settings are saved would be more than enough, I'll happily copy them over manually.

**Comment by siikamiika** [comment]
I'm not sure if it works so simply between different browsers (or versions!) but if you go to the search page (Alt+Insert) and write this to the browser console, you can get the settings:

```javascript
chrome.storage.local.get(null, store => console.log(store.options));
```

Importing could be done with the reverse `chrome.storage.local.set`.

Anyway, careful with those as you could break your config with them :P

**Comment by siikamiika** [comment]
Oh, and importing the dictionaries is probably best done manually but at least my Firefox saves the databases in `(profile)/storage/default/moz-extension+++<uuid>/idb/`

**Comment by FooSoft** [comment]
While it would be possible to export settings, it is not technically feasible to export dictionaries, making the whole process kind of moot.

**Comment by oudajosefu** [comment]
After more than a year later, I'd like to bring attention to this because of all the recent additions to the settings that make it way too long to have to reconfigure every time. I tried the `chrome.storage.local.get()` and `chrome.storage.local.set()` functions but they only barely reacted. I'm thinking there could be a way to export settings as file and easily import them to other browsers that you'd like to move to if something isn't working on the one you're currently using.

**Comment by toasted-nutbread** [comment]
I think this would be a useful feature as well, especially for testing, development, and setting transfers across devices. I've had this on my radar for a while now, I just haven't gotten around to it.

**Comment by Atemu** [comment]
With the recent Firefox breakage, this has also become a feature users could really use.

I could've used it multiple times while trying to figure out what was going on.

**Comment by toasted-nutbread** [comment]
The main issue that has been preventing me from implementing this is having a way to safely import valid settings without potentially causing corruption. I have recently finished some validation for options, so I can probably implement that soon. Unfortunately, it's not there when we need it, but I think this definitely motivates making this a higher priority.
