### ISSUE TITLE
Unable to export from Yomichan to anki

### ISSUE THREAD

**Issue by plug-unplug** [FooSoft/yomichan#1128]
Since yesterday I have been facing the problem of unable to export from Yomichan to anki .
The plus sign is coming Greyed out.
I have re installed anki and anki aconnect as well as Yomi - still no luck

Any suggestions?

**Comment by toasted-nutbread** [comment]
Can you export your settings and share the file here?

**Comment by stegatxins0** [comment]
I'm facing the same issue too and I found an interesting pattern.
When the first field value is empty, this feature will not work.
![]()
Example 1:
Not working: 
![](https://i.imgur.com/FCBzWpS.png)
Working:
![](https://i.imgur.com/oiZfPBb.png)
Example 2:
Not working: 
![](https://i.imgur.com/tyZTozs.png)
Working
![](https://i.imgur.com/l9MaGoX.png)

**Comment by toasted-nutbread** [comment]
It is expected to not work when the first field is empty, which I should probably clarify on the settings v2 page. The first field is used as the unique identifier that Anki uses for the card, so if it is empty, or matches something else that already exists, a new card cannot be created.

**Comment by toasted-nutbread** [comment]
Are either of you still having the issue?

**Comment by stegatxins0** [comment]
No, everything working fine. Thanks.
