### ISSUE TITLE
Frequency/tag display errors with new yomichan update (v20.12.6.1)

### ISSUE THREAD

**Issue by Thermospore** [FooSoft/yomichan#1130]
**Description**
1. Frequency lists are showing up twice:
![image](https://user-images.githubusercontent.com/35350819/102681712-42ee7b00-4170-11eb-98d3-92e1f56e857f.png)
![image](https://user-images.githubusercontent.com/35350819/102681719-4da91000-4170-11eb-88b8-28953d5f5f8c.png)

2. I don't know if this is a bug or not (or if it's even new), but it seems tags don't show up unless they are in the top dictionary entry. Here is 食べる again, but with jmdict on top:
![image](https://user-images.githubusercontent.com/35350819/102681943-f99f2b00-4171-11eb-95f1-9c53a1aad257.png)

~~3. Not sure what that `adv` in the 素早い screenshot was. It doesn't show up anymore (even with 新明解 back on top)
![image](https://user-images.githubusercontent.com/35350819/102682098-37508380-4173-11eb-95c0-6fbdaae19c9b.png)~~
edit: my bad, that was just the conjugation

**Browser version**
Google Chrome
`バージョン: 87.0.4280.88（Official Build） （64 ビット）`

**Yomichan version**
`v20.12.6.1`

**Exported settings file**
(exported from v1 settings page; haven't taken a look at v2 yet)
[yomichan-settings-2020-12-19-05-36-26.txt](https://github.com/FooSoft/yomichan/files/5718945/yomichan-settings-2020-12-19-05-36-26.txt)

Thanks for taking a look!

EDIT: Also, in case it's relevant, I created that jmdict on 9/21/2020 using yomichan import

**Comment by Thermospore** [comment]
Oh, I figured out #3, it's just the conjugation haha
![image](https://user-images.githubusercontent.com/35350819/102682673-db3c2e00-4177-11eb-890e-094e0f911290.png)

Didn't immediately recognize it since everything is a bit jumbled at the moment

**Comment by shadiow6** [comment]
Same, almost everyone I talked to also have this problem. Hope it gets fixed soon :)

**Comment by Thermospore** [comment]
> Also, why is the text blue by the way?

That's a new thing, I think to make entries with the `P` "popular term" tag stick out

**Comment by toasted-nutbread** [comment]
For anyone who is experiencing this issue, can you reproduce the problem on the search page, then open the browser's dev console (F12), and run this code:
```js
console.log(document.querySelector('.term-special-tags').innerHTML)
```
And copy what it outputs? I'm trying to reproduce, even after importing the settings file, but only one of them shows up for me (which is what _should_ be happening).

**Comment by c-ehrlich** [comment]
I'm also having this issue, here's my output for that console command.

`<div class="frequencies tag-list" data-count="1"><span class="tag" data-category="frequency" data-expression="ペン" data-reading="ペン" data-reading-is-same="true" data-dictionary="Innocent Corpus" data-frequency="7932" data-index="0"><span class="tag-inner"><span class="tag-frequency-disambiguation"><span class="tag-frequency-disambiguation-expression">ペン</span><span class="tag-frequency-disambiguation-separator"></span><span class="tag-frequency-disambiguation-reading">ペン</span></span><span class="tag-frequency-dictionary-name">Innocent Corpus</span><span class="tag-frequency-separator"></span><span class="tag-frequency-value">7932</span></span></span></div>`

When I disable the frequency list it shows up 0 times (as expected), after re-enabling it it shows up twice again.

**Comment by toasted-nutbread** [comment]
Hmm, testing with that snippet didn't help as much as I had expected. Could you (or anyone) share either:
1. The result of this command (assuming the first definition in the list exhibits the issue):
   ```js
    console.log(document.querySelector('.entry').innerHTML)
    ```
2. Save the entire page HTML (CTRL+S) and share the HTML file here.

**Comment by toasted-nutbread** [comment]
Issue is fixed and will be included in an upcoming patch release. The issue was due to an incorrect CSS selector which doesn't work in Chrome 87, but does in Chrome 89 and Firefox.

As a temporary workaround, add this custom CSS rule:
```css
:root[data-glossary-layout-mode=compact] .entry:not([data-expression-multi=true]) .term-special-tags {
    display: none;
}
```

 I will also look into the second issue mentioned in the OP.

**Comment by toasted-nutbread** [comment]
As for the second issue, I think the behaviour was always that way. #1138 updates it to include the tags from all definitions.

**Comment by Thermospore** [comment]
Awesome, thanks for the patches and the workaround!

(personally, I've since been converted to `Group related terms` mode 😈)

I guess we should leave this issue open until the patch goes through, so people can find the workaround?

**Comment by Thermospore** [comment]
Looks like the patch with #1135 is pushed through. Works great for me! And I assume #1138 will come though at some point as well, too.

Thanks!
