### ISSUE TITLE
Change color of "popular terms" (P) and show them fist in the popup list

### ISSUE THREAD

**Issue by Samuel-Castonguay** [FooSoft/yomichan#1131]
Hi there,

- Is there an option to change the color/colour of the "popular terms" (P)? The blue on dark is a little difficult to see.
- Is there a way to make "popular terms" (P) show first in the popup list?

Thank you for you hard work!

**Comment by Pintliz** [comment]
:root{
  --accent-color: ;
}
you can add this to your custom popup CSS and use it to change the color of popular terms
for example :root{--accent-color: pink}

**Comment by Samuel-Castonguay** [comment]
Thanks a lot!

**Comment by Pintliz** [comment]
try :root{--accent-color: pink !important;}

**Comment by Samuel-Castonguay** [comment]
Perfect!

Thank you for your time and for your prompt responses!

Cheers,

**Comment by toasted-nutbread** [comment]
Note that the blue coloring on popular terms is partially a bug, as described here: https://github.com/FooSoft/yomichan/issues/1079#issuecomment-748489436, so you may notice that color go away in the future. Beyond that, Pintliz's CSS for changing the main accent color should work.

**Comment by Samuel-Castonguay** [comment]
Thanks for the note!

**Comment by toasted-nutbread** [comment]
Also, forgot to mention:

> Is there a way to make "popular terms" (P) show first in the popup list?

I believe popular terms are already given an increased priority to appear before other terms, but there are other factors that apply as well, such as word length. Let me know if you have seen something that looks very wrong, or something that might be better organized in another manner (with an option).
