### ISSUE TITLE
[Feature Request] Ability to work on offline files (e.g (X)HTML)

### ISSUE THREAD

**Issue by Laurence02** [FooSoft/yomichan#114]
I currently have a few HTML files saved that I open in Chrome with your extension installed, but it seems to be unable to parse text from those files, though it grabs text from online web pages OK. 
Am I an idiot and have missed something small (therefore making this a case of user error), or would it be feasible to add this functionality (if it isn't already implemented)?
Cheers!

**Comment by FooSoft** [comment]
This works, you just have to enable an option on the extensions page for it. Check out the FAQ on the project page.
