### ISSUE TITLE
Req: add ability to turn off the animating bar

### ISSUE THREAD

**Issue by msikma** [FooSoft/yomichan#1144]
Hi there. I've been happily using Yomichan for a long time now. I'd like to request the possibility to turn off the new animating bar. I personally think it'd actually be best if there were no bar, as I'm not sure why the top item should necessarily be highlighted as if it's "active" or "selected" in some way. (Or is it?)

On a side note, I'd also appreciate the ability to turn off the blue/gray coloring of items for contrast purposes. It's just easier for me to read that way.

**Comment by toasted-nutbread** [comment]
I will be adjusting the sidebar in a patch release; it is highlighted because it is selected, there are some keyboard shortcuts which operate on the currently selected item (not used by everyone).

The coloring is a bug which will also be fixed.
