### ISSUE TITLE
Extension Option UI can't scroll under MD style extension manager

### ISSUE THREAD

**Issue by ninja33** [FooSoft/yomichan#115]
hi Foosoft:
Long time no see. 
Just for your information, dont know if your users also met same problem if they upgraded to Chrome v65 . I  already opened an ticket on bugs.chrouim.org
https://bugs.chromium.org/p/chromium/issues/detail?id=820792

Because I am not native speaker, so if your extension has same problem, maybe you know better what I am talking about and help clarify it. thanks.

**Comment by FooSoft** [comment]
Wow, that's pretty shitty. Thanks for the heads up. 

Here is my lame workaround (that required me to push a release to address this issue): 
https://github.com/FooSoft/yomichan/commit/f659702ba2f5df557e602d7b0ffb900f63288cc4

**Comment by toasted-nutbread** [comment]
Closing since the original Chrome issue should be fixed and since Yomichan now uses ```open_in_tab=true``` for the settings page.
