### ISSUE TITLE
Kanji Entry Only Shown For Split Second

### ISSUE THREAD

**Issue by mamande** [FooSoft/yomichan#1158]
**Description**
When clicking on a kanji in the entry header, it used to switch to the corresponding kanji entry. 
It was possible to return by using arrow keys at the top left. 
Now, the kanji entry is shown for some milliseconds, then the view switches back to the previous screen. 
In the hold-shift version of the entry display, it is possible to use the new arrow keys on the right to switch to the kanji entry permanently. After one click, the history has three views. The one from the beginning, the kanji entry, and again the one from the beginning. 

**Browser version**
Firefox 84.0, 64bit.
No other plugins except uBlock Origin.
Many installed dictionaries, seventeen currently. 

**Yomichan version**
20.12.6.2 and 20.12.6.1.
Still works as usual in 20.11.1.1, even after switch between the versions.

**Comment by toasted-nutbread** [comment]
Check if you have the option `Enable search when clicking glossary entries and tags` enabled on the settings v1 page, and try disabling that option to see if it's the issue.

**Comment by mamande** [comment]
Thank you for the quick reply.  Indeed, that seems to be the issue. 
Said option was enabled.  After disabling it, the issue has disappeared. 
It seems that simultaneously the kanji entry is opened and a search performed that eventually leads back to the previous result page. 
Thus, I suspect that clicking on the dash-underlined header should somehow be prevented from starting a search.

**Comment by toasted-nutbread** [comment]
Indeed, I actually fixed this issue just yesterday. #1153

**Comment by mamande** [comment]
Oh, I see. Thank you for this. I have checked that I have newest version available in the Firefox update manager before commenting.
In this case I guess that I just have to wait longer for a new version to appear for Firefox, although the fix is merged into FooSoft:master already. (Sorry, I do not yet quite understand all these processes in GitHub and beyond.)

**Comment by toasted-nutbread** [comment]
Yeah, the change hasn't been released to the store pages yet. Did you rely on having the `Enable search when clicking glossary entries and tags` option enabled?

**Comment by mamande** [comment]
I have been using this feature daily many times, but I can wait for the new release. Unless this will take very long (weeks) and there would an easy way for me to get to fixes directly on my machine; in this case I'd be happy to learn about it.

**Comment by toasted-nutbread** [comment]
As a workaround for now, you can enable scanning on popup content (`Allow scanning popup content` on the settings v2 page), but I can also try to set up a new patch release if that's not suitable for your use case.

**Comment by mamande** [comment]
Thanks for the suggestion, this does work as a workaround for me until the new regular release comes out. (Many levels of popups are quite confusing.)

**Comment by toasted-nutbread** [comment]
Forgot to comment when the release was made, but this issue should be resolved in the latest release.
