### ISSUE TITLE
[Feature Request] Assign priorities to the audio sources

### ISSUE THREAD

**Issue by erasedff** [FooSoft/yomichan#116]
Now that Yomichan has multiple audio sources available (JP101 and Jisho, and potentially more in the future), I think, if possible, it would be nice to have an option of assigning priorities to the audio sources or to add a fallback source in case main source doesn't have an audio clip for a selected word.

**Comment by toasted-nutbread** [comment]
Audio source fallbacks are now supported.
7ce54864f3fbaaeade2ebc20d80bcb084d9fa426...6208d6c93b3921ac8726140869ae71d784569b48
