### ISSUE TITLE
[Feature Request] Options to Go Back in History

### ISSUE THREAD

**Issue by mamande** [FooSoft/yomichan#1162]
The newer versions have the arrow keys in the popup at the right end instead of at the top left. 
While it looks good, it makes it quite a bit more cumbersome to go through the kanji entries for one single word/phrase, one after another, requiring to move repeatedly between the left and the right part of the window and hit the right small arrow (und not accidentally the cross) to go back in the history, be it by cursor or touch. 
Maybe shortcuts for going forward/back in the history could be added?
Or having a click on the kanji entry be equivalent to the back button. 
Although I also often use a double click in the kanji entry page to select and then copy the kanji to look it up in an external dictionary; so it would interfere with this. But double clicking right to the big kanji seems to work as well for selecting.
Maybe the kanji entry page would provide sufficient room for an additional back button? But maybe that's a bad design choice.

**Comment by toasted-nutbread** [comment]
> Maybe shortcuts for going forward/back in the history could be added?

There are keyboard shortcuts already; ALT+B, ALT+F

As far as the positioning goes, I have added some new options to control the visibility and positioning of the action bar; #1140. This allows the bar to be positioned on the top, so the forward/back buttons will be closer to the kanji.

![action-bar](https://user-images.githubusercontent.com/11037431/102703104-ca072600-4238-11eb-9a22-9bef77d7a65f.gif)

**Comment by mamande** [comment]
Thanks! I like the positioning at the top best, also asthetically.
I have not found the mentioned shortcuts in the settings; it only referred me to the Firefox addon hotkey settings, which does not list these.

**Comment by toasted-nutbread** [comment]
If you mouse over the buttons, there is a tooltip that indicates the shortcuts. They are also listed in the repo's [readme](https://github.com/FooSoft/yomichan/blob/master/README.md#keyboard-shortcuts).

There are plans to implement customizable keyboard shortcuts, so as that gets implemented, these hotkeys will be better indicated on the settings page.

**Comment by toasted-nutbread** [comment]
Customizable keyboard shortcuts are now in the latest release, closing issue.
