### ISSUE TITLE
pitch accent style not updated when part-of-speach tags are present 

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#1163]
**Description**
after the last update pitch accents are packed into one line, but when the tags are present the old style is used.
![image](https://user-images.githubusercontent.com/24824399/103066419-d3571080-45f3-11eb-91ad-00f802d3e4b7.png)

**Browser version**
84.0

**Yomichan version**

Version
20.12.6.2

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page; zip or rename the resulting file to .txt to attach to the issue.)

**Comment by toasted-nutbread** [comment]
This is actually the expected behaviour, since it can look confusing depending on how the lines are word wrapped (e.g. the tag shows up on the previous line).
