### ISSUE TITLE
In the seach page, how to activate the highligter when an unknown word is clicked?

### ISSUE THREAD

**Issue by quriousxr** [FooSoft/yomichan#1164]
Before updating the new version, when I clicked an unknown word from the text copied from the clipboard monitor, the unknown word would be highlighted. This was very convenient for my usage. Is there any way to reactivate this in the new version?

**Comment by toasted-nutbread** [comment]
There are two things which may be affecting you:
* Check the option `Select matched text` on the settings v1 page, make sure it is checked.
* Check the `Enable search when clicking glossary entries and tags` option; if it is enabled, disable it and see if that fixes the issue. Let me know if this is the problem and if you used the functionality this option provides.

**Comment by quriousxr** [comment]
I have checked:
 `Select matched text` is checked and `Enable search when clicking glossary entries and tags` is unchecked.

Before updating (word is highlighted in blue):
![before](https://user-images.githubusercontent.com/62241353/103171985-48e90800-48a4-11eb-8513-c1858cf742c4.PNG)

After updating (word is not highlighted anymore):
![after](https://user-images.githubusercontent.com/62241353/103171996-59997e00-48a4-11eb-93c4-dd3254598c8b.PNG)

Why I need this:
If the word is highlighted, I can simply press one hotkey to search the word in an external dictionary (e.g., GoldenDict) in my mother language (when I cannot get the meaning of the word in Japanese / English).

**Comment by toasted-nutbread** [comment]
1. Can you export your settings file for me to test with?
2. When you are selecting the text, are you clicking on it or using mousemove + modifier key?

**Comment by quriousxr** [comment]
1. Here is my setting file: https://drive.google.com/file/d/1D3svpI5svSabTYorcazhpal6ArjPLlnH/view?usp=sharing
2. I just left click the word

**Comment by toasted-nutbread** [comment]
Thanks, I am able to reproduce the issue on Firefox now (but not Chrome strangely). I will work on a fix.

**Comment by quriousxr** [comment]
Thanks very much for working on this.
