### ISSUE TITLE
Clicking on a Kanji in the popup results in both a normal dictionary search and a kanji dictionary search

### ISSUE THREAD

**Issue by Garbaz** [FooSoft/yomichan#1166]
**Description**

https://user-images.githubusercontent.com/13696798/103217444-e4b45b80-4918-11eb-9b12-a0b1393d08ec.mp4

When clicking on a kanji to get to it's corresponding entry in the kanji dictionary, the entry briefly flashes up, before showing the results of the search in the (normal) dictionary.
This happens independent of the "Search terms when clicking text from the results list" setting.

**Browser version**
Firefox 84.0.1 (64-bit)

**Yomichan version**
20.12.6.2 (using settings v2)

**Exported settings file**
[yomichan-settings-2020-12-28-13-25-33.txt](https://github.com/FooSoft/yomichan/files/5747425/yomichan-settings-2020-12-28-13-25-33.txt)

**Comment by toasted-nutbread** [comment]
There is a bug on the current settings v2 page where the setting for `Search terms when clicking text from the results list` doesn't work (amusingly it's only that setting...); try making sure that setting is disabled on the settings v1 page.

**Comment by toasted-nutbread** [comment]
Should be resolved with the December 2020 release.
