### ISSUE TITLE
[Bug] Add expression to anki buttons seemingly missing for some words

### ISSUE THREAD

**Issue by 2c2c** [FooSoft/yomichan#117]
https://imgur.com/a/clalH

Odd behavior that only seems to happen on my laptop.

**Comment by FooSoft** [comment]
I notice that you are moving the mouse pretty quickly -- do the buttons not pop up even if you wait for a longer time on a definition screen?

**Comment by 2c2c** [comment]
No. I notice that the icons never appear for words I already have added (even though they should, since the add by kana only option is still something I should be able to do). If that were the only case I wouldn't care-- but it does appear to happen with words I don't have added occasionally as well. Also, if the icons dont show, they wont show for all entries

Just did a reboot to see if it was a fluke thing but it's still happening

**Comment by FooSoft** [comment]
I just pushed out a new version of AnkiConnect which should address the issue you are having. Go ahead and give that a shot and let me know if that fixes the issues you are experiencing.

**Comment by 2c2c** [comment]
Yeah that caught it. thanks

**Comment by FooSoft** [comment]
Good to hear it :+1:
