### ISSUE TITLE
[Feature Request] More Cosmetic Control

### ISSUE THREAD

**Issue by anonymouse333** [FooSoft/yomichan#119]
At present, the ability to modify Yomichan's appearance is quite limited, and most of the options which are available don't allow the user much in the way of fine-tuned control, instead amounting pretty much to a choice between two presets. The only real specific control available is the adjustment of the pop-up size itself.

It would be nice if users themselves were able to modify details such as the pop-up color, the font color, which tags are visible (it would be especially nice for those of us who only use one dictionary to be able to completely hide the huge dictionary name tag which takes up so much space, rather than only hiding its duplicates within a single entry), and so on.

As for implementation, maybe it could be like the bit under the Anki Options settings where the code is revealed to the user so they can freely mess around with it. Or maybe there could just be color presets added, checkboxes for specific tags, etc.

**Comment by anonymouse333** [comment]
Some more specific options I'd like to see which I forgot to mention before:
- adjustment of font size (particularly that of the word being defined)
- allow displaying of tags as plain text, surrounded by brackets and separated by commas, instead of as icons
- option to trade furigana written above the word being defined for simple kana written to the right of it (might be wise to have an exception in the case that the definitions exceeds X number of characters*, in which case Yomichan will fall back to displaying furigana)
* where X = number of characters required for the kanji + kana string to wrap onto a second line

Intention of these options is allowing the user to trade fancy looks for reduced consumption of visual space.

**Comment by thebasser123** [comment]
I second this! The white background hurts my eyes and Kanji in the definitions from Japanese dictionaries are illegibly small!

**Comment by toasted-nutbread** [comment]
FYI: Once PR #253 is merged, there will be improved settings for adjusting the style of the popup using CSS. This doesn't cover everything mentioned in the request, but it gets a good portion of it.

**Comment by toasted-nutbread** [comment]
With the merge of #317, it is now possible to more consistently and extensively customize the CSS to change how certain elements are displayed.
