### ISSUE TITLE
December 2020 Release

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1193]
https://github.com/FooSoft/yomichan/releases/tag/20.12.31.0

@FooSoft Here's a high-level overview of the most relevant changes for you:
* Some extension pages have been updated in terms of their style and content, including:
  * `/bg/legal.html` _(style updated)_
  * `/bg/welcome.html` _(style/content updated; formerly `/bg/guide.html`)_
  * `/bg/info.html` _(new)_
  * `/bg/permissions.html` _(new)_ - also available as documentation [here](https://github.com/FooSoft/yomichan/blob/master/docs/permissions.md)

  Feel free to review what's on these pages and see if you would like any changes to be made.
* The extension now supports a build targeting [Manifest v3](https://github.com/FooSoft/yomichan/issues/455). This is pretty stable and mostly feature complete, bust I would still consider it experimental, and it should not be deployed until MV3 is mandatory on Chrome. The build file is `chrome-mv3.zip`.
* In order to support MV3, the [parse5](https://github.com/inikulin/parse5) library is included only in the MV3 build. The legal page is updated with the license information, which is technically present in all releases, but it is hidden when the file is not included.

**Comment by FooSoft** [comment]
Changes are looking awesome as always, great work :+1: 
I've pushed the testing builds for Firefox and Chrome

**Comment by toasted-nutbread** [comment]
Should be set for stable release; only issue detected so far is #1204, which is fairly minor. If other issues come up, I can include it in a patch release.

**Comment by FooSoft** [comment]
Cool! Released :+1:
