### ISSUE TITLE
[Feature Request] ignore parentheses

### ISSUE THREAD

**Issue by fedexman** [FooSoft/yomichan#1195]
Hello, i had an idea while using netflix. Often a website or netflix subtitles use parentheses instead of furigana :  e.g " なんかあったら 遠慮(えんりょ)なく言(い)いなさい "
Having an option that ignore the parentheses so we can search 言いなさい  will be useful because currently yomichan will block at 言 and willn't make the link with いんさい. 
Thank for developing this extension that I use every day ! I hope my explanation is understandable 😄

**Comment by toasted-nutbread** [comment]
I've run into this same issue before as well. I've added support for this with a new feature that supports generic pattern replacement using [regular expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) in #1199.

Pattern for your case: `[(]([^)]*)[)]`

Note that you may need to increase the value of the `Text scan length` setting to catch longer words, as the removal of characters will shorten the input.

**Comment by fedexman** [comment]
Ok thanks ! It seems very powerful even for another problems, i'll wait the next update to test it
