### ISSUE TITLE
Enabling Rikai-like behaviour should be more obvious

### ISSUE THREAD

**Issue by anonymouse333** [FooSoft/yomichan#120]
I think Yomichan should have a more clear option for enabling the Rikaichan/Rikaisama-like behaviour mode. Right now, you have to edit three separate options (uncheck "Middle mouse button scans", set "Scan modifier key" to "None", and check "Automatically hide results") which is very unintuitive. To someone who doesn't know any better, unchecking "Middle mouse button scans" and setting "Scan modifier key" to "None" sounds like it would completely disable the functionality of the add-on, and it isn't very obvious what the "Automatically hide results" option is supposed to do since the option doesn't state under what condition the results will be automatically hidden (not to mention, checking this option doesn't even do anything with the default config where the scan key is still enabled).

It would be more intuitive to have a checkbox like the "Show advanced options" one which opens up extra options when checked:
[ r ] Scan on mouse-over
----[ x ] Automatically hide results on mouse away
[ r ] Scan on key press
----[ "Scan modifier key" drop-down menu here ]
----[ x ] Also scan on middle-mouse button press

Or maybe:
[ r ] Rikai Mode (scan on mouse-over, auto-hide pop-up on mouse away)
[ r ] Scan on key press
----[ "Scan modifier key" drop-down menu here ]
----[ x ] Also scan on middle-mouse button press

( [ r ] = radio button, [ x ] = checkbox )

Containing key press and middle-mouse button press under a single tree makes a lot more sense considering that the "Middle mouse button scans" option doesn't even work when the "Scan modifier key" option is set to "None".

**Comment by nicolas-raoul** [comment]
wow I spent weeks thinking Yomichan did not work, until I randomly found this issue and realized I must press Shift.
My fault for not reading the Yomichan Usage Guide properly.

**Comment by toasted-nutbread** [comment]
This issue is probably resolved with the new settings v2 page. The settings are organized and described a bit better, and there are expandable descriptions for certain things, including _Scan modifier key_.
