### ISSUE TITLE
Kanji entries incorrectly added to Terms deck

### ISSUE THREAD

**Issue by lukeburns** [FooSoft/yomichan#1203]
**Description**
When I click to add a Kanji entry to Anki, it is added to the `Terms` deck I've assigned to Terms, rather than the `Kanji` deck to which it has been assigned. I've noticed some weird behavior trying to get the configuration to save properly with the v2 settings page, but that's not the problem here, because the exported JSON (below) is the correct configuration.

<img width="384" alt="Screen Shot 2021-01-05 at 3 39 52 PM" src="https://user-images.githubusercontent.com/189068/103711462-5b320880-4f6c-11eb-92a4-2eb6bfd2acfd.png">

<img width="404" alt="Screen Shot 2021-01-05 at 3 39 30 PM" src="https://user-images.githubusercontent.com/189068/103711478-6127e980-4f6c-11eb-858d-9261f09ae764.png">

**Browser version**
Firefox 84.0.1

**Yomichan version**
20.12.6.2

**Exported settings file**
```
{ 
...
    "terms": {
        "deck": "Terms", 
        ...
    },
    "kanji": {
        "deck": "Kanji",  
        ...
    }
... 
}
```

**Comment by toasted-nutbread** [comment]
The definition is still a "term" definition; it's just that the term is made up of a single kanji. To add a kanji definition, you need to click on the kanji character, which shows some different info about the character.

I have also fixed the other issue you mentioned about the settings v2 page.

**Comment by lukeburns** [comment]
Oh! I see. I misunderstood. Thank you.
