### ISSUE TITLE
How to delete this blue indicator in css?

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/yomichan#1210]
![image](https://user-images.githubusercontent.com/24941285/104086681-f972e680-526a-11eb-9694-6ce2f2d0a191.png)

I can't find it using elements/styles on chrome

**Comment by toasted-nutbread** [comment]
There is a setting to remove it on the settings v2 page - `Selection indicator style`.

**Comment by toasted-nutbread** [comment]
I'm assuming you resolved your issue; let me know if you need further information. Closing for now.
