### ISSUE TITLE
Audio not loading/playing

### ISSUE THREAD

**Issue by mikewiner** [FooSoft/yomichan#1216]
**Description**
Audio not working for words and no audio in anki card exports. 
![image](https://user-images.githubusercontent.com/4367703/104131965-31039080-5348-11eb-99f2-3aafda016411.png)

**Browser version**
Version 87.0.4280.141 (Official Build) (64-bit)

**Yomichan version**
20.12.31.0

**Comment by toasted-nutbread** [comment]
Same issue as #180, #280, #471, #676

JPod's fails to renew their certificate every few months. Wait a day or so and it should fix itself. As a workaround, adjust your audio settings to have a second source as a fallback.

**Comment by mikewiner** [comment]
Great thanks! Is there an API or website where I can access/listen to the jpod sound files in the meantime? Or would I have to use something like forvo?

**Comment by toasted-nutbread** [comment]
Yomichan supports these sources:
![image](https://user-images.githubusercontent.com/11037431/104133240-54323e00-5350-11eb-9023-1c43fd4ad3aa.png)

The _(Alternate)_ version usually still works, and Jisho is a separate source that should also work. They all have somewhat different word coverage, but it helps for common words.

For specifically the JPod source, I am not aware of another mirrored source.

**Comment by Rahey94** [comment]
It seems to be fixed now!
