### ISSUE TITLE
Don't show popup for arrow characters (→)

### ISSUE THREAD

**Issue by andrewguertin** [FooSoft/yomichan#1226]
**Description**
The Yomichan popup shows up for arrow characters (→ ↑ ↓ ←). This isn't useful, and frequently happens on non-japanese pages.

Presumably it's from an entry in dictionaries - it looks like it's coming from both JMdict and KireiCake. I'm not sure whether it would be better to remove the entries from the dictionaries or to make a code change in the extension.

**Browser version**
Firefox Nightly (86.0a1), although this has been happening for years

**Yomichan version**
20.12.31.0, although this has been happening for years

**Comment by D0liphin** [comment]
I don't agree with this. This is also the result of it being in a dictionary, as you say. I don't see why you can't just remove this yourself from the file.

**Comment by toasted-nutbread** [comment]
Would disabling the _Search text with non-Japanese characters_ option work for your case? Not sure if you need to scan other non-JP characters.

The behaviour you are noticing is the extension functioning as expected. If the option I mentioned doesn't work for your use case, I could look into some other options for character filtering. One of the newly added features (#1199) may also work for that, which will be in the next release.

**Comment by andrewguertin** [comment]
Either of those options work for me, and I'll be happy to use one and forget about this - but I still think that although it's working as designed, it's not a great user experience.

This would probably make a great simple default/example entry for the filter in #1199...

**Comment by toasted-nutbread** [comment]
For the future option:
Example pattern: `[→↑↓←]`. Replacement: either empty, or something that is usually not scanned, like a hyphen `-`.

> I still think that although it's working as designed, it's not a great user experience.

This is what the _Search text with non-Japanese characters_ option is for. If this would be considered a "fault" at all, it's the fault of the dictionary. https://jisho.org/search/%E2%86%92

**Comment by Thermospore** [comment]
Yea looks like JMdict removed the arrow symbols back in 2019, so it's just left behind in KireiCake

90% of what I see from KireiCake are just nearly decade old JMdict entries. Personally I don't mind, because I find it interesting to compare with the modern JMdict entries :^)

**Comment by FooSoft** [comment]
It's been so long that I don't even remember anymore, but people were going on about how KireiCake is awesome. I didn't really care one way or another, so I added a bunch of code to the importer to support loading and parsing the Rikaichan sqlite databases in order to get this data into the dictionary format that Yomichan uses... Once I was actually looking through the data though, it did just look like old JMdict... 

Maybe it would be worthwhile to subtract everything already in JMdict from KireiCake and see what's actually left.

**Comment by Thermospore** [comment]
> Maybe it would be worthwhile to subtract everything already in JMdict from KireiCake and see what's actually left.

@FooSoft Yeah I'd be interested to see this as well. I recall KireiCake coming in handy a few times, so it's probably worthwhile

Sort of off topic now, but how old of a JMdict build could I import without yomichan import breaking? I assume there have been format changes over the years

**Comment by FooSoft** [comment]
There was the crazy CSV-style file, which eventually became the pointlessly complex XML file. I think as long as you feed Yomichan-Import XML data it should work. A simpler solution would probably to get a copy of Rikaichan, open the extension and import the database file included in there through Yomichan Import.

**Comment by Thermospore** [comment]
Thanks for the info. I found a copy of the XML version from 2006 here
https://web.archive.org/web/20130401000000*/http://ftp.monash.edu.au/pub/nihongo/JMdict_e.gz
Yomichan imported it without a hitch!
![image](https://user-images.githubusercontent.com/35350819/104798544-2300a600-5774-11eb-9b95-e2603f3bbca8.png)

**Comment by FooSoft** [comment]
I just checked, apparently there were some updates to KireiCake here:
https://kireicake.com/rikaicake-online/

Can't find any actual downloads though :|

**Comment by Thermospore** [comment]
Judging from the number entries, it looks like that page doesn't have JMdict mixed in yet. Looks like you would have to get creative to pull the data though

**Comment by FooSoft** [comment]
...and it doesn't have part of speech info, so it would be impossible to deinflect terms from that dictionary

**Comment by Thermospore** [comment]
lmao you can just edit the number of entries shown to 7000 in dev mode, then copy paste right off the page
![image](https://user-images.githubusercontent.com/35350819/104801534-f1400d00-577c-11eb-88ba-7ef609e794e2.png)

**Comment by Thermospore** [comment]
same for the 2nd table at the bottom

**Comment by Thermospore** [comment]
> ...and it doesn't have part of speech info, so it would be impossible to deinflect terms from that dictionary

At a brief glance it looks like it does have pos info, but it's just dropped for nouns and phrases
![image](https://user-images.githubusercontent.com/35350819/104805445-2731c100-577e-11eb-8bb4-c44c44a4d3c8.png)

**Comment by Thermospore** [comment]
Oh right, no pos on the lower table though. I think those are all new though, so it wouldn't be a backpedal to add them. The only entries from there that show up in the current yomichan kireicake are actually just from jmdict

**Comment by toasted-nutbread** [comment]
Feature #1199 is now in the stable release, closing this issue.
