### ISSUE TITLE
Issue after porting Yomichan to MS Edge

### ISSUE THREAD

**Issue by mjuzikfrik** [FooSoft/yomichan#124]
Hello,

I'm aware that this extension is not primarily made for use with MS Edge. However if you could help me out I'd be very happy. The thing is that after loading the extension I get such an error in the options screen.

![screenshot_1](https://user-images.githubusercontent.com/16630872/39989917-937b6354-576b-11e8-9e72-9f1ee16e805e.png)
![screenshot_2](https://user-images.githubusercontent.com/16630872/39989918-939b470a-576b-11e8-8db9-a6ee1f9b7a1c.png)

**Comment by weirdalsuperfan** [comment]
Did you ever get this working? I'd be interested in knowing if there's an edge port, since edge is the go-to option for windows tablets.

**Comment by mjuzikfrik** [comment]
Unfortunately, no. I have no idea how to go about it.

**Comment by Const4ntin3** [comment]
Would also be interested to see if this will work.
1+
