### ISSUE TITLE
[Feature Request] Cycle audio sources from the popup-view

### ISSUE THREAD

**Issue by MichaelGatesDev** [FooSoft/yomichan#1249]
I found a word I wanted to lookup:

![image](https://user-images.githubusercontent.com/10709067/104818906-669cf380-57f8-11eb-9947-bf26243ffcee.png)

But I found that the audio is not correct. I believe that another audio source I have configured my have the correct audio for this word/phrase. Unfortunately, it would only be possible to check by changing my settings to try out each source as the 'top level' resource as detailed here in the config:

```
 When searching for audio, the sources are checked in order until the first valid source is found. This allows for selecting a fallback source if the first choice is not available. 
```

Ideally, there should be a way to change the source of the audio without going into the settings. Perhaps CTRL+Clicking the audio button  would go to the next source, and shift+click would go to the previous. Hovering over the icon should say which source the audio is from.

**Comment by toasted-nutbread** [comment]
Related, but not the same: #544. Could potentially handle both issues with the same change.
