### ISSUE TITLE
Issues with imposter document

### ISSUE THREAD

**Issue by Garethp** [FooSoft/yomichan#125]
Hey. So this isn't an issue with Yomichan directly, but rather with how imposter documents are handled if you happen to use the `document.js` in a project that doesn't require holding shift to get definitions. So, the main issues I've found (and solved in my own repo) are:

1. Sometimes the imposter document stays around longer than desired, and can get in the way scrolling through an input box. So I hover over a textarea to get the definition, but then when I try to scroll through that text area, the scrolling has no effect since the imposter document overlays the textarea. Solution? [Right after getting the text ranges, set the z-index be behind the original element](https://github.com/Garethp/RikaiRebuilt/blob/master/src/content/document.js#L86). Since the imposter is only really needed to get the text range, there's no point in keeping in front of the original element any longer than necessary

2. When you get the caret position for an element (easiest seen in page-sized textareas like [Editpad](https://www.editpad.org/)), it can ignore the y-axis. That is to say that if you have some Japanese text at the top of the textarea, and nothing below it, you can put your mouse under (say, 20-30 lines below) the text and it will still create a range for that text. Not so much of an issue when you need to hold down a button to enable Yomi-chan, but for me this was an issue. Solution: [Fetch the rect shape of the text range and check that the mouse is actually near that text range](https://github.com/Garethp/RikaiRebuilt/blob/master/src/content/document.js#L89)

I don't know if you see a need to bring these in to Yomichan, but I figured I may as well report the issues I found and how I solved them anyway

**Comment by Garethp** [comment]
Or, at least, the second fix works in Firefox. I suppose I need to do more testing to say it works in Chrome

**Comment by FooSoft** [comment]
These fixes make sense to me. If you could check that everything is fine in Chrome and send me a pull request, I would be happy to merge it in.

**Comment by Garethp** [comment]
I'ved moved the check for the range outside of the declaration of `document.createRangeFromPoint`, which has it working in Chrome as it does in Firefox. PR made.

Had a quick question, how do you feel your implementation of reading EPWING databases compares to what Rikaisama had? To implement EPWING support, I was planning on just wrapping the existing lookup for Rikaisama in a JSON request/response and just use it through Native Messaging, but if your implementation is much better I'm wondering how difficult it would be to have your project do lookups of a definition, as opposed to just exporting them

**Comment by FooSoft** [comment]
Why do you want to do lookups instead of loading an exported version of the data? libeb (which Rikaisama uses) allows you to query dictionary forms only and since you will have to do deinflection, it will mean doing tons and tons of queries against the library in order to get results. Having all of that go through native messaging is going to be pretty slow. Forcing people to keep a separate binary running in the background all the time is not great either. You can no longer bundle executables in extensions like back in Rikaisama days.

**Comment by Garethp** [comment]
Well, as to the why it's mostly because I thought it might be a better user experience if they don't have to download a program and use that program to export a new dictionary to import in to RikaiRebuilt. From what I gathered, part of the design philosophy of Rikaisama was ease of setup and use, so if I could have it a more one step process that would be ideal. I even played around with the idea of maybe hosting it as a separate website that had an API you could call to do the transform for you (So the user uploads their dictionary to the extension, and then the extension asks the service to do the transform in the background), but I wanted to see if this would be more doable.

I did think of some of the downsides, and here's what I have:

 * If there were a tonne of queries previously, then it must have been at acceptable enough speeds. It should be doable again
 * You don't necessarily have to use connection based messaging for Native Applications. Connectionless messaging may need to run up a new instance, but it was how Rikaisama worked and while there may be some overhead in the actual messaging clearly the overhead in constantly starting the application wasn't too much of an issue (I assume)
 * I don't see anything where you *can't* bundle the binary with extensions, you just need to then register that binary as a Native Application. So for the first time you want to use an EPWING dictionary, you'd have to download a `.reg` or `.sh` file to do the registration. I haven't tried it, but that's what I've come to after reading the documentation

Still, perhaps you're right. Maybe it is a bit of a stretch to try this as Native Messaging. Doing the import as a regular database might work, but I was at least *hoping* for a setup closer to what the original Rikaisama had.

**Comment by FooSoft** [comment]
Rikaisama unfortunately was anything but easy to use (in practice). To me, EPWING support seemed like bolted on functionality and as such these dictionaries were presented to the user completely differently. There was also no effort made to actually parse the EPWING entries to get deinflection information, and I don't even know if RikaiSama could perform deinflected searches on these dictionaries. Maybe it tried to do some crazy thing with trying to deinflect using JMDICT and then try to find those terms in EPWING? I honestly don't know.

I would be very surprised if you could bundle executables in extensions as that would appear to be a huge security concern. One thing is running sandboxed JavaScript that needs permissions to do pretty much anything... it is a whole different game if you want to run actual programs on people's machines. If I am wrong about that, you might be on to a good path to do good lookups, but you should look into this into more detail.

**Comment by Garethp** [comment]
So I didn't package it as an actual web-extension, I just tested it with `web-ext run`, but [when I tested having the binary in the same place as the extension](https://github.com/Garethp/RikaiRebuilt/tree/master/native-messaging-test), it worked fine. Admittedly I hardcoded the directory for the binary (and for OSX and Linux the manifest would need changing), but theoretically it works. Here's the main issues that would face it running properly:

1. You'd need to discover the location of the extension on runtime. Since you need to register the location of the manifest, you need to know where it is. Since it's part of the web-extension, you need to know where that is. However, since Chrome and Firefox both have documented places where they store extensions, you should be able to have your `.bat` or `.sh` file just look for the extension in that location.
2. You need to take the location you find and then edit the `manifest.json` file for OSX and Linux. Since they require absolute paths to the binary, you need to edit that in to the manifest when you find the path. Still, this can be done in the registration script you have the user run the first time around

Still, as long as your registration script is written to locate the extension and edit the `manifest.json`, the rest seems quite feasible

**Comment by toasted-nutbread** [comment]
Closing since the original issue should have been resolved with changes to the imposter element. The secondary discussion can be opened in a new issue if it is still relevant.
