### ISSUE TITLE
Not working on Youtube Firefox

### ISSUE THREAD

**Issue by andrewhu-uw** [FooSoft/yomichan#132]
First, awesome tool. I'd love to see this get more recognition.

It looks like Yomi-chan doesn't work on any of the text on Youtube videos. Using Firefox 61.

JS is not really my strongsuit, but I can fork and take a look if you have any ideas what might be causing this.

**Comment by toasted-nutbread** [comment]
As far as I can tell, the current development version of Yomichan works on both the text of Youtube and video subtitles. It's been a year+ since this issue has been opened, so maybe something's changed which fixed it. Closing for now, but please re-open if there is still an issue.
