### ISSUE TITLE
[Feature Request] Custom audio source

### ISSUE THREAD

**Issue by HelenFoster** [FooSoft/yomichan#135]
The "Audio playback source" lets us select from 3 sources, which can go down or be changed at any time. As discussed previously, Yomichan can't be responsible for hosting audio. So I'm thinking it would be useful if there was an option to specify a URL template for requesting the audio files. Then if anyone wants to run a personal audio server, they can easily redirect Yomichan to fetch the audio from there.

**Comment by toasted-nutbread** [comment]
Custom audio source URL has now been implemented.
7ce54864f3fbaaeade2ebc20d80bcb084d9fa426...6208d6c93b3921ac8726140869ae71d784569b48

**Comment by weirdalsuperfan** [comment]
How do you actually use this? I selected "Custom" from the dropdown menu, but where tf do I designate the URL?? I've been wondering this for probably a year now.

**Comment by toasted-nutbread** [comment]
Just above the "**Audio playback sources**" option, there is an option "**Custom audio source** (URL)"; you have to tick the "Show advanced options" checkbox at the top to see it.

I'm working on a settings resign, so I'll try to make that easier to use.

**Comment by OliverSpeak** [comment]
Hi. I'm new here and learning a bunch. I want to hold a website that hosts audio files for yomichan to pull from. What would be the best setup for that?

**Comment by toasted-nutbread** [comment]
@OliverSpeak I'd recommend creating a new issue since this one is old and any new comment thread is likely to easily lost.

**Comment by OliverSpeak** [comment]
@toasted-nutbread Ok will do. I didn't think my query was necessarily an "issue" which is why I commented here.

**Comment by toasted-nutbread** [comment]
A new issue is fine for that, "issues" don't necessarily have to be problems, they're often used as discussions. I suggested it as a new issue since other users may have similar questions in the future.
