### ISSUE TITLE
Data repo is missing?

### ISSUE THREAD

**Issue by HelenFoster** [FooSoft/yomichan#136]
The .gitmodules file specifies a repo on bitbucket which doesn't seem to exist.

Today when I made a new clone with `git clone --recurse-submodules` the specified folder didn't appear, but it didn't actually give any error either, so maybe I misunderstood something about how this works...

**Comment by toasted-nutbread** [comment]
.gitmodules removed in 82dd41f58010c60a856c8c364f32a7078c112f29

**Comment by FooSoft** [comment]
Yup, this was a dead reference that was not used in a long time...
