### ISSUE TITLE
[Feature Request] Separate glossaries for anki card creation if you have multiple dictionaries imported

### ISSUE THREAD

**Issue by fatslob12** [FooSoft/yomichan#1363]
I have 2 dictionaries imported into yomichan. It would be nice to have the option to be able to only have the entries from 1 dictionary added when cards are made. 

For example: I have daijirin and shinjirin imported and when I create a new card, the entries from both of those dictionaries get added automatically. It would be nice if I could set it so that only entries from daijirin get added instead. 

Another thing that would be cool: the option to select 1 specific dictionary entry that will be added to the card when you click the plus button like in this picture:
![image](https://user-images.githubusercontent.com/37754588/107371369-81574500-6ae4-11eb-87cd-f2c4c6050b6a.png)

If there's a way to do either of these things already and I just haven't figured them out please let me know. 

Thanks

**Comment by Pintliz** [comment]
For adding dictionaries separately you may refer to #1345 


As for selecting which dictionary to use for the anki card. You can make multiple profiles, each having a different anki template and different hotkey triggers.

This is the setup I’m using now to switch between sentence front and vocab front cards. For visual clarity you can also include different css for each profile.

**Comment by fatslob12** [comment]
> For adding dictionaries separately you may refer to #1345
> 
> As for selecting which dictionary to use for the anki card. You can make multiple profiles, each having a different anki template and different hotkey triggers.
> 
> This is the setup I’m using now to switch between sentence front and vocab front cards. For visual clarity you can also include different css for each profile.

Thank you, that handlebar works great. How do you switch between the card types though? I'm trying to have it so that scanning with shift uses 1 profile and scanning with ctrl uses another. I used "if modifier keys are" as a conditional for both profiles but only the manually selected active one works. I had this working a while ago when I had a setup like yourself for different card types but I can't remember how I set it up.

**Comment by toasted-nutbread** [comment]
> I'm trying to have it so that scanning with shift uses 1 profile and scanning with ctrl uses another. I used "if modifier keys are" as a conditional as shown here #816 but only the manually selected active one works. I had this working a while ago when I had a setup like yourself for different card types but I can't remember how I set it up.

You would have to set up multiple scanning inputs on the main profile, and on the secondary profile, have a condition which checks if the modifier key is pressed.

To configure multiple scanning inputs, enable the _Advanced_ toggle, then go to the _Inputs_ section and click the _Configure advanced scanning inputs…_ button. Add a new input which is the same as the primary mouse input (usually the top one in the list), then change the input to `Ctrl` for your case.

**Comment by fatslob12** [comment]
> > I'm trying to have it so that scanning with shift uses 1 profile and scanning with ctrl uses another. I used "if modifier keys are" as a conditional as shown here #816 but only the manually selected active one works. I had this working a while ago when I had a setup like yourself for different card types but I can't remember how I set it up.
> 
> You would have to set up multiple scanning inputs on the main profile, and on the secondary profile, have a condition which checks if the modifier key is pressed.
> 
> To configure multiple scanning inputs, enable the _Advanced_ toggle, then go to the _Inputs_ section and click the _Configure advanced scanning inputs…_ button. Add a new input which is the same as the primary mouse input (usually the top one in the list), then change the input to `Ctrl` for your case.
