### ISSUE TITLE
Failure to import when catalogs file is lowercase

### ISSUE THREAD

**Issue by melissaboiko** [FooSoft/yomichan#138]
Hi,

I tried to import the Kenkyūsha Japanese-English dictionary, 5th edition, on Linux.  `yomichan-import` complained about unknown dictionary format.

On a whim, I tried to symlink the dictionary's `catalogs` file in uppercase as `CATALOGS`, and then it worked.

**Comment by FooSoft** [comment]
Fixed in development version of `yomichan-version`
