### ISSUE TITLE
Kanji iteration mark

### ISSUE THREAD

**Issue by angry-flying-pig** [FooSoft/yomichan#14]
Hey, thanks for your work developing this wonderful addon.

There's a problem when searching for translations of words that contain 々. For example 人々 will return translations only for 人 (にん, ひと, じん etc.) but not ひとびと. However if I search for ひとびと in hiragana it will show the correct translation for 人々.

Also I've noticed that in the latest version the tags like (n) for nouns and (P) for common words have been removed from the translation. I really liked those since knowing if the word is a noun, adverb, adjective etc. helps with the grammar. Also knowing if it is a common word or not helps sometimes decide if to add it to the deck or not. It would be nice to have them back, hope you will reconsider.

**Comment by dayjaby** [comment]
In https://github.com/FooSoft/yomichan/pull/9#issue-86642589 I provided a solution for the 々, which is basically just replacing 々 with the kanji before. This specific code is available at https://github.com/dayjaby/yomichan/blob/be88d2f878339d9d519923c9dfaccf7b3e16173f/yomi_base/japanese/util.py

**Comment by FooSoft** [comment]
@angry-flying-pig good points... I separated the tags from the definitions for the chrome extension, but didn't add anything to display them back in this extension. I'll add that. "noma" doesn't work in the chrome extension either, so I'll fix it in both places :)

**Comment by FooSoft** [comment]
Fixed
