### ISSUE TITLE
Cannot read properties (regression)

### ISSUE THREAD

**Issue by HelenFoster** [FooSoft/yomichan#141]
Every so often while scanning across text in a web page, it pops up an error with "Error: TypeError: Cannot read property 'bottom' of undefined"

Seems 39cf302 has the issue and 68cdd7d is OK. @Garethp ?

(Using Chrome 69.0.3497.81 on Fedora)

![2018_1010_t144131](https://user-images.githubusercontent.com/5677614/46747965-72f58600-ccaa-11e8-9c0d-be159c01b7ca.png)

Also saw this one, one time:

![2018_1010_t161801](https://user-images.githubusercontent.com/5677614/46747966-738e1c80-ccaa-11e8-9f0c-8803e0609a23.png)

**Comment by toasted-nutbread** [comment]
Closing since several changes have been made which should no longer cause errors. If any errors persist, please re-open.
