### ISSUE TITLE
Bundled JMdict English dictionary last updated?

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#1414]
The definitions I see from Yomichan's JMdict dictionary are often fairly different from the ones listed on jisho.org. My understanding is that they have the same source, but obviously the Yomichan dictionary is just a snapshot in time. When's the last time the dictionary included on this github page has been updated from the source? If possible, could we get an updated version, and make updating it a once or twice per year kind of thing?

**Comment by toasted-nutbread** [comment]
January 1, as per https://github.com/FooSoft/yomichan/issues/910#issuecomment-753414070. You would have to delete and re-import the dictionary if you haven't done so.

**Comment by Thermospore** [comment]
Handy feature of JMdict I noticed recently: search `ＪＭｄｉｃｔ` (caps sensitive + full width) to see the build date
![image](https://user-images.githubusercontent.com/35350819/108151539-686e0700-7083-11eb-8372-dd20f8843778.png)

Also you can use yomichan import to build an up to date version of jmdict at your own leisure, which is what I do

**Comment by seanblue** [comment]
@Thermospore Well, my version is old enough apparently that it doesn't even have an entry for `ＪＭｄｉｃｔ`. 🙃

**Comment by Thermospore** [comment]
Huh now I wonder exactly how that entry makes its way into yomichan. You can look it up on jisho too, so I assumed it was just a plain ol jmdict entry
![image](https://user-images.githubusercontent.com/35350819/108299245-8bafb980-714a-11eb-93f9-c4fb62eb869e.png)

Even back to 2006 jmdict included the date at the top of the xml file, at least
![image](https://user-images.githubusercontent.com/35350819/108298938-370c3e80-714a-11eb-9bde-30a0d9490e4e.png)

Still there today
![image](https://user-images.githubusercontent.com/35350819/108299132-52774980-714a-11eb-81ca-3fbe4020e43e.png)

**Comment by byjtje** [comment]
> Huh now I wonder exactly how that entry makes its way into yomichan. You can look it up on jisho too, so I assumed it was just a plain ol jmdict entry

It is, they just automatically add it to the end of the JMDICT file, no need for it to be something editable in the datebase
![2021-02-18-08:04:58](https://user-images.githubusercontent.com/14181316/108318492-d4ea2280-71b7-11eb-9bbc-09f201b61c52.png)

**Comment by Thermospore** [comment]
Ahh well there ya go. Must have been added in the last couple years if it isn't even in yomichan's previous jmdict build. Thanks for the info ✌️

**Comment by byjtje** [comment]
I thank you too, never knew about that entry being in there ^^
