### ISSUE TITLE
Incorrect note ID for kanji import to Anki

### ISSUE THREAD

**Issue by masonc15** [FooSoft/yomichan#1415]
**Description**
Hello, I have recently started using Yomichan.  I often add vocab and kanji to Anki with Yomichan.  However, when I try to add kanji, the Yomichan popup says that a note is already created in Anki.  When I go to view the note in Anki, it pulls up a card from a completely unrelated deck.  For example, a search query is "nid:1276461766140" and the card with this nid is a card from another deck completely unrelated to Japanese.   I thought maybe this was a coincidence so I deleted that card and tried again but again, it pulled up a different card from that other deck.  This is frustrating since it's not letting me send kanji cards to Anki.  Any help would be appreciated.  Thanks!

**Browser version**
Chrome version 88.0.4324.150

**Yomichan version**
Yomichan 21.1.31.0

**Comment by toasted-nutbread** [comment]
Can you export your settings and share it here? I can take a look at that to see if something seems wrong there.

**Comment by masonc15** [comment]
[yomichan-settings-2021-02-17-22-34-01.txt](https://github.com/FooSoft/yomichan/files/5999033/yomichan-settings-2021-02-17-22-34-01.txt)

**Comment by toasted-nutbread** [comment]
Looks like your settings don't have the kanji cards configured. The format used for term/expression cards is separate from that of kanji cards. In the Anki card popup, change _Card type_ to _Kanji_ and then configure that.

This seems to indicate that the UI for that is unclear. I can try to rework that for improved clarity, as there are some upcoming changes related to that.

**Comment by masonc15** [comment]
Ah, I didn't realize that there was a specific Kanji card type instead of just the Terms one I was using.  That fixed it.  Thanks!
