### ISSUE TITLE
[Feature Request] Expand the hotkey feature to allow toggling specific options

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#1416]
https://github.com/FooSoft/yomichan/issues/1197#issuecomment-780350479
currently the only way to quickly switch an option on/off is through profile conditions, which is a bit difficult to setup and manage.

**Comment by toasted-nutbread** [comment]
#1571 adds a hotkey action for toggling a specific option. The `sentenceParsing.enableTerminationCharacters` path is relevant for the case you are interested in.
