### ISSUE TITLE
Text highlighting not working Learn Language with Netflix extension

### ISSUE THREAD

**Issue by mikewiner** [FooSoft/yomichan#1429]
Sorry if this is not the right place to post this or if this is a LLN issue!

**Description**
I use LLN extension and Yomichan together. Before I used to able to highlight/select the elements from the subs at the bottom. 
Now after updating something (not sure what) I can't copy the subtitles into my clipboard anymore.
Could this be a z-index issue?

![image](https://user-images.githubusercontent.com/4367703/108617340-a2247200-73e3-11eb-913f-afe7370ff6c1.png)

**Browser version**
Version 88.0.4324.182 (Official Build) (64-bit)

**Yomichan version**
21.1.31.1

**Comment by toasted-nutbread** [comment]
Can you check to make sure you have the _Select matched text_ option enabled? Does this affect other websites besides LLN? Can you manually select the text?

Additionally, if you can try doing the following, this might provide some additional info:
1. Open a video with subs and pause at a point when the subs are visible.
2. Right click on the text and click the "Inspect" option in the menu.
3. In the dev window that appears, hover over the entry that has the " == $0" at the end; make sure this corresponds to the subtitle text.
4. Switch to the "Console" tab and run this script:
   ```js
   (() => {
     const styles = window.getComputedStyle($0);
     const result = {};
     for (const v of styles) { result[v] = styles.getPropertyValue(v); }
     console.log(JSON.stringify(result, null, 4));
   })();
   ```
5. That should print a large block of text to the console. Click the "Show more" button at the end, then scroll to the bottom, the click the "Copy" button.
6. Paste the results here.

**Comment by toasted-nutbread** [comment]
No feedback for a few months, so closing; re-open if this is still an issue.
