### ISSUE TITLE
"Add expression" and "add reading" buttons often fail to appear

### ISSUE THREAD

**Issue by mattalbr** [FooSoft/yomichan#145]
The two green plus icons to add the expression/reading to Anki often fail to appear or are extremely slow to load (30+ seconds). I can't seem to find a reliable way to make them appear, and the alt + e shortcut only works when they're present. Makes trying to import to Anki really frustrating. When they're present, import works no problem.

It does seem like bringing Anki into the foreground with the card open is my best bet, so I wonder if this is really a problem with AnkiConnect or that integration?

**Comment by FooSoft** [comment]
Are you per chance running on MacOS?

**Comment by mattalbr** [comment]
Indeed I am.

**Comment by edoreld** [comment]
I'm having the same exact issue with the Add to Anki buttons taking forever to appear.

MacOs: 10.13.6
Chrome: 77.x
Latest Yomichan, Latest Anki (2.1.16), latest AnkiConnect

**Comment by toasted-nutbread** [comment]
Does this help?
https://foosoft.net/projects/anki-connect/#notes-for-mac-os-x-users

**Comment by edoreld** [comment]
Yes! I tested a bit and the icons are appearing much faster. Thanks!

**Comment by toasted-nutbread** [comment]
Yomichan now shows an information message to users who are setting up Anki on Mac which includes a link to the above URL. Hopefully this will help to keep users informed of potential issues as they set up Anki integration.

17e2f825f4620e31e89a14d72b84a733cd98a277, 437fe4e62e4326db093961fea5cfa6c3cd4c59d8

![image](https://user-images.githubusercontent.com/11037431/66723494-d21f3680-ede7-11e9-9c8a-4f58cce882b2.png)
