### ISSUE TITLE
Ability to grab words from Dropdown Lists ("select" html element)

### ISSUE THREAD

**Issue by S-ed** [FooSoft/yomichan#1460]
Sometimes I need to get a translation for words that are part of the [Select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) dropdown. Is it possible to implement this feature? (I've searched and found no answers if it's possible now)

![screenshot 1614512409](https://user-images.githubusercontent.com/3008353/109417189-99c7ca80-79d3-11eb-8881-f5fb957d06a7.png)
```

<select>
<option value="" selected="selected" style="">選択なし</option>
	<option value="1">映像（テクニカル）</option>
	<option value="2">映像（番組制作）</option>
	<option value="3">映像（CM）</option>
	<option value="4">映像（映画・ドラマ）</option>
	<option value="5">映像（VP・展示映像）</option>
	<option value="6">広告</option>
	<option value="7">出版</option>
	<option value="8">Web</option>
	<option value="9">コンシューマーゲーム</option>
	<option value="10">ソーシャルゲーム</option>
	<option value="11">ネイティブゲーム</option>
	<option value="12">遊技機</option>
	<option value="13">アミューズメント</option>
	<option value="14">カジノ</option>
	<option value="15">アニメ</option>
	<option value="16">その他</option>
	<option value="17">バイオ</option>
	<option value="18">化学・分析</option>
	<option value="19">試作・開発・評価</option>
	<option value="20">メディカル</option>
	<option value="383435099">未経験</option>
</select>
```

**Comment by toasted-nutbread** [comment]
What is the expectation for behaviour, that it scans just the text of the selected value, or shows all of the options?

**Comment by S-ed** [comment]
The selected value is preferable, as those lists may be long.

**Comment by toasted-nutbread** [comment]
Cool, that's what has been implemented. There was already some functionality to support this for other elements (`<img>` and `<button>`), so it was easy to extend to `<select>`.

I'll close this for now, as the next release has the feature (coming out soon).
