### ISSUE TITLE
Cant add add card to anki with Brave browser

### ISSUE THREAD

**Issue by Svintoz** [FooSoft/yomichan#1484]
**Description**
Yomichan does not have green buttons to add words to anki anymore. This problem only seems to occur to people that use the Brave(chromium) browser

**Browser version**
Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)

**Yomichan version**
Yomichan 21.1.31.1

![JJYK7mT](https://user-images.githubusercontent.com/80062685/110008861-8347a900-7d1c-11eb-869f-f659966b2997.jpeg)

**Comment by toasted-nutbread** [comment]
Seems to be a browser bug. Localhost requests from the background page are being blocked by the browser. Strangely, they seem to work correctly when run from a normal page, such as the settings page.
https://github.com/brave/brave-browser/issues/14473

**Comment by toasted-nutbread** [comment]
Issue seems to be fixed on the latest version of Brave.
