### ISSUE TITLE
Card "add button" has vanished and something i don't know exactly how to descrive

### ISSUE THREAD

**Issue by MrD0lph** [FooSoft/yomichan#1487]
another problem first that's most likely unrelated to my main one, for the past couple of months or so whenever i scanned a word that i knew i had already added and was even already reviewing and seeing on my usual anki sessions, i'd be able to add certain cards regardless of that and they'd show up as new cards times later, but that never bothered me too much

my main thing rn is that the add button has vanished, i can't recall when was the last time it both loaded up and greened up because well, as the time passed, i've been knowing more and more words and thus, not needing to add words as often, but i will say in the past week i was still able to add words

now it's just gone, i can scan stuff fine, i've exported my yomi settings and reinstalled the extension + dictionaries and nothing.

I can say i'm guilty of having gone through my anki tabs to look for a few things and i might have clicked on something i shouldn't have that in turn isn't matching the yomi settings and thus, not allowing me to add cards, but if i recall correctly i didn't do anything that should have had anything to do with yomi

**Comment by toasted-nutbread** [comment]
What browser are you using? Can you export your settings file and share it here?

**Comment by MrD0lph** [comment]
Yikes, yes i do use Brave indeed, glad to know that at least the source of the problem is already known, i've used it here ever since the beginning and never had any real problems with it, but i guess for now i will probably set it up on another browser as well, for the time being 
[yomichan-settings-2021-03-06-00-14-07.txt](https://github.com/FooSoft/yomichan/files/6095725/yomichan-settings-2021-03-06-00-14-07.txt)

had to change the file from json to txt just to get it here, just a mention

**Comment by toasted-nutbread** [comment]
Issue seems to be fixed on the latest version of Brave. Let me know if you continue to have issues after it has been updated.
