### ISSUE TITLE
Yomichan won't work

### ISSUE THREAD

**Issue by UnknownGlasses** [FooSoft/yomichan#149]
I just installed yomichan but when I try to use it on jp text it does absolutely nothing.

**Comment by dbqpdb** [comment]
Same. No pop-up or anything when holding shift key.

**Comment by dbqpdb** [comment]
It's working now for some reason. I don't know what is different. May have had something to do with my other plugins. I tried disabling AdBlockPlus and Ghostery, but now it runs fine with both of those active again.

**Comment by toasted-nutbread** [comment]
Closing as this issue is now a year old. Reopen or create a new issue if this is still a problem for anyone.
