### ISSUE TITLE
Anki add card button is gone.

### ISSUE THREAD

**Issue by ShadewG** [FooSoft/yomichan#1490]
**Description**
I updated my brave browser to the latest version and now the buttons add Anki card button is gone, have seen other people have the same issue with the latest version of the brave browser.

**Browser version**
Brave V1.21.73

**Yomichan version**
 Yomichan 21.1.31.1

**Comment by toasted-nutbread** [comment]
It is a browser issue. https://github.com/FooSoft/yomichan/issues/1484#issuecomment-791040478 has some info.

**Comment by toasted-nutbread** [comment]
Issue seems to be fixed on the latest version of Brave.
