### ISSUE TITLE
Yomichan Google search

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1498]
@FooSoft Just FYI: this may or may not be something you can control (not sure how Anki addon authoring works), but when searching Google for "Yomichan", the top result is for the old Anki plugin version. Google also tries showing a "featured snippets" preview of the information, which is also out of date. This may potentially be confusing to anyone who tries searching for the extension. This may be a recent "change", as I thought the top result used to be for the Chrome/Firefox store pages.

https://www.google.com/search?q=yomichan
https://ankiweb.net/shared/info/934748696

**Comment by Thermospore** [comment]
huh here is what it looks like for me (in Alaska, USA)
![image](https://user-images.githubusercontent.com/35350819/110224863-31259580-7e8c-11eb-9876-937412ac9604.png)

**Comment by toasted-nutbread** [comment]
It may vary based on location.

![image](https://user-images.githubusercontent.com/11037431/110226040-57155f00-7eb9-11eb-85f2-1a07de3b1d29.png)
