### ISSUE TITLE
OpenFailedError after Chromium Update, lookup doesn't work

### ISSUE THREAD

**Issue by ika-musuko** [FooSoft/yomichan#150]
I just updated Chrome/Chromium to Version 71.0.3578.98 and suddenly looking up words doesn't work. I navigated over to Yomichan's dictionaries setting and got the following message. 

`OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.`

I decided to purge the database, but I got this message.

`UnknownError: Internal error opening backing store for indexedDB.deleteDatabase.`

With this error message, I assume that the database was not properly purged but I tried importing one of my dictionaries back anyway just to see what would happen, but it resulted in the above "OpenFailedError".

For reference, I had jmdict_english and some custom dictionary I made but this error happens even if I just try to import jmdict_english.

**Comment by FooSoft** [comment]
What operating system are you running on? I just tried this exact version on the Linux version of Chrome and everything worked as expected. Do you have any extensions which could be interfering with Yomichan?

**Comment by ika-musuko** [comment]
Actually, after not using my Linux box for a while, this problem magically resolved itself so I will close this. Thanks.
