### ISSUE TITLE
"Search terms when clicking text from the results list" interferes with text selection

### ISSUE THREAD

**Issue by sihue** [FooSoft/yomichan#1507]
**Description**
Trying to select part of a definition with "Search terms when clicking text from the results list" enabled can be close to impossible at times. The problem is that upon releasing the mouse button, yomichan searches for the term the mouse is currently pointing at. Particularly in monolingual definitions, it may not be possible to avoid resting over searchable terms after selecting the desired passage.

**Comment by toasted-nutbread** [comment]
Fixed and uplifted to the queued release (#1472).
