### ISSUE TITLE
Yomichan not working anymore on older firefox

### ISSUE THREAD

**Issue by Pluige** [FooSoft/yomichan#1510]
**Description**
Yomichan seems to have broken entirely. Whenever I open the addon up top, the switch is in the off state. I am able to flip the switch, however, when I close the menu and immediately open it again, the switch is once again set to the off state. None of the other 3 buttons seems to do anything anymore either (cog/search/help). Here is a small video that demonstrates the problem:
https://files.catbox.moe/6eok0p.webm

I last used this addon about a week ago and it worked fine, so I assume the problem was introduced during the last update.

**Browser version**
Firefox 62.0.3 (64-bit)

**Yomichan version**
21.2.28.1

**Exported settings file**
/

**Extra maybe useless info**
For what it's worth, I also use yomichan v20.8.24.1 on Firefox 55, which still works to this day.

**Comment by toasted-nutbread** [comment]
Are you experiencing this issue on Firefox 55, or some other version?

**Comment by toasted-nutbread** [comment]
Issue should be fixed by the patch version that went out last night. Please re-open if you are still having troubles.

**Comment by Pluige** [comment]
Works as it should. Thanks a lot for the quick fix!
