### ISSUE TITLE
[Feature Request] Detect duplicates across all note types

### ISSUE THREAD

**Issue by archiif** [FooSoft/yomichan#1519]
Currently yomichan only looks for duplicates of cards with the same note type as the one chosen in the "Configure Anki card format..." menu.
It would be nice if we can have an option to look for duplicates across all note types. Or maybe a more granular option of choosing which note types to check against.

**Comment by toasted-nutbread** [comment]
This issue is technically has more to do with the way Anki detects duplicates rather than Yomichan, which uses `notetype_id` in its checks.

https://github.com/ankitects/anki/blob/248373ef304cc2b063ea652d516664dda1e47e61/rslib/src/notes/mod.rs#L532-L561

**Comment by eccentric-fellow** [comment]
Anki's card browser has a built-in "Find Duplicates" option, which can find duplicates across all note types. In that case, the different note types must a field with the same name in common.
Could Yomichan and/or Ankiconnect be made to use this built-in feature?

I may be willing to collaborate on this if wanted.


By the way, the directions in the settings says 

> "A card is considered a duplicate if the value of the **first field** matches that of **any other card**. By default, this check will include cards across all decks in a collection..."

It says nothing about note types. I got tricked into wasting time reordering fields across my note types for no reason. Can we please clarify that this limitation currently exists?
