### ISSUE TITLE
Anki integration - Windows 'Invalid Response' /Linux 'connected

### ISSUE THREAD

**Issue by Const4ntin3** [FooSoft/yomichan#152]
Hello,

I've tried to get to run Yomichan and Anki Connect on my Windows 10 machine.
I'm using Anki 2.1 and Firefox 64.0.2 (64-Bit).
I've followed the instructions and it doesn't seem to work on it although the connection to Anki is established.

Then I wanted to test if it would on my Linux (Ubuntu) machine and I have no issues there.

Am I missing something as to why it doesn't work?

**Comment by HyphenSam** [comment]
Same issue here. Latest browser version with Anki 2.1.19 on Windows 10.
Connection is established yet I'm getting an Invalid Response. Allowing the app in Windows firewall didn't do anything.

**Comment by toasted-nutbread** [comment]
@HyphenSam I think this may be the same issue we are trying to debug in #327.

**Comment by HyphenSam** [comment]
@toasted-nutbread Ah, thank you. For some reason that thread doesn't show up when doing a Google search. Maybe it's still too new.

**Comment by toasted-nutbread** [comment]
If you would like to help debug the issue, we are still trying to get someone to try out the new debugging information that was recently added. It's not in a new release yet, but https://github.com/FooSoft/yomichan/issues/327#issuecomment-576947594 describes what was added, and https://github.com/FooSoft/yomichan/issues/327#issuecomment-577255073 describes how install the latest branch.

**Comment by toasted-nutbread** [comment]
Closing as out-of-date and likely fixed. Please open a new issue if the problem persists.
