### ISSUE TITLE
[Feature Request] Furigana for full sentence in Anki

### ISSUE THREAD

**Issue by nbieck** [FooSoft/yomichan#153]
Would it be possible to have the full sentence of the highlighted term, with furigana, as an option to add to Anki cards?

My reasoning for this is that I generally want to create cloze cards for the sentence as a whole, while blanking out only a few characters at a time. While it is fine on the front for the sentence to stand on its own, it would be very helpful if the back could show the furigana for the entire sentence (or at least the kanji in it), rather than just the furigana for the originally searched term, since I am not at all confident in my ability to properly read the other kanji in the sentence correctly (or at least would like some verification).
This would also make it easier to create clozes for words in the same sentence that wasn't the originally searched term.

**Comment by psychodelicwasabi** [comment]
[This](https://ankiweb.net/shared/info/3918629684) and [this](https://ankiweb.net/shared/info/524223385) are possibly what you're looking for.

**Comment by siikamiika** [comment]
This would require parsing the entire sentence which is prone to errors. I would say this is out of scope, but I happen to know that [MeCab](https://taku910.github.io/mecab/) works quite nicely and could be used from the browser with some hassle.

I didn't try the Anki plugins that @psychodelicwasabi linked, but especially the first one looks like it could solve your problem.

**Comment by grenzionky** [comment]
I think [this](https://ankiweb.net/shared/info/278530045) is more in line to what u want

**Comment by siikamiika** [comment]
Update: support for text parsing was added to master, but it's currently used on search page only. Some things are still needed before furigana can be added to Anki sentences.

**Comment by rajlego** [comment]
Has any progress been made on this?
