### ISSUE TITLE
Accessing the first pitch accent through handlebars

### ISSUE THREAD

**Issue by archiif** [FooSoft/yomichan#1535]
Is there any way to access only the first (or 2nd, 3rd, etc.) pitch in a pitch accent list in handle bar so that it can be used in a card field? I'm not really familiar with js or handlebars, so I'm not sure how to approach this.

**Comment by toasted-nutbread** [comment]
Add:
```handlebars
{{#*inline "pitch-accent-position-first"}}
    {{~#if pitches.[0]~}}
        {{pitches.[0].pitches.[0].position}}
    {{~else~}}
        Unknown
    {{~/if~}}
{{/inline}}
```

Then use the marker `{pitch-accent-position-first}`. The data layout is a bit messy and not really documented, so as I kind of mentioned in the other issue, I'm working towards improving that at some point.

**Comment by archiif** [comment]
Thanks!
But I also came up with this while I was messing around with it:

```
{{#*inline "pitch-accent-index"}}
    {{~#if (op ">" pitchCount 0)~}}
        {{~#each pitches~}}
            {{~#each pitches~}}
                {{~#if (op "==" @index ../../index)~}}
                    {{~> pitch-accent-item-disambiguation~}}
                    {{~> pitch-accent-item format=../../format~}}
                {{~/if~}}
            {{~/each~}}
        {{~/each~}}
    {{~else~}}
        No pitch accent data
    {{~/if~}}
{{/inline}}

{{#*inline "pitch-accent-0"}}
    {{~> pitch-accent-index index=0 format='downstep-notation'~}}
{{/inline}}
```
It works during some casual testing, but do you think this is robust or are there any pitfalls of doing it this way?

**Comment by toasted-nutbread** [comment]
If you have multiple pitch accent dictionaries installed, it would give multiple results, but it's otherwise fine, just more complex.

**Comment by archiif** [comment]
Alright thanks, one more question. How do you sent the morae count to a field?

I tried something like this, but it always returns some invalid number.

```handlebars
{{#*inline "morae-counter"}}
    {{~#set "morae" (getKanaMorae reading)}}{{/set~}}
    {{~#set "morae-count" (property (get "morae") "length")}}{{/set~}}
    {{~#get "morae-count"}}{{/get}}
{{/inline}}
```

**Comment by toasted-nutbread** [comment]
```handlebars
{{#*inline "morae-counter"}}
    {{~#if merge~}}
        {{~#property (getKanaMorae definition.reading.[0]) "length"}}{{/property~}}
    {{~else~}}
        {{~#property (getKanaMorae definition.reading) "length"}}{{/property~}}
    {{~/if~}}
{{/inline}}
```

**Comment by archiif** [comment]
Thanks, it worked!
