### ISSUE TITLE
"Add anki" gets greyed out after adding 2-3 cards

### ISSUE THREAD

**Issue by Aakasan** [FooSoft/yomichan#154]
Is there any workaround for this? I always have to restart yomichan extension (turning it on and off in chrome-extensions) to get it working again. It's quite a pain

**Comment by FooSoft** [comment]
What browser and operating system are you using? If you are running on Mac OS, please make sure to turn off app nap (see https://github.com/FooSoft/anki-connect).

**Comment by Aakasan** [comment]
> What browser and operating system are you using? If you are running on Mac OS, please make sure to turn off app nap (see https://github.com/FooSoft/anki-connect).

Not sure why, but the problem just stopped on it's own. I think it happens sometimes when I tried to take definitions from the same sentence
