### ISSUE TITLE
[Feature Request] display a play button for each source (with a default one)

### ISSUE THREAD

**Issue by grospoulpe** [FooSoft/yomichan#1541]
Sometimes, for a word, there's a pronunciation mistake in a source, but it's correct in the other (or vice-versa) (eg: JapanesePod101 is wrong, JapanesePod101 (alternative) / Jisho.org is right)
Because of that, I keep the setting/Audio Sources (in another tab) always open, so I can change the first selected source (I use JapanesePod101 and alternative, Jisho.org and Text 2 Speech/Google)

That could be useful to have a button for each source (at least, two), and then be able to play different version of the same word, so I won't to go back to the setting and change the first source whenever I need it to.

I don't know if it's possible, but thanks in advance :)

PS: I tried to make an example of what that would be... (picture included)
![2021-03-18 sound button](https://user-images.githubusercontent.com/67185866/111630765-fa883d00-87f2-11eb-91c9-f3f317316f20.png)

**Comment by toasted-nutbread** [comment]
Right click/shift click on the audio button will open a menu for all audio sources. Does this satisfy your need?

**Comment by grospoulpe** [comment]
Thanks for the info, I've never noticed that (nice) functionality, I've just tested, now.
Some feedback:
- when clicking on another source, it show if the pronunciation is available or not (green / red icons) - which is good
- each time I want to play with one of the other sources, I need to make several clicks (right click, then left click) - a bit cumbersome if I want to listen several time the same source in a row. (which I do a lot, when study vocabulary)
- I thought, while typing, of another possibility: besides the Automatic kana conversion / Clipboard monitor toggle button, maybe adding a field / toggle for the playback source (like, for example, just a field where I enter the source number, so the source chosen among several could be change without going to the setting page)

**Comment by toasted-nutbread** [comment]
> each time I want to play with one of the other sources, I need to make several clicks (right click, then left click) - a bit cumbersome if I want to listen several time the same source in a row. (which I do a lot, when study vocabulary)

What if you could click entries without closing the menu, e.g. shift-click entries to play audio, but leave the menu open?

**Comment by grospoulpe** [comment]
> What if you could click entries without closing the menu, e.g. shift-click entries to play audio, but leave the menu open?
That'd be nice, because each time I left-click (or shift-left-click, but I had to change Scan modifier key to something else, in order to work) the pronunciation played and the menu closed soon after (therefore I have to right-click again to make appear again - that would be that action I'd be happy to avoid.. in order to play the same word in a row, with only one left-click at a time)
Therefore, the process would be:
1) I right-click on the button, then the menu appear
2) I left-click/shift (or whatever) left-click on the source, and the menu stay there
3) I click again on the same source, or another one in the list (currently four: Jpod, Jpod, Jisho, Text-to-speech)
That'd be nice to be able to do that.

**Comment by grospoulpe** [comment]
To complete my request, maybe the possibility to configure a shortcut for each audio source.
I mean, currently we only have the action "Play audio" available (in fact, I just discovered recently that I can configure many shortcut I may want/need) - eg: I used a lot of F2/F3/... when listening to stuff using Aegisub (F2 for playing current line, for example)
Then, I've just configure a new key for "Play audio" using F2 key (leaving alt+P alone)

So, my request would be to add those actions: Play audio/source 1,  Play audio/source 2, etc..
If that's possible, that'd be really great :)
