### ISSUE TITLE
Yomichan doesn't scan html text anymore.

### ISSUE THREAD

**Issue by Rusiann** [FooSoft/yomichan#1543]
**Description**
This version doesn't scan html text for some reason I don't know. At least version 21.1.31.1 still works. You can reproduce it from from a blank html file below though you have to copy text from clipboard. If you have an html file somewhere, you can try with it too.

[Vertical Text HTML.zip](https://github.com/FooSoft/yomichan/files/6170494/Vertical.Text.HTML.zip)
  

**Browser version**
 Microsoft Edge 89.0.774.54 

**Yomichan version**
 21.2.28.2

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page; zip or rename the resulting file to .txt to attach to the issue.)

**Comment by Thermospore** [comment]
Make sure you have permission to access local files enabled (not sure where it is on edge)

**Comment by Rusiann** [comment]
Oh. My bad. I installed this version from chrome store so I forgot to go to settings again.
