### ISSUE TITLE
Scanning: ～っちまう and が・は

### ISSUE THREAD

**Issue by sihue** [FooSoft/yomichan#1545]
Just two cases where I felt the scanning result was suboptimal:

1. ～っちまう
Searching for 狂っちまう does not return 狂う, while 狂ってしまう and 狂っちゃう do.

2. が・は
I came across the expression 肝は据わってる and wanted to look it up. As it turns out, there is an entry for 肝が据わる in 新明解国語辞典, but yomichan only finds it if you search for the exact term.
I don't know how much use you would get out of replacing は with が while scanning, but at least in this case it would have lead to a more relevant result. Still, it is very much possible that the cost would outweigh the benefit.
Furthermore,  肝が据わって fails to be resolved to 肝が据わる. This seems to be the behaviour for all such expressions (e.g. also 気がある). Is there a particular reason as to why the okurigana at the end of the search term aren't simple collapsed to the dictionary form if there is no immediate match?

**Comment by masatami** [comment]
This requires some tinkering with the settings, but you can use the "custom text replacement patterns" option in the translation section of Yomichan settings to search for both が and は, even in the middle of a phrase. It also works for the ちまう conjugation, you only need to set it up so ちまう or ちま is searched as てしまう and てしま, which in your example effectively changes the search term from 狂っちまう to 狂ってしまう.

**Comment by sihue** [comment]
This is very useful, thanks!
In the case of ちまう I suppose you could argue it deserves its spot in yomichan/ext/data/deinflect.json.
Currently it looks like this:

> "-chau": [
        {"kanaIn": "ちゃう", "kanaOut": "る", "rulesIn": ["v5"], "rulesOut": ["v1"]},
        {"kanaIn": "いじゃう", "kanaOut": "ぐ", "rulesIn": ["v5"], "rulesOut": ["v5"]},
        {"kanaIn": "いちゃう", "kanaOut": "く", "rulesIn": ["v5"], "rulesOut": ["v5"]},
        {"kanaIn": "しちゃう", "kanaOut": "す", "rulesIn": ["v5"], "rulesOut": ["v5"]},
        {"kanaIn": "っちゃう", "kanaOut": "う", "rulesIn": ["v5"], "rulesOut": ["v5"]},
        {"kanaIn": "っちゃう", "kanaOut": "く", "rulesIn": ["v5"], "rulesOut": ["v5"]},
        {"kanaIn": "っちゃう", "kanaOut": "つ", "rulesIn": ["v5"], "rulesOut": ["v5"]},
        {"kanaIn": "っちゃう", "kanaOut": "る", "rulesIn": ["v5"], "rulesOut": ["v5"]},
        {"kanaIn": "んじゃう", "kanaOut": "ぬ", "rulesIn": ["v5"], "rulesOut": ["v5"]},
        {"kanaIn": "んじゃう", "kanaOut": "ぶ", "rulesIn": ["v5"], "rulesOut": ["v5"]},
        {"kanaIn": "んじゃう", "kanaOut": "む", "rulesIn": ["v5"], "rulesOut": ["v5"]},
        {"kanaIn": "じちゃう", "kanaOut": "ずる", "rulesIn": ["v5"], "rulesOut": ["vz"]},
        {"kanaIn": "しちゃう", "kanaOut": "する", "rulesIn": ["v5"], "rulesOut": ["vs"]},
        {"kanaIn": "為ちゃう", "kanaOut": "為る", "rulesIn": ["v5"], "rulesOut": ["vs"]},
        {"kanaIn": "きちゃう", "kanaOut": "くる", "rulesIn": ["v5"], "rulesOut": ["vk"]},
        {"kanaIn": "来ちゃう", "kanaOut": "来る", "rulesIn": ["v5"], "rulesOut": ["vk"]},
        {"kanaIn": "來ちゃう", "kanaOut": "來る", "rulesIn": ["v5"], "rulesOut": ["vk"]}
    ],

But generally, the only thing that keeps me from considering this issue closed is the deinflection issue with clauses.

> Furthermore, 肝が据わって fails to be resolved to 肝が据わる.

**Comment by toasted-nutbread** [comment]
Adding ちまう is probably a good idea.

As for adding が <=> は conversions, this could cause some false positives where the character is converted when it is not being used as a particle (e.g. during kana-only or reading lookups).

> (Although it does work with JMdict. Does that have to do with the tags?)

This probably due to a mismatched part-of-speech in whatever dictionary you are using.

**Comment by sihue** [comment]
> As for adding が <=> は conversions, this could cause some false positives where the character is converted when it is not being used as a particle (e.g. during kana-only or reading lookups).

Yes, I agree.

> This probably due to a mismatched part-of-speech in whatever dictionary you are using.

Yes, it has "" instead of "v5".

Well, if a quantifier inside the dictionary is required, I don't see an easy fix for this.

By the way, an import/export function for text replacements could be convenient.
Would large replacement lists of, say, 1000 entries significantly impact performance?

**Comment by toasted-nutbread** [comment]
> Yes, it has "" instead of "v5".

Yeah, another dictionary format issue. I've noticed that a lot of the J-to-J dictionaries have similar issues, likely just do to the source data formatting not being standard or consistent. I haven't done much with dictionary generation, so I can't say whether that's fixable for the dictionaries (as you mentioned).

> Would large replacement lists of, say, 1000 entries significantly impact performance?

Most likely yes, it would add some overhead for initial text lookup generation, but I'm not sure how significant it would be.
