### ISSUE TITLE
[bug] cases where furigana distribution breaks

### ISSUE THREAD

**Issue by Thermospore** [FooSoft/yomichan#1547]
**Description**
引っ掻き傷 (ひっかききず)
![image](https://user-images.githubusercontent.com/35350819/111948631-51f90800-8a94-11eb-8b8d-a42a9d1c5ffa.png)
掻き傷 (かききず)
![image](https://user-images.githubusercontent.com/35350819/111948644-57eee900-8a94-11eb-9dd9-778724b5153b.png)
ブルータスよ、お前もか (ブルータスよおまえもか)
![image](https://user-images.githubusercontent.com/35350819/111948710-6f2dd680-8a94-11eb-9c63-25174432139f.png)

**Yomichan Info**
Extension version: Yomichan (development build) 21.2.28.2
Platform: Windows
Browser: Chrome
Language: ja
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
AnkiConnect version: Unknown (Anki not running or connected)
Installed dictionaries: JMdict, 新明解国語辞典 第五版, 大辞林３, Weblio 古語辞典, KANJIDIC (English), JMnedict, B短, B長, IC, AJ, W, 明鏡国語辞典, 故事ことわざの辞典, RikaiCake [lower], 実用日本語表現辞典, 漢字源, RikaiCake [upper], 広辞苑第六版・付属資料, 精選版　日本国語大辞典, デジタル大辞泉, 岩波国語辞典

**Comment by toasted-nutbread** [comment]
Likely not a bug, it's that the furigana distribution is ambiguous. #94, #281

**Comment by Thermospore** [comment]
Ah, I see. Thanks for the info
