### ISSUE TITLE
[Feature request] Auto scan toggle

### ISSUE THREAD

**Issue by himawri** [FooSoft/yomichan#155]
Love the extension. So much in fact that I want to convert all the ebooks I have into plain .html files just so I can use Yomichan. However, the scan activation currently requires either keyboard or mouse. If possible I would like to use it in tablet mode (with or without pen).

I think the easiest would be having another toggle button in the context menu where the user can switch on an "always scan mode". The default would be off, of course. If this is something that generally makes sense, I would be happy to create a PR.

**Comment by FooSoft** [comment]
You should already be able to accomplish what you want by setting the "Scan modifier key" to "None" on the settings page :smiley:

**Comment by himawri** [comment]
Ooh somehow it didn't occur to me that this can also solve it. So I basically can change Scan modifier key to "None" and then toggle the whole extension in the context menu. :+1: Thanks a lot!
