### ISSUE TITLE
Yomichan preview loading very slowly

### ISSUE THREAD

**Issue by Thecouncillor** [FooSoft/yomichan#1574]
Hello, I tried to use Yomichan while reading today, and I noticed when I hovered over a word, the blue bar continuously was loading, and  it took 20+ seconds for the audio to play and for me to be able to add the flashcard to Anki. I use Yomichan on chrome, and I thought it may have been chrome or my computer, but then I tried it on firefox and the same thing happened. Is this something I need to fix myself or is there an issue somewhere else? I appreciate yall making Yomichan and your hard work on updating it. Thank you so much.

**Comment by jacksonavery** [comment]
copied from my comment on a similar issue on the anki-connect page: "The issue seems to be with the JapanesePod101 audio source. Switching to "JapanesePod101 (alternate)" within Yomichan fixes the issue I was having with slower load times."

**Comment by toasted-nutbread** [comment]
Yeah, it's likely just a slow connection to the audio server. You can verify by opening the browser dev tools (F12) and going to the _Network_ tab to see how long the request takes when playing an audio clip. I'm seeing some connection timeouts for terms which don't have an audio clip.

**Comment by Thecouncillor** [comment]
> copied from my comment on a similar issue on the anki-connect page: "The issue seems to be with the JapanesePod101 audio source. Switching to "JapanesePod101 (alternate)" within Yomichan fixes the issue I was having with slower load times."

Thank you! It seems to fix most of the issues. I think there are a few that still load slowly, but those are the ones without any audio, but it us not a big deal. I can still add most cards with audio now, and I'll just wait until the others get fixed.

**Comment by tvvoty** [comment]
Switching to alternative worked for a while but now it seems to not load as well.

**Comment by Thecouncillor** [comment]
Everything is now normal for me at least. Thanks so much yall.
