### ISSUE TITLE
enable second dictionary only on scan within pop up (pop in pop up)

### ISSUE THREAD

**Issue by elwendyr** [FooSoft/yomichan#1594]
Before i think you could do that (and have only a j-j dictionary in the first pop-up, then look up a word within the pop up and only have the english dictionary in the second pop up) but it doesnt seem to be an option anymore.

**Comment by toasted-nutbread** [comment]
You have to set up a second profile with a condition of `depth > 0` or similar.

**Comment by elwendyr** [comment]
Thanks, it worked.
