### ISSUE TITLE
Yomichan No longer opens with search bar already selected

### ISSUE THREAD

**Issue by Jirachi145** [FooSoft/yomichan#1595]
As of a few weeks ago, yomichan now has an incredibly irritating bug where, about 75% of the time, opens without the search bar automatically selected, e.g. "type-able". This is tedious, as opening the dictionary and typing in a phrase now will simply not appear as the search bar was not selected by default, therefore wasting whatever was typed in. The way it used to work would be ideal (where one can start typing in a keyword as soon as yomichan opens, without having to click on the search bar)

**Comment by toasted-nutbread** [comment]
Browser?

**Comment by Jirachi145** [comment]
Oh my bad, I'm on the current Google Chrome, here's my settings 
[yomichan-settings-2021-04-07-01-54-58.txt](https://github.com/FooSoft/yomichan/files/6268480/yomichan-settings-2021-04-07-01-54-58.txt)

**Comment by toasted-nutbread** [comment]
When you are opening the settings page, are you opening it via the Yomichan extension button on the browser bar? And are you getting this issue when it's opening a new search tab?

**Comment by Jirachi145** [comment]
Yes, that's how I open the settings page. And yes, it's when i open a new search tab and go to type in it (both ways, using the shortcut and directly clicking the magnifying glass icon in the extension button. I also checked and no other plugins are active on the page.
