### ISSUE TITLE
[feature request] Display frequency ranks for words

### ISSUE THREAD

**Issue by denyeo** [FooSoft/yomichan#16]
(This one's a nice-to-have)
One thing I miss from Rikaisama is the frequency rank that it can output for each word. This helps me decide whether I should export the definition to Anki (I tend not to export uncommon words). Maybe Yomichan could potentially consider displaying this in the future, though the work might be slightly involved. [Rikaisama uses the 5,000+ novel (Innocent?) corpus](http://rikaisama.sourceforge.net/), while [Aedict3 uses the Kamermans and Matsushita frequency lists](https://github.com/mvysny/aedict/issues/539).

Yomichan already displays frequency tags like P, news, ichi, etc. Those are useful and I always export words with those tags to Anki. But most words don't have them, so having specific frequency ranks would be helpful for more advanced learners. For example, I now add words from Aedict3 when they're in the top 20,000 by Matsushita rank.

**Comment by FooSoft** [comment]
Fixed
