### ISSUE TITLE
Disable auto-conversion from katakana to hiragana in the search page

### ISSUE THREAD

**Issue by quriousxr** [FooSoft/yomichan#1602]
How can I disable the auto-conversion from katakana to Hiragana in the search page?

![image](https://user-images.githubusercontent.com/62241353/114118578-5d6d7f80-992c-11eb-9cfc-086cc4e57aea.png)

I know I can disable it in the `Convert katakana to hiragana` field (instead of using both variants) but then I won't able to find the word's meaning.

![image](https://user-images.githubusercontent.com/62241353/114118934-0025fe00-992d-11eb-8239-aaa8aa872481.png)

It works fine in an older version of yomichan:

![image](https://user-images.githubusercontent.com/62241353/114119133-6ca0fd00-992d-11eb-960b-b02b94f864dd.png)

**Comment by Thermospore** [comment]
This bug got fixed in #1532 !

it is in the testing release currently

**Comment by quriousxr** [comment]
Great. Thanks very much.
