### ISSUE TITLE
"Sentence" field only works for the first kanji

### ISSUE THREAD

**Issue by oeeq** [FooSoft/yomichan#162]
1. Select a word with multiple kanjis
2. Add a word to the "Terms" deck (click [+] button)
3. Click to the first kanji, 3.1. Add it to the "Kanji" deck
4. Click "Source term" to get back
5. Click to the second kanji, 5.1. Add it to the "Kanji" deck
Look at the anki note of the second kanji, you'll see the field that gets filled with "sentence" variable is blank.

**Comment by oeeq** [comment]
Obviously, the workaround is to avoid using "Source term" button. Reopen the popup if want to add another kanji of the same word to the anki deck.

**Comment by toasted-nutbread** [comment]
Fixed in cb9f9b585a802c7b8dfb5689d326e7482f5ff2db.
