### ISSUE TITLE
It was working fine until a couple hours ago.

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1622]
It was working fine until a couple hours ago. 
![2021-04-21 18_33_59-Window](https://user-images.githubusercontent.com/72221896/115624037-6cf7ab80-a2d0-11eb-9200-974ab6973ec7.png)
I can't create any card at all, can only see the ones I already have in my deck.
![2021-04-21 18_37_45-Window](https://user-images.githubusercontent.com/72221896/115624296-d24b9c80-a2d0-11eb-8e78-3e6b0d01732d.png)

_Originally posted by @patoniilista in https://github.com/FooSoft/yomichan/issues/1068#issuecomment-824374381_

**Comment by toasted-nutbread** [comment]
@patoniilista Can you share an export of your settings file?

**Comment by patoniilista** [comment]
Sure. 
[yomichan-settings-2021-04-21-21-24-39.zip](https://github.com/FooSoft/yomichan/files/6354108/yomichan-settings-2021-04-21-21-24-39.zip)

**Comment by toasted-nutbread** [comment]
I think I found the issue causing the error, but that error shouldn't have been preventing Anki cards from being generated. The error would be caused when you scanned non-Japanese text (e.g. English), but scanning Japanese text should have been fine. If you are having issues with the Anki buttons showing up as gray, check the settings page and your Anki fields, make sure there are no errors showing up and that the model/deck is valid (while Anki is running).

**Comment by patoniilista** [comment]
Found the problem: for some reason the card model had an empty space at the end. Removed it and it's working again.

**Comment by toasted-nutbread** [comment]
Cool; another user had a similar issue recently, so I've improved the display of the model/deck dropdowns to indicate when they are invalid: #1611. Thanks for noticing the other (unrelated) error as well.
