### ISSUE TITLE
[Feature Proposal] GiNZA integration?

### ISSUE THREAD

**Issue by ribbanya** [FooSoft/yomichan#1633]
**GiNZA**<sup>[[1]](https://megagon.ai/projects/ginza-install-a-japanese-nlp-library-in-one-step/)[[2]](https://github.com/megagonlabs/ginza/blob/develop/README.md#ginza-nlp-library)</sup> is an open-source Japanese parser, similar to MeCab, but uses natural language processing.

According to the [readme](https://github.com/megagonlabs/ginza/blob/develop/README.md#2-execute-ginza-from-command-line), "`ginzame` command provides tokenization function like [MeCab](https://taku910.github.io/mecab/). The output format of `ginzame` is almost same as `mecab`, but the last `pronounciation` field is always '*'."

If I were to write a feature integrating GiNZA similar to the [MeCab Installer](https://github.com/siikamiika/yomichan-mecab-installer), would a pull request be considered?

**Comment by toasted-nutbread** [comment]
Sure, the MeCab stuff can probably be used as a template to a certain extent (although note that it doesn't support installing on all types of browsers)

**Comment by ribbanya** [comment]
Cool, thanks for the response. Will open a new PR when I complete it.
