### ISSUE TITLE
[Feature Request] Multiple custom audio sources

### ISSUE THREAD

**Issue by archiif** [FooSoft/yomichan#1634]
Having multiple custom audio sources would make things so much more flexible.

For example, if you are using multiple audio hosts, you could bundle them together and serve them through a single Python server, but that means you need to query all of those hosts all at once which makes things slow at the first load.

But if Yomichan allows multiple custom audio sources, you can split them up and allow them to load incrementally.

**Comment by toasted-nutbread** [comment]
I agree this makes sense, and I've looked into doing it multiple times, but haven't gotten around to it yet. I'll see if I can get to it.
