### ISSUE TITLE
April 2021 Release

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1642]
https://github.com/FooSoft/yomichan/releases/tag/21.4.30.1

@FooSoft 

### General
* [x] Create [release tag](https://github.com/FooSoft/yomichan/tree/21.4.30.1).
* [x] Create [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.4.30.1).

### Testing
* [x] Update Chrome testing release.
* [x] Update Firefox testing release.
* [x] Update Firefox [updates.json](https://github.com/FooSoft/foosoft.github.io/blob/master/projects/yomichan/dl/updates.json) and [verify](https://foosoft.net/projects/yomichan/dl/updates.json).
* [x] Upload testing builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.4.30.1).

### Stable
* [x] Update Chrome stable release.
* [x] Update Firefox stable release.
* [x] Upload stable builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.4.30.1).

### Issues to address before stable
* [x] #1650
* [x] #1651
* [x] #1653
* [x] #1654

**Comment by FooSoft** [comment]
Tested release shipped!

**Comment by Thermospore** [comment]
took a while to notice this (was busy with finals) but it seems the grouping in merged mode got broken at some point. Seems some dictionaries are unaffected
![image](https://user-images.githubusercontent.com/35350819/117539627-f9d08380-afb7-11eb-898a-e0b357b5875d.png)

another example
![image](https://user-images.githubusercontent.com/35350819/117539712-5895fd00-afb8-11eb-8a62-1a6c728c29fe.png)

**Comment by toasted-nutbread** [comment]
Seems to be related to the sequence info of the ungrouped dictionary entries, where each entry has a unique index. Improved behaviour in #1653 so that they are all grouped together, regardless of sequence.

**Comment by toasted-nutbread** [comment]
@FooSoft fixed some small issues and updated the OP to 21.4.30.1, which is probably ready for stable.

**Comment by FooSoft** [comment]
Sweet! 

Updated testing and stable releases. One small  problem was that I forgot to check to see that the version was bumped to 21.4.30.1, so Chrome stable is going to get this as 21.4.30.0. Annoyingly, I'm not allowed to resubmit while the previous submission is in review. 

Other than the version number everything else should be the same, it's just worth remembering that 21.4.30.0 for Chrome is actually 21.4.30.1. Firefox makes this update process a lot simpler, so there was not a similar problem there.

**Comment by toasted-nutbread** [comment]
Oops my bad, I did forget to update the version after cherry picking. Maybe I should see if there's a better way to notify that the version doesn't match.

**Comment by FooSoft** [comment]
Maybe we can just check what the latest tag is and plug that into the version fields? This would make it so that there is one source of truth for what version we're on.

**Comment by toasted-nutbread** [comment]
## Patch release 21.4.30.2

@FooSoft This time the version is actually updated properly; I'll look into a way of auto-filling the version based on git tags, but for now, I've at least added a task to the checklist.

https://github.com/FooSoft/yomichan/releases/tag/21.4.30.2

### General
* [x] Create [release tag](https://github.com/FooSoft/yomichan/tree/21.4.30.2).
* [x] Create [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.4.30.2).
* [x] Ensure the version is updated in the [manifest](https://github.com/FooSoft/yomichan/blob/21.4.30.2/ext/manifest.json).

### Testing
* [ ] Update Chrome testing release.
* [ ] Update Firefox testing release.
* [ ] Update Firefox [updates.json](https://github.com/FooSoft/foosoft.github.io/blob/master/projects/yomichan/dl/updates.json) and [verify](https://foosoft.net/projects/yomichan/dl/updates.json).
* [ ] Upload testing builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.4.30.2).

### Stable
* [ ] Update Chrome stable release.
* [ ] Update Firefox stable release.
* [ ] Upload stable builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.4.30.2).

**Comment by FooSoft** [comment]
Shipped!
