### ISSUE TITLE
[Feature Request] anki: some fields should be empty if adding from Yomichan Search

### ISSUE THREAD

**Issue by cyphar** [FooSoft/yomichan#1643]
I'd like to have my Anki cards contain the source of the text I'm creating a card from (this is useful if I want to go back and get an image or something to add to my card) as well as a screenshot of the page. `{url}` and `{screenshot}` solve this problem if you're browsing regular webpages and that is the primary method you use to mine sentences.

However I use Yomichan Search pretty frequently (with [mpvacious](https://github.com/Ajatt-Tools/mpvacious)) with the clipboard monitor to let me make cards from video subtitles. Thus if I use `{url}` or `{screenshot}` on my cards, a bunch of my cards now have screenshots and URLs from the Yomichan Search window -- which isn't very useful and also needlessly wastes space (both visually as well a storage space).

I have worked around this by having some JS on my cards which hides the screenshot and URL if the URL has the `moz-extension://` protocol -- but this is far from ideal.

Would it be possible to make fields like `{url}`, `{title}`, `{screenshot}`, and the like empty if you are adding a card outside of the pop-up Yomichan dictionary?

<details>
<summary>For those interested, here's the JS I added to my cards.</summary>

You need to wrap `{screenshot}` and `{url}` to be `<span id="yomichan-screenshot">{screenshot}</span>` and `<p id="yomichan-source">{url}</p>` respectively.

```html
<script>
	function hideBadSource() {
		const yomi_source = document.getElementById("yomichan-source");
		if (yomi_source === null)
			return;
		var any_valid = false;
		for (link of yomi_source.getElementsByTagName("a")) {
			try {
				let url = new URL(link.href);
				if (url.protocol === "moz-extension:")
					link.style["display"] = "none";
				else
					any_valid = true;
			} catch {
				// ...
			}
		}
		if (!any_valid) {
			yomi_source.style["display"] = "none";
			const yomi_screenshot = document.getElementById("yomichan-screenshot");
			if (yomi_screenshot !== null)
				yomi_screenshot.style["display"] = "none";
		}
	}
	document.addEventListener('DOMContentLoaded', hideBadSource(), false);
</script>
``` 

</details>

**Comment by toasted-nutbread** [comment]
You can set up a second profile and add a condition so that it is automatically used on the settings page, then have that second profile have empty url/title/screenshot

**Comment by cyphar** [comment]
Oh I didn't know you could do that with profiles. I just set it up and it seems to work pretty well. Thanks and closing.
