### ISSUE TITLE
[Feature Request] Add support for inline images

### ISSUE THREAD

**Issue by ttu-ttu** [FooSoft/yomichan#1652]
There are times when the dictionary makes use of inline image when describing the definition of a word

Case 1:
When it involves 外字 (characters that doesn't have a glyph)
![image](https://user-images.githubusercontent.com/83872826/117542941-41551f00-b04d-11eb-9c75-22801644aeb5.png)

Case 2:
Describing a mathematical expression (which is still in a way 外字)
![image](https://user-images.githubusercontent.com/83872826/117542992-71042700-b04d-11eb-9629-daa8a925de90.png)

Currently there isn't a way to reference these images in a sentence without losing some user experience

Solutions proposed:

- Support inline HTML definitions, so the dictionary maker/converter may add custom styling such as resizing images to fit the sentence (as discussed in #322, there may be some security concerns, but that may be mitigated with a sanitizer)
- Allow dictionary maker to mark up certain words/text positions so parser knows it's referencing an image. Might also want to allow us to categorize the image such as "gaiji" to ensure the image aligns with the surrounding font, or custom width/height values in case it's a special case (can't think of any use case at the moment)

**Comment by epistularum** [comment]
Concerning the gaiji category, we need to make sure that those are always displayed, even in compact mod.

**Comment by ttu-ttu** [comment]
Hi @toasted-nutbread, I've briefly tried the new schema at #1689, looks pretty nice but it seems like it doesn't support scaling image according to their surrounding text, As a result, the browser may render gaiji such as the screenshot shown below:

![image](https://user-images.githubusercontent.com/83872826/118906867-276ee280-b951-11eb-940d-95c97d6d9f9e.png)

I believe this feature's needed and could be easily implemented by allowing `em` height, or with another property to control it.
Below's another example with similar html structure, but with `height: 1em` on the gaiji image.

![image](https://user-images.githubusercontent.com/83872826/118907060-73218c00-b951-11eb-80a6-72c36207521a.png)

**Comment by toasted-nutbread** [comment]
14px = 1em assuming the CSS var `--font-size-no-units` hasn't been modified

**Comment by wizo06** [comment]
@toasted-nutbread what if `--font-size-not-units` has been modified then? is there a workaround for this?

**Comment by toasted-nutbread** [comment]
#1692 add support for `"sizeUnits": "em"` on structured content images.
