### ISSUE TITLE
Unable to scan local files (after allowing access to file URLs)

### ISSUE THREAD

**Issue by suspiciousphish** [FooSoft/yomichan#1666]
Previously I was able to use Yomichan on local HTML files after turning on the "Allow access to file URLs" option in the Yomichan extension settings. I gathered from the FAQ and a few closed issue threads that this option was the only requirement for Yomichan to work in local files.

**Comment by toasted-nutbread** [comment]
What browser are you using?

**Comment by suspiciousphish** [comment]
The file was an .htm but changing it to a .html has fixed the issue. Thank you for your assistance.

**Comment by toasted-nutbread** [comment]
That's bizarre, I just tested on a .htm file and it works as expected. Are you able to reproduce if you rename it back, and if so, are you able to share this file? Maybe it's an issue that can be fixed
