### ISSUE TITLE
Google Docs changing to canvas-based rendering - will this affect Yomichan?

### ISSUE THREAD

**Issue by Ceiyne** [FooSoft/yomichan#1670]
I happened to see this today:
https://workspaceupdates.googleblog.com/2021/05/Google-Docs-Canvas-Based-Rendering-Update.html

There's more details at the link, but basically Google is changing Docs from an HTML-based rendering approach to canvas-based.  I don't know too much about the internals of Yomichan but I am assuming it looks at the HTML elements to find the text to lookup, so it sounds like this will cause Yomichan to no longer work on Docs.  Is there anything you can do?

**Comment by toasted-nutbread** [comment]
Wow, looks like another great change by google! Yes this will probably break Yomichan entirely on GDocs and there will likely be nothing that can be done on our end.

**Comment by Ceiyne** [comment]
I had a feeling you were going to say that.  Oh well, might be time for me to switch to office.com for my online Japanese word processing.  Thanks for letting me know.

**Comment by toasted-nutbread** [comment]
I can almost guarantee this will piss off some other users, so thanks for bringing it to our attention. The alternatives they present don't seem to be very helpful for something like Yomichan either.

**Comment by Thermospore** [comment]
here is how rikaikun is handling it
![image](https://user-images.githubusercontent.com/35350819/128248937-ad31ec31-eb63-41e7-aab2-1fb56d3ddd99.png)

**Comment by toasted-nutbread** [comment]
Relevant issue: https://github.com/melink14/rikaikun/issues/593
