### ISSUE TITLE
Add button on yomichan is gray

### ISSUE THREAD

**Issue by cathyxiaoxitv** [FooSoft/yomichan#1671]
Hi I am not quite sure if it is the right place to ask this question. If it is not, my apologize.
I installed yomichan and anki connect. 
When I tried to add a Japanese word into Anki, the add button on yomichan is gray and could not be clicked. 
I think I have done all the necessary settings and restarted for a few times but it still doesn't work.
Does anyone have any clues? Thanks in advance!
![2021-05-13 at 10 58](https://user-images.githubusercontent.com/62381876/118066762-43ff9d80-b3da-11eb-8179-9616fd83bbe5.png)

**Comment by toasted-nutbread** [comment]
Have you set up the Anki card model/deck/fields? If so, can you screenshot what they look like or share an export of the settings file?

**Comment by cathyxiaoxitv** [comment]
Hey there thanks for quick response :)
There is no option to choose here.
![2021-05-13 at 15 14](https://user-images.githubusercontent.com/62381876/118085895-188eaa00-b3fe-11eb-8372-b9fb093f7c0f.png)

[yomichan-settings-2021-05-13-06-15-58.pdf](https://github.com/FooSoft/yomichan/files/6470650/yomichan-settings-2021-05-13-06-15-58.pdf)

**Comment by toasted-nutbread** [comment]
Anki + AnkiConnect must be running connected for the list to be populated. Open Anki and refresh the page; the connection status is shown on the _Enable Anki integration_ option.

**Comment by cathyxiaoxitv** [comment]
Yes!! It worked now. Thank you so much toast san!
