### ISSUE TITLE
Add button disappears randomly.

### ISSUE THREAD

**Issue by DZ4VR** [FooSoft/yomichan#1672]
**Description**
Hello! I have a question about anki yomichan workflow. I use macOS. So I installed everything as intended. And it does work, but in a strange way. Every time I add a new word I have to press this green plus button. But after that with the next word it tends to disappear. And it reappears only after I click at anki window (click, not launch, the anki app is always launched). The strange thing is that it happens randomly. Sometimes I can add like 3 words in a row with no problems, but sometimes I have to click at anki window after every word. Why is that so?
Thank you for your help!

Extension version: Yomichan (development build) 21.4.30.1
Platform: Mac OS 10.12.6
Browser: chromium
AnkiConnect version: 6
Anki Version 2.1.35 (84dcaa86)
Python 3.8.1 Qt 5.9.7 PyQt 5.13.2

[yomichan-settings-2021-05-13-10-14-23.txt](https://github.com/FooSoft/yomichan/files/6471822/yomichan-settings-2021-05-13-10-14-23.txt)

**Comment by toasted-nutbread** [comment]
Check and see if this info helps:
https://foosoft.net/projects/anki-connect/#notes-for-mac-os-x-users

**Comment by DZ4VR** [comment]
> Check and see if this info helps:
> https://foosoft.net/projects/anki-connect/#notes-for-mac-os-x-users

Thank you very much! That worked for me.
