### ISSUE TITLE
[Feature Request] Screenshot export to Anki (Netflix, etc. support)

### ISSUE THREAD

**Issue by weirdalsuperfan** [FooSoft/yomichan#169]
You can currently use Yomichan with subtitled videos by using it in combination with extensions like Subadub (actually, not sure if that's even necessary). However, you can't create Subs2srs-style Anki cards. For people who don't pirate videos (e.g. companies, people without access to torrents, etc., etc.), this is a huge issue, because it means they can't easily make cards with pictures to accompany their sentences.

A simple feature like this would basically turn Yomichan into Voracious (without the audio, I guess...)*, but would let it work for things besides just video (i.e., anything in the browser). It's of course possible to take screenshots manually by yourself, but then you have to go through all the trouble of locating the newly created Anki card, etc.

*and btw there's a Chrome extension that lets you automatically pause Netflix videos at each subtitle if that's your thing, so combined with that it'd REALLY be like Voracious.

**Comment by Mrslapdabass** [comment]
I use this Chrome screenshot extension to download images:
https://chrome.google.com/webstore/detail/video-screenshotter/ppkojackhibeogijphhfnamhemklmial

The image pops up in a download bar at the bottom of the window. Just drag and drop the image from that bar into an anki field.

I also use this extension to close the download tab as soon as I have dragged the image. In the settings under 'Only disable download shelf', click the box that says 'Disable download shelf'
https://chrome.google.com/webstore/detail/always-clear-downloads-in/efoelbbfbknfhpmgclpcdbkoieedkkai?hl=en

**Comment by weirdalsuperfan** [comment]
Hmm, thanks for the temporary solution, but it seems like to make an anki card using this and yomichan I need to go through half a dozen steps :
1. Make card with yomichan (assuming the video is automatically paused)
2-3. Adjust windows so both Anki and the browser are shown (or degrade your watching experience by always having them both in view), or have two monitors
4. Switch to anki
5. Click on the newly created card
6. Click button to download image
7. Drag image to anki field

I would like to eliminate steps 2-7

**Comment by Mrslapdabass** [comment]
I would really recommend 2 monitors as it has really changed the way I do things. On yomichan click the 'plus' button then the 'book' button straight after and the browser for anki will show up with the card details on the second monitor (eliminating step 2-3). Clicking the button to download the image and dragging it to the field only takes about 2 seconds from this point!

Also if you watch anime I would recommend https://www.daiweeb.org . You can right-click on the screen and click copy image. This is slightly faster than the method using the extension.
