### ISSUE TITLE
Can't access clipboard in card template

### ISSUE THREAD

**Issue by icedicerice** [FooSoft/yomichan#1700]
**Description**
Yomichan is able to monitor the clipboard, but `definition.clipboardText` and `definition.clipboardImageFileName` are always empty. I haven't changed any template code, having something in the clipboard and pressing "test" yields empty text field. clipboard-text, clipboard-image are empty when set in card format.

**Browser version**
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0

**Yomichan version**
21.4.30.2

**Comment by toasted-nutbread** [comment]
Check to make sure you have clipboard permissions granted. Open the permissions page from the info page => permissions, or open moz-extension://.../permissions.html directly.

**Comment by icedicerice** [comment]
> Check to make sure you have clipboard permissions granted. Open the permissions page from the info page => permissions, or open moz-extension://.../permissions.html directly.

I have it granted. Tried reinstalling Yomichan/reopening/downgrading Firefox/, doesn't help.

![Screenshot from 2021-05-23 17-44-26](https://user-images.githubusercontent.com/60948004/119260999-bc423c00-bbee-11eb-9d57-98b5380b5db9.png)

**Comment by icedicerice** [comment]
Here are my settings
[yomichan-settings-2021-05-23-13-08-18.json.txt](https://github.com/FooSoft/yomichan/files/6528104/yomichan-settings-2021-05-23-13-08-18.json.txt)

**Comment by toasted-nutbread** [comment]
* Do you have any other extensions or browser settings which could potentially disable clipboard access?
* Can you share what OS you're running, any specific distro/version? There have been some other unreproducible issues that may stem from something OS-specific (#1664).

Here's something else you can test:
* Open the _Addons_ page (about:addons)
* Click the _Cog_ menu on the top right, select _Debug Addons_
* Find the entry for _Yomichan_ and click the _Inspect_ button
* From the _Console_ tab, run:
  ```js
  (() => {
    navigator.clipboard.readText().then(
      (content) => console.log({content}),
      (error) => console.error({error})
    );
  })();
  ```
* Copy the output and share it here. It should print `{content: "<clipboard text>"}` on success.
* You can also try running that from the dev console on the settings page, see if the behaviour is any different.

**Comment by icedicerice** [comment]
Executing the code in the console on both pages outputs the clipboard content (so `Object { content: "(() => {\n  navigator.clipboard.readText().then(\n    (content) => console.log({content}),\n    (error) => console.error({error})\n  );\n})();" }`)

Here's uname: `5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

I've tried creating a separate profile for Firefox and only installing Yomichan, but that also doesn't work. Doesn't work on fresh installation of Chromium too.



\* In case it was unclear, by `Yomichan is able to monitor the clipboard` I meant that Yomichan is able to read the clipboard on the search page with the "Monitor clipboard" option on, that works fine. I made sure that clipboard is not somehow randomly cleared - it's not.

**Comment by toasted-nutbread** [comment]
Yeah, I was just verifying that copying isn't doing anything fishy. I imported your settings and tested text/image clipboard fields and they worked for me.

If you are comfortable cloning the repo and adding some debugging statements / installing a dev build, I could give some guidance on how to try to diagnose the issue from your end, since I'm unable to reproduce it.

> I haven't changed any template code, having something in the clipboard and pressing "test" yields empty text field.

This is expected; media injection isn't performed for the test field, and both text/image clipboard reads fall in this category.

**Comment by icedicerice** [comment]
>  I could give some guidance on how to try to diagnose the issue from your end, since I'm unable to reproduce it.

Yes that's cool

**Comment by toasted-nutbread** [comment]
Alright here goes. I need to make better documentation on some of this at some point, but here's a brief overview:

---

For testing on Firefox, you need to do one of the following:
* For any version of Firefox, install a temporary build from about:addons => Cog menu => Debug Add-ons > Load Temporary Add-on. This is temporary, and the addon will be removed after the browser is closed.
* If you install/use Firefox Developer/Nightly Edition, you can install an unsigned addon from a file if you set _xpinstall.signatures.required_ to _false_ in about:config. This will persist after the browser has been closed.

---

To set up and build Yomichan for Firefox:
* Dev environment uses node/npm for testing and building
* Clone project using git
* To build after making changes, run `./build.sh firefox-dev`
* In the ./builds/ folder, there should be a file named yomichan-firefox-dev.xpi which can be loaded as an extension.

---

For debugging the relevant parts, here are two checks that could be helpful:

1. The most pertinent line is probably this:
   https://github.com/FooSoft/yomichan/blob/54e102f343b651ac41b2ce34d38a3a4638192d4a/ext/js/display/display.js#L1587-L1593
   You could log the args and result by changing it to something like this:
   ```js
   const result = await yomichan.api.injectAnkiNoteMedia(
       timestamp,
       dictionaryEntryDetails,
       audioDetails,
       screenshotDetails,
       clipboardDetails
   );
   console.log({
       timestamp,
       dictionaryEntryDetails,
       audioDetails,
       screenshotDetails,
       clipboardDetails,
       result
   });
   return result;
   ```
   This would log messages in the dev console on the main webpage.
2. The second place to check would be the clipboard reader itself, to make sure it works/is being invoked when adding an Anki card.
   https://github.com/FooSoft/yomichan/blob/54e102f343b651ac41b2ce34d38a3a4638192d4a/ext/js/comm/clipboard-reader.js#L73-L80
   You could add a `console.log` here to make sure it's running and to check what the result of the clipboard read is at that time.
   
   This would log messages on the background page, which I described how to debug in https://github.com/FooSoft/yomichan/issues/1700#issuecomment-846618784.

**Comment by icedicerice** [comment]
I've added console.log statement to yomichan/ext/js/comm/clipboard-reader.js@73 and it doesn't appear to execute when I'm clicking 'Test'. Also, it just randomly started showing this: 'null has no properties' (see pic) and when I click 'Test' it inserts 'null has no properties' into the textfield (clipboard content is definitely different) (same behavior with non modified build). I've also added console.log statement to yomichan/ext/js/display/display.js but that also doesn't appear to be called. 
![image](https://user-images.githubusercontent.com/60948004/119582487-08070800-bdde-11eb-8251-f34e44ddbd39.png)

**Comment by toasted-nutbread** [comment]
Can you run `git rev-parse HEAD` to show what commit you're on? Have you changed any settings/field templates?

Also, using the test fields on the settings page won't actually read from the clipboard; this is only performed when adding an Anki card.

**Comment by icedicerice** [comment]
Update: I've noticed that I also couldn't access clipboard in snap applications. libx11 update came out today, I updated it and it all works now. So should the issue be closed?

**Comment by toasted-nutbread** [comment]
Yeah, you can close it if it's working now. For posterity, do you know what previous version you were on (that may have been causing the issue)?

**Comment by icedicerice** [comment]
I believe it was libx11 2:1.6.8-1
