### ISSUE TITLE
Can't use it with Calibre server

### ISSUE THREAD

**Issue by patoniilista** [FooSoft/yomichan#1702]
Hi. I'm trying to use Yomichan with Calibre content server, so I can read epubs from my browser with proper text orientation and hopefully while creating anki cards. The problem is, whenever I hover a word Calibre intercepts the hovering and sends a bunch of errors to yomichan, such as:

> core.js:724 Yomichan 21.4.30.2 has encountered a problem.
Originating URL: about:srcdoc
TypeError: Cannot read property 'location' of null
    at setupFrame (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/app/popup.js:260:39)
    at chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/comm/frame-client.js:159:13
    at new Promise (<anonymous>)
    at FrameClient._connectIternal (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/comm/frame-client.js:52:16)
    at FrameClient.connect (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/comm/frame-client.js:30:53)
    at Popup._createInjectPromise (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/app/popup.js:268:27)
Issues can be reported at https://github.com/FooSoft/yomichan/issues
log @ core.js:724
core.js:724 Yomichan 21.4.30.2 has encountered a problem.
Originating URL: about:srcdoc
TypeError: Cannot read property 'location' of null
    at setupFrame (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/app/popup.js:260:39)
    at chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/comm/frame-client.js:159:13
    at new Promise (<anonymous>)
    at FrameClient._connectIternal (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/comm/frame-client.js:52:16)
    at FrameClient.connect (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/comm/frame-client.js:30:53)
    at Popup._createInjectPromise (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/app/popup.js:268:27)

Yomichan can, however, capture the word if I enable the "Use a native browser window instead of an embedded popup" option, but that's not really practical because the focus is lost to calibre's word selection so I have to keep deselecting the text everytime.

![2](https://user-images.githubusercontent.com/72221896/119263869-3060ed80-bbb7-11eb-8352-4dfff6b07d48.png)

I'll probably have to report this to Calibre's developer too, so I might as well start from here. Is there something that can be done from Yomichan's side or is all on Calibre?

A full log is attached to the post.

Extension version: Yomichan 21.4.30.2
Platform: Windows
Browser: Chrome
Language: en-US

[yomichan-calibre-console.txt](https://github.com/FooSoft/yomichan/files/6528188/yomichan-calibre-console.txt)

**Comment by toasted-nutbread** [comment]
The issue is that the content is in a sandboxed iframe without having `allow-same-origin` in the `sandbox` attribute. Therefore, the Yomichan popup cannot be created in that frame. As a workaround, you can enable the _Show iframe popups in the root frame_ option on the settings page, under the _Popup_ heading.

**Comment by patoniilista** [comment]
Enabling the iframe option seems to make it work. However Calibre uses Yomichan selection to select the word and thus steals focus. A workaround for this is to disable the _Select matched text_ under the _Scanning_ section so Calibre doesn't take over Yomichan's scanner. This way I can hover around the text freely, without having to smash the Esc key to cancel the Calibre's selection whenever I want to scan another word using Yomichan.

**Comment by toasted-nutbread** [comment]
Yeah I noticed that as well. There's a transparent overlay element which covers the entire page, and Yomichan will only scan the top element under the cursor. Seems like a questionable design choice, but at least there's a workaround.
