### ISSUE TITLE
[Feature Request] Maintain the dimensions of the popup window when zooming in through gestures

### ISSUE THREAD

**Issue by kirawi** [FooSoft/yomichan#1720]
On devices that support Chromium's gestures, such as a laptop, it's possible to zoom in without affecting the scaling ratio through the pinch gesture. However, it seems like it does affect yomichan's dimensions. Is there a way to maintain the dimensions while zooming in?

Normal:
![Capture](https://user-images.githubusercontent.com/67773714/120114660-32462600-c14e-11eb-9c4a-02b388cdf526.PNG)

Zoomed In:
![Capture1](https://user-images.githubusercontent.com/67773714/120114666-3d995180-c14e-11eb-9d23-8f348410cd70.PNG)

FYI, the screenshots are of the entire viewport.

**Comment by toasted-nutbread** [comment]
Adjust auto-scale settings (need to enable Advanced)

![image](https://user-images.githubusercontent.com/11037431/120115214-a386d880-c150-11eb-94f4-2c44483fd4e8.png)

**Comment by kirawi** [comment]
Oh yep, that did it. Thanks!
