### ISSUE TITLE
May 2021 Release

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1725]
https://github.com/FooSoft/yomichan/releases/tag/21.5.31.1

### General
* [x] Create [release tag](https://github.com/FooSoft/yomichan/tree/21.5.31.1).
* [x] Create [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.5.31.1).
* [x] Ensure the version is updated in the [manifest](https://github.com/FooSoft/yomichan/blob/21.5.31.1/ext/manifest.json).

### Testing
* [x] Update Chrome testing release.
* [x] Update Firefox testing release.
* [x] Update Firefox [updates.json](https://github.com/FooSoft/foosoft.github.io/blob/master/projects/yomichan/dl/updates.json) and [verify](https://foosoft.net/projects/yomichan/dl/updates.json).
* [x] Upload testing builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.5.31.1).

### Stable
* [x] Update Chrome stable release.
* [x] Update Firefox stable release.
* [x] Upload stable builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.5.31.1).

### Issues to address before stable
* [x] #1727
* [x] #1733

**Comment by toasted-nutbread** [comment]
@FooSoft 

I did try to set up some auto-updating of the git tag in #1724, but I reverted it for now in 744f9bb8364845dc81fb28650986499205cc8af5 since it had some errors with the CI tests. Also note that the workflow for trying to set up the test was a bit non-standard (modify manifest.json, create commit, tag commit), and also has some odd effects on CI.

**Comment by FooSoft** [comment]
Shipped!

The automatic versioning based on tag is mostly a nice-to-have -- if the whole thing feels like going up against the grain then it might not be worth it. It's just nice to have a single source of truth for any given state, otherwise bugs can sneak in : )

**Comment by toasted-nutbread** [comment]
A few additional fixes added to the release, OP updated for 21.5.31.1.

**Comment by FooSoft** [comment]
Updated for testing.

**Comment by toasted-nutbread** [comment]
It should be good for stable as well.
