### ISSUE TITLE
Anki integration: Definitions with images do not work

### ISSUE THREAD

**Issue by shoui520** [FooSoft/yomichan#1741]
For an upcoming monolingual dictionary we are making we are taking advantage of Yomichan's images and gaiji (structured-content) feature.  
They display correctly in the extension but not without [this CSS](https://pastebin.com/VSBNGFYz)   

![chrome_UKY0amtaF0](https://user-images.githubusercontent.com/77593657/122283713-bd604380-cee4-11eb-8f78-3219574c88a1.png)
![chrome_0nKeQ2XrDx](https://user-images.githubusercontent.com/77593657/122283723-c05b3400-cee4-11eb-8415-df97927786f6.png)

Well done.

However, when you try to make an Anki card from it, the glossary field turns into `[object Object]` 
Here are my Anki integration settings
![brave_yyR2Gf65hp](https://user-images.githubusercontent.com/77593657/122284038-19c36300-cee5-11eb-8f67-6446ec9574ae.png)
I mainly use the handlebars.js featured on animecards.site, which adds the `{test}` field, which adds definitions to your cards in plain text. 
**However, this does not matter here as stock handlebars.js and either {glossary} or {glossary-brief} have the exact same result**
 
![chrome_nWXh5n4ecI](https://user-images.githubusercontent.com/77593657/122284440-7cb4fa00-cee5-11eb-8235-abf67385ded6.png)

The Anki card result...
![anki_cX5kkBoLDC](https://user-images.githubusercontent.com/77593657/122284562-a110d680-cee5-11eb-98f1-742fa4faf7f7.png)

**Comment by shoui520** [comment]
I have attached a test dictionary that includes the entries 藍, 亜 and 謎
[test-dictionary.zip](https://github.com/FooSoft/yomichan/files/6665572/test-dictionary.zip)

**Comment by toasted-nutbread** [comment]
Yes, this is currently expected. Anki integration isn't implemented yet for either images for structured-content, and the "definition" text is a JSON object instead of a string, so handlebars stringifies it to "[Object object]". I'll have to make some changes to how Anki receives the images and formats the fields.

**Comment by shoui520** [comment]
@toasted-nutbread I have a question regarding this.
Will fixing this require making additional changes to the dictionary? Or will that handled entirely by the add-on?

**Comment by toasted-nutbread** [comment]
No changes required.
