### ISSUE TITLE
[Feature Request] Handle frequency ranking on a global basis.

### ISSUE THREAD

**Issue by epistularum** [FooSoft/yomichan#1742]
Currently the frequency ranking is handled within the dictionary format itself. This means that you either have to always have the provided jmdict dictionary imported and activated or have to manually export the freq info of the jmdict into the dictionary you want to actually use. This behaviours is fine if you use jmdict but it's quite annoying when trying to use monolingual dictionaries, or even when making new dictionaries as it means you have to re-match all the same frequencies.

Wouldn't it be much better to just handle the freq info for all dictionaries at the addon level?

I don't know if it's useful in any ways but I've compiled a tsv with all the possible reading/writing combos, their frequency and ID based on the available jmdict dictionary.
https://github.com/epistularum/japanese-word-frequency

I've done some small changes like:

- Removing duplicate reading/writing combos (only keeping the highest freq for each combo)
- Adding more granular freq for reading/writing combos with the same ID and same freq (was an issue for things like 鳩尾[みずおち] vs 鳩尾[みぞおち] vs 水落[みぞおち] vs 水落[みずおち] which all had the same freq). This was done by prioritizing the order those entries are found in JMdict. Decimals were used in those cases in order to not mess with other possible matches.
- Getting rid of negative values by scaling up all frequencies. This is more of a practical change, I find it hard to handle negative values because they don't get sorted correctly when doing numerical sorts.

**Comment by shoui520** [comment]
It does not make sense that frequency (word and reading pairs) is handled on a per dictionary basis rather than controlled on an addon basis. Seeing how issues opened about other languages are instantly closed it is clear Yomichan is an extension made specifically for Japanese, so why not have Japanese frequency (Bear in mind I am NOT talking about frequency dicts like innocent and bccwj) info is not implement into the extension itself?

**Comment by toasted-nutbread** [comment]
I may not be clear on what exactly you mean by "frequency" if you mean something other than "frequency dicts like innocent and bccwj", can you clarify? Are you referring to the "score" value used in dictionaries?

https://github.com/FooSoft/yomichan/blob/master/ext/data/schemas/dictionary-term-bank-v3-schema.json#L140-L143

**Comment by epistularum** [comment]
Yes, I mean the score value given to each reading/writing combo.
For instance the 6  in
`["汽艇","きてい","n","",6,["(steam) launch"],1791440,""]`

**Comment by toasted-nutbread** [comment]
The score is really just a fairly arbitrary way of ordering definitions within a dictionary, it doesn't really have meaning across dictionaries since it doesn't have any concept of a "unit". This occasionally presents an issue when multiple dictionaries are installed which have the same priority, since as it currently stands, the scores are naively compared. There's room for improvement, but the effects should be fairly minor.

https://github.com/FooSoft/yomichan-import/blob/35175a5a1ef618847f940767fb94b8ce82c728d0/edict.go#L157-L162
https://github.com/FooSoft/yomichan-import/blob/35175a5a1ef618847f940767fb94b8ce82c728d0/edict.go#L48-L65

With regard to dictionary generation, the scores can probably be left as 0 if there isn't sufficient information to generate the "arbitrary" value, or if it's not important. [yomichan-import](https://github.com/FooSoft/yomichan-import) already seems to do that for some of the [J2J dictionaries](https://github.com/FooSoft/yomichan-import/blob/35175a5a1ef618847f940767fb94b8ce82c728d0/daijirin.go#L87-L91).

And with regard to why this information isn't included at the addon level:
1) The scoring metric is fairly arbitrary, as mentioned above.
2) A preset list that is included with the extension wouldn't be able to cover every _possible_ term. Some dictionaries include "terms" which are phrases, and it's unrealistic to try to account for every potential term in advance.
3) The TXT or JSON data would have to be included with the application, which would increase size by ~10MB judging based on the repo linked.
4) A preset list would lead to a large amount of data redundancy. The data would have to be imported into the database, so the data would technically exist in two locations.

**Comment by epistularum** [comment]
>1. The scoring metric is fairly arbitrary, as mentioned above.

I understand that the score is fairly arbitrary but it's actually an excellent way to disambiguate matches even when ported to other dicts. What I mean by that is ranking the most probable writing for a specific reading found and the other way around. For instance giving priority to 上 over 筌 when matching うえ or giving priority to こおり over つらら when matching 氷. When adding a new word to your learning list the first thing you want to do is make sure you're getting the most probable option first and then go through the possibilies in case it doesn't make sense, for that purpose it's plenty enough and doesn't need to be absolutely perfect.

>2. A preset list that is included with the extension wouldn't be able to cover every possible term. Some dictionaries include "terms" which are phrases, and it's unrealistic to try to account for every potential term in advance.

And that's absolutely fine and it doesn't need to account for everything. The overwhelming majority of the time if the term isn't covered it's something that doesn't need disambiguation to begin with because of the rarity of the match causes a lack of ambiguity. On top of that, if the match is rare than it deserves to be matched lower and it's something that should be expected by the end user. If the user is proficient enough to find such rare cases then he is proficient enough to understand that the word is rare and will be ranked lower. In any case it's always better to have very good disambiguation 99%+ of the time than no disambiguation at all.

>3. The TXT or JSON data would have to be included with the application, which would increase size by ~10MB judging based on the repo linked.
>4.  A preset list would lead to a large amount of data redundancy. The data would have to be imported into the database, so the data would technically exist in two locations.

If we have to add the frequency information ourself to every single dict in order to make them usable for the end user that wouldn't that mean that the same data exists in every single instance of the imported dicts? If I have 8+ dicts installed all with the same frequency information, am I not replicating the data 8+ times? This is already something we have to do in order to keep disambiguation working because we cannot know in advance what type of combination of dictionary the end user is going to use.
That being said, I have no knowledge whatsoever of coding. I've picked up regex and various other skills for the sole purpose of improving dictionaries. If you're telling us that it is not feasible on a coding standpoint then so be it, I just wanted to lay down my improvement ideas based on my experience and usage of the tool and the dicts.

You might mention adding a frequency dict but this doesn't solves the sorting issue which hurts clarity and ease of filtering information on top of the fact that frequency lists only take into account the writing of the word and not the actual reading/writing combo. I could be wrong about that but this is the conclusion I ended on after working extensively on custom dictionaries.

I've ported this information on various monolingual dictionaries and used them daily as well as promoted them within various learning communities and I don't think I've ever seen something out of place. It's in fact so useful that I made this feature request wondering how is this not a standard feature. A lot of people out there are using non custom monolingual dicts and have a pretty hard time with the unperfect sorting of entries because they don't have the default jmdict installed.

**Comment by toasted-nutbread** [comment]
> If we have to add the frequency information ourself to every single dict in order to make them usable for the end user then wouldn't that mean that the same data exists in every single instance of the imported dicts? If I have 8+ dicts installed all with the same frequency information, am I not replicating the data 8+ times?

1. That is only assuming that they all have the same frequency information, which is not necessarily the case.
2. For entries which don't have a frequency in the "master list", those would still be liable to include the frequency information.
3. The data format already includes the frequency value, and for backwards compatibility reasons, this feature cannot be removed. Therefore I did not factor this potential repetition into the repeated data evaluation.
4. The "master list" includes term/reading pairs, which is where the large size comes from. In dictionaries, this information is already (and necessarily) present in the data, so the inclusion of a score should realistically add maybe ~8 bytes per entry.

> You might mention adding a frequency dict ...

Those serve a/multiple separate purpose(s), and I agree they should not be used for this purpose.

---

I guess my overall takeaway is that I don't see a clear benefit to effectively hardcoding the frequencies of term/reading pairs when the score field already serves this purpose, and it seems (to me) to be more limiting than helpful. The score field also allows for ordering of dictionary entries with the same term/reading.

It may be a potential pain point for dictionary creators that want to have these rankings, but that seems to be a relatively minor challenge during the initial creation of a dictionary. It should be transparent to the subsequent end-users. Dictionary creation (outside of what is supported by yomichan-import) is already a non-trivial process anyways.

The shortcomings related to sorting I mentioned in my previous post are a valid concern and worth some looking into.

Perhaps I need a better example of where this is causing an issue?

**Comment by epistularum** [comment]
>1. That is only assuming that they all have the same frequency information, which is not necessarily the case.

This doesn't really matter because for the purpose of having a general priority ranking to disambiguate entries with the same reading or same writing it's more than enough.

>2. For entries which don't have a frequency in the "master list", those would still be liable to include the frequency information.

Like I said before, if the entry isn't present in JMdict (which the master list is based on) then it's only fair to assume that the given combination is rare and giving it an arbitrary ranking of 0 is only natural. You also mentioned terms as they won't get a frequency information. Terms inherently do not need for any frequency information because most probably there's not going be any other match for the same matched text so there's nothing to disambiguate from. And even if there is, it's only going to be an alternate writing of the exact same glossary so the end user isn't mislead in any way.

>3. The data format already includes the frequency value, and for backwards compatibility reasons, this feature cannot be removed. Therefore I did not factor this potential repetition into the repeated data evaluation.

Wouldn't it be possible to prioritize the frequency within the dict and if no frequency is found then fallback on a master list? This way older dictionaries still work while dictionaries that don't support frequency information will still be disambiguated correctly.

>I guess my overall takeaway is that I don't see a clear benefit to effectively hardcoding the frequencies of term/reading pairs when the score field already serves this purpose, and it seems (to me) to be more limiting than helpful.

Yomichan doesn't support and doesn't plan to support other languages. So why would the exact same frequency information be carried within every single dictionary format? This information isn't really related to the dictionary, it's a way to rank possible matches by order of frequency in order to disambiguate entries that contain the matched text but have different reading or writing among them. It's just redundant to not have this frequency work on a global basis. Most users are not going to use some custom dictionary with frequency hacked into it and are going to wonder why suddenly the ordering doesn't make much sense when jmdict is removed. This shouldn't be the case as the frequency of a given reading/writing combo is the same across the whole language. The current behaviour forces people to use JMdict which frankly isn't optimal for learning Japanese on a medium-intermediate level. Not only that but it makes it extremely hard to update the "master list" since we're forced to encode it in all dicts to have a basic functionality properly working.

**Comment by toasted-nutbread** [comment]
To me, it seems the argument of frequencies being a global is something that could apply to other data in the dictionary, such as sequence, tags, and corpus freq. And even the distinction between the "score frequency" and "corpus frequency" is fuzzy at best. So at that point, the question would be why not include all that information as well, or even the entirety of JMDict? And my argument is that information is part of the dictionary data, and the design of Yomichan separates that from the implementation. The data comprising a dictionary should be complete and independent of the program that displays it.

Consider: what if the frequency of a word changes over time, creating a mismatch between the hypothetical list bundled with Yomichan and the dictionary data? The information presented would not be a coherent snapshot for a single point in time.

I'll mention again that I don't see the benefit of hardcoding the relative ordering of terms when there is already a data point that cannot be removed which provides ordering, which IMO I consider part of the dictionary. The concerns with custom dictionaries without frequency information or being "forced" to use JMDict is more indicative of incomplete or insufficient dictionary data.

**Comment by epistularum** [comment]
>To me, it seems the argument of frequencies being a global is something that could apply to other data in the dictionary, such as sequence, tags, and corpus freq.

Not sure what sequence is. Tags can differ on a dictionary basis so I wouldn't do that. Corpus on the other hand can very much be implemented in the same way. Although it's pretty much how it works already, it's global.

>Consider: what if the frequency of a word changes over time, creating a mismatch between the hypothetical list bundled with Yomichan and the dictionary data? The information presented would not be a coherent snapshot for a single point in time.

This is exactly one of the point I'm trying to make. If the freq changes, it's nearly impossible to update that info since each and every single dict has to be updated instead of just having a centralized place to update that information (not to mention there's no way to tell what version of the freq is currently imported if updates to the freq are to be made). We could very much have system like with have with corpus freq dicts but for freq of reading/writing. This would make versioning and updating a breeze.

>I'll mention again that I don't see the benefit of hardcoding the relative ordering of terms when there is already a data point that cannot be removed which provides ordering, which IMO I consider part of the dictionary. The concerns with custom dictionaries without frequency information or being "forced" to use JMDict is more indicative of incomplete or insufficient dictionary data.

I understand your point, what I'm just trying to say that the current way is redundant, hard to update and not user-friendly.

**Comment by toasted-nutbread** [comment]
Sequence is what groups the definitions with the same headword. AFAIK only JMDict uses this information, but it's very similar to what you're describing for frequency, in that some users want to have this information applied to other dictionaries. (related: #1546)
![image](https://user-images.githubusercontent.com/11037431/122485066-0c20e280-cfa4-11eb-8734-50f621ff9c5e.png)

Corpus is global, but not bundled with Yomichan.

> We could very much have system like we have with corpus freq dicts but for freq of reading/writing. This would make versioning and updating a breeze.

I'm not necessarily opposed to that, assuming the data is not bundled directly in Yomichan; that's been my main grievance. It sounds like that would be basically using the existing frequency dictionary data system to order definitions, which has less technical challenges vs what I was previously thinking.

> hard to update

It can probably be scripted fairly easily given a dictionary zip + the repo data you created. Maybe a downside is that the re-import process might take a while, potentially an argument to support patching, but that's a separate discussion with its own set of issues.

> not user-friendly

Not sure which dictionaries you're referring to, but if it's anything generated by yomichan-import, that codebase could be updated to include that data during the build process.

**Comment by epistularum** [comment]
>Sequence is what groups the definitions with the same headword. AFAIK only JMDict uses this information, but it's very similar to what you're describing for frequency, in that some users want to have this information applied to other dictionaries. (related: #1546)

Is that the ID at the very end of the dict? I don't think this can be achieved reasonably on a global basis, there would be a lot of isntances where a word is written is a certain way but isn't actually the same gloss (unless the purpose is to group regardless of gloss? I've never used this feautre honestly). Having this on a dictionary basis, like tags, makes much more sense.

>I'm not necessarily opposed to that, assuming the data is not bundled directly in Yomichan; that's been my main grievance. It sounds like that would be basically using the existing frequency dictionary data system to order definitions, which has less technical challenges vs what I was previously thinking.

I'm sorry for the poor wording on my part. I wasn't advocating for it to be actually hardcoded into yomichan but rather it being an easy to update external database that would act on a global basis. As you've noticed already I'm not familiar with programming, everything I've learned is for the purpose of making custom dicts so it's mostly text processing and regex.

>Not sure which dictionaries you're referring to, but if it's anything generated by yomichan-import, that codebase could be updated to include that data during the build process.

You're right.

**Comment by toasted-nutbread** [comment]
Yeah, I think it's now more clear to me what the ask is here, and it should be quite a bit simpler than what I was originally thinking, since it's based on existing functionality. It may need some updates to the data that frequency dictionaries contain, but that's not a huge difference. The idea is very similar to how there is a "primary dictionary" that is used for the sequencing information when grouping related terms.

**Comment by YYYYY-yyyyyy** [comment]
@epistularum removed the frequency info from his dicts and made a dict that has only frequency info. However the downside is that this approach doesn't work when `Result grouping mode` is set to `no grouping`. would be really nice to see support for global frequency dict (for ordering results).

**Comment by toasted-nutbread** [comment]
FYI #1938 adds support for using a frequency dictionary to sort results. Let me know if this is different than what is expected, otherwise I can close this issue once I've merged that PR.

**Comment by Thermospore** [comment]
nice, it even autodetects rank vs occurrence lists 👀 

think something is off with the sorting tho
![image](https://user-images.githubusercontent.com/35350819/132996933-2f66d901-9dc2-4815-8bec-5fa3b8d69558.png)
(埜 and 箆 are too high) 

I'm guessing currently:
length of headword > number of defs > freq dict sort ?

**Comment by Thermospore** [comment]
> `> number of defs >`

huh, maybe that was a coincidence
![image](https://user-images.githubusercontent.com/35350819/132997359-0760e167-c3fc-49d3-bb35-40cee5655390.png)

**Comment by toasted-nutbread** [comment]
Can you share the "JJ" dictionary you're using?

**Comment by Thermospore** [comment]
yea: [[Freq] 国語辞典.zip](https://github.com/FooSoft/yomichan/files/7150052/Freq.zip)

**Comment by ttu-ttu** [comment]
A little bit more on this, "Occurance-based" seems to sort correctly, but not "Rank-based"
I think it's because it treats "no frequency data" as rank 0 (top rank), which also looks like what's happening in the previous screenshots

**Comment by toasted-nutbread** [comment]
d89dedf8ebf6586fd6d7b017c66ef14b4956b5db should fix the issue.
