### ISSUE TITLE
[Feature Request] Monitor yomichan window

### ISSUE THREAD

**Issue by TingTingin** [FooSoft/yomichan#1743]
Don't know if there is a way to do this but im writing a script that edits cards after theve been added to anki from yomichan and one of the problems im having is that i need to gather metadata as soon as the button is pressed in yomichan but i only know that is was pressed after I get a response back from anki saying that a new card was added is there a way to gain access to the yomichan window that pops up in clipboard mode in python and potential scrape the page for example to test when the add card button is pressed

**Comment by TingTingin** [comment]
the main thing I want to know is when the card is added from yomichan and if there is a more efficient way of finding that out than polling anki

**Comment by toasted-nutbread** [comment]
Sounds like more of a task for [anki-connect](https://github.com/FooSoft/anki-connect) rather than Yomichan. There are many complexities that make it difficult to provide an easy event for when a card is added via popup.

**Comment by TingTingin** [comment]
Anki connect is what Im using to know when the card is added to anki by polling once a sec but there's a delay so wanted to know how get the information quicker if there was maybe a way to tell when a request is _sent_ to anki connect before a response is received back from anki or speed up the polling maybe and yes ive tried setting the poll time lower but there seems to be a limit on how fast responses come back setting the poll rate to .1 secs is barely any faster than 1 secs the current command I use is 

`invoke('findNotes', query='added:1')` 

which searches notes added today I don't know if there is a faster way to find newly added cards than this

**Comment by toasted-nutbread** [comment]
When you say you "_need to gather metadata_", what do you mean by that? What information / where is it coming from? How would you expect Yomichan to "notify" your script/program?

**Comment by TingTingin** [comment]
I mean I said it above but 

> The main thing I want to know is when the card is added from yomichan and if there is a more efficient way of finding that out than polling anki

and as for what means well the question I was asking is what means are available so if I could tell you what means I wouldn't have to ask the question but to be more specific 

I'm writing my script in python it takes info from mpv and adds it to the card in anki after its added via yomichan, since you can use yomichan with text from the clipboard the subs are copied to the clipboard from mpv as they show up and if a card is added via yomichan data from mpv like the present sentence, the sentence before, the sentence after and a rendered video file are added to the card that was just added the problem is that this info is time sensitive if for example someone were to add a card in yomichan and then continue playing the vid in mpv immediately when a notice from anki connect comes through a sec later the info that is added to the card in anki would be from the present sentence not the one that was there when you added the card to anki via yomichan 

if I could know faster when a card is added via yomichan I could save the present state of the player into a queue and when the notice comes back from anki add the saved values and not the ones presently available in the player

The best solution I could come up with was since I add the present sentence from yomichan when copied to the clipboard is when a card is added to a get the card info as well via anki connect and then search the subtitle file for that sentence and use assume the first occurrence of the sentence is the correct one and use the data from that to to determine the where to render the video from and where to get the before and after sentences this is kinda a hacky solution however which I rather avoid

**Comment by toasted-nutbread** [comment]
Okay, I was feeling out whether you were doing some scripting within the webpage that Yomichan is running or something more external, and it seems like the latter. The only thing I can think of doing that isn't a complete hack would be to run some sort of middleware server that effectively intercepts the request to create an Anki card, in there you do your processing, and then you forward that information to AnkiConnect to finally create the card.

**Comment by 0x766F6964** [comment]
Have you heard of [mpvacious](https://github.com/Ajatt-Tools/mpvacious)?
To me it sounds like a lot of what you want is done by it. It requires a keypress in mpv to update the last added note (which you would have added from yomichan) so its not fully automated. I don't really think its a problem since you probably paused the video to add a card from yomichan anyways.

Personally I would just modify it to get whatever extra functionality you want. Its written in Lua instead of Python (it needs to be to directly interact with mpv) but there isn't that much different between the two.

I think the main difference between what you want and what mpvacious does is that mpvacious just takes a screenshot of the paused frame and records the audio from the specified time stamps. Since all of that is already implemented you would just need to change it to record video with the timestamps instead.

Even if you don't want to directly edit mpvacious I'm sure your can find some ideas there to help you with your script.

**Comment by TingTingin** [comment]
> Personally I would just modify it to get whatever extra functionality you want. Its written in Lua instead of Python (it needs to be to directly interact with mpv) but there isn't that much different between the two.
> 
> I think the main difference between what you want and what mpvacious does is that mpvacious just takes a screenshot of the paused frame and records the audio from the specified time stamps. Since all of that is already implemented you would just need to change it to record video with the timestamps instead.
> 

Thanks for the help but yes I'm familiar with the the script and damn near all the scripts/programs in the Japanese learning space the reason I'm writing my own script is because I got tired of using scripts/programs that only partially do what I want

> Personally I would just modify it to get whatever extra functionality you want. Its written in Lua instead of Python (it needs to be to directly interact with mpv) but there isn't that much different between the two.

The reason I ended up writing the script in python is because could find very little documentation on lua and even less info on lua with mpv specifically I am nowhere near capable enough of modifying another script to do what want in lua, as for interacting with mpv from python I use this https://github.com/iwalton3/python-mpv-jsonipc which allows for direct interaction with mpv from python 

> To me it sounds like a lot of what you want is done by it. It requires a keypress in mpv to update the last added note

If it were the case of a keypress I could just do that with my script as you can bind keys with https://github.com/iwalton3/python-mpv-jsonipc the whole point of this was to get around that 

>just need to change it to record video with the timestamps instead.

The video that's rendered is from the start of the sub before to the end of the sub after in mpv you only have access to time data regarding the present sub this is true in lua and also https://github.com/iwalton3/python-mpv-jsonipc how I gain access to this is by accessing the sub files directly and then matching the present time in the playing file to the sub file this also has the bonus of allowing me to access the secondary sub-text which you couldn't do in mpv naturally (though they just recently added this feature its not in stable releases however) anyway considering my lack of knowledge of lua there's no way I could figure out how to do this in there not to mention

The script isn't just meant for mpv though that's what I'm using it for now its really meant to intercept cards when there added to anki to add additional context that would be more difficult to do otherwise which was a constant pain point for me since I started learning Japanese

> The only thing I can think of doing that isn't a complete hack would be to run some sort of middleware server that effectively intercepts the request to create an Anki card, in there you do your processing, and then you forward that information to AnkiConnect to finally create the card.

I was actually looking into this but I couldn't figure it out I was trying to use this https://scapy.net/ is that the sort of tool I would need or do you know where I should be looking to find info on how to do this

**Comment by toasted-nutbread** [comment]
Basically what I was thinking would be just a just a simple listening and requesting server. Not sure what languages you're familiar with, but you could do it in node or python, among others. I wasn't thinking of anything too complex.
* Node - [http](https://nodejs.org/api/http.html) library can handle and send requests. [example](https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTP-server/)
* Python - [http.server](https://docs.python.org/3/library/http.server.html) for listening and [urllib](https://docs.python.org/3/library/urllib.request.html) for requesting. [example](https://www.afternerd.com/blog/python-http-server/)

**Comment by TingTingin** [comment]
> Basically what I was thinking would be just a just a simple listening and requesting server. Not sure what languages you're familiar with, but you could do it in node or python, among others. I wasn't thinking of anything too complex.
> 
> * Node - [http](https://nodejs.org/api/http.html) library can handle and send requests. [example](https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTP-server/)
> * Python - [http.server](https://docs.python.org/3/library/http.server.html) for listening and [urllib](https://docs.python.org/3/library/urllib.request.html) for requesting. [example](https://www.afternerd.com/blog/python-http-server/)

thanks ill look into it

**Comment by toasted-nutbread** [comment]
Oh also, a potential benefit of using python is that you could load it as an addon as Anki, so you wouldn't need to run a second application whenever Anki is running. There's maybe a little bit of extra setup to get it to work as an addon, but it's probably not bad.

**Comment by TingTingin** [comment]
Im trying this and cant seem to make sense of it,  looking into it seems only one app can have access to a port at a time is it that I'm suppose to receive the requests myself and then forward them to anki if so could that cause issues like if I were to release this script to people could there be a problem and cards end up not getting sent or something if so id rather avoid that 

Is there maybe a way to simply monitor the data sent to the port where anki connect is which I could then filter through in python

**Comment by toasted-nutbread** [comment]
You would have to use two ports and listen on a different port than AnkiConnect does, then forward requests to the AnkiConnect port after you're done processing. You may have to change the server address in Yomichan's settings.

**Comment by TingTingin** [comment]
I couldn't really figure out the http solution  but I solved the problem by using multiprocessing and optimizing some other parts of the code
