### ISSUE TITLE
[Feature Request] Add support for <sub> and <sup>.

### ISSUE THREAD

**Issue by epistularum** [FooSoft/yomichan#1745]
Most monolingual dictionaries use those tags extensively and it's quite hard to convert those while trying to keep the original meaning. The main usage is for furigana information. I'm aware of this https://github.com/FooSoft/yomichan/issues/1655 but it's not always feasible to use ruby because of the way monolingual dictionaries are structured. The current way I've been converting those is by putting the furigana within parenthesis but obviously parenthesis already have another purpose and it's a bit awkward to tell wether the content of a prenthesis is furigana or additional information.

Another use case is for chemical and math related terms. I'm aware that for those there exist a limited unicode subset but I've converted dictionaries myself and I've found many instances where no unicode equivalent was available.

Perhaps other basic tags such as those are also worth adding:
italic - `<i>`
bold - `<b>`
underline - `<u>`
small - `<small>`

**Comment by ttu-ttu** [comment]
Would also like to add `<table>`

Example words that makes use of these tags:
- [Bold (or \<strong\> in this case), Table](https://dictionary.goo.ne.jp/word/%E9%9D%92%E7%94%B0%E8%B2%B7%E3%81%84/)
- [Italic](https://dictionary.goo.ne.jp/word/%E3%82%A2%E3%83%BC%E3%83%AB/#jn-167_)
- [Underline](https://dictionary.goo.ne.jp/word/%E6%B2%93%E5%86%A0/)
- [Subscript](https://dictionary.goo.ne.jp/word/%E6%82%AA%E6%80%A7%E8%B2%A7%E8%A1%80/)
- [Superscript](https://dictionary.goo.ne.jp/word/%E3%82%A2%E3%82%AF%E3%83%81%E3%83%8E%E3%83%B3/)
- [Small](https://dictionary.goo.ne.jp/word/%E5%90%88%E7%B8%81%E5%A5%87%E7%B8%81/#idiom_sanseido-20_)

Also do note that `<u>` doesn't really mean underline [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u), if you wanna follow the docs from it.
