### ISSUE TITLE
Firefox 89+ scans single kanji only

### ISSUE THREAD

**Issue by oiao** [FooSoft/yomichan#1746]
**Description**
In the recent Firefox versions (89+) word detection seems to be broken. Yomichan only detects single kanji characters. Any kana or words consisting of multiple Kanji are not recognized anymore.  This happens with the default settings.

**Browser version**
Firefox 90.0b6 

**Yomichan version**
 21.5.31.1

**Comment by toasted-nutbread** [comment]
Do you have an example webpage where this occurs? Maybe a screenshot or recording of what you're seeing? I can't reproduce the issue.

**Comment by oiao** [comment]
Strange. What other reason could there be? The webpage does not seem to matter, but for demonstration's sake, I have attached two screenshots from _jisho.com,_ Edge and Firefox respectively.

![edge](https://user-images.githubusercontent.com/29927996/122645383-b0c53080-d11a-11eb-869d-877f1aef0d3a.png)
![firefox](https://user-images.githubusercontent.com/29927996/122645385-b15dc700-d11a-11eb-99c0-50338e922624.png)

**Comment by toasted-nutbread** [comment]
Do you have a non-kanji dictionary enabled? Can you export your settings file?

**Comment by oiao** [comment]
I realized yesterday that there was indeed an issue with the jmdict dictionary. Re-importing it has solved the issue. Thanks a lot and sorry for the trouble!
