### ISSUE TITLE
[Feature Request] Typing in the Search page will always focus the text box

### ISSUE THREAD

**Issue by psychodelicwasabi** [FooSoft/yomichan#1751]
I wonder if there's a way to always focus the text box in the Search page whenever typing in it. That's a feature Discord has, for example. As for now, Yomichan Search requires that you click in the box and type in it, which delays the search and flow. If the user is reading without the use of a mouse and quickly moves to the Search tab, supposing that a card was previously made or a word in a sentence was clicked, the search will require the use of the mouse (Or pressing TAB three times).

**Comment by toasted-nutbread** [comment]
Something must have broken, because this was supposed to be a feature already. I'll check it out.
