### ISSUE TITLE
[Bug Report] secondary search bug

### ISSUE THREAD

**Issue by Thermospore** [FooSoft/yomichan#1768]
**Description**
noticed this while trying out some new dictionaries
easier to do in a vid: https://youtu.be/j4L3l_SUn-I
I can send those dicts in the vid if you want them for testing

**Environment**
```
Extension version: Yomichan (development build) 21.5.31.1
Platform: Windows
Browser: Chrome
Language: ja
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
AnkiConnect version: Unknown (Anki not running or connected)
Installed dictionaries: 新明解国語辞典 第五版, 大辞林３, Weblio 古語辞典, KANJIDIC (English), B短, B長, IC, AJ, 明鏡国語辞典, 故事ことわざの辞典, RikaiCake [lower], 実用日本語表現辞典, 漢字源, RikaiCake [upper], 広辞苑第六版・付属資料, 精選版　日本国語大辞典, 岩波国語辞典, KireiCake, 新明解国語辞典　第七版, JMdict, JMnedict, W, 大辞林 第三版, 大辞林 第三版（画像のみ）, デジタル大辞泉, デジタル大辞泉 OLD, JJ
```

**Exported settings file**
[yomichan-settings-2021-06-27-08-56-33.txt](https://github.com/FooSoft/yomichan/files/6721290/yomichan-settings-2021-06-27-08-56-33.txt)

**Comment by toasted-nutbread** [comment]
In short, is this the discrepancy you're referring to?

![test](https://user-images.githubusercontent.com/11037431/123550080-c5688080-d739-11eb-816b-5dbc6e8b2426.gif)

**Comment by Thermospore** [comment]
yessir

(and I do recognize 藍 != eye, but yomichan can't tell the difference in this case, so it should get pulled up)

**Comment by Thermospore** [comment]
Another situation where this is coming up:

![image](https://user-images.githubusercontent.com/35350819/128613187-57059a77-12c5-44ad-8deb-083bbc7c2170.png)

Probably has to do with how some dicts put katakana in the expression while others put it in the reading

**Comment by toasted-nutbread** [comment]
This issue was due to the reading field of "アイ" being an empty string (""), indicating that the reading and term are the same. The dictionary import process has been updated in #1941 to normalize these strings such that they won't be empty.
