### ISSUE TITLE
June 2021 Release

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1782]
https://github.com/FooSoft/yomichan/releases/tag/21.6.30.0

### General
* [x] Create [release tag](https://github.com/FooSoft/yomichan/tree/21.6.30.0).
* [x] Create [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.6.30.0).
* [x] Ensure the version is updated in the [manifest](https://github.com/FooSoft/yomichan/blob/21.6.30.0/ext/manifest.json).

### Testing
* [x] Update Chrome testing release.
* [x] Update Firefox testing release.
* [x] Update Firefox [updates.json](https://github.com/FooSoft/foosoft.github.io/blob/master/projects/yomichan/dl/updates.json) and [verify](https://foosoft.net/projects/yomichan/dl/updates.json).
* [x] Upload testing builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.6.30.0).

### Stable
* [x] Update Chrome stable release.
* [x] Update Firefox stable release.
* [x] Upload stable builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.6.30.0).

@FooSoft

**Comment by Thermospore** [comment]
sweet update!

I think this was already present, but I noticed this bug with the options ui https://youtu.be/BqfbA0WQixo

**Comment by Thermospore** [comment]
@toasted-nutbread @FooSoft btw here is a lil discord server where we are working on importing dictionaries to yomichan https://discord.gg/5vfAxd7jNa

**Comment by toasted-nutbread** [comment]
@FooSoft Testing release seems to be stable without needing a patch, should be good to ship.

The bug mentioned in https://github.com/FooSoft/yomichan/issues/1782#issuecomment-873539789 has been addressed, but it's not so critical as to warrant a patch.

**Comment by FooSoft** [comment]
Rolled out to stable!

**Comment by toasted-nutbread** [comment]
## Patch Release 21.6.30.1

https://github.com/FooSoft/yomichan/releases/tag/21.6.30.1

### General
* [x] Create [release tag](https://github.com/FooSoft/yomichan/tree/21.6.30.1).
* [x] Create [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.6.30.1).
* [x] Ensure the version is updated in the [manifest](https://github.com/FooSoft/yomichan/blob/21.6.30.1/ext/manifest.json).

### Testing
* [ ] Update Chrome testing release.
* [ ] Update Firefox testing release.
* [ ] Update Firefox [updates.json](https://github.com/FooSoft/foosoft.github.io/blob/master/projects/yomichan/dl/updates.json) and [verify](https://foosoft.net/projects/yomichan/dl/updates.json).
* [ ] Upload testing builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.6.30.1).

### Stable
* [ ] Update Chrome stable release.
* [ ] Update Firefox stable release.
* [ ] Upload stable builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.6.30.1).

@FooSoft Looks like I spoke too soon about there being no bugs.

**Comment by FooSoft** [comment]
Updated testing and stable releases with bugfix 👍🏻

**Comment by toasted-nutbread** [comment]
@FooSoft Sorry about that, updated the comment above again with the actual commit.

**Comment by FooSoft** [comment]
Shipped!
