### ISSUE TITLE
[Feature Request] Add marker for selected text

### ISSUE THREAD

**Issue by stegatxins0** [FooSoft/yomichan#1787]
I would like to request a Anki card marker for selected text such as `{selected-text}` if possible. The marker will add selected text in Yomichan popup window if available to Anki. If that is not possible, then something like [auto copy selected text to clipboard](https://chrome.google.com/webstore/detail/auto-copy/bijpdibkloghppkbmhcklkogpjaenfkg) in Yomichan popup window should work too.

Use case:
I manually copy the definition from Yomichan with `ctrl + c` before adding it to Anki. I wonder if it's possible to eliminate the extra keystroke.

Thanks.

**Comment by epistularum** [comment]
This would be a very useful feature. I end up doing this as well because it's easier when doing reps if you have a single concise hand picked gloss.
