### ISSUE TITLE
[Feature request] Unify default font between popup and search page?

### ISSUE THREAD

**Issue by Thermospore** [FooSoft/yomichan#1795]
![image](https://user-images.githubusercontent.com/35350819/124444018-a914a700-dd2a-11eb-8962-24dfda014cee.png)

![image](https://user-images.githubusercontent.com/35350819/124444034-ab770100-dd2a-11eb-8e7d-54eedfde0c5e.png)

here is the text pasted out of yomi, for ref:

たい‐が【大河】
1️⃣大きな川。幅が広くて、水量も多い川。
2️⃣黄河 (こうが) のこと。→大江2️⃣

たい‐こう〔‐カウ〕【大江】
1️⃣大きな川。大河。
2️⃣揚子江 (ようすこう) のこと。→大河2️⃣

**Comment by toasted-nutbread** [comment]
The font should be the same. What browser are you using and can you describe what the images are intended to show?

**Comment by Thermospore** [comment]
Ah sorry, should have provided more info
> What browser are you using
```
Extension version: Yomichan (development build) 21.6.30.0
Platform: Windows
Browser: Chrome
Language: ja
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
AnkiConnect version: Unknown (Anki not running or connected)
Installed dictionaries: 漢字源, Weblio 古語辞典, 実用日本語表現辞典, 精選版　日本国語大辞典, B長, B短, IC, KANJIDIC (English), RikaiCake [lower], RikaiCake [upper], AJ, 故事ことわざの辞典, 新明解国語辞典 第五版, 新明解国語辞典　第七版, W, 大辞林 第三版, 大辞林 第三版（画像のみ）, JJ, 広辞苑 第六版, デジタル大辞泉, 学研 四字熟語辞典, 新明解四字熟語辞典, 旺文社国語辞典 第十一版, 明鏡国語辞典, 明鏡国語辞典 OLD, 岩波国語辞典 第六版, ハイブリッド新辞林, JMdict, JMnedict, 広辞苑 第七版 INDEV
```
[yomichan-settings-2021-07-06-14-12-29.txt](https://github.com/FooSoft/yomichan/files/6770633/yomichan-settings-2021-07-06-14-12-29.txt)

> can you describe what the images are intended to show?

I guess in hindsight it was only necessary to post a single entry (those screenshots were just from the moment I first noticed the discrepancy). Here is an annotated image of the 大河 entry:
![image](https://user-images.githubusercontent.com/35350819/124615098-641f6c00-de21-11eb-9792-1c35161cf01b.png)

(btw I think I was accidentally zoomed out a lil bit just on the search page in those two original screenshots I posted)

**Comment by toasted-nutbread** [comment]
The difference is due to the scaling factor of 110% you have assigned, which is causing the popup font size to be scaled up by 10%. This is currently the expected behaviour, since the search page can be zoomed independently (CTRL++, CTRL+-, CTRL+mousewheel)

**Comment by Thermospore** [comment]
Ah, I see. Yeah I have the popup at 110% scale and the search page zoomed at 110% in chrome to match. Thanks for taking a look
