### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by Mrslapdabass** [FooSoft/yomichan#180]
The audio has suddenly stopped working. Is this happening for everyone else? The click sound that plays when there is no audio for a word is not playing either, there is just silence.

Thank you!

**Comment by siikamiika** [comment]
It seems that the certificate at https://assets.languagepod101.com has expired, preventing your browser from downloading the audio. As a quick fix you could add an exception for this site, but that's not a good long term solution and compromises security. I bet that many japanesepod101 have noticed this same issue.

**Comment by Mrslapdabass** [comment]
Thank you for the very quick reply. It's started to work again today, my life has been saved!
