### ISSUE TITLE
Popup is not present in local MHTML files

### ISSUE THREAD

**Issue by morning-paradigm** [FooSoft/yomichan#1807]
**Description**
I've got a few books saved as MHTML instead of HMTL + files for less cluttering. While scanning works, the popup won't _pop up_. This isn't the issue with a usual HMTL file.

**Browser version**
Vivaldi 4.1.2345.3 (Chromium 92.0.4515.65)

**Yomichan version**
21.5.31.1

**Exported settings file**
Not sure it's relevant.

**Comment by toasted-nutbread** [comment]
Similar issue to #1702, it seems mhtml files are sandboxed and don't allow `<iframe>` elements, which prevents Yomichan's popup from being shown.

**Comment by toasted-nutbread** [comment]
As a potential workaround, you could use the _Use a native browser window instead of an embedded popup_ option on the settings page (requires enabling _Advanced_).
