### ISSUE TITLE
Yomichan allowing duplicates to be created. 

### ISSUE THREAD

**Issue by Euphy0** [FooSoft/yomichan#1808]
it is showing the + buttons for cards that i already have
Expression
Reading
Glossary
Sentence
Picture
Audio
Sentence-Audio
Graph
Hint
Pronunciation 
these are my fields i use expression for the kanji
[yomichan-settings-2021-07-07-22-30-41.zip](https://github.com/FooSoft/yomichan/files/6780364/yomichan-settings-2021-07-07-22-30-41.zip)

**Comment by toasted-nutbread** [comment]
I tested with a note+deck setup matching yours on the latest Anki, AnkiConnect, and Yomichan, and could not reproduce the issue. Is your software up to date? Does this happen for all terms? Can you share an example of a term for which this happens?

**Comment by Euphy0** [comment]
> 
> 
> I tested with a note+deck setup matching yours on the latest Anki, AnkiConnect, and Yomichan, and could not reproduce the issue. Is your software up to date? Does this happen for all terms? Can you share an example of a term for which this happens?

ive tried upgrading and downgrading my software but it still happens. it happens for all terms
瞳
群衆
四
![gH1s952ykj](https://user-images.githubusercontent.com/87099685/124843762-80b5c400-df47-11eb-8a07-d7da77a1fd2a.jpg)
![c3mVedGnqB](https://user-images.githubusercontent.com/87099685/124843767-827f8780-df47-11eb-9dd4-224645224226.jpg)

**Comment by toasted-nutbread** [comment]
Can you try opening the search page and running this script in the dev console while Anki is running? (Press F12, paste this into the Console tab, and press enter to run.) This will simulate the check to see if the term "瞳" has been added; copy or screenshot what it prints to the console after running it.

```js
(async () => {
  let response;
  try {
    const body = '{"action":"canAddNotes","params":{"notes":[{"fields":{"Expression":"瞳","Reading":"ひとみ","Glossary":" pupil (of eye) eye","Sentence":"瞳","Picture":"","Audio":"","Sentence-Audio":"","Graph":"","Hint":"","Pronunciation":""},"tags":["yomichan"],"deckName":"Mining","modelName":"Mining-475ae","options":{"allowDuplicate":false,"duplicateScope":"deck","duplicateScopeOptions":{"deckName":null,"checkChildren":false}}},{"fields":{"Expression":"ひとみ","Reading":"","Glossary":" pupil (of eye) eye","Sentence":"瞳","Picture":"","Audio":"","Sentence-Audio":"","Graph":"","Hint":"","Pronunciation":""},"tags":["yomichan"],"deckName":"Mining","modelName":"Mining-475ae","options":{"allowDuplicate":false,"duplicateScope":"deck","duplicateScopeOptions":{"deckName":null,"checkChildren":false}}}]},"version":2}';
    response = await fetch('http://127.0.0.1:8765', {
      method: 'POST',
      mode: 'cors',
      cache: 'default',
      credentials: 'omit',
      redirect: 'follow',
      referrerPolicy: 'no-referrer',
      body
    });
  } catch (e) {
    console.log('error1', response, e);
    return;
  }

  if (!response.ok) {
    console.log('error2', response);
    return;
  }

  let responseText = null;
  try {
    responseText = await response.text();
  } catch (e) {
    console.log('error3', response);
  }

  console.log('responseText', responseText);
})();
```

**Comment by Euphy0** [comment]
> 
> 
> Can you try opening the search page and running this script in the dev console while Anki is running? (Press F12, paste this into the Console tab, and press enter to run.) This will simulate the check to see if the term "瞳" has been added; copy or screenshot what it prints to the console after running it.
> 
> ```js
> (async () => {
>   let response;
>   try {
>     const body = '{"action":"canAddNotes","params":{"notes":[{"fields":{"Expression":"瞳","Reading":"ひとみ","Glossary":" pupil (of eye) eye","Sentence":"瞳","Picture":"","Audio":"","Sentence-Audio":"","Graph":"","Hint":"","Pronunciation":""},"tags":["yomichan"],"deckName":"Mining","modelName":"Mining-475ae","options":{"allowDuplicate":false,"duplicateScope":"deck","duplicateScopeOptions":{"deckName":null,"checkChildren":false}}},{"fields":{"Expression":"ひとみ","Reading":"","Glossary":" pupil (of eye) eye","Sentence":"瞳","Picture":"","Audio":"","Sentence-Audio":"","Graph":"","Hint":"","Pronunciation":""},"tags":["yomichan"],"deckName":"Mining","modelName":"Mining-475ae","options":{"allowDuplicate":false,"duplicateScope":"deck","duplicateScopeOptions":{"deckName":null,"checkChildren":false}}}]},"version":2}';
>     response = await fetch('http://127.0.0.1:8765', {
>       method: 'POST',
>       mode: 'cors',
>       cache: 'default',
>       credentials: 'omit',
>       redirect: 'follow',
>       referrerPolicy: 'no-referrer',
>       body
>     });
>   } catch (e) {
>     console.log('error1', response, e);
>     return;
>   }
> 
>   if (!response.ok) {
>     console.log('error2', response);
>     return;
>   }
> 
>   let responseText = null;
>   try {
>     responseText = await response.text();
>   } catch (e) {
>     console.log('error3', response);
>   }
> 
>   console.log('responseText', responseText);
> })();
> ```

![YA8rnGbwe9](https://user-images.githubusercontent.com/87099685/124845621-f3c13980-df4b-11eb-9a5a-7d1d411d6744.jpg)

**Comment by toasted-nutbread** [comment]
The issue seems to be coming from Anki or AnkiConnect, as it's signalling to Yomichan that it _can_ add the card. Can you screenshot the full details of the card in the Anki card browser? Maybe screenshot the details of the fields for the note type? (Tools > Manage Note Types)

![image](https://user-images.githubusercontent.com/11037431/124847902-d3a07300-df69-11eb-9bbb-a75c98155f0c.png)

**Comment by Euphy0** [comment]
> The issue seems to be coming from Anki or AnkiConnect, as it's signalling to Yomichan that it _can_ add the card. Can you screenshot the full details of the card in the Anki card browser? Maybe screenshot the details of the fields for the note type? (Tools > Manage Note Types)
> 
> ![image](https://user-images.githubusercontent.com/11037431/124847902-d3a07300-df69-11eb-9bbb-a75c98155f0c.png)

front
{{Expression}}
<div style='font-size: 20px;'>{{Hint}}</div>
 
styling
.card {
   font-family: IPAexGothic;
 font-size: 50px;
 text-align: center;
 color: White;
 background-color: Black;
}

back
{{FrontSide}}
<hr id=answer>
{{Reading}}
<br>
<div style='font-size: 25px;'>{{Glossary}}</div>
<div style='font-size: 20px;'>{{Picture}}</div>
<br>
<div style='font-size: 25px;'>{{Sentence}}</div>
<br>
<div style='font-size: 25px;'>{{Graph}}</div>



______
{{Audio}}
{{Sentence-Audio}}
![5wGKKxQW6E](https://user-images.githubusercontent.com/87099685/124848530-e7d87600-df51-11eb-983d-9a3e01eeb267.jpg)
![5yuJSeNSL7](https://user-images.githubusercontent.com/87099685/124848531-e8710c80-df51-11eb-8129-254e07299ab3.jpg)
![QBPrk1bqyB](https://user-images.githubusercontent.com/87099685/124848533-e909a300-df51-11eb-8796-860fc579c29b.jpg)
![S1r4jNobEw](https://user-images.githubusercontent.com/87099685/124848536-e9a23980-df51-11eb-8e41-45137fee944f.jpg)

**Comment by Euphy0** [comment]
https://drive.google.com/file/d/1CmU2Q6iqUabTKoB7clq89XQAnlQUiRm2/view?usp=sharing
this is the deck if you need it

**Comment by toasted-nutbread** [comment]
The issue is that the mining deck contains an additional space after the expression, which is used to determine uniqueness.

`"瞳 " != "瞳"`

![image](https://user-images.githubusercontent.com/11037431/124854697-ba9dbf00-df75-11eb-887c-ed4faf7b399d.png)

**Comment by Euphy0** [comment]
> The issue is that the mining deck contains an additional space after the expression, which is used to determine uniqueness.
> 
> `"瞳 " != "瞳"`
> 
> ![image](https://user-images.githubusercontent.com/11037431/124854697-ba9dbf00-df75-11eb-887c-ed4faf7b399d.png)

Thanks when I get home will check if that fixes it

**Comment by Euphy0** [comment]
> > The issue is that the mining deck contains an additional space after the expression, which is used to determine uniqueness.
> > `"瞳 " != "瞳"`
> > ![image](https://user-images.githubusercontent.com/11037431/124854697-ba9dbf00-df75-11eb-887c-ed4faf7b399d.png)
> 
> Thanks when I get home will check if that fixes it

I clicked ctrl a and deleted it then retyped it.
still let’s me add it. 

do I need to remove the space a different way?

**Comment by Euphy0** [comment]
after checking what i can duplicate i found that It lets me add a duplicate for all cards that are not new
this happens for both my decks.

**Comment by toasted-nutbread** [comment]
I am guessing this may be due to the note type being different or something, seeing as how your model name has an auto-generated suffix (-475ae). If that's the case, this is related to #1519.

If you are able to share the following file:
"C:\Users\_USERNAME_\AppData\Roaming\Anki2\User #\collection.anki2"
I could try to verify that.

The trailing space would also still have been an issue, so there may be multiple problems at play here.

**Comment by Euphy0** [comment]
> I am guessing this may be due to the note type being different or something, seeing as how your model name has an auto-generated suffix (-475ae). If that's the case, this is related to #1519.
> 
> If you are able to share the following file:
> "C:\Users_USERNAME_\AppData\Roaming\Anki2\User #\collection.anki2"
> I could try to verify that.
> 
> The trailing space would also still have been an issue, so there may be multiple problems at play here.

https://drive.google.com/file/d/1WSydWxtCQZjua6F33KY4udE6QICXcbHL/view?usp=sharing

**Comment by toasted-nutbread** [comment]
Well it looks like the model type does match, so that's not an issue, but there was still a space in expression of `"瞳 "`. This is probably still the case for every expression.

**Comment by Euphy0** [comment]
> Well it looks like the model type does match, so that's not an issue, but there was still a space in expression of `"瞳 "`. This is probably still the case for every expression.

I’ve tried replacing 
(^(&nbsp;)+|(&nbsp;)+$)
and (^\s+)
With nothing but it says that zero cards were edited so I don’t think there is any space in the cards

**Comment by toasted-nutbread** [comment]
did you have all note selected when you performed the find & replace? It seems that only operates on the selected cards, and I'm getting several hundred notes modified after running the replacement.

**Comment by toasted-nutbread** [comment]
Related: #321 (which never had a solution, but referencing to link the issues)

**Comment by Euphy0** [comment]
> did you have all note selected when you performed the find & replace? It seems that only operates on the selected cards, and I'm getting several hundred notes modified after running the replacement.

I went into the mining deck and hit ctrl a to select all the cards
Had it replace expression field only.
Can you explain what you mean by select all notes  so that I can try that when I get off work. Thanks for your help and time

**Comment by Euphy0** [comment]
> Related: #321 (which never had a solution, but referencing to link the issues)

This issue did start happening after I added a deck that contains duplicate cards

**Comment by toasted-nutbread** [comment]
> I went into the mining deck and hit ctrl a to select all the cards
> Had it replace expression field only.
> Can you explain what you mean by select all notes so that I can try that when I get off work. Thanks for your help and time

That sounds right to replace all fields, I guess my worry is that somehow that didn't work or something. Here's what it looks like when I do it (using the database you shared, which still contained spaces):
![example](https://user-images.githubusercontent.com/11037431/125125969-66572400-e0c8-11eb-9cd5-6e333659eafb.gif)

> This issue did start happening after I added a deck that contains duplicate cards

I suspect that it's an issue with the deck formatting in both cases. If you create a new empty deck and add cards to that, do you have any issue with adding duplicates?

**Comment by Euphy0** [comment]
> > I went into the mining deck and hit ctrl a to select all the cards
> > Had it replace expression field only.
> > Can you explain what you mean by select all notes so that I can try that when I get off work. Thanks for your help and time
> 
> That sounds right to replace all fields, I guess my worry is that somehow that didn't work or something. Here's what it looks like when I do it (using the database you shared, which still contained spaces):
> ![example](https://user-images.githubusercontent.com/11037431/125125969-66572400-e0c8-11eb-9cd5-6e333659eafb.gif)
> 
> > This issue did start happening after I added a deck that contains duplicate cards
> 
> I suspect that it's an issue with the deck formatting in both cases. If you create a new empty deck and add cards to that, do you have any issue with adding duplicates?

the reason it did not edit cards for me seems to be because i did not check treat input as regular expression after doing so it edited cards but still does not work.

if i make a new deck or add new cards to the current deck i dont have an issue with those just the old cards

**Comment by toasted-nutbread** [comment]
Can you share your updated collection.anki2 file?

**Comment by Euphy0** [comment]
> Can you share your updated collection.anki2 file?

https://drive.google.com/file/d/1A9AvZAZo5l4i2qTAi2szsqnJhg-vkQlY/view?usp=sharing

**Comment by toasted-nutbread** [comment]
I am unable to reproduce the issue using your updated database file and the settings file you shared.

![image](https://user-images.githubusercontent.com/11037431/125129394-64dc2a80-e0cd-11eb-86e4-d4a911adab30.png)

Can you also try running the script in https://github.com/FooSoft/yomichan/issues/1808#issuecomment-876029977 again?

**Comment by Euphy0** [comment]
> I am unable to reproduce the issue using your updated database file and the settings file you shared.
> 
> ![image](https://user-images.githubusercontent.com/11037431/125129394-64dc2a80-e0cd-11eb-86e4-d4a911adab30.png)
> 
> Can you also try running the script in [#1808 (comment)](https://github.com/FooSoft/yomichan/issues/1808#issuecomment-876029977) again?

![mCypqqAytc](https://user-images.githubusercontent.com/87099685/125130120-4b2ee900-e0b5-11eb-9168-7ada4b94a9c6.jpg)

**Comment by Euphy0** [comment]
after running that command again it is working now

**Comment by Euphy0** [comment]
thanks for your help
