### ISSUE TITLE
Template Render Error - Anki Integration just suddently stopped working

### ISSUE THREAD

**Issue by DySQRD** [FooSoft/yomichan#1821]
**Description**
Hello ! I was adding words to my Anki deck through Yomichan as usual when all of a sudden the add-on stopped being able to find words already in my deck. Trying to create a card produces these errors :
<img width="301" alt="2021-07-11 00_34_03-神武 - Jisho org" src="https://user-images.githubusercontent.com/74011531/125177885-c5f42300-e1df-11eb-95a9-b1433344dba4.png">

And creates a card like this : (once created, ANY dictionary definition will point to this one card)
<img width="150" alt="2021-07-11 00_07_30-Browse (1 of 2 cards selected)" src="https://user-images.githubusercontent.com/74011531/125177598-5ed56f00-e1dd-11eb-9263-0c41c008c995.png">

I don't think there's any change of settings worth mentioning. Everything was working fine and I have absolutely no clue why it suddenly started doing this.

I have tried resetting Yomichan's settings, uninstalled/reinstalled it, same with Anki, cleared cache and cookies. Nothing has changed.

I'm sorry for the lack of information, I have tried everything I could think of aside from uninstalling/reinstalling Firefox.

**Browser version**
89.0.2 (64 bits)

**Yomichan version**
21.6.30.0

**Comment by toasted-nutbread** [comment]
Can you share an export of your settings file?

**Comment by tvvoty** [comment]
I'm having this issue too.
Here's the settings file.

https://drive.google.com/file/d/1pyv6bkltu6CYtDIA8WmzVs9zwrZpQr1-/view?usp=sharing

The browser: Firefox 89.0.2
Yomichan version: 21.6.30.0
Anki verion:Version 2.1.35
Operating system: Kubuntu 21.04

I also have ODH extention installed and it works normally.
Firefox says yomichan was last updated on July 10, so maybe the problem might be in the update. 

I'll post the console debug output once I figure out how to copy it all.

**Comment by toasted-nutbread** [comment]
F12 to open dev console. You should just have to expand one of the errors to see the real error.

![image](https://user-images.githubusercontent.com/11037431/125178599-af84a200-e1b4-11eb-9281-fb62bda0c462.png)

**Comment by tvvoty** [comment]
Oh, so like this then?
![Screenshot_20210711_022943](https://user-images.githubusercontent.com/75815245/125178736-3b67ef80-e1f0-11eb-971c-d641771e369a.png)


Btw, I've also seen that "Terminated" thing in the settings too.

![Screenshot_20210711_023055](https://user-images.githubusercontent.com/75815245/125178742-4458c100-e1f0-11eb-8c20-c028f2ec4c0f.png)

**Comment by toasted-nutbread** [comment]
Yes that's it, thanks. It looks like something is causing the template rendering frame to be reloaded. There was a minor change to the file causing the error in #1772, but I haven't ran into an issue myself. Does this error consistently happen every time you do anything with Anki, or is there anything specific you've had to do to reproduce the issue?

**Comment by tvvoty** [comment]
> Does this error consistently happen every time you do anything with Anki, or is there anything specific you've had to do to reproduce the issue?

uhh, I'm not sure if I understand the question, but it happens consistently every time I try to add a word by clicking on one of the "green pluses" after pasting/typing something in the search bar and clicking on a word. I don't think I did anything specific, just the regular things I do every day. Like, I don't think there's anything I can do with anki in yomichan except adding cards to it? 

I'll try installing yomichan on brave and check if it works there.

**Comment by toasted-nutbread** [comment]
I think I know what the issue is, I'm just surprised it's not something that affects everyone, hence why it was overlooked. I'll work on a patch that should fix it.

**Comment by Feripe-a** [comment]
Some thing here.
![image](https://user-images.githubusercontent.com/84395172/125179277-a4853e00-e1c3-11eb-80c8-686b8ece2b42.png)

**Comment by Feripe-a** [comment]
> it happens consistently every time I try to add a word by clicking on one of the "green pluses" after pasting/typing something in the search bar and clicking on a word.

Same here.

**Comment by tvvoty** [comment]
>I'm just surprised it's not something that affects everyone, hence why it was overlooked

I checked it on brave and everything seems to be working normally, mb it's a Firefox thing. OP seems to be on firefox too.

>Same here.

@Feripe-a Are you perhaps on firefox as well?

**Comment by Feripe-a** [comment]
>Are you perhaps on firefox as well?

Yes. Linux as well.

**Comment by KingCoinless** [comment]
It's not exclusive to Linux. Using Win 10 and Firefox, same issues as the others.

**Comment by toasted-nutbread** [comment]
I've been able to reproduce the issue, working on a fix.

**Comment by toasted-nutbread** [comment]
Prepared a patch release in https://github.com/FooSoft/yomichan/issues/1782#issuecomment-877728808, and we shall await @FooSoft for deployment. This issue can be closed once it's out.

**Comment by Feripe-a** [comment]
Thanks. We are looking forward to the update.

**Comment by tvvoty** [comment]
<3

**Comment by FooSoft** [comment]
Fix shipped to both stable and testing releases 🚀

**Comment by FooSoft** [comment]
Actually... @toasted-nutbread are you sure that the fix made it into 21.6.30.1? I'm seeing only a manifest version diff between the two here.

**Comment by toasted-nutbread** [comment]
One minute, apparently the cherry-pick failed for some reason...

**Comment by toasted-nutbread** [comment]
Fixed + commented in the release issue. Apologies, was in too much of a hurry to get a build ready to release.

**Comment by FooSoft** [comment]
No worries at all 😄  

21.6.30.2 has been rolled out everywhere. I think this makes 21.6.30.1 the shortest lived release ever!

**Comment by DySQRD** [comment]
Thank you so much everyone !
