### ISSUE TITLE
Profiles disappearing on Chromium

### ISSUE THREAD

**Issue by thymetony** [FooSoft/yomichan#1825]
Every time I try to add a new profile for alternative settings, the profile is deleted upon navigating away from the settings page or closing the browser. I'm also unable to add conditions to new profiles, there is just no response when I click the button.

I am using was unable to reproduce these issues in Chrome but I also wasn't able to import my settings from Chromium so I'm unsure if it's a problem with the Yomichan, the browser, or my settings.

```Extension version: Yomichan 21.6.30.2
Platform: Mac OS
Browser: Chrome
Language: en-GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
AnkiConnect version: 6
Installed dictionaries: JMdict, Kanjium Pitch Accents, 旺文社国語辞典 第十一版, ハイブリッド新辞林, 新明解国語辞典 第五版, Anime & J-drama, Netflix, VN Freq, 国語辞典, SoL```

**Comment by toasted-nutbread** [comment]
If you can reproduce the problem, try and make it happen again and then press F12 to open the dev tools. Check the console to see if there is any error, or if the browser button icon shows a red "!".

**Comment by thymetony** [comment]
Thanks for the reply. Checked the console and I am getting this error every time I do anything (changing settings, etc.) after creating a new profile. Also when I switch back to editing my default profile on the main settings screen the new profile deletes itself.

No errors when I only have my default profile.
```
Uncaught (in promise) TypeError: scan-inputs-simple-controller.js:194
Cannot read property 'options' of undefined
    at Backend._getProfileOptions (js/background/backend.js:988)
    at Backend._onApiOptionsGet (js/background/backend.js:395)
    at invokeMessageHandler (core.js:360)
    at Backend._onMessage (js/background/backend.js:312)
    at Backend._onMessageWrapper (js/background/backend.js:283)```

**Comment by toasted-nutbread** [comment]
Does the error persist if you reload the extension from chrome://extensions/?

**Comment by thymetony** [comment]
Yes. Additionally I have tried removing and reinstalling Yomichan to no effect. Same issue from the beginning with all default settings.

**Comment by toasted-nutbread** [comment]
Are you able to export your settings file from the settings page and share it here?

**Comment by thymetony** [comment]
Settings attached. Yes, I am having the issue with the all-codecs+ version of Chromium. There is no sign of the issue on Google Chrome.

[yomichan-settings-2021-07-14-00-42-35.json.zip](https://github.com/FooSoft/yomichan/files/6812714/yomichan-settings-2021-07-14-00-42-35.json.zip)

**Comment by toasted-nutbread** [comment]
On the settings page, enable _Advanced_, go to the _Text Parsing_ section, and change _Sentence termination characters_ to _Custom_. There is a bug that is causing this value to be invalid.

**Comment by thymetony** [comment]
This fixed it. Thank you so much.
