### ISSUE TITLE
[Help wanted] Field return blank

### ISSUE THREAD

**Issue by ntvkhoasgt** [FooSoft/yomichan#1828]
My onyomi and kunyomi field return blank and the feature in attached picture also say "No results found". Is there anyway to fix this? 🙇 

![image](https://user-images.githubusercontent.com/67872483/125581566-78fe7866-d84e-43bc-b08e-47ef822b0a67.png)

**Comment by 0x766F6964** [comment]
Do you have the KANJIDIC dictionary installed?

**Comment by ntvkhoasgt** [comment]
@0x766F6964 
Unfortunately, i don't have the KANJIDIC dictionary. 
I tried installing it and it worked as expected. 🙇 
Thank you very much. 🙇
