### ISSUE TITLE
[Feature Request] Go to previous/next dictionary with term-reading grouping.

### ISSUE THREAD

**Issue by RicBent** [FooSoft/yomichan#1830]
The "Go to previous/next dictionary" shortcuts currently do not work with term-reading result grouping.

Especially with long dictionary entries it would be really useful to just skip through dictionaries of the current result group without having to fall back to arrow keys or the mouse wheel.

Maybe shortcuts for skipping through the meaning entries of a given group would also be useful.

**Comment by toasted-nutbread** [comment]
Can you define "don't work"? What are the shortcuts you're trying to use? Are you having the issue with the popup and/or on the search page?

> Maybe shortcuts for skipping through the meaning entries of a given group would also be useful.

Not sure what you mean by "meanings entries" and "group" in this context.

**Comment by RicBent** [comment]
I have these shortcuts: 
![image](https://user-images.githubusercontent.com/12817990/125920298-d185c0cc-344b-4365-9fd7-9aedc9bd8ef7.png)

As you can see I can move between the term-reading groups with w and s, but the shortcuts for going to the next/previous dictionary do nothing (same behaviour on the search page as in the popup). I think it would make sense for the next/previous dictionary of the current term-reading group to be scrolled into view (like the one I'm showing at the end) with these shortcuts.

https://user-images.githubusercontent.com/12817990/125921799-8c8c31d0-ed29-47ed-9f70-49e46cbe4ee1.mp4

> Not sure what you mean by "meanings entries" and "group" in this context.

I mean the 1. 2. 3. etc bullet points of each term-reading group.

**Comment by toasted-nutbread** [comment]
I see what you mean. Yeah the next/previous dictionary was originally only intended for split card entries, hence why it doesn't work when multiple dictionaries are grouped. I'll look into if that can be changed.
