### ISSUE TITLE
[Bug Report] Can't add words to Anki deck anymore - Anki Integration just suddenly stopped working 2: Electric Boogaloo

### ISSUE THREAD

**Issue by DySQRD** [FooSoft/yomichan#1831]
Hello ! Like last time (#1821) I was adding words to my deck with Yomichan when suddenly... it wouldn't let me anymore :

<img width="495" alt="2021-07-15 18_03_20-literally - Jisho org" src="https://user-images.githubusercontent.com/74011531/125820845-22a28f0b-a142-427a-bc49-f951c4b9ef5e.png">

This is the only issue, other options seem to be working fine.
Still no change of parameters, I was just mining when it stopped.
This time I will provide the settings export :

[yomichan-settings-2021-07-15-15-52-57.txt](https://github.com/FooSoft/yomichan/files/6824579/yomichan-settings-2021-07-15-15-52-57.txt)

**Browser version**
Firefox 90.0 (64 bits)
(although this is the newest version, the bug occurred before updating)

**Yomichan version**
21.6.30.2

**Comment by toasted-nutbread** [comment]
With Anki running, can you open the settings page, go to the _Anki_ section, click _Configure Anki card format…_, and see if there are any fields highlighted in red? And can you screenshot what that looks like for you?

One potential cause of this issue is if the Anki deck or model is invalid.

**Comment by DySQRD** [comment]
> 
> 
> With Anki running, can you open the settings page, go to the _Anki_ section, click _Configure Anki card format…_, and see if there are any fields highlighted in red? And can you screenshot what that looks like for you?
> 
> One potential cause of this issue is if the Anki deck or model is invalid.

Nevermind... I did mess with the decks' names and forget about that. Sorry for the inconvenience.
