### ISSUE TITLE
'add card' buttons have disappeared 

### ISSUE THREAD

**Issue by Mrslapdabass** [FooSoft/yomichan#184]
The small and large '+' buttons to add a new card have suddenly disappeared in chrome. They are there in firefox though. Are other people having this issue with chrome?

 Thank you :)

**Comment by FooSoft** [comment]
I pushed a fairly large update to Yomichan earlier today; it is possible that something with your Anki setup is not compatible. That being said, everything appears to work fine here. Can you try closing all instances of Chrome, and double checking your Anki settings (seeing if it is properly detected). You might also have to update AnkiConnect if you are running an old version (you should be using 6, check what you have by going to <http://127.0.0.1:8765/> while Anki is running.

**Comment by Mrslapdabass** [comment]
Wow, thank you for the very quick response! I just updated ankiconnect to v6 then restarted my computer and I'm getting the same result. It's strange that it works on firefox but not on chrome (when testing on chrome I disabled anki integration in the firefox extension and disabled the plugin as well). Have you got any other ideas that I could try? I am using the version of chrome 'Version 76.0.3809.100 (Official Build) (64-bit)', are you using the same version?

**Comment by Mrslapdabass** [comment]
Which anki settings would I need to check?

**Comment by Mrslapdabass** [comment]
I don't know if this helps or not: When highlighted, the 'add card' buttons are clearly there but you just can't see them. Could this be an issue with the yomichan interface not showing the buttons properly? The first image below is with the 'Enable Anki integration' switched on and the second image is it switched off (where the buttons disappear completely).

<img width="499" alt="Screen Shot 2019-08-19 at 04 54 09" src="https://user-images.githubusercontent.com/51394257/63238455-849aa900-c23e-11e9-95ef-d83ca8b55bfa.png">
<img width="497" alt="Screen Shot 2019-08-19 at 04 58 09" src="https://user-images.githubusercontent.com/51394257/63238460-86fd0300-c23e-11e9-9fd0-a2714fcf03d0.png">

**Comment by FooSoft** [comment]
What's likely happening is that AnkiConnect is saying that it cannot create the card with the Anki settings you have set up in the extension for whatever reason. Can you try reinstalling it in Chrome, and re-specifying your settings and see if that helps? Also, could you paste a screenshot of your Anki settings in Yomichan?

**Comment by Mrslapdabass** [comment]
You are a life saver! I deleted and then reinstalled the extension and it's working again. I should of tried that from the beginning but it didn't cross my mind. I am sorry for wasting your time for that!

Although, I have just noticed a couple new issue arise (for chrome & firefox). Have you changed how yomichan grabs sentences?

The 'add card' buttons only work for certain words and are grayed out on the rest of the words. For example, very few words on this wikipedia page are working, but some of the words dotted about work. '時代' and 'により'  from（時代により変動）work, but '変動' doesn't. But then when I use yomichan on '変動' in this response box on github, yomichan works fine. 
https://ja.wikipedia.org/wiki/日本

The second issue is that yomichan isn't grabbing sentences properly anymore: If I create a card using '時代' from the sentence above while on github, the sentence it grabs is "from（時代により変動）work, but" (which I believe is how yomichan used to work: grabbing everything before and after the word up until there is punctuation). If I create the card on wikipedia I just get '日本' as the sentence (for some reason it is grabbing the heading at the top of the page).

**Comment by Geniusssmit** [comment]
Wow, I have the same problem, I read just yesterday and everything was ok, but now I google it

**Comment by Geniusssmit** [comment]
weird... I can add from this https://vndb.org/v25168 "original title" line: 絶対服従 but not from this site https://djt.netlify.com/b/[%E3%82%A2%E3%83%8D%E3%82%B3%E3%83%A6%E3%82%B5%E3%82%AE]%20%E7%9B%BE%E3%81%AE%E5%8B%87%E8%80%85%E3%81%AE%E6%88%90%E3%82%8A%E4%B8%8A%E3%81%8C%E3%82%8A/[%E3%82%A2%E3%83%8D%E3%82%B3%E3%83%A6%E3%82%B5%E3%82%AE]%20%E7%9B%BE%E3%81%AE%E5%8B%87%E8%80%85%E3%81%AE%E6%88%90%E3%82%8A%E4%B8%8A%E3%81%8C%E3%82%8A1/index.html

**Comment by Geniusssmit** [comment]
Actually I can add some words, but most can't

**Comment by Geniusssmit** [comment]
I can add words like 緑 初体験 覆いつくされている but can't 見える 旅行 一歩 一応 etc.

**Comment by Geniusssmit** [comment]
> You are a life saver! I deleted and then reinstalled the extension and it's working again. I should of tried that from the beginning but it didn't cross my mind. I am sorry for wasting your time for that!
> 
> Although, I have just noticed a couple new issue arise (for chrome & firefox). Have you changed how yomichan grabs sentences?
> 
> The 'add card' buttons only work for certain words and are grayed out on the rest of the words. For example, very few words on this wikipedia page are working, but some of the words dotted about work. '時代' and 'により' from（時代により変動）work, but '変動' doesn't. But then when I use yomichan on '変動' in this response box on github, yomichan works fine.
> [https://ja.wikipedia.org/wiki/日本](https://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC)
> 
> The second issue is that yomichan isn't grabbing sentences properly anymore: If I create a card using '時代' from the sentence above while on github, the sentence it grabs is "from（時代により変動）work, but" (which I believe is how yomichan used to work: grabbing everything before and after the word up until there is punctuation). If I create the card on wikipedia I just get '日本' as the sentence (for some reason it is grabbing the heading at the top of the page).

I have the same issue with grabbing sentence, there is some nonsense in my expression field but not what used to be. Is there a quick fix?

**Comment by ilcane87** [comment]
I have the same issue today, can't find a single word I can add though.

Is there a way to roll back to a previous version of yomichan, and to stop it from auto-updating?

**Comment by Geniusssmit** [comment]
> I have the same issue today, can't find a single word I can add though.
> 
> Is there a way to roll back to a previous version of yomichan, and to stop it from auto-updating?

yes, please, I would like too. I thought testing branch was for this type of stuff, but apparently that is not.

**Comment by siikamiika** [comment]
I tested some possible combinations, and it seems that the buttons are missing if you have edited your Anki templates (behind advanced options), preventing the templates from auto-updating. To fix the issue, you should copy your modified template somewhere to preserve your changes, reset the templates to default, and incorporate your modifications to the updated default template. In 1.7.2 Yomichan got a feature that allows you to add page screenshots to the flashcards, and the template doesn't work if a handler for screenshots is missing. I haven't yet tested if it's possible to make the templates work despite missing some of the required handlers.

`{sentence}` for Anki was broken by an off-by-one error in a fix that handles a hack by Google in Docs (https://bugs.chromium.org/p/chromium/issues/detail?id=994302). I'll push a fix for that to master in a moment.

**Comment by Geniusssmit** [comment]
I reinstalled addon but still can't add some words

**Comment by siikamiika** [comment]
@Geniusssmit What dictionaries do you use (including versions) and what is the value of your flashcard's front?

**Comment by Geniusssmit** [comment]
> @Geniusssmit What dictionaries do you use (including versions) and what is the value of your flashcard's front?

![image](https://user-images.githubusercontent.com/24941285/63288236-e00f7a00-c2c4-11e9-8922-deefd0a37358.png)
![image](https://user-images.githubusercontent.com/24941285/63288274-f3224a00-c2c4-11e9-8270-67e8f2d955f3.png)
I can't add most of the words, but some can, just yesterday everything was ok

**Comment by Geniusssmit** [comment]
on the front: <div style='font-family: YUMIN; font-size: 45px;'>{{Expression}}</div>

**Comment by Sabeurre** [comment]
It's seems yomichan doesn't pick up sentences anymore.

**Comment by Geniusssmit** [comment]
> It's seems yomichan doesn't pick up sentences anymore.

yep, no more sentence mining :(

**Comment by FooSoft** [comment]
I just pushed and update with the fix @siikamiika provided; should solve the sentence issues.

**Comment by FooSoft** [comment]
@Geniusssmit your first Anki field is the sentence, and since sentence extraction is broken, you would not have been able to generate the majority of the cards. I'm pretty sure that this will fix your problem, but if it does not, please feel free to reopen this issue.
