### ISSUE TITLE
pitch-accent-graph-render-error in Anki import

### ISSUE THREAD

**Issue by bajidu** [FooSoft/yomichan#1844]
Hi there,
I'm using Anki 2.1 ( Version 2.1.35 (84dcaa86) Python 3.9.6 Qt 5.15.2 PyQt 5.15.4) with Ankiconnect. In addition I'm using Kanjium Pitch Accents rev.pitch1  (which is awesome!) which displays just fine within the browser. Importing from yomichan to anki however yields  "pitch-accent-graph-render-error" although Anki is (at least in principle) able to display svg (one problem might be that the svg definition aren't imported).
Importing from browser throws an error: "An error occurred: Template render error for {pitch-accent-graph}" and the log from the console is:

`Object { ankiNoteErrors: (1) […] }
​
ankiNoteErrors: Array [ Error ]
​​
0: Error: Template render error for {pitch-accent-graph}
​​​
columnNumber: 35
​​​
data: Object { error: Error }
​​​
fileName: "moz-extension://addon-id/js/data/anki-note-builder.js"
​​​
lineNumber: 122
​​​
message: "Template render error for {pitch-accent-graph}"
​​​
stack: "_formatField/<@moz-extension://addon-id/js/data/anki-note-builder.js:122:35\nasync*_stringReplaceAsync@moz-extension://addon-id/js/data/anki-note-builder.js:136:59\n_formatField@moz-extension://addon-id/js/data/anki-note-builder.js:116:27\ncreateNote@moz-extension://addon-id/js/data/anki-note-builder.js:59:53\n_createNote@moz-extension://addon-id/js/display/display.js:1538:44\nasync*_addAnkiNote@moz-extension://addon-id/js/display/display.js:1267:37\n_onNoteAdd@moz-extension://addon-id/js/display/display.js:719:14\n"
​​​
<prototype>: Error.prototype { stack: "", … }
​​
length: 1
​​
<prototype>: Array []
​
<prototype>: Object { … }
display.js:1321:25`
Sorry about the formatting, Firefox won't let me properly export the whole message; but it should be reproducable without a problem.

It is a really minor issue but a fix would be nice; If the problem is somehow on my end please let me know (or probably some workaround which might be enough for my case)!
Thanks for all the work!

**Comment by toasted-nutbread** [comment]
Can you export and share your setting file here?

**Comment by bajidu** [comment]
Hope this helps; I didn't change much except for showing the pitch accent graph. The Anki was a fresh Anki install.

[yomichan-settings-2021-07-22-00-26-06.json.gz](https://github.com/FooSoft/yomichan/files/6859367/yomichan-settings-2021-07-22-00-26-06.json.gz)

**Comment by toasted-nutbread** [comment]
And does this happen for all words, or only specific words? (example?)

**Comment by toasted-nutbread** [comment]
Nevermind, you need to use the marker <code>{pitch-accent-graph<b><i>s</i></b>}</code> instead of `{pitch-accent-graph}`.

**Comment by bajidu** [comment]
You are absolutely right, sorry for the trouble and thanks for the help! Closed!
