### ISSUE TITLE
{sentence-furigana} not working {sentence-furigana-render-error}

### ISSUE THREAD

**Issue by VanillaEssence** [FooSoft/yomichan#1848]
**Description**
Trying to use the {sentence-furigana} option in one of my anki fields. The option did not appear in drop down menu, so I just typed it. Has it not been implemented yet? Cards just show {sentence-furigana-render-error} in the field. Regular {sentence} works fine.

**Browser version**
(92.0.4515.107 (Official Build) (arm64))

**Yomichan version**
(e.g. 20.11.1.1)

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page; zip or rename the resulting file to .txt to attach to the issue.)

**Comment by toasted-nutbread** [comment]
It has not been released yet, it wil be included in the next release.

**Comment by VanillaEssence** [comment]
Very glad to hear it. Sorry for the confusion, looking forward to using it in the next release!
