### ISSUE TITLE
Structured content breaks Anki export?

### ISSUE THREAD

**Issue by Thermospore** [FooSoft/yomichan#1854]
Howdy! This follows from #1853 

I'm currently working on converting a dictionary to yomichan and some people are testing it out for me

I've actually never used the Anki export feature myself and don't have it set up, but I've received reports that it is broken for this dict

I'm guessing this is due to the structured content (it is used in every entry in this dict)

[Here is a link to the dict for testing](https://drive.google.com/file/d/1WzHiIPt5R-7wirM6WOrCAGmdRaU4BygR/view?usp=sharing)

Thanks for taking a look!! :^)

**Comment by toasted-nutbread** [comment]
If by "Anki export" you mean "creating Anki notes/cards", then that is not supported in the released version. The next version will support it.

Also just a note, the uncompressed data for this dictionary is massive large (125mb) and somewhat inefficient (empty "" text and empty tags). This will probably result in a really large database on Firefox, see #1846.

**Comment by Thermospore** [comment]
> If by "Anki export" you mean "creating Anki notes/cards", then that is not supported in the released version. The next version will support it.

Ah sweet, nevermind then! Saw that issue a while back but didn't notice it added support for more than images

> Also just a note, the uncompressed data for this dictionary is massive large (125mb) and somewhat inefficient (empty "" text and empty tags). This will probably result in a really large database on Firefox

Thanks for taking a look!

Yea it's practically an encyclopedia O_O the source data is a 130mb html file

Looks like the yomichan import koj6 is only 63mb uncompressed. I suspect the extra space in my koj7 is from the structured content syntax. Compresses quite well; the koj6 and koj7 zip files are almost the same size!

The empty "" are from the (somewhat lazy) way I convert the html tags; I should really clean those up. And yea the original HTML file has empty/redundant tags, which I should also clean up
