### ISSUE TITLE
Fields {cloze-prefix} and {cloze-suffix} do not make it over to Anki anymore

### ISSUE THREAD

**Issue by Muuse** [FooSoft/yomichan#186]
The {cloze-prefix} and {cloze-suffix} fields do not make it over to Anki anymore. Yesterday (2019-08-18) everything worked fine. It seems like some text-parsing algorithm was changed, and now it only catches the word/phrase that you looked up but fails at catching the sentence around it.

I'm mainly using Yomichan on this news site: https://www3.nhk.or.jp/news/easy/

I'm using Yomichan on a desktop Firefox with the connect app at version 6.
Thank you in advance for any help you can give me!

**Comment by siikamiika** [comment]
Fix one bug (#179), cause another. It's currently fixed in master and hopefully a hotfix is released soon. Sorry for the trouble!

**Comment by Muuse** [comment]
Alright, I'll wait for the fix. Thank you for your help! :)

**Comment by FooSoft** [comment]
Fix has been pushed out for Chrome and Firefox.

**Comment by Muuse** [comment]
Yes, it's working now. Thank you once again! :)
