### ISSUE TITLE
July 2021 Release

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1869]
https://github.com/FooSoft/yomichan/releases/tag/21.7.31.1

### General
* [x] Create [release tag](https://github.com/FooSoft/yomichan/tree/21.7.31.1).
* [x] Create [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.7.31.1).
* [x] Ensure the version is updated in the [manifest](https://github.com/FooSoft/yomichan/blob/21.7.31.1/ext/manifest.json).

### Testing
* [x] Update Chrome testing release.
* [x] Update Firefox testing release.
* [x] Update Firefox [updates.json](https://github.com/FooSoft/foosoft.github.io/blob/master/projects/yomichan/dl/updates.json) and [verify](https://foosoft.net/projects/yomichan/dl/updates.json).
* [x] Upload testing builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.7.31.1).

### Stable
* [x] Update Chrome stable release.
* [x] Update Firefox stable release.
* [x] Upload stable builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.7.31.1).

### Issues to address before stable
* [x] #1873
* [x] #1877

@FooSoft

**Comment by FooSoft** [comment]
Updated testing!

**Comment by Thermospore** [comment]
looks like image import is broken?
![image](https://user-images.githubusercontent.com/35350819/128100372-2b2a2d84-b275-423d-b7a5-272b5cf87278.png)

6 is a dict I already had imported
5 is the same dict, but renamed and then imported with july 2021 release
![image](https://user-images.githubusercontent.com/35350819/128100390-ac008779-ba02-45ca-b8c2-a5fdef362f88.png)

**Comment by toasted-nutbread** [comment]
Well that's fun, this seems to be a timing issue due to the database modifications happening on a separate thread. The issue seems to stem from the worker thread being terminated, which doesn't make sense since the database transaction is already marked as "completed". The issue also does not consistently occur; sometimes the images will be present, sometimes they won't be. Probably a browser bug that needs to be worked around.

**Comment by toasted-nutbread** [comment]
@FooSoft OP updated for release 21.7.31.1, which addressed two issues. Should be stable now.

**Comment by FooSoft** [comment]
Pushed out to testing and stable

**Comment by toasted-nutbread** [comment]
## Patch Release 21.7.31.2

https://github.com/FooSoft/yomichan/releases/tag/21.7.31.2

### General
* [x] Create [release tag](https://github.com/FooSoft/yomichan/tree/21.7.31.2).
* [x] Create [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.7.31.2).
* [x] Ensure the version is updated in the [manifest](https://github.com/FooSoft/yomichan/blob/21.7.31.2/ext/manifest.json).

### Testing
* [ ] Update Chrome testing release.
* [ ] Update Firefox testing release.
* [ ] Update Firefox [updates.json](https://github.com/FooSoft/foosoft.github.io/blob/master/projects/yomichan/dl/updates.json) and [verify](https://foosoft.net/projects/yomichan/dl/updates.json).
* [ ] Upload testing builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.7.31.2).

### Stable
* [ ] Update Chrome stable release.
* [ ] Update Firefox stable release.
* [ ] Upload stable builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.7.31.2).

---

@FooSoft Made a patch that addresses a few bugs: fix for #1881; workaround for #1888.

**Comment by FooSoft** [comment]
Released to testing and stable
