### ISSUE TITLE
Auto-play audio is triggered on some kind of DOM update after scanning

### ISSUE THREAD

**Issue by cyphar** [FooSoft/yomichan#1872]
**Description**

I have auto-play audio enabled, but I've noticed that whenever I use it on some websites (most notably YouTube), after scanning a word, the same audio will be replayed several times long after the word has been looked up and the pop-up closed (it appears to be whenever YouTube does some kind of dynamic DOM manipulation, such as navigating to the home page or selecting a new video to watch). I've noticed it on other sites as well, but YouTube is the one that immediately comes to mind.

This doesn't happen *every* time, but I just managed to reproduce it a few times by looking up the word 高い on the front page of YouTube and then clicking on the YouTube logo to "reload" the page. The only way to stop this from happening in a tab that has been "cursed" is to refresh the tab.

**Browser version**
Firefox 90.0.2, openSUSE Tumbleweed

**Yomichan version**
Yomichan 21.6.30.2

**Exported settings file**
[yomichan-settings.zip](https://github.com/FooSoft/yomichan/files/6915332/yomichan-settings.zip)

**Comment by toasted-nutbread** [comment]
#1873 should fix the issues, but I wasn't able to reproduce exactly what you mentioned. That PR fixes:
* Auto-play not being cancelled when the popup is hidden.
* Auto-play occurring due to a settings change when the popup is hidden.

**Comment by cyphar** [comment]
I'll ping you again if I notice the issue again after the update.
