### ISSUE TITLE
Auto-play doesn't work in the Search window

### ISSUE THREAD

**Issue by grospoulpe** [FooSoft/yomichan#1881]
**Description**
Auto-play search result audio doesn't work in the Search Window (but it works in the popup windows / if I click the Play audio button)

**Browser version**
Chrome Version 92.0.4515.131 (Official Build) (64-bit)
Edge Version 92.0.902.67 (Official build) (64-bit)

**Yomichan version**
Yomichan 21.7.31.1

**Exported settings file**
in case (Auto-play search result audio is enabled)
[yomichan-settings-2021-08-10-18-54-38.zip](https://github.com/FooSoft/yomichan/files/6963872/yomichan-settings-2021-08-10-18-54-38.zip)

**Comment by toasted-nutbread** [comment]
Fixed; I will leave the issue open as a reminder that I might need to set up a patch release (will see if anything else comes up first).
