### ISSUE TITLE
Yomichan doesn't add audio to anki

### ISSUE THREAD

**Issue by mavicena21** [FooSoft/yomichan#1887]
**Description**
Yomichan doesn't add audio to anki when i click add buton, 2 days ago everything is normal suddenly yesterday yomichan starting error, yomichan doesn't add audio to anki card (but i don't receive any warning or errror code) i tried reinstalling yomichan and then yomichan goes back to normal, but today the same problem repeated again with warning and error code

**Browser version**
Chrome Version 92.0.4515.131 (Official Build) (64-bit))

**Yomichan version**
Yomichan
21.7.31.1

**Exported settings file**
[yomichan-settings-2021-08-11-03-43-07.txt](https://github.com/FooSoft/yomichan/files/6965715/yomichan-settings-2021-08-11-03-43-07.txt)

![image](https://user-images.githubusercontent.com/77527946/128966186-03a940af-8e8e-45c7-8b7d-e0e66a591b05.png)
![anki_SGJJrVtX9w](https://user-images.githubusercontent.com/77527946/128966700-eecbbb80-9a6c-4694-9d60-60fe1f96238e.png)

**Comment by toasted-nutbread** [comment]
Your audio template is named `{audiox}`.

```handlebars
{{#*inline "audiox"}}
    {{~#if definition.audioFileName~}}
        [sound:{{definition.audioFileName}}]
    {{~/if~}}
{{/inline}}
```

**Comment by mavicena21** [comment]
yes now i have changed that, but when i click add there is still no audio

**Comment by mavicena21** [comment]
thanks, it work now

**Comment by DDDespair** [comment]
Having a similar error with all my fields. Seems to be some sort of timeout error? Same situation, worked before the new the recent update. https://imgur.com/a/Va6A78x Also looking at templates, my audio is already updated to the format above. I'm not very good at this kind of stuff so let me know if there's something else you need.

**Comment by toasted-nutbread** [comment]
@DDDespair See #1888, it could be that the browser that you're using is out of date (and has a bug). If that's not the issue, let me know (and share which browser you're using).
