### ISSUE TITLE
Anki integration doesn't work

### ISSUE THREAD

**Issue by MarcoPolo-PasTonMolo** [FooSoft/yomichan#1888]
**Description**
Anki integration doesn't work, to reproduct install yomichan and anki connect, open up anki install a random dictionary and set appropriate settings for anki integration to work. Try to add a word to anki via yomichan. Get error "Template render error".

This is the error I get in the console.
![image](https://user-images.githubusercontent.com/79863493/129084649-5da3dc67-2491-4692-96cd-c6bb369de12b.png)

Also there's an error in the handlebars template that says "Cannot destructure dicionaryEntry of (unknow property)" or something along those lines. If I change the handlebars I get "Timeout"

**Browser version**
Brave Version 1.18.70 Chromium: 87.0.4280.101 (Official Build)

**Yomichan version**
21.7.31.1

**Comment by toasted-nutbread** [comment]
@MarcoPolo-PasTonMolo can you try updating your browser? And could you also share an export of your settings file?

@MohamSmith / @mavicena21 what browsers/version are you using, and have either of you modified the handlebars templates?

**Comment by MarcoPolo-PasTonMolo** [comment]
Updating the browser fixed it.
[yomichan-settings-2021-08-10-17-58-47.txt](https://github.com/FooSoft/yomichan/files/6976981/yomichan-settings-2021-08-10-17-58-47.txt)

**Comment by MohamSmith** [comment]
> @MarcoPolo-PasTonMolo can you try updating your browser? And could you also share an export of your settings file?
> 
> @MohamSmith / @mavicena21 what browsers/version are you using, and have either of you modified the handlebars templates?

This solved it. Just wanted to say thanks for developing this plugin, it has done so much for my learning!

**Comment by toasted-nutbread** [comment]
The latest release [21.7.31.2](https://github.com/FooSoft/yomichan/issues/1869#issuecomment-898072579) includes a workaround for this issue which allows Anki integration to still work for the most part. However, the underlying issue seems to have been a browser bug, so if anyone else comes across a similar issue, try updating the browser first.
