### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#189]
I have recently been looking into some optimizations in order to get Yomichan's word scanning to perform faster, particularly on lower-powered mobile devices where scanning is inevitably going to be somewhat slower. Before I jump in and start making unsolicited pull requests, I would like to gauge if this is interesting or worthwhile.

Some preliminary profiling seems to indicate that it's possible to speed up the typical scan by roughly 3x on Chrome, Firefox, and Firefox Mobile. It also looks like the Edge support PR (#188) can be improved to run at nearly-usable speeds, in case that feature is desirable (using the same optimizations, nothing per-browser).

Would it be worthwhile to pursue these optimizations? If so, I can provide further details on what all could be done.

**Comment by erasedff** [comment]
Some optimizations would be great. Reading long-ish articles in Japanese always makes me want to open Firefox and use Rikaichamp instead. Rikai's scan is pretty much instant while Yomichan is quite sluggish, particularly if you set it to mimic Rikai behavior (no hotkey scan, autohide results, low delay).

**Comment by toasted-nutbread** [comment]
I am closing this issue as I now largely consider it to be completed. There may be some more opportunities for optimization, but they are beyond the scope of what I had in mind for this issue. While it's difficult to quantify exactly, the speed improvements feel quite noticeable. Doing a screen recording with a pre-optimized Yomichan and post-optimized Yomichan running simultaneously, post-optimized Yomichan consistently shows the updated popup several frames before pre-optimized Yomichan.

With all of these changes, Yomichan is in a fairly usable state as an extension for Edge. It's certainly not as fast as on Firefox or Chrome, but it's tolerable. Further, some Edge-specific differences may be irrelevant after Edge switches to be Chromium-based. So it's probably viable to release on the Edge extension store if @FooSoft has any interest in doing that.
