### ISSUE TITLE
{pitch-accents} value doesn't show up in Anki

### ISSUE THREAD

**Issue by c-ehrlich** [FooSoft/yomichan#1890]
**Description**
In my Anki Card format I send the {pitch-accents} value to one of the fields. With the newest version of Yomichan, this seems to be broken. All the other fields fill in as normal, but the field that should receive the {pitch-accents} value remains blank.

Sending a different value to that field in Anki works. Sending the {pitch-accents} value to a different field doesn't work. The bug persists after restarting Anki and Edge, and rebooting.

I believe that this issue is new with 21.7.31.1, this would make sense in terms of when the bug started appearing. But not 100% sure about this. I could try to reproduce in previous versions if that might be helpful.

**Browser version**
Edge 91.0.864.41

**Yomichan version**
21.7.31.1

**Exported settings file**
[yomichan-settings-2021-08-11-21-11-40.json.zip](https://github.com/FooSoft/yomichan/files/6971433/yomichan-settings-2021-08-11-21-11-40.json.zip)

![Screenshot 2021-08-11 at 23 10 56](https://user-images.githubusercontent.com/8353666/129103911-f2289730-de2f-46f6-b4c4-a573a621b3d4.jpg)

Here is an example of a card created before the bug:
![image](https://user-images.githubusercontent.com/8353666/129107146-50711190-c323-498d-bdd8-af99ae6e8a63.png)

**Comment by toasted-nutbread** [comment]
Not sure if you had any custom modifications, but it looks like the handlebars templates are messed up. Try resetting those to the default value.

_Advanced_ => _Configure Anki card templates…_ => _Reset Templates_

**Comment by c-ehrlich** [comment]
Yes, it was related to handlebars. Thanks!
