### ISSUE TITLE
Crash on Raspberry Pi when importing (image heavy?) dictionary

### ISSUE THREAD

**Issue by hellosup** [FooSoft/yomichan#1896]
**Description**
Other dictionaries, including the large 広辞苑 第七版 and the test dictionary with a few small images in it, import fine in Yomichan on the Raspberry Pi 4 but when I import 旺文社国語辞典 第十一版 it gets to step 5: post-processing data quickly, but then it goes painfully slowly for about 5 minutes and then the window becomes unresponsive and Yomichan crashes soon after. In that time the CPU usage starts off high but then slowly dwindles down to <1%. 旺文社国語辞典 has a lot of images and the images are very big compared to the test dictionary so I suspect that's why its having a problem with this one and not the test dictionary. 

I don't expect this to ever get fixed and I understand that I could be hitting the limitations of the Raspberry Pi (though I don't think I am) but I thought I would document it in case it comes up again in the future.

Steps to reproduce:
1) Install Yomichan on Chromium
2) Import 旺文社国語辞典 第十一版

**Browser version**
Chromium 88.0.4324.187 on Raspberry Pi 4

**Yomichan version**
21.7.31.2

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page; zip or rename the resulting file to .txt to attach to the issue.)

**Comment by toasted-nutbread** [comment]
I take it that means that it never reaches _Step 6: Importing data_?

**Comment by hellosup** [comment]
That's right yeah, doesn't get past like .01% of step 5.

**Comment by toasted-nutbread** [comment]
Interesting. Step 5 of 6 is basically when the extension does all the validation of image data, so maybe there's an issue how that's handled on the RPi. It could be an issue with multithreading, since at that point, the import thread has to send data to the main UI thread to load and process the image data.

**Comment by toasted-nutbread** [comment]
Could you also share the model of the RPi4 you're using?

**Comment by hellosup** [comment]
It's a Raspberry Pi 400, with 4GB of memory

**Comment by toasted-nutbread** [comment]
#1926 should fix this issue. Images should now be loaded in serial rather than parallel.

**Comment by toasted-nutbread** [comment]
Should be fixed in latest release; re-open if issues persist.
