### ISSUE TITLE
Purging Yomichan data when extension no longer functional

### ISSUE THREAD

**Issue by dddlr** [FooSoft/yomichan#1916]
So I bricked my installation when installing a [dictionary file](https://drive.google.com/file/d/1Mmr7IIy9CWv9YlCezrOE7JK-7PBV_CyI/view?usp=sharing) - I believe the dictionary installation dialog box hanged on the last step? I wanted to diagnose this problem further so I could format it into a proper issue, but it looks like the Yomichan settings page now hangs indefinitely and none of the functionality works anymore.

Now I'm a bit stuck on how to clear all of my Yomichan data to return to a working Yomichan installation again, especially as the settings page is no longer accessible.

What I've tried:
- Removing extension and adding it again
- "Restore settings to their original defaults" in Chromium settings

Setup:
Yomichan, v21.7.31.2
Chromium 92 on Linux

Any help would be much appreciated. Cheers!

**Comment by toasted-nutbread** [comment]
Can you check to see if you are getting any errors?
* Open chrome://extensions/
* Enable developer mode
* On the Yomichan entry, Inspect Views => background.html
* In the window that pops up, check to see if the dev console has any errors listed in it.

**Comment by dddlr** [comment]
Looks like I spoke too soon - half an hour later, removing and reinstalling Yomichan seems to do the trick in removing the dictionary data this time. Not quite sure why it worked this time but not half an hour ago.

I've also been able to reproduce the dictionary installation issue that caused this in the first place - I'll see if I can diagnose it with your advice and report it as a new issue. Thanks!

**Comment by toasted-nutbread** [comment]
There is sometimes a difference between _Uninstall -> Reinstall_ and _Uninstall -> Restart browser (close all tabs) -> Reinstall_, so that could have potentially played a factor.

**Comment by dddlr** [comment]
Ah that would make sense, thank you :)
