### ISSUE TITLE
Yomichan freezes when installing very large dictionary file

### ISSUE THREAD

**Issue by dddlr** [FooSoft/yomichan#1918]
**Description**

Yomichan freezes and stops working when installing a 400MB dictionary file.

Reproduction steps:

1. Install Yomichan on Chromium
2. Install [this dictionary file](https://drive.google.com/file/d/1Mmr7IIy9CWv9YlCezrOE7JK-7PBV_CyI/view?usp=sharing) through Settings
3. Yomichan hangs indefinitely on Step 5 at 0%. There didn't seem to be any console output through Developer Tools at any stage in the process.

![Screenshot from 2021-08-31 13-39-06](https://user-images.githubusercontent.com/2908767/131428433-c6a56db6-1821-443f-b9ec-40e868a9ae08.png)

4. CPU usage is maxed out, and settings page is unresponsive and no longer loads. Extension stops working until extension data is cleared (i.e. through removing extension and reinstalling).

(follow up to #1916)

**Browser version**
Chromium 92 on Linux

(Attempting this on Firefox 92 causes entire computer to freeze)

**Yomichan version**
21.7.31.2

**Exported settings file**
N/A

**Comment by Thermospore** [comment]
As a point of reference, the dictionary seems to import without issue on my setup. I believe step 5 involves image data? For that step it took maybe 15 seconds at 0%, another 15 seconds until 10%, then quickly jumped to 100%

dxdiag
![image](https://user-images.githubusercontent.com/35350819/131434798-ad5ba6f7-e853-4e30-8d9d-d83fbc225fe1.png)

yomichan info
```
Extension version: Yomichan (development build) 21.7.31.2
Platform: Windows
Browser: Chrome
Language: ja
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
AnkiConnect version: Unknown (Anki not running or connected)
Installed dictionaries: 新明解国語辞典 第五版, Weblio 古語辞典, KANJIDIC (English), B短, B長, IC, AJ, 故事ことわざの辞典, 実用日本語表現辞典, 漢字源, 精選版　日本国語大辞典, 新明解国語辞典　第七版, W, 大辞林 第三版, 大辞林 第三版（画像のみ）, JJ, 広辞苑 第六版, 学研 四字熟語辞典, 新明解四字熟語辞典, 明鏡国語辞典, 岩波国語辞典 第六版, ハイブリッド新辞林, JMdict, JMnedict, 旺文社国語辞典 第十一版, 広辞苑 第七版, デジタル大辞泉, 広辞苑 第七版 TESTBED
```

**Comment by Thermospore** [comment]
maybe related? hangs at step 5 too #1896

**Comment by dddlr** [comment]
Ah, thanks for the insight.

Here's my Linux setup
![Screenshot from 2021-08-31 15-10-44](https://user-images.githubusercontent.com/2908767/131435602-b717d63c-1567-41ff-b617-93ac28ecd09a.png)

I tried installing the dictionary on Windows just now (dualbooting) with the latest version (can't check at the moment but it should be 21.7.31.2?) and it looks like it does work there. It took 10 minutes for the whole installation process from start to finish, including about a minute where it seemed to be stuck at 0% in Step 5 before finally progressing. It also incidentally continued to 102% in Step 6 before finishing...

![2021-08-31 15_25_53-DirectX Diagnostic Tool](https://user-images.githubusercontent.com/2908767/131438822-93437042-38df-4ee9-9bc3-a00c0bc6976b.png)

For comparison, the installation process hung for at least 15 minutes on Linux before I called it a day. (I had no dictionaries installed beforehand on both Linux and Windows)

**Comment by toasted-nutbread** [comment]
I'm not sure why step 5/6 is giving issues, all it's doing is the worker thread sends image data to the main page to load and validate, then returning the resolution. I'll see if I can test the dictionary file provided to see if I can see something going wrong, based on the comment that it hangs at 0% for a while, but note that I am not running Linux, so I might not see exactly the same issue.

#1921 fixes the [DKC2](https://dkcspeedruns.com/DKC2_102%25 "102%") bug.

**Comment by toasted-nutbread** [comment]
#1926 should fix this issue. Images should now be loaded in serial rather than parallel.

**Comment by dddlr** [comment]
Can confirm #1926 fixes the issue. Huge thank you for your hard work! :+1:

I can't believe I didn't do this earlier, but I made some recordings just now to show the big difference it makes.

Before: (21.8.31.0 development build from Chrome Web Store)

https://streamable.com/1ubwyl

After: (latest, i.e. commit f68ad1f)

https://streamable.com/nfx4m3

Thanks again!
