### ISSUE TITLE
August 2021 Release

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1922]
https://github.com/FooSoft/yomichan/releases/tag/21.8.31.1

### General
* [x] Create [release tag](https://github.com/FooSoft/yomichan/tree/21.8.31.1).
* [x] Create [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.8.31.1).
* [x] Ensure the version is updated in the [manifest](https://github.com/FooSoft/yomichan/blob/21.8.31.1/ext/manifest.json).

### Testing
* [x] Update Chrome testing release.
* [x] Update Firefox testing release.
* [x] Update Firefox [updates.json](https://github.com/FooSoft/foosoft.github.io/blob/master/projects/yomichan/dl/updates.json) and [verify](https://foosoft.net/projects/yomichan/dl/updates.json).
* [x] Upload testing builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.8.31.1).

### Stable
* [x] Update Chrome stable release.
* [x] Update Firefox stable release.
* [x] Upload stable builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.8.31.1).

### Issues to address before stable
* [x] #1926
* [x] #1927
* [x] #1932
* [x] #1933
* [x] #1934

**Comment by FooSoft** [comment]
Testing release updated

**Comment by Thermospore** [comment]
Deleting jmnedict on my laptop; it froze at 100% 👀 On my desktop it deleted without issue
![image](https://user-images.githubusercontent.com/35350819/132106848-93550e2e-e0a4-49ab-ab8b-4ab8174de87b.png)

**Comment by Thermospore** [comment]
force closed the tab, re-opened, and it appears to be deleted now
![image](https://user-images.githubusercontent.com/35350819/132106963-d6056a76-0a7f-43b9-b77f-25be9885c882.png)

**Comment by Thermospore** [comment]
Seems to have re-imported without issue (I was just updating it)

**Comment by toasted-nutbread** [comment]
#1932 may fix the hang at 100%, but the original issue wasn't consistent to reproduce. It should at least improve the behaviour if an incomplete deletion is interrupted.

**Comment by Thermospore** [comment]
Huh, maybe I had another settings tab open in my other window, not sure

Tried deleting it again just to see if it was consistent or not (with only one settings window open). This time it didn't hang at 100%, and the dict was removed from the dictionaries list. But I did get this when I re-imported:
![image](https://user-images.githubusercontent.com/35350819/132149615-f3ac2fa5-8a20-4905-8aeb-e1c7cbd00ad7.png)

steps to reproduce:
1. start deleting a dictionary
2. close the "Dictionaries" popup
3. close the "Tasks in progress:" popup at the bottom of the screen
4. re-open the "Dictionaries" popup
5. wait for the deletion to complete (everything should still appear as normal)
6. start importing a dictionary (the "Tasks in progress:" popup returns, with the previous deletion remaining at 100%)

**Comment by toasted-nutbread** [comment]
> maybe I had another settings tab open in my other window

The multiple tabs was a separate but related issue where the settings on both page would locked in an infinite update loop, triggered by the other. That issue could be reproduced reliably; the hang at 100% seemed to be unrelated.

**Comment by Thermospore** [comment]
> The multiple tabs was a separate but related issue

ah I see

> run an integrity check, see if anything looks odd.

Integrity check looks good. Results were identical between my laptop and desktop as well

**Comment by toasted-nutbread** [comment]
@FooSoft Release updated to 21.8.31.1; should be stable now.

**Comment by FooSoft** [comment]
Updated stable and testing releases.
