### ISSUE TITLE
Yomichan no longer works within Google Docs since switching to Canvas Rendering

### ISSUE THREAD

**Issue by bforks** [FooSoft/yomichan#1923]
Hey Everyone, 

Google Docs is slowly migrating everyone from [HTML DOM rendering to Canvas rendering](https://workspaceupdates.googleblog.com/2021/05/Google-Docs-Canvas-Based-Rendering-Update.html) for the actual document page area. I was curious if y'all had a plan to support it?

Thank you for your time.

**Comment by toasted-nutbread** [comment]
There will be a workaround supported in the next release, [https://github.com/FooSoft/yomichan/releases/tag/21.8.31.0](21.8.31.0).

#1670

**Comment by bforks** [comment]
This is such good news! I use Yomichan everyday, and depend on it for my Japanese studies. Thank you again!!!
