### ISSUE TITLE
[Feature Request] Add support for structured content classes

### ISSUE THREAD

**Issue by seth-js** [FooSoft/yomichan#1925]
Could you add support for custom classes in structured content?

Ex:
`{ "type": "structured-content", "content": [ { "tag": "div", "class": "test-class", "content": "test" } ] }`

I could then just use custom CSS to change the appearance of certain elements, rather than having to repeat my styles throughout the dictionary. Also, I would have more style attributes available than what is currently provided through structured content.

**Comment by toasted-nutbread** [comment]
That presents somewhat of a usability issue, where now in addition to installing a dictionary, users also have to modify Yomichan's settings to get it to work properly, and additionally modify Anki's configuration if they want to export them.

**Comment by seth-js** [comment]
Sharing the dictionary would definitely take a bit more work if a dictionary used this feature. Since I'm using it for myself, I don't mind doing the extra work each time I import the dictionary. If a custom class is too much to ask, would it be possible to add fontColor to structured content styling? The whole reason I wanted the feature was to add color to certain definitions.

**Comment by Thermospore** [comment]
I'm curious, what dictionary are you working on?

**Comment by seth-js** [comment]
It's not officially supported by Yomichan, but I created a Chinese dictionary I've been using. Everything works well, but it would be nice to have an extra definition entry for each word that has the word with tone coloring.

Ex:
![example](https://user-images.githubusercontent.com/83692925/132078342-06d7956c-5b1d-40f5-8ecc-d698db4bcbb4.png)

**Comment by toasted-nutbread** [comment]
#1930 should be usable to resolve your issue once it's included in a release; check the issue link for some details.
