### ISSUE TITLE
[Feature Request] Use regexMatch as a conditional

### ISSUE THREAD

**Issue by Skillesss** [FooSoft/yomichan#1928]
Nesting `regexReplace` becomes a mess and when one of the inner `regexReplace` fails to replace anything, the text still gets replaced by one of the outer nest resulting in a messed up format.
This feature would really be useful with something like `{selection-text}`.

For example:
If `regexMatch` matches `^[a-z]` in `{selection-text}` then return `true`. If no match then return `false`.
Pretty much like `hasMedia` and `getMedia`

My use case would be to reformat English only definitions and leave the Japanese definition alone when selected.

---
Yomichan 21.7.31.2

**Comment by toasted-nutbread** [comment]
Can you post an example handlebars snippet of what you are trying to do?

**Comment by Skillesss** [comment]
This is the simplest could make it while still getting the result I'm aiming for. 
```handlebars
{{#*inline "selection-text"}}
    {{~#if (hasMedia "selectionText")}}
        {{#regexReplace "^;\s" "" "g"}}
        {{#regexReplace "\s{4,}" "; " "g"}}
        {{#regexReplace "(<br>)+" "    " "g"}}
        {{#multiLine}}{{#getMedia "selectionText"}}{{/getMedia}}{{/multiLine}}
        {{/regexReplace}}
        {{/regexReplace}}
        {{/regexReplace}}
    {{/if~}}
{{/inline}}
```

**Comment by toasted-nutbread** [comment]
Based on:

>  If `regexMatch` matches `^[a-z]` in `{selection-text}` then return `true`. If no match then return `false`.

Are you wanting to do something like:

```handlebars
{{#if (regexMatch "pattern" "i" "content")}}
    Matched
{{else}}
    Not matched
{{/if}}
```

**Comment by Skillesss** [comment]
Yes! Exactly that!

**Comment by toasted-nutbread** [comment]
Okay, #1934 will add support for using it that way.
