### ISSUE TITLE
[Feature Request] Allow custom mapping for the hiragana and katakana handlebar tags

### ISSUE THREAD

**Issue by Lolle2000la** [FooSoft/yomichan#1947]
When converting katakana to hiragana, words like 'オーストラリア' will become 'おうすとらりあ', however I would like the 'ー' to remain in the hiragana. In wanakana.js, I can achieve this with custom kana mapping. Would it be possible to expose that or at least add the option for 'ー' to remain in the result?

**Comment by toasted-nutbread** [comment]
Kana conversion is not performed using wanakana; besides the `ー` character, are there any other special cases you'd like considered?

**Comment by Lolle2000la** [comment]
Personally the `ー` character is enough. I thought I had more, but most are already achievable.

Anyway, thank you! I really appreciate this!

**Comment by toasted-nutbread** [comment]
Cool; #1965 adds an option to the `{{#hiragana}}` helper, check the issue for an example.
