### ISSUE TITLE
[Feature Request] Add marker for frequency info

### ISSUE THREAD

**Issue by aiko-tanaka** [FooSoft/yomichan#1950]
Just some kind of {freq-info} marker or something like that.

Use case/rationale:
I usually just mine whatever words I come across in order to build a personalized sentence bank. I don't study every word however since some words are rarely used, so I simply suspend them, but I still keep them for future reference.
Having the frequency data inside the card would help me decide whether or not to study/suspend/delete certain cards.

Thanks.

**Comment by toasted-nutbread** [comment]
`{frequencies}` exists

**Comment by aiko-tanaka** [comment]
I had no idea, thanks!
