### ISSUE TITLE
"Select matched text" bug?

### ISSUE THREAD

**Issue by Ceynou** [FooSoft/yomichan#1953]
**Description**
"Select matched text" option can't be disabled in yomichan search window, hovering a word and pressing ctrl+c effectively copy the what's hovered, this option works fine outside this page.

![image](https://user-images.githubusercontent.com/41862916/134260433-947a46d8-54db-417c-8a92-9e48dc000fe1.png)

**Browser version**
92.0

**Yomichan version**
21.8.31.1

**Exported settings file**
[yomichan-settings-2021-09-21-23-19-58.txt](https://github.com/FooSoft/yomichan/files/7206795/yomichan-settings-2021-09-21-23-19-58.txt)

**Comment by Ceynou** [comment]
Oh and selecting something you wrote in google search for exemple, then hovering it will unselect it

**Comment by toasted-nutbread** [comment]
Your second profile doesn't have _Select matched text_ disabled.

**Comment by toasted-nutbread** [comment]
> Oh and selecting something you wrote in google search for exemple, then hovering it will unselect it

The popup window is focused when it is opened, which transfers focus from any selected text input, thus deselecting the text field.

**Comment by Ceynou** [comment]
It doesn't seem to change a thing but I've seen the deleted comments and you're probably right about the focus thing, it seems that the selection is kinda saved and you can clic and drag what you selected before(which is now unselected) and it will move, but it's not really an issue for me I was just stating this weird(?) behavior in case it could ruin your code idk.
We can close this

**Comment by toasted-nutbread** [comment]
> it's not really an issue for me I was just stating this weird(?) behavior in case it could ruin your code

It's a known behaviour (well, at least for me) that hasn't been too much of an issue. Something related is how normal text selection (outside of a textbox) appears as gray instead of blue when the popup is opened. This is also because the popup is focused, and the reason the popup receives focus is so it can accept keyboard inputs for hotkeys, navigation, etc.

Closing per comment.
