### ISSUE TITLE
[Bug] Yomichan crashing

### ISSUE THREAD

**Issue by morning-paradigm** [FooSoft/yomichan#1955]
**Description**
After upgrading to the [latest Vivaldi Snapshot](https://vivaldi.com/blog/desktop/new-capture-and-sync-uis-vivaldi-browser-snapshot-2431-3/), Yomichan has started crashing. The pop-up and the settings page appear for a second and then turn into a dead bird. If I try reloading Yomichan and crashing it again several times, other random extensions start crashing at the same time, and in the end it crashes all enabled extensions.
I suspect it might be related to the new Chromium version (94.0.4606.57) it was built with.

**Browser version**
Vivaldi 4.3.2431.3

**Yomichan version**
21.8.31.1

**Exported settings file**
Can't export since the setting won't open. Is there another way to backup my settings so I can try reinstalling the extension?
<img width="429" alt="Screenshot 2021-09-24 at 01 33 58" src="https://user-images.githubusercontent.com/39773982/134565226-c17d5a96-6fda-4d95-81af-045c04f95457.png">

**Comment by toasted-nutbread** [comment]
Can you try reverting to a previous version?

**Comment by morning-paradigm** [comment]
I'm not sure. The last and only time I tried to downgrade Vivaldi, it messed up my profile (apparently they're not backwards compatible). Also I'm not sure if this issue won't persist in the next update.
I've tried a few things to investigate the issue:

1. I've cleared storage cache, it stopped crashing, however as soon as I imported dictionaries back it started crashing again (with existing settings)
2. Then I decided to reinstall the extension and try out default settings. I tried kanjidic_english first and it worked fine, but then I tried setting up Anki integration, set up the deck for terms, and then it immediately crashed after I set up the deck for kanji
3. Just having jmdict_english imported causes crashing even with default settings
4. It doesn't crash on the welcome, search or help pages (search does crash when you look up a word)
5. I've tried Firefox and ungoogled Chromium with my settings imported, they worked just fine, so it seems to be specifically a Vivaldi issue

Also I couldn't see any errors with developer mode turned on in extensions as I should have.
I'll report this issue to Vivaldi, although I'm not sure if it's going to be addressed since it doesn't seem to affect other extensions (I couldn't find any topics on their forum).

**Comment by morning-paradigm** [comment]
Alright, I've finally managed to get an error message in developer mode, if it's of any help.

> Yomichan 21.8.31.1 has encountered a problem. Originating URL: https://www.post.japanpost.jp/question/faq/index.html Error: Unexpected response of type undefined ({"action":"termsFind","params":{"text":"お問い合わせ\n\t\t\t","details":{},"optionsContext":{"depth":0,"url":"https://www.post.japanpost.jp/question/faq/index.html","modifiers":["shift"],"modifierKeys":["shift"]}}})
> 
> Context
> https://www.post.japanpost.jp/question/faq/index.html
> 
> Stack Trace
> ```js/core.js:729 (anonymous function)```

**Comment by toasted-nutbread** [comment]
I am able to reproduce the issue, but it's very likely to be a browser-specific issue which is beyond the control of Yomichan. It seems to have to do with the sandboxed `<iframe>` that exists within the popup `<iframe>`.

Also, it might be too late for this, but the settings can be exported from the info page (/info.html) using the _Export settings_ link.

**Comment by toasted-nutbread** [comment]
This crash can be reproduced from Yomichan's info.html page by running the following code:

```js
const frame = document.createElement('iframe');
frame.src = '/template-renderer.html';
document.body.appendChild(frame);
```

`template-renderer.html` is a sandboxed webpage according to `manifest.json`. The crash occurs even if `template-renderer.html` is empty. The crash does not occur for a non-sandboxed webpage.

You can use this info to report the issue to Vivaldi.

**Comment by morning-paradigm** [comment]
Thanks. Send them a report. Hopefully it'll be fixed.

**Comment by morning-paradigm** [comment]
Fixed in both [Vivaldi Snapshot](https://vivaldi.com/blog/desktop/translate-panel-vivaldi-browser-snapshot-2465-3/) and [stable](https://vivaldi.com/blog/desktop/update-three-4-3/).
Thanks for your input once again.
