### ISSUE TITLE
逸 breaks furigana?

### ISSUE THREAD

**Issue by Thermospore** [FooSoft/yomichan#1956]
**Description**
selected results from a search of `逸*`:
![image](https://user-images.githubusercontent.com/35350819/134754057-a45b771d-0606-45ec-99a0-9f7de2585c63.png)
![image](https://user-images.githubusercontent.com/35350819/134754059-d5a28fe7-0952-4c68-aa91-d242d13009da.png)
![image](https://user-images.githubusercontent.com/35350819/134754064-83d859ec-34e7-4738-988d-792f7bc933c8.png)
![image](https://user-images.githubusercontent.com/35350819/134754071-58e408e3-43fe-418f-b25f-8fcb63699fa9.png)
![image](https://user-images.githubusercontent.com/35350819/134754075-f4c408a3-41a1-4b65-8142-8f53b7d9a7b4.png)
etc

The only results are from 大辞林 第三版 and デジタル大辞泉, which manually added a bunch of old kanji forms etc.

here is the 大辞林 第三版 for testing purposes:
[[Monolingual] 三省堂 大辞林 第三版2.zip](https://github.com/FooSoft/yomichan/files/7229005/Monolingual.2.zip)

**install info**
```
Extension version: Yomichan (development build) 21.8.31.1
Platform: Windows
Browser: Chrome
Language: ja
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
AnkiConnect version: Unknown (Anki not running or connected)
Installed dictionaries: 新明解国語辞典 第五版, Weblio 古語辞典, KANJIDIC (English), B短, B長, IC, AJ, 故事ことわざの辞典, 実用日本語表現辞典, 漢字源, 精選版　日本国語大辞典, 新明解国語辞典　第七版, W, 大辞林 第三版, 大辞林 第三版（画像のみ）, JJ, 広辞苑 第六版, 学研 四字熟語辞典, 新明解四字熟語辞典, 明鏡国語辞典, 岩波国語辞典 第六版, ハイブリッド新辞林, 旺文社国語辞典 第十一版, デジタル大辞泉, JMdict, JMnedict, 広辞苑 第七版
```

**Exported settings file**
[yomichan-settings-2021-09-25-02-01-55.txt](https://github.com/FooSoft/yomichan/files/7229009/yomichan-settings-2021-09-25-02-01-55.txt)

**Comment by toasted-nutbread** [comment]
The issue was a missing range of unicode characters for rare characters, which is fixed in #1960.

While testing I also noticed an issue with string normalization during import, which has been fixed in #1959. Thanks for bringing this up, I probably wouldn't have noticed this second issue otherwise.
