### ISSUE TITLE
September 2021 Release

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1975]
https://github.com/FooSoft/yomichan/releases/tag/21.9.30.1

### General
* [x] Create [release tag](https://github.com/FooSoft/yomichan/tree/21.9.30.1).
* [x] Create [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.9.30.1).
* [x] Ensure the version is updated in the [manifest](https://github.com/FooSoft/yomichan/blob/21.9.30.1/ext/manifest.json).

### Testing
* [x] Update Chrome testing release.
* [x] Update Firefox testing release.
* [x] Update Firefox [updates.json](https://github.com/FooSoft/foosoft.github.io/blob/master/projects/yomichan/dl/updates.json) and [verify](https://foosoft.net/projects/yomichan/dl/updates.json).
* [x] Upload testing builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.9.30.1).

### Stable
* [x] Update Chrome stable release.
* [x] Update Firefox stable release.
* [x] Upload stable builds to the [GitHub release](https://github.com/FooSoft/yomichan/releases/tag/21.9.30.1).

### Issues to address before stable
* [x] #1977

**Comment by FooSoft** [comment]
Updated testing!

**Comment by toasted-nutbread** [comment]
@FooSoft Updated one issue for the stable version, should be good now.

**Comment by FooSoft** [comment]
Updated!
