### ISSUE TITLE
[Feature Request] Allow setting some dictionaries to only appear in child popups

### ISSUE THREAD

**Issue by JakobBruenker** [FooSoft/yomichan#1980]
Motivation: If you're trying to do the monolingual transition, i.e. switch from using bilingual to using monolingual dictionaries, it can be useful to look up the definition for a word in a monolingual dictionary, and then look up any unknown words in that definition in a bilingual dictionary.

Yomichan's "child popup" feature, i.e. scanning a word within a Yomichan popup to get the Yomichan popup for that word, seems perfect for that - except that if you enable both monolingual and bilingual dictionaries, it will be hard to avoid seeing the monolingual definition in the parent popup, giving away the meaning before you have a chance to try understanding the monolingual definition.

If it were possible to set monolingual dictionaries to only show up in child popups, this would not be an issue.

**Comment by toasted-nutbread** [comment]
This can be done by adding a second profile with the preferred dictionary enabled and giving it a condition that _Popup Level > 0_.

**Comment by JakobBruenker** [comment]
Very cool, thank you!
