### ISSUE TITLE
ttu ebook reader and yomichan error

### ISSUE THREAD

**Issue by gamefreezy** [FooSoft/yomichan#1983]
**Description**
(Describe what the issue is, if it is reproducible, and if possible, how to reproduce it.)
I was reading on ttu ebook reader and after the update on Oct 13th i was unable to use yomichan. I tried to refreshing, relaunching the browser reset my computer, cleared the local settings on the ebook site and reset settings on yomichan and I am unable to get yomichan to work with the reader. Before the latest update there were no issues. 

**Browser version**
Google Chorme Version 94.0.4606.81 (Official Build) (64-bit)

**Yomichan version**
21.9.30.1

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page; zip or rename the resulting file to .txt to attach to the issue.)

**Comment by ttu-ttu** [comment]
Related to #1985

**Comment by toasted-nutbread** [comment]
Closing as this should be resolved now.
