### ISSUE TITLE
Vertical text does not show popup anymore

### ISSUE THREAD

**Issue by Shadowlauch** [FooSoft/yomichan#1985]
**Description**
When I am in a frame with only vertical text it will scan the text and highlight the word, but it will not show any popup. If there is any none vertical text it will show the popup even if you move over to the vertical text but it won't move the popup. This all worked yesterday.

First try scanning the vertical text: https://codepen.io/Shadowlauch/pen/porjyQJ

**Browser version**
Chrome 94.0.4606.81

**Yomichan version**
21.9.30.1

**Comment by Shadowlauch** [comment]
After some additional probing I found out that this only happens if Vertical text positioning is not set to "Same as horizontal text"

**Comment by toasted-nutbread** [comment]
Thanks for finding this, I'll work on setting up a patch release.
