### ISSUE TITLE
Can I use yomichan to detect English words?

### ISSUE THREAD

**Issue by WeiChienHsing** [FooSoft/yomichan#200]
I want to use it as a reading tool to read some English novels.

**Comment by siikamiika** [comment]
Yomichan is meant for Japanese text, so you're probably better off with some other extension or software such as [GoldenDict](http://goldendict.org/). I found [this extension](https://krv5vignesh.github.io/) on Google but didn't test.

If you want to use Yomichan for some of its features not available in the above software, it would be possible to import an English dictionary but I'm not aware of any ready-made one.

Either way, it isn't officially supported as mentioned in the end of the FAQ section of readme: https://github.com/FooSoft/yomichan#frequently-asked-questions

**Comment by FooSoft** [comment]
As @siikamiika said, other languages are outside the scope of Yomichan.
