### ISSUE TITLE
jsonschema2pojo does not generate POJO from schemas

### ISSUE THREAD

**Issue by kuroahna** [FooSoft/yomichan#2007]
I'm looking to generate POJOs from the [yomichan json schemas](https://github.com/FooSoft/yomichan/tree/master/ext/data/schemas) using [jsonschema2pojo](https://www.jsonschema2pojo.org/), but unfortunately it doesn't not work.

[dictionary-index-schema.json](https://github.com/FooSoft/yomichan/blob/master/ext/data/schemas/dictionary-index-schema.json) produces a valid POJO

![image](https://user-images.githubusercontent.com/85209455/141661229-2024690a-9a08-4484-96c6-8d710a47cc98.png)

But when I try [dictionary-term-bank-v1-schema.json](https://github.com/FooSoft/yomichan/blob/master/ext/data/schemas/dictionary-term-bank-v1-schema.json) or [dictionary-term-bank-v3-schema.json](https://github.com/FooSoft/yomichan/blob/master/ext/data/schemas/dictionary-term-bank-v3-schema.json), I just get a empty response.

![image](https://user-images.githubusercontent.com/85209455/141661257-351c6474-d8de-40bb-b229-82c0f9863587.png)

These are the settings I am using 

![image](https://user-images.githubusercontent.com/85209455/141661209-04d50c3b-e841-48cb-b8df-59186f4fa3f7.png)

Is this expected? How can I get POJOs to be generated from these schema files?

**Comment by toasted-nutbread** [comment]
The same result happens with
```json
{
  "type":"array"
}
```
so the issue is probably due to the root being an `array` instead of an `object`.

**Comment by toasted-nutbread** [comment]
It also looks like some features aren't supported by that tool: https://github.com/joelittlejohn/jsonschema2pojo/issues/831

**Comment by kuroahna** [comment]
Hm, okay, thanks for looking into it! I think I'll settle with manually creating my own POJOs and serialization that align with the schema

**Comment by toasted-nutbread** [comment]
As a workaround for the `'array'` issue, you could potentially wrap the entire schema:
```jsonc
{
  "type": "object",
  "properties": {
    "data": // Yomichan schema goes here
  }
}
```
