### ISSUE TITLE
"Parse text using installed dictionaries" and "Parse text using MeCab" feature clarification?

### ISSUE THREAD

**Issue by kuroahna** [FooSoft/yomichan#2011]
Under the Text Parsing section, it says
> Yomichan is able to scan the sentence surrounding a term and parse individual words of the query text on the search page. This information can be added to Anki cards to provide additional context.

And 
> Parse text using installed dictionaries
>
> Words are scanned by automatically advancing in the sentence after a matching word.

> Parse text using MeCab
>
> Requires a native component to be installed that Yomichan will connect to.
> MeCab is a third-party program which uses its own dictionaries and parsing algorithm to decompose sentences into individual words. In order for Yomichan to use it, both MeCab and a native messaging component must be installed. A setup guide can be found here.

1. Does enabling "Parse text using installed dictionaries" and/or "Parse text using Mecab" affect the parsing algorithm when scanning text? Or does this simply just affect the automatic sentence generation to anki with the `{sentence}` marker in the anki card format settings? 
2. Can both "Parse text using installed dictionaries" and "Parse text using Mecab" be enabled at the same time?
3. What does "Parse text using installed dictionaries" exactly do? The description "words are scanned by automatically advancing in the sentence after a matching word" doesn't exactly clarify it to me. Does this mean it uses entries from your installed dictionaries to find new words?
4. What is the advantages/disadvantages of using "Parse text using Mecab"? Does it provide more accurate parsing compared to Yomichan's built-in parsing algorithm when scanning text? Is it faster?

If possible it would be nice to clarify some of these questions in the main settings page itself

**Comment by toasted-nutbread** [comment]
1. It affects the parsed text at the top of the standalone search page (see reference images below), but it does not affect the `{sentence}` marker. The `{sentence}` marker only uses the internal non-Mecab parser (currently).
2. Yes, if Mecab is installed. There will be a dropdown menu on the search/popup page to change the parse results.
3. It's a somewhat naive algorithm for parsing words in a sentence. It does this by finding the longest matched text using the installed dictionaries and assuming that is a word. It does not do any sort of sophisticated contextual analysis of whether word boundaries actually form grammatically correct sentences.
4. Mecab is probably more sophisticated and accurate, though I cannot speak to the exact implementation details. The internal parser will have some results that aren't always so great (see reference image 2), but in the general case it's acceptable.

See also:
https://en.wikipedia.org/wiki/MeCab

Reference image 1:
![image](https://user-images.githubusercontent.com/11037431/141873523-59548fbf-16a2-4b29-90bd-6faac2fab675.png)
Reference image 2 (internal parser's not-so-great results for full-width romaji words):
![image](https://user-images.githubusercontent.com/11037431/141874112-7bf7363e-0c36-45e9-b2a3-7924481b5eda.png)

**Comment by kuroahna** [comment]
oh wow, thank you!

> Yomichan is able to scan the sentence surrounding a term and parse individual words of the query text **on the search page**. This information can be added to Anki cards to provide additional context.

I honestly didn't know that there was a "search page" available in Yomichan 😅  (click the magnifying glass)

![image](https://user-images.githubusercontent.com/85209455/141879308-bdc2deaa-c21a-434d-b377-7cc2b0d0c316.png)

That one's definitely on me. 

> 1. It affects the parsed text at the top of the standalone search page (see reference images below), but it does not affect the `{sentence}` marker. The `{sentence}` marker only uses the internal non-Mecab parser (currently).

So just for further clarification, enabling the "Parse text using Mecab" feature doesn't affect when you hold SHIFT + hover over a word to look at the definition, for example? It's only for analyzing words in a sentence in the search page?

Perhaps a quick suggestion to slightly clear up any confusion is that in the explanation:
> Yomichan is able to scan the sentence surrounding a term and parse individual words of the query text **on the search page.** This information can be added to Anki cards to provide additional context.

The "on the search page" part should be a hyperlink to the search page itself. I honestly didn't know that Yomichan had a useful search page feature 😄

**Comment by toasted-nutbread** [comment]
> So just for further clarification, enabling the "Parse text using Mecab" feature doesn't affect when you hold SHIFT + hover over a word to look at the definition, for example? It's only for analyzing words in a sentence in the search page?

99% of the time, yes. There are rare occasions where the embedded popup will show the parsed text, but it's for very specific content that cannot be scanned any other way.
