### ISSUE TITLE
Yomichan can not find/parse partially matching phrases (like 浮かばれる from 浮かば)

### ISSUE THREAD

**Issue by Argolics** [FooSoft/yomichan#2012]
**Description**
I was reading something or other in japanese and stumbled upon a parsing bug (or maybe it's working as intended):
Yomichan could not parse the '浮かばなし' part in '何にも浮かばなし', while both [Jisho](https://jisho.org/search?utf8=%E2%9C%93&keyword=%E6%B5%AE%E3%81%8B%E3%81%B0) and my local version of Jmdict (used in Goldendict) could at the very least find 浮かばれる / 浮かばれない by searching 浮かば.
Not entirely sure what could (and should) be done on the Yomichan's side, but this is at least third time i discovered something like this - unfortunately i have not saved earlier examples - for at first i thought those words/phrases were just missing from the dictionary itself, even though i have a fairly freshly converted one for Yomichan.
It's however not very convenient and i would consider Yomichan refusing to parse/search for even 浮 alone (or with か, as in this example it would give lotsa more partial matches) a bug or at least an oversight and QOL/usability problem.

**Browser version**
Firefox 95 beta

**Yomichan version**
21.9.30.2

**Comment by toasted-nutbread** [comment]
Jisho is implicitly searching for "浮かば*" (wildcard suffix), which is why "浮かばれる" and "浮かばれない" come up on Jisho. Yomichan can search wildcards on the search page if you explicitly include the asterisk, but it does not search for wildcards otherwise. This is why "浮かば" or "浮" will not bring up any results.

If "浮かばなし" is an inflected form of "浮かばない", the reason it doesn't come up is because Yomichan currently does not have a deinflection rule for なし => ない. Do you know what conjugation rules are being used to inflect 浮かぶ to get 浮かばなし?

Do you have an example of this word in the context of a sentence?

**Comment by Argolics** [comment]
I am really sorry, i double checked the source and turns out it's my mistake all along - it should have been "何にも浮かばない" and Yomichan both parses and translates that correctly now (my incorrect transcribing was truly baffling - hence this bug report).
[Jisho](https://jisho.org/search?utf8=%E2%9C%93&keyword=%E6%B5%AE%E3%81%8B%E3%81%B0%E3%81%AA%E3%81%84)'s too giving the correct results now.
Additionally here's the [source](https://nitter.net/pic/media%2FFEJ_YFbaIAInqQs.jpg%3Fname%3Dorig) of this phrase for anyone willing to check it.

By the way, shall i just close this now, or maybe repurpose/rename the bug to be something about pop up mode (optionally, and probably opt-in in settings) performing wildcard searches too? Irregardless of my erroneous initial issue, i think this could be a useful feature for anyone willing to suffer the performance/speed penalty (if any).

**Comment by toasted-nutbread** [comment]
> By the way, shall i just close this now, or maybe repurpose/rename the bug to be something about pop up mode (optionally, and probably opt-in in settings) performing wildcard searches too? 

I think it's worth making a new issue for it, it will make it easier to search for. You can close this afterwards.

**Comment by Argolics** [comment]
Sure thing, done in #2013.
