### ISSUE TITLE
Cards not recognized in Anki

### ISSUE THREAD

**Issue by fello3** [FooSoft/yomichan#2014]
I have an issue with cards not being recognized and duplicates being created in the same Anki deck. See here: https://imgur.com/a/lAuPOwx

Firefox 94.0.1

Yomichan 21.9.30.2

**Comment by toasted-nutbread** [comment]
Can you share:
1. An export of your settings file
2. An export of your Anki profile

**Comment by fello3** [comment]
[yomichan-settings-2021-11-21-15-40-28.json.txt](https://github.com/FooSoft/yomichan/files/7576551/yomichan-settings-2021-11-21-15-40-28.json.txt
[ankicollection211121.colpkg.txt](https://github.com/FooSoft/yomichan/files/7576552/ankicollection211121.colpkg.txt)
)
Settings & anki collection without media
(Remove the .txt)

**Comment by toasted-nutbread** [comment]
Assuming you still have the term `二つ` in your deck, can you try running this script from the dev console on the Yomichan search page (F12 to open):
```js
(async () => {
  let response;
  try {
    const body = '{"action":"canAddNotes","params":{"notes":[{"fields":{"Vocabulary-Kanji":"二つ","Vocabulary-Furigana":"<ruby>二<rt>ふた</rt></ruby>つ","Vocabulary-Kana":"ふたつ","Vocabulary-English":"<div style=\\"text-align: left;\\">two</div>","Vocabulary-Audio":"","Vocabulary-Pos":"num","Caution":"","Expression":"","Reading":"","Sentence-Kana":"","Sentence-English":"","Sentence-Clozed":"","Sentence-Audio":"","Sentence-Image":"","Notes":"JMdict (English)","Core-Index":"","Optimized-Voc-Index":"","Optimized-Sent-Index":""},"tags":["yomichan"],"deckName":"Japanese::Core 2k/6k Optimized Japanese Vocabulary with Sound","modelName":"Yomichan","options":{"allowDuplicate":false,"duplicateScope":"collection","duplicateScopeOptions":{"deckName":null,"checkChildren":false,"checkAllModels":false}}}]},"version":2}';
    response = await fetch('http://127.0.0.1:8765', {
      method: 'POST',
      mode: 'cors',
      cache: 'default',
      credentials: 'omit',
      redirect: 'follow',
      referrerPolicy: 'no-referrer',
      body
    });
  } catch (e) {
    console.log('error1', response, e);
    return;
  }

  if (!response.ok) {
    console.log('error2', response);
    return;
  }

  let responseText = null;
  try {
    responseText = await response.text();
  } catch (e) {
    console.log('error3', response);
  }

  console.log('responseText', responseText);
})();
```

And then share the output of that. Should look something like:
```
Promise {<pending>}
responseText [false]
```

**Comment by fello3** [comment]
Did I do it right?
https://imgur.com/a/nTgVzbU

**Comment by toasted-nutbread** [comment]
Run it from the standalone Yomichan search page (or settings page), which is probably at the url:

`chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/search.html`

You can also open this page from the extension's browser button in the toolbar.

**Comment by fello3** [comment]
Got it, here you go!
https://imgur.com/a/iwYDcLl

**Comment by fello3** [comment]
I changed "checkAllModels":false to "checkAllModels":true and I think it gives the wanted response now.
https://imgur.com/a/kNaAEjh
Is that some setting I can change to make it work?

**Comment by toasted-nutbread** [comment]
Yes, enable _Advanced_ on the settings page and then enable _Check for duplicates across all models_ under _Anki_ settings.

**Comment by fello3** [comment]
It works, thank you! Incredible work by the way. I extend my gratitude on behalf of all users of the extension. I wish I could be of help to anyone as much as you have helped me and my Japanese classmates! どうもありがとうございました。
