### ISSUE TITLE
Remove Timestamp from Subtitles

### ISSUE THREAD

**Issue by AsuraAce** [FooSoft/yomichan#2026]
would be nice if you could add the option to remove timestamps from subtitles. I've read that
Yomichan does that automatically but it doesn't work with asbplayer.

I use Yomichan for sentence mining and have the problem that Yomichan always adds the 
timestamp at the end, even though it is not visible in the video itself.

![image](https://user-images.githubusercontent.com/13394741/143851263-5dcbc92a-b3f5-4806-bcdd-72262b9e11fe.png)

would be nice if we could use the "Text Replacement Patterns" on strings 
before they are copied to Anki as well.

**Comment by toasted-nutbread** [comment]
You can use the `regexReplace` template helper in your Anki field templates.
https://github.com/FooSoft/yomichan/blob/master/docs/templates.md#regexreplace

You could also try enabling _Layout-aware scanning_ on the settings page (enable _Advanced_) to see if that fixes the issue.

**Comment by AsuraAce** [comment]
Thank you, regexReplace is pretty much what I was looking for, this will help with other things
I don't want in my subs as well.

(already had Layout-Aware Scanning enabled, it helps to some degree.)
