### ISSUE TITLE
Yomichan doesn't seems to run

### ISSUE THREAD

**Issue by WingHaa** [FooSoft/yomichan#2027]
**Description**
Clicking on Gear; Magnifying Glass and Question Mark button doesn't do anything. Clicking Off button to On then reclick extension icon again will show as Off. All options in Extension Options are also the same. Every function not working and also can't export import settings
![image](https://user-images.githubusercontent.com/95285518/144038835-9eae2d64-6773-4897-b9f5-2f0abeceb059.png)
![image](https://user-images.githubusercontent.com/95285518/144039308-5b967f69-ecf1-45b8-b5cd-d0aaf5c5f284.png)

**Browser version**
Vivaldi | 4.3.2439.65

**Yomichan version**
21.10.31.1

**Exported settings file**
Function not working. Please let me know if there's a manual way to export.

**Comment by toasted-nutbread** [comment]
Was the extension previously working for you, or is this a fresh install?

Can you check vivaldi://extensions/, enable _Developer mode_, and then click the _background.html_ link under Yomichan's _Inspect views_ section. See if there are any errors listed in there.

This behaviour corresponds to Yomichan's background page misbehaving, but not sure what exactly it might be.

**Comment by WingHaa** [comment]
Last time I know it working was somewhere around 48 hours ago. I have custom handlebar and a few dictionaries installed. Here's the errors shown in console.
![image](https://user-images.githubusercontent.com/95285518/144163756-dec381a0-1b02-4202-b4cf-9109abe1b41d.png)

**Comment by toasted-nutbread** [comment]
Looks like your install is corrupted somehow, try reinstalling from the Chrome store. You should be able to remove it from chrome://extensions and then reinstall it, and I think that shouldn't wipe the save data unless you close the browser between the steps. You may want to make a backup of the extension's saved data beforehand, look up where Vivaldi stores its user profile folder.

**Comment by WingHaa** [comment]
Seems like that fixed it. Thank you for the support.
