### ISSUE TITLE
Is it possible to use structured content to embed hyperlinks inside yomichan dicts?

### ISSUE THREAD

**Issue by aiko-tanaka** [FooSoft/yomichan#2031]
Been checking some monolingual dicts on how to do such but the only examples I can find are HTML tags without an attribute (e.g. div, img, etc.)
So is it possible to do something like `type: a, attribute(href):<link to website>? ` 

On a related note, I tried googling about how to format structured content but I couldn't find something that matches the way yomichan uses it, so, would also appreciate help regarding that.

**Comment by toasted-nutbread** [comment]
Currently, there is not a way to do this, but it could probably be added.

The structure is "documented" using a JSON schema [here](https://github.com/FooSoft/yomichan/blob/f2102ade4cfe97be4182bb22d1ae4f609d2364a7/ext/data/schemas/dictionary-term-bank-v3-schema.json#L4).

**Comment by aiko-tanaka** [comment]
Thanks!
would be nice to have something like that.
