### ISSUE TITLE
Git LFS?

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#2037]
@FooSoft Since you have recently added several zip files directly to the repository, do you think it would be useful to set those up using git LFS? I can update that if you agree.

**Comment by FooSoft** [comment]
@toasted-nutbread the last time I used it was several years ago, so things might have improved but... git-lfs is a nightmare.

* Storage and transfer limited to 1GB per month for the *entire user account* unless you want to pay GitHub money specifically for LFS.
* Once something is stored in git-lfs you essentially cannot delete it... meaning that it will continue to count against your quota. Going through and wiping the commit that added the object in the first place does not help. You basically have to wipe and re-create the repo.
* There is no actual downside to using binaries inside vanilla git unless you plan to do heavy iteration on them (bloats size of repo), or you want to upload large files (I think GitHub starts complaining at 40MB or so).
* General lack of familiarity of git-lfs from developers, meaning you have to explain the extra step and even then people will get it wrong.
* The technical implementation of git-lfs was pretty much garbage where pulling down objects can fail depending on latency. I remember running into this while in Japan. I had good internet access, but higher ping to GitHub. There was an ongoing issue about this where the maintainer couldn't figure out what is up for like 6 months. May still be broken actually, lol.

**Comment by FooSoft** [comment]
Hah, so apparently this repo is the one I've actually had the issues with in using git-lfs. There is absolutely nothing in the history of this repo that should be contributing to this, but nevertheless I am not getting this 1.5GB back :smile: 

![Screenshot from 2021-12-17 10-19-25](https://user-images.githubusercontent.com/544478/146590355-1429e158-586e-40a7-abc3-1c315803a2f2.png)

**Comment by toasted-nutbread** [comment]
> Storage and transfer limited to 1GB per month for the entire user account unless you want to pay GitHub money specifically for LFS.

Forgot about that, that's probably a dealbreaker for using on the entire repository.

> There is no actual downside to using binaries inside vanilla git unless you plan to do heavy iteration on them (bloats size of repo), or you want to upload large files (I think GitHub starts complaining at 40MB or so).

Yeah, my only worry was with regards to updating the dictionaries (JMdict) or adding more, but I suppose that's not that frequent. I've seen repos without LFS have clone times blown out to huge durations because of this.

> General lack of familiarity of git-lfs from developers, meaning you have to explain the extra step and even then people will get it wrong.

These days, with up-to-date versions of git, it's been mostly transparent in my experience.

---

Other thoughts: would it potentially be a useful idea to put binary downloads (mainly just the dictionary .zips) on an orphan branch? This would make the cloning process not need to pull that data down for standard development, and would make it easier to track changes to the dictionary files, since the history would only include them.

**Comment by FooSoft** [comment]
The cynic in me thinks that this is a GitHub marketing strategy. Get people to use git-lfs and then once they start hitting these limits, force them to either pay money or recreate the the repository. At the same time, they are adding limits to normal git, to force people to start moving to git-lfs. 

> These days, with up-to-date versions of git, it's been mostly transparent in my experience.

It's just an extra package to install (at least on Linux). If you were to naively install only git, and then attempt to clone a project that uses git-lfs, you would get get stuck with only a partially populated workspace (and not be told that something is missing).

> Other thoughts: would it potentially be a useful idea to put binary downloads (mainly just the dictionary .zips) on an orphan branch? This would make the cloning process not need to pull that data down for standard development, and would make it easier to track changes to the dictionary files, since the history would only include them. Would also make it easier to extract/transfer/move/delete to another location if ever necessary (perhaps unlikely).

That's a good call, although we could probably just create a whole new repository, something like "yomichan-dicts" and dump all the blobs in there. That being said, the combined size of all the dictionaries is only 46MB (compared to 74MB for the rest of the repo), so I am not too concerned about this at this point. If it ever does get bad, we can easily migrate the data elsewhere with [bfg](https://rtyley.github.io/bfg-repo-cleaner/) (rewrite history and force push).

**Comment by toasted-nutbread** [comment]
> It's just an extra package to install (at least on Linux).

Ah, that's probably the difference in my usage; the Windows installer includes a bunch of extra packages by default these days, which includes lfs and gui.

That being said, I'm fine with leaving the dictionaries in master.

---

This is somewhat of an aside, but the only potentially extra consideration is that licenses for all dictionaries in the repo should be included somewhere. This is already basically handled for the current ones, but it would apply to anything added/changed in the future, kind of like the pitch accents dictionary.

Technically, I don't think the core of Yomichan should require any licensing information outside the 3rd party Javascript libraries, since Yomichan doesn't include or support directly using any proprietary data formats. It's all converted to a different format prior to use and requires a user to explicitly import.

I guess my point with that is that this license information below may not be required as part of the core of Yomichan, but rather as part of the relevant dictionary .zip files. (This is how the pitch accents dictionary handles attribution.)
https://github.com/FooSoft/yomichan/blob/70fa701c906fa4319e0d62818fe5737e983b49ef/ext/legal.html#L48-L55

**Comment by FooSoft** [comment]
You are correct -- by default Yomichan ships with no dictionaries, and the user has to import them. That being said, there could probably be an argument made that these are the "official" dictionaries supported by the extension, and it is expected that most of the users will download at least some of them in order to have a working product. Since compliance is not that big of a deal, we may as well just do it for the core even though as you accurately pointed out, we don't technically have dependencies here.

This isn't something I have a very strong opinion about though. I think as long as we aren't just dumping dictionaries with no attribution whatsoever we are unlikely to have problems.
