### ISSUE TITLE
Sentence parsing does not recognize vertical period (︒) as sentence stop

### ISSUE THREAD

**Issue by justremember** [FooSoft/yomichan#2045]
**Description**
I'm using Yomichan on a PDF (sample here [sample.pdf](https://github.com/FooSoft/yomichan/files/7808227/sample.pdf)) opened in [PDF.js](https://mozilla.github.io/pdf.js/web/viewer.html). The "save to anki" feature does not recognize the vertical periods ︒ at all, instead copies the entire page as the sentence.
![image](https://user-images.githubusercontent.com/14817065/148073834-2946befd-261d-4f33-b562-5371f28c95d3.png)
Instead, the feature should only copy the sentence the word is located in, as signified by the periods (︒).

**Browser version**
Firefox 95.0.1 (64-bit)

**Yomichan version**
Yomichan 21.10.31.1

**Comment by FLESHNIK** [comment]
Yomichan settings -> Text Parsing -> Sentence termination characters - Configure -> Add > Terminator -︒ -  At end

**Comment by justremember** [comment]
It works. Thank you.
