### ISSUE TITLE
Yomichan not detecting text on vertical-rl + touch screen

### ISSUE THREAD

**Issue by ChaseOxide** [FooSoft/yomichan#2049]
**Description**
Conditions to reproduce:
- Detect word by touching screen (never tested on non-Android device, but pretty sure it's the way Yomichan handles touch event)
- Set `writing-mode: vertical-rl` on `html` or `body`
- Have the document overflow (as in make it horizontally scrollable)

Test html:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" name="viewport">
    <style>
      html {
        writing-mode: vertical-rl;
        font-size: 50px;
      }

      .extra {
        width: 5000px;
      }
    </style>
  </head>
<body>
  <div class="container">
    <div>こんにちは</div>
    <div class="extra"></div>
  </div>
</body>
</html>
```
It will work if either of these changes are made:
- `writing-mode: vertical-rl` gets moved to `.container`
- remove `width: 5000px` from `.extra`
- remove `writing-mode: vertical-rl`

**Browser version**
Kiwi Browser 98 (Android)

**Yomichan version**
21.10.31.1

**Exported settings file**

**Comment by toasted-nutbread** [comment]
This seems to be a browser bug in Chromium-based browsers.

Bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1292815

**Comment by toasted-nutbread** [comment]
According to [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1292815#c29), the bug should be fixed in Chrome 99, so this can be closed accordingly.
