### ISSUE TITLE
[Feature Request] scanning popup content with different dictionary

### ISSUE THREAD

**Issue by Hiwoyn** [FooSoft/yomichan#2050]
My goal with this feature is to stay focus on my main reading, I would like to use a Japanese dictionary but use an English one when scanning popup content.
![image](https://user-images.githubusercontent.com/35316996/149438642-394c1e13-5614-4941-8262-9661971da80b.png)

Thank you very much.

**Comment by Thermospore** [comment]
You can do this by creating a second profile with the english dict enabled, and setting the condition like so:
![image](https://user-images.githubusercontent.com/35350819/149442482-ba58ee05-1204-4007-a662-6bf5b5f2bc92.png)
