### ISSUE TITLE
{audio} field blank even when audio exist

### ISSUE THREAD

**Issue by RfzVd** [FooSoft/yomichan#2064]
**Description**

The {audio} field always gives empty result. The audio can be played fine on the popup. Here's a picture for clarification, using the default template, result is empty after pressing the Test button, no error messages: https://i.imgur.com/Xnkfe5F.png. Other fields I tested worked.

**Operating System**

Debian Linux 10/Buster

**Browser version**

Firefox 91.5.0esr (64bit)
Brave Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (64-bit)

These are the newest version available on the system, but if they look too old I can try and see if I can use the standard release of Firefox.

**Yomichan version**

Yomichan 21.10.31.1
Yomichan (development build) 21.10.31.1

**Exported settings file**
[yomichan-settings-2022-02-05-06-43-54.txt](https://github.com/FooSoft/yomichan/files/8007561/yomichan-settings-2022-02-05-06-43-54.txt)

**Comment by toasted-nutbread** [comment]
Is this issue purely for the test field on the settings page, or are you having an issue when generating cards?

It's currently expected that the test field on the settings page has this behaviour. Media content isn't generated, so the `hasMedia` function will return `false` and empty content will be generated.

**Comment by RfzVd** [comment]
The default template indeed works when actually generating the cards (I started with a custom template that didn't work when generating cards and went to troubleshoot it with the test field). Sorry for the trouble, and thanks.
