### ISSUE TITLE
[Feature Request] Don't select matched text if user selected some text manually

### ISSUE THREAD

**Issue by oakkitten** [FooSoft/yomichan#2071]
Unless I am mistaken, when the option “Select matched text” is on, the only way to copy some text from the page without turning off Yomichan is to select text and press `Ctrl-C` while still holding the left mouse button. It would be nice to be also able to select text after releasing the mouse button—and also via the context menu.

I imagine that it works like this; Yomichan selects matched text only when user has no manually selected text on the page, and user must dismiss their selection by clicking on the page to make Yomichan resume selecting matching text.

**Comment by Ceynou** [comment]
I assume you're using "no key", so this is a problem you can avoid using a modifier key for scanning.
Also you just need to have your cursor between two characters to not scan anything and leave your selection still.
