### ISSUE TITLE
Anki integration error

### ISSUE THREAD

**Issue by bungthebadger** [FooSoft/yomichan#2072]
**Description**
I've been trying to solve this issue for a while with no avail, the integrator throws me an error constantly saying: 
```
"{
    "action": "version"
}

_invoke@moz-extension://ad5cb2c7-d504-451e-bc27-5918486d184a/js/comm/anki.js:185:27"
```
To do a quick run down of what I've already did: 

- I've tried reinstalling Yomichan and Ankiconnect multiple times
- I've tested to see if I can connect to localhost and I can, it displays `AnkiConnect v.6`
- I've excluded Anki from my AV
- I've tried various versions of Anki including the latest version (2.1.49)
- I've ran the console codes to give me the log file (which is attached) since I was looking over at [#327](https://github.com/FooSoft/yomichan/issues/327) to see if it could help me out, mine says version 2 for the decks in the .txt as well. The result is 
![image](https://user-images.githubusercontent.com/34408241/154814625-f3c0cd0c-b81d-48c7-bcdc-dbc0b33d7455.png)
- Finally, no error is given for the card templates

If it also helps, I was following animecard's guide for mining with Yomichan and using the handlebar for my templates: https://animecards.site/yomichansetup/

**OS version**
Windows 10: Feature 20H2 (build 19042.1526)

**Browser version**
Firefox: 97.0.1 (64-bit)

**Yomichan version**
22.2.2.0

**Anki Version**
Version 2.1.33 (3f403040)

[log.txt](https://github.com/FooSoft/yomichan/files/8102762/log.txt)

**Comment by toasted-nutbread** [comment]
> I've been trying to solve this issue for a while with no avail, the integrator throws me an error constantly saying:

I assume you're seeing this issue on the Settings page?

One other things you could do is debug the connection:
1. Open [about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox)
2. Find Yomichan's entry and click the _Inspect_ button
3. Select the _Network_ tab
4. Open the Settings page in a new tab
5. See what happens back on the _Network_ tab
6. Share any info about that here

**Comment by bungthebadger** [comment]
> I assume you're seeing this issue on the Settings page?

Yes, the issue is on the settings page for Yomichan. 

> One other things you could do is debug the connection:

This is my result after hitting the "Enable Anki Integrator" button a few times:
![image](https://user-images.githubusercontent.com/34408241/154894584-e1b612d3-2e6d-4f3c-b2d3-4bb58bc94954.png)
![image](https://user-images.githubusercontent.com/34408241/154894703-7c1282e6-cb9f-41ff-a7a3-16cc497985f0.png)
![image](https://user-images.githubusercontent.com/34408241/154894730-159e3b9c-67a7-48aa-8931-58803305925e.png)

As far as I'm understanding, the connection is blocked to my Anki or Anki is blocked though I'm unsure of how to solve that.

**Comment by toasted-nutbread** [comment]
Check your settings, you might be missing the port from the _AnkiConnect server address_ setting; it should be `http://127.0.0.1:8765`.

**Comment by bungthebadger** [comment]
Odd, my issue is fixed I believe? It's strange given I've tried that method before and nothing came to fruition of it, it may have been because I was messing with Ankiconnect on my Anki when I was attempting to figure out my issue solo.

![image](https://user-images.githubusercontent.com/34408241/155027326-e71d0249-7891-4470-9619-05c7e043ccfa.png)

It still however gives me the "connection failure" with the same error even though I'm now able to connect and make cards with Yomichan:

![image](https://user-images.githubusercontent.com/34408241/155027448-818010f0-d33a-4c10-b683-4d3072263467.png)

But asides from that, all else is working fine and as intended. Thank you for the help!
