### ISSUE TITLE
[Feature Request] Clickable links in definitions

### ISSUE THREAD

**Issue by Twinov** [FooSoft/yomichan#2078]
I have a daijisen dictionary which displays definitions like this one:  
![image](https://user-images.githubusercontent.com/23278147/155611465-8036f948-b631-4cea-b0de-067bc0266811.png)
As you can see, there's a link to https://weblio.hs.llnwd.net/e7/img/dict/sgkdj/images/112719.jpg in it, but it isn't clickable. Would it be possible to add link support for web links and have them export to Anki clickable as well? Currently it's just plain text. Thank you!

**Comment by Thermospore** [comment]
In any case, there is a newer version of that dict with the images embedded and some other improvements :)
![image](https://user-images.githubusercontent.com/35350819/155636488-c3c54adb-358e-4526-a174-4cfc76e02e10.png)

https://learnjapanese.link/dictionaries

**Comment by Twinov** [comment]
Thank you!
