### ISSUE TITLE
[Feature Request] Option to add notes from any website (GitHub pages) using AnkiConnect and Anki Integration of this extension

### ISSUE THREAD

**Issue by krmanik** [FooSoft/yomichan#2080]
Hi,
I have implemented some web apps that used to create Anki deck. Such as
- https://github.com/krmanik/image-occlusion-in-browser
- https://github.com/krmanik/ocloze

The web apps work by adding notes to JSZip and sql.js db. But it needs to download the generated deck then import.

So, my feature request is that, is it possible to let the web pages use the AnkiConnect and yomichan's Anki Integration to add notes using JavaScript to Anki?

Also it will be useful to have separate addon as `Anki Integration` for web developer to use AnkiConnect.

I have tried something like this
```js
var id = "ogmnaimimemjmbakcfefmnahgdfhfami";  // yomichan's extension id

console.log("This is content script's message");
chrome.runtime.sendMessage(id, { data: document.title }, function (response) {
    console.log(response);
});
```

Thanks

**Comment by krmanik** [comment]
I have created a sample extension for this.
[anki-integration](https://github.com/krmanik/anki-integration)

**Comment by Capu-Johann** [comment]
test
