### ISSUE TITLE
Yomichan popup doesn't go away/gets stuck on browser version of microsoft word

### ISSUE THREAD

**Issue by foolishstrawberry** [FooSoft/yomichan#2086]
**Description**
When you shift and hover over a word on the browser version of microsoft the pop-up will not disappear if you click elsewhere on the page like normal. If you hover over another word it will change and move location but you still cannot get the window to disappear without refreshing the page. I have the "Force HTML-based rendering for Google Docs" turned on (issue still persists if turned off). 

**Browser version**
Firefox 98.0.1 (64 bit)

**Yomichan version**
22.2.2.0

**Exported settings file**

**Comment by toasted-nutbread** [comment]
I have reproduced this issue. As a temporary workaround, you can set the _Action bar appearance_ > _Visibility_ setting to _Always_, which will show an "X" button to close the window.
