### ISSUE TITLE
hasMedia of selection-text always true

### ISSUE THREAD

**Issue by Capu-Johann** [FooSoft/yomichan#2097]
Hi, I'm trying to replace **selection-text** by **glossary** if there is no text selected.
Someone told me to try adding an else statement after the `if hasMedia`:

```
{{#*inline "selection-text"}}
    {{~#if (hasMedia "selectionText")}}
has media
        {{#getMedia "selectionText"}}{{/getMedia}}
    {{~else~}}
no media
        {{~> glossary ~}}
    {{/if~}}
{{/inline}}
```

Even when I selected no text, the if statement is always true on my computer, so selection-text is always just "has media" (I added that to test it).

Is this a bug?
Is there another way to do what I want to do?

Thanks for reading!

**Browser version**
Chrome 99.0.4844.84 64bit

**Yomichan version**
22.2.2.0

**Comment by toasted-nutbread** [comment]
The `hasMedia` doesn't check to see if the selection text is empty, it just checks whether that value is present. It's value can be an empty string `''`, so you would have to do a second check, something like:
```handlebars
{{~#if
  (op
    "&&"
    (hasMedia "selectionText")
    (op "!==" (getMedia "selectionText") "")
  )
}}
```
(Newlines added for clarity, you can collapse it when you use it)

**Comment by aiko-tanaka** [comment]
on a related note, is it possible to add furigana to selection-text?

I was trying to do something like
```
{{#*inline "selection-text-furigana-plain"}}
    {{~#if (hasMedia "selectionText")}}
		{{~#set "select-Text"}}
			{{~> selection-text.~}}
		{{~/set~}}
		
		{{~#if (hasMedia "textFurigana" (get "select-Text") )}}
			{{#regexReplace "<rt>" "[" "g"~}}
			{{#regexReplace "</rt>" "]" "g"~}}
			{{#regexReplace "(<ruby>)" " " "g"~}}
			{{#regexReplace "(</ruby>)" "" "g"~}}
			{{#regexReplace '<span class="term">' "" "g"~}}
			{{#regexReplace "</span>" "" "g"~}}
				{{#getMedia "textFurigana" (get "select-Text") escape=false}}{{/getMedia}}
			{{~/regexReplace}}
			{{~/regexReplace}}
			{{~/regexReplace}}
			{{~/regexReplace}}
			{{~/regexReplace}}
			{{~/regexReplace}}
		{{/if~}}
		
    {{/if~}}
{{/inline}}
```
but it didn't work

**Comment by Capu-Johann** [comment]
> The `hasMedia` doesn't check to see if the selection text is empty, it just checks whether that value is present. It's value can be an empty string `''`, so you would have to do a second check, something like:
> 
> ```
> {{~#if
>   (op
>     "&&"
>     (hasMedia "selectionText")
>     (op "!==" (getMedia "selectionText") "")
>   )
> }}
> ```
> 
> (Newlines added for clarity, you can collapse it when you use it)

Thanks a lot!!

**Comment by toasted-nutbread** [comment]
@Capu-Johann 
> on a related note, is it possible to add furigana to selection-text?

As it stands currently, no, because that would be chaining two asynchronous functions:
1. Getting the selection text
2. Converting a value to its furigana representation

Unfortunately, Handlebars template parsing is synchronous, which is why the asynchronous features have to be handled in such an obtuse manner. Although I can't guarantee I can address it, you can create a new issue to track the missing functionality so it doesn't get lost in this closed issue.

**Comment by Capu-Johann** [comment]
> @Capu-Johann
I think you wanted to mention @aiko-tanaka, not me

**Comment by toasted-nutbread** [comment]
Oops, my bad; @aiko-tanaka ^^
