### ISSUE TITLE
Text cutoff when creating anki cards while watching netflix.

### ISSUE THREAD

**Issue by jtafernando** [FooSoft/yomichan#2119]
**Description**
I have yomichan set to export the {sentence} field into one of the fields of my anki notecard. When watching netflix using Langauge Reactor (formerly known as Language Learning with Netflix), if I try to create a flash card for a word, the entire subtitle that that word is in does not get exported to my ank card. 
For example:
Subtitle: “この男 廃人クラスの ゲーヲタですよ”ってね
Sentence field in my anki card: “この男 廃人クラスの

**Browser version**
Chrome Version 100.0.4896.127 (Official Build) (64-bit)

**Yomichan version**
22.4.4.0

**Comment by toasted-nutbread** [comment]
Is the text split across multiple lines? Can you screenshot what it looks like?

Sentence detection is partially determined by how the text elements are organized from the browser. I'm not sure if this will work or not, but you could try enabling the _Advanced_ > _Scanning_ > _Layout-aware scanning_ option on the settings page. This option uses a slightly different text parsing algorithm.

**Comment by jtafernando** [comment]
I enabled the layout-aware scanning and that worked! Thank you! I think we can close this issue then.
