### ISSUE TITLE
Yomichan Trigers on Stylus Hover

### ISSUE THREAD

**Issue by KamWithK** [FooSoft/yomichan#2120]
**Description**
Trying to use Yomichan on an eReader with stylus. Instead of Yomichan activating on stylus click, it also activates when the stylus is hovered just above the screen which isn't desirable.

**Browser version**
Kiwi Browser

**Yomichan version**
v22.4.4.0

**Exported settings file**
I've attached my settings to this file
I've tried playing around with the advanced options scanning inputs but haven't been able to stop hovering stylus just above the screen from triggering yomichan. Any help would be greatly appreciated :)

[yomichan-settings-2022-04-23-03-18-11.zip](https://github.com/FooSoft/yomichan/files/8546075/yomichan-settings-2022-04-23-03-18-11.zip)

**Comment by toasted-nutbread** [comment]
Try _Advanced_ > _Scanning_ > _Configure advanced scanning inputs…_ > _⋮_ > _Show advanced options_ > disable _Scan on pen hover_

**Comment by KamWithK** [comment]
Didn't know these options existed before (they're a little difficult to find, seems to be working now though)
Thanks for the help!

**Comment by toasted-nutbread** [comment]
Yeah, they're pretty out of the way due to how specific they are. Prior to this issue, I've never received any feedback about using pen inputs, so I put them there due to my own experimentation during testing.

I'll close this issue for now, re-open it or re-comment if you have any other issues.
