### ISSUE TITLE
Prevent Popups when Scrolling on Mobile

### ISSUE THREAD

**Issue by KamWithK** [FooSoft/yomichan#2122]
**Description**
On mobile even if you disable "Scan on touch move" and "Prevent touch/pen scrolling", the popups still appear as you move your finger across the screen to scroll. On small mobile screens this can make it very difficult to scroll.

[This previous issue](https://github.com/FooSoft/yomichan/issues/870) discusses the problem but the previous solution (as mentioned) allows you to scroll whilst the popup still opens instead of preventing it from coming up in the first place. Ideally the popup should only display when you tap on a single word.

Here are the relevant options used:
![image](https://user-images.githubusercontent.com/51506271/164958339-8aa3f532-810f-45cd-8e5d-80f19d0df42d.png)

**Browser version**
Kiwi Browser

**Yomichan version**
v22.4.4.0

**Exported settings file**
I've attached my settings to this file
[yomichan-settings-2022-04-24-02-28-14.zip](https://github.com/FooSoft/yomichan/files/8549077/yomichan-settings-2022-04-24-02-28-14.zip)

Any help would be greatly appreciated :)

**Comment by toasted-nutbread** [comment]
Are you having this issue with finger touches, pen touches, or both?

**Comment by KamWithK** [comment]
> Are you having this issue with finger touches, pen touches, or both?

Just finger touches

**Comment by KamWithK** [comment]
Just to quickly clarify, when you first hit your finger or stylus onto the screen (in an effort to scroll) the popup appears even though you're not just tapping but actually sliding the finger/stylus across the screen
