### ISSUE TITLE
Popup having suboptimal position on websites with specific layouts

### ISSUE THREAD

**Issue by ChaseOxide** [FooSoft/yomichan#2124]
**Description**
Happens when:
* (horizontal-tb) start of term at the bottom, ends at the top
* (vertical-rl) start of term at the left, ends at the right

It can be reproduced if the website uses [column layouts](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Column_layouts).

My reproduction:

```html
<div id="data" style="height: 600px; column-width: 100px; width: 300px">
</div>
<script>
  data.textContent = Array(100).fill('こんにちは。').join('')
</script>
```

Tiny screen (500x624)
![image](https://user-images.githubusercontent.com/15276837/165502426-c5435cb0-28d7-44d9-87c4-a5940d5b453f.png)

Larger screen
![image](https://user-images.githubusercontent.com/15276837/165502661-c5a84d94-a0ec-4ccf-bc16-acdce858dc9b.png)

**Browser version**
Brave 1.37 (Chromium 100)

**Yomichan version**
Yomichan 22.4.4.0

**Comment by toasted-nutbread** [comment]
#2135 makes some internal improvements to make this edge case handled a bit better. There is still potentially some room for improvement (which is more complex), but this is how it should look now (depending on popup size settings):

![image](https://user-images.githubusercontent.com/11037431/168711450-eadf845c-a280-40fa-9456-ff4f3a38c2ab.png)
Cursor was down here ^
