### ISSUE TITLE
[Feature Request] Add support for AnkiConnect apiKey

### ISSUE THREAD

**Issue by cabo40** [FooSoft/yomichan#2139]
Hi, sorry if I'm missing the config, but, is there a way to connect to Anki when an apiKey is set?

**Comment by toasted-nutbread** [comment]
On the settings page, try changing _AnkiConnect server address_ to `http://127.0.0.1:8765/?key=YOUR_API_KEY`

**Comment by cabo40** [comment]
Tanks for the suggestion, I've tried with this url `http://127.0.0.1:8765/?key=pass` in _Yomichan v22.4.4.0_ and this settings in _AnkiConnect_, Anki v2.1.51
```
{
    "apiKey": "pass",
    "apiLogPath": null,
    "ignoreOriginList": [],
    "webBindAddress": "127.0.0.1",
    "webBindPort": 8765,
    "webCorsOriginList": [
        "http://localhost"
    ]
}
```
without luck. Is this config working on your side?
