### ISSUE TITLE
[Feature Request] (Add a card (note) to a Deck, and at the same time add the reversed card to another deck) feature

### ISSUE THREAD

**Issue by Malivuca** [FooSoft/yomichan#2159]
I like to separate reverse cards (notes) from the normal, non reversed cards.
I can set up Anki to create both normal and reversed cards when I click the "Add card" button of Yomichan, using the Anki's "Card Type" feature, but both cards are added to the same Deck. Then I need to open the Anki "Browse" tab, and manually move the reversed card from DeckOfNormalCards to DeckOfReversedCards.
This is an image of what I think the feature would look like:
![feature_description](https://user-images.githubusercontent.com/48441789/169706954-b5ae984a-d02f-4fd7-9f77-711280b591a0.png)

**Comment by oakkitten** [comment]
Perhaps you can use [deck override](https://docs.ankiweb.net/templates/intro.html?highlight=Deck%20override#the-templates-screen) to make Anki put cards in separate decks automatically? Not sure if it works with Anki-Connect but if it doesn't it probably should be fixed.

**Comment by Malivuca** [comment]
It works! Thanks a lot!
