### ISSUE TITLE
Shortcut for enabling/disabling the pop-up dictionary

### ISSUE THREAD

**Issue by weirdalsuperfan** [FooSoft/yomichan#217]
PLEASE add a hotkey to control enabling/disabling Yomichan (with a single press/without needing to hold it down)

Yomichan is way too aggressive, such that it will attempt to look up even single alphanumeric characters if my mouse passes over them. The relatively huge results box takes a while to go away, too, which clogs up my screen and makes it a real pain to try and find/read actual Japanese text that's often hidden underneath the results box (this is especially bad if I'm doing lookups on the fly while watching Netflix with Subadub, since it gets in the way of subtitles I might be looking up live, or it gets in the way of the picture and the scrubber bar). For this reason, I often disable Yomichan when I'm not immediately using it.

However, this is a giant pain, as it requires 4 actions: moving the mouse up to the yomichan icon, clicking it, enabling/disabling it, and returning my mouse to where it way before.

I also don't like having to hold down a key just to use yomichan, since when I am using, I tend to use it for much longer than I care to hold a key down for (and I prefer having one of my hands free, because I'm not insane...).

So, all I'm asking for is a hotkey that will turn Yomichan on and off with a single press (no need to hold it down). This is seriously the biggest pet peeve of mine about this extension. It's a MAJOR usability flaw and it frustrates me to no end. I often end up unfortunately just using Rikaikun just because it's less aggressive with lookups (and takes one less button press for turning on/off), even though it doesn't have monolingual dictionaries.

**Comment by toasted-nutbread** [comment]
> I also don't like having to hold down a key just to use yomichan, since when I am using, I tend to use it for much longer than I care to hold a key down for

If you're talking about needing to hold the shift/ctrl/alt key, you can change that to "None" in settings under "Scanning Options" > "Scan modifier key".

> So, all I'm asking for is a hotkey that will turn Yomichan on and off with a single press

While not a single press, Alt+Delete currently does this by default. It sounds like the extension may need some info about how to customize shortcuts, since even I wasn't sure how to do this.
* If you are using Firefox, [check this](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox).
* If you are using Chrome, navigate to the URL chrome://extensions/shortcuts.

**Comment by lcyne** [comment]
> Yomichan is way too aggressive, such that it will attempt to look up even single alphanumeric characters if my mouse passes over them.

You should be able to disable it by unchecking the "Search alphanumeric text" checkbox under "Scanning options".

**Comment by weirdalsuperfan** [comment]
Thank you both. These two things together solved my woes.

I did a fair bit of googling to see how to set shortcuts, but nothing came up. The button for shortcuts from the extensions menu seems to have been removed from Chrome as well, so the direct link was very helpful.

**Comment by toasted-nutbread** [comment]
> The button for shortcuts from the extensions menu seems to have been removed from Chrome as well

I thought so too, but you can apparently get to it by doing: 
* Open settings page (chrome://settings/)
* Open extensions link in the left sidebar (chrome://extensions/)
* Open the side panel using the hamburger (```≡```) menu button, then click "Keyboard shortcuts". (takes you to chrome://extensions/shortcuts)

I have no idea why it is so hard to find these options on both browsers.
