### ISSUE TITLE
JapanesePod101 audio takes a long time to properly load and makes it so that Yomichan can't make anki cards until it's done.

### ISSUE THREAD

**Issue by okaytommy** [FooSoft/yomichan#2182]
I apologize if this isn't the right place to be asking about this. I have been using yomichan for over a year with no problems but recently I've had problems with the JapanesePod101 audio source. When I try to look up a word It will take a very long time(somtimes upwards of a minute) to load the JapanesePod101 audio when it used to just take a few seconds at most and it's not possible to yomichan to create anki cards until it's done. 

This means I can't create a lot of cards at one time which I often do since I have to wait a significant chunk of time in between making cards.

I've tried using both JapanesePod101 with JapanesePod101(Alternative) and just JapanesePod101(Alternative) and the same issue remains. If I don't use JapanesePod101 and just use the other audio sources everything seems to load fine but I want to be able to still use JapanesePod101 because it's easily the best resource for audio sources.

**Browser Version**
Firefox 101.0.1(and when I tried Brave 1.39.122 with the same settings the problem remained)

**Yomichan Version**
22.4.4.0(I tried doing a clean install of yomichan and the problem is the same)

**Computer Info**
I'm on fresh Windows 10 install with the same hardware that I used prior. JapanesePod101 had no issues at first but started started having issues about an hour or so in. Restarting my computer didn't help.

**Exported Settings File**
[yomichan-settings-2022-06-20-23-40-30.zip](https://github.com/FooSoft/yomichan/files/8944750/yomichan-settings-2022-06-20-23-40-30.zip)

**Comment by SeafoamGreeen** [comment]
I also have this issue, exactly as described here. On Linux and Windows 10 using Firefox and Yomichan 22.4.4.0

**Comment by gitSuki** [comment]
Thirding this issue. Running into the exact same problem using Chrome, Windows 11, and Yomichan 22.4.4.0.

**Comment by Ceynou** [comment]
See on TMW discord server how to set that up, download the vocab audio, and a custom URL that points to this local collection, creating cards should be instant and possible offline

**Comment by okaytommy** [comment]
> See on TMW discord server how to set that up, download the vocab audio, and a custom URL that points to this local collection, creating cards should be instant and possible offline

I'm not familiar with what the TMW discord server is. Do you know where I could find a link?

**Comment by ostrea** [comment]
I think the previous commentator meant [this guide](https://learnjapanese.moe/yomichan/#offline-audio-server).

**Comment by Ceynou** [comment]
> I think the previous commentator meant [this guide](https://learnjapanese.moe/yomichan/#offline-audio-server).

Oh I didn't see it was added, I left the server a few months ago

**Comment by okaytommy** [comment]
The guide on the website for TheMoeWay has outdated files but I went into the discord and was able to get the updated ones. For anyone else having this problem this seems to be the best solution to this issue since once you get it setup all of the audio loads instantly which is even better than doing it online since even when it's working well there can still be a small delay.

https://nyaa.si/view/1544279 Here's the link to the files and instructions for anyone else that needs them. If linking to nyaa.si isn't allowed just let me know and I can remove it.

**Comment by toasted-nutbread** [comment]
For those who are having the issue, is there also an issue with trying to play audio via the button in the Yomichan popup? Or is this issue only affecting card creation?

With some brief testing, I'm currently not able to reproduce the issue. [Historically](https://github.com/FooSoft/yomichan/issues?q=label%3A%22audio+cert%22+is%3Aclosed), JPod has had some certificate issues which has led to audio not working sometimes, not sure if the issue is the same or not.

**Comment by SeafoamGreeen** [comment]
> For those who are having the issue, is there also an issue with trying to play audio via the button in the Yomichan popup? Or is this issue only affecting card creation?
> 
> With some brief testing, I'm currently not able to reproduce the issue. [Historically](https://github.com/FooSoft/yomichan/issues?q=label%3A%22audio+cert%22+is%3Aclosed), JPod has had some certificate issues which has led to audio not working sometimes, not sure if the issue is the same or not.

I just tested again. it seems that everything is back to normal (at least for me) probably a Jpod issue, as you said.

**Comment by ostrea** [comment]
Thank you very much. Didn't expect it to be added at all.
