### ISSUE TITLE
Yomichan doesn't load on Google Chrome

### ISSUE THREAD

**Issue by boopnbop** [FooSoft/yomichan#2188]
**Description**
Yomichan doesn't load. On the extension bar, it shows a yellow box with 3 dots over it. By default the switch is "off", and everytime I click "on" it goes right back to "off" again. None of the other buttons do anything. I am only able to access yomichan's settings by going to "manage extension" and clicking "extension options". When I get to the settings, everything is blank and at the top there is an error stating "This page is taking longer than expected to load." I am not able to configure dictionaries, or import or export settings. Uninstalling and reinstalling yomichan didn't work, and neither did loading the extension from zip files from this github page or using developer mode. This problem is very similar to [this issue](https://github.com/FooSoft/yomichan/issues/595), except I do not use Kiwi Browser (I don't even know what that is haha). The solution to their issue did not work for me though, and I was unable to log my issue using the debug release. When I went to "log" nothing showed up (likely because that zip file was from 2020). This only started happening when I closed and reopened Chrome, so this seems very sudden, I don't know what to do.

**Browser version**
Google Chrome 103.0.5060.53

**Yomichan version**
(e.g. 20.11.1.1)

**Exported settings file**
As the title of the file shows, this is from the 18th, before this error occurred, so it likely isn't relevant but thought I'd share anyway.
[yomichan-settings-2022-06-18-22-52-19.txt](https://github.com/FooSoft/yomichan/files/8984112/yomichan-settings-2022-06-18-22-52-19.txt)

**Comment by toasted-nutbread** [comment]
1. Open chrome://extensions/
2. Enable _Developer mode_ on the top right
3. Find Yomichan's card
4. Under _Inspect views_, click _background.html_ (or click the _# more..._ link if it's not the first one listed)
5. Open the Console tab of the developer window that opens
6. Check to see if any errors or other messages show up

**Comment by toasted-nutbread** [comment]
Those issues/warnings should be harmless and wouldn't be causing the issue. When you say you downloaded it from Github, did you install the repository's source code folder? Or did you download one of the zipped builds? I can generate a debug version that you could test.

**Comment by toasted-nutbread** [comment]
You have to select the "ext" folder inside the main folder.

I've created a debug branch which includes some logging to see where the background is stalling at.
[Branch](https://github.com/toasted-nutbread/yomichan/tree/test-issue-2188) | [Download](https://github.com/toasted-nutbread/yomichan/archive/refs/heads/test-issue-2188.zip) | [Diff](https://github.com/toasted-nutbread/yomichan/compare/master...test-issue-2188)

**Comment by toasted-nutbread** [comment]
That's what I wanted, thanks. Looks like it's stalling on setting up the database for some reason. I've pushed an update to that same branch with some more logs, could you download it again and update the files / reinstall? Links are the same as above.

**Comment by toasted-nutbread** [comment]
Can you open the _Application_ tab, and then under _Storage_ on the left, expand _IndexedDB_ and see what's under there?

**Comment by toasted-nutbread** [comment]
Hmm, interesting. I've made another update, try this new one out.

**Comment by toasted-nutbread** [comment]
Okay, I've pushed one last update with a few extra logs, but it's still not clear what's happening, or rather, why. IndexedDB is expected to be empty, so that's fine.

**Comment by toasted-nutbread** [comment]
Effectively what this info tells me is that Chrome is stalling opening the database, and it isn't triggering any of the events that should happen when the database is successfully opened. Have you tried restarting your browser and computer entirely? I'd suggest doing that if you haven't already, in case there's something wrong with the file system. Does your device have adequate free space also?

Following that, I'd say check the URL `chrome://indexeddb-internals`, search for the extension ID (ghbepcc... given your screenshot), and screenshot what it says there.

**Comment by toasted-nutbread** [comment]
Yeah, it seems like it's an issue with Chrome. 94GB should be fine and shouldn't be crashing the database process, I'd be more worried if it was something less than 1GB.

Overall, the issue seems very similar to this issue:
https://stackoverflow.com/questions/35276061/indexeddb-open-callbacks-not-called-on-chrome
Which was resolved by restarting the browser.
