### ISSUE TITLE
Can't import dictionaries. 

### ISSUE THREAD

**Issue by phil-markarian** [FooSoft/yomichan#2193]
<img width="931" alt="Screen Shot 2022-06-28 at 12 32 45" src="https://user-images.githubusercontent.com/53072828/176088691-43a8891e-d279-4d36-b59b-044b913453cb.png">
**Description**
When I try to import dictionaries the above error shows up in the console. 

**Browser version**
Brave v1.40.107

**Yomichan version**
22.4.4.0

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page; zip or rename the resulting file to .txt to attach to the issue.)

**Comment by toasted-nutbread** [comment]
Have you been able to install dictionaries previously, or is this a new install?

**Comment by phil-markarian** [comment]
@toasted-nutbread 
A new install.

**Comment by toasted-nutbread** [comment]
What dictionary are you trying to load?

**Comment by phil-markarian** [comment]
@toasted-nutbread 
A couple dictionaries I found online. Although, I just figured out my issue. I had multiple dictionaries bundled into one zip file so it couldn't read the file contents. After unzipping it and reading in the individual dictionaries it worked.
