### ISSUE TITLE
Unable to create more profiles

### ISSUE THREAD

**Issue by creaaidev** [FooSoft/yomichan#2199]
**Description**
I'm trying to have multiple profiles, for sentence mining, word mining... etc. But whenever I create a profile and try to add conditions, the button to add said conditions is missing (the "Add" button), only the "Add Group" button appears, but does nothing on clicking. 
Upon restarting the web browser (brave or firefox I tested), the new profile is gone.
I can edit the default profile, add dictionaries, etc. 
I can also add conditions with the "Add" button on the default profile.
Is it me just being dumb or is there really some random issue preventing me from creating more profiles?

**Browser version**
Brave browser 1.40.113 Chromium 103.0.5060.114
Firefox 102.0.1-1

**Yomichan version**
Yomichan 22.4.4.0

**Exported settings file**
[export_settings.zip](https://github.com/FooSoft/yomichan/files/9111283/export_settings.zip)

**Comment by toasted-nutbread** [comment]
Can you open the dev console (F12 => Console) to see if any errors show up while doing this?

**Comment by SolarBlaze** [comment]
Oh, that's funny, I was about to ask the exact same thing. 
Tried on multiple devices and browsers and for some reason, this happened. I assume our problems might be the same so I am sending screencap of what I have on my end. No matter what I do, even on the default profile this error 
![image](https://user-images.githubusercontent.com/37492126/179120246-378a7eb8-0444-471a-a1c2-591f657079f5.png)

I get this error message whenever I press something in the "Profile" window.

**Comment by SolarBlaze** [comment]
> Oh, that's funny, I was about to ask the exact same thing. Tried on multiple devices and browsers and for some reason, this happened. I assume our problems might be the same so I am sending a screencap of what I have on my end. No matter what I do, even on the default profile this error pops up. ![image](https://user-images.githubusercontent.com/37492126/179120246-378a7eb8-0444-471a-a1c2-591f657079f5.png)
> 
> I get this error message whenever I press something in the "Profile" window. [yomichansettings.txt](https://github.com/FooSoft/yomichan/files/9116661/yomichansettings.txt) .

Wad wondering did you find a fix for the problem?

**Comment by creaaidev** [comment]
> > Oh, that's funny, I was about to ask the exact same thing. Tried on multiple devices and browsers and for some reason, this happened. I assume our problems might be the same so I am sending a screencap of what I have on my end. No matter what I do, even on the default profile this error pops up. ![image](https://user-images.githubusercontent.com/37492126/179120246-378a7eb8-0444-471a-a1c2-591f657079f5.png)
> > I get this error message whenever I press something in the "Profile" window. [yomichansettings.txt](https://github.com/FooSoft/yomichan/files/9116661/yomichansettings.txt) .
> 
> Was wondering did you find a fix for the problem?

Maybe not a proper *fix* but just as importing the broken settings to a new pc also breaks it, importing the settings from another computer without this issue fixes it on an affected one.
Here's my current settings, see if it helps.
[yomichan-settings-2022-07-22-03-45-03.json.zip](https://github.com/FooSoft/yomichan/files/9164448/yomichan-settings-2022-07-22-03-45-03.json.zip)

**Comment by SolarBlaze** [comment]
> > > Oh, that's funny, I was about to ask the exact same thing. Tried on multiple devices and browsers and for some reason, this happened. I assume our problems might be the same so I am sending a screencap of what I have on my end. No matter what I do, even on the default profile this error pops up. ![image](https://user-images.githubusercontent.com/37492126/179120246-378a7eb8-0444-471a-a1c2-591f657079f5.png)
> > > I get this error message whenever I press something in the "Profile" window. [yomichansettings.txt](https://github.com/FooSoft/yomichan/files/9116661/yomichansettings.txt) .
> > 
> > 
> > Was wondering did you find a fix for the problem?
> 
> Maybe not a proper _fix_ but just as importing the broken settings to a new pc also breaks it, importing the settings from another computer without this issue fixes it on an affected one. Here's my current settings, see if it helps. [yomichan-settings-2022-07-22-03-45-03.json.zip](https://github.com/FooSoft/yomichan/files/9164448/yomichan-settings-2022-07-22-03-45-03.json.zip)

Oh thanks a lot, it did work!
