### ISSUE TITLE
Green plus is grayed out for all words

### ISSUE THREAD

**Issue by phil-markarian** [FooSoft/yomichan#2201]
**Description**
Same as the title. Green plus is grayed out for all entries. It says it is connected to Anki in the settings. It worked perfectly last week. However I tried changing the handlebars and it stopped working.  

Extension version: Yomichan 22.6.6.0
Platform: Mac OS
Browser: Chrome
Language: en-US
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36
AnkiConnect version: 6

**Exported settings file**
[yomichan-settings-2022-07-16-10-14-49.txt](https://github.com/FooSoft/yomichan/files/9125552/yomichan-settings-2022-07-16-10-14-49.txt)

**Comment by phil-markarian** [comment]
HeHere is an example of what I am talking about. 
<img width="505" alt="Screen Shot 2022-07-17 at 23 42 12" src="https://user-images.githubusercontent.com/53072828/179403632-d044e60a-2c16-4922-82e4-4ff554caf8ec.png">

**Comment by toasted-nutbread** [comment]
Your model may be wrong. What do you see when you click _Configure Anki card format..._ on the settings page?

**Comment by phil-markarian** [comment]
@toasted-nutbread 
Thanks! I found out my issues. I recently had rearranged my Anki Decks to be a bit more organized. In doing so, I did not change the deck settings to the new location of the deck which was apart of a larger group of decks. Mining > Internet for example. Thanks for the help!
