### ISSUE TITLE
JMdict zip files are broken

### ISSUE THREAD

**Issue by salixor** [FooSoft/yomichan#2218]
**Description**
Current JMdict zip files seem broken and miss a lot of information. Nothing is recognized when using them. Downloading the zip files from before 160305e21515687cc13d5ede26736e67f2373a91 resolves the issue, and recognition works properly once again.

Browsing the zip files (at least the English one) shows that all the "term_bank.json" files have gone missing, which may be the source of the problem.

**Browser version**
Firefox 103

**Yomichan version**
22.6.6.0

**Comment by toasted-nutbread** [comment]
Temporarily reverting.
FYI @FooSoft

**Comment by stephenmk** [comment]
BTW, [search-only forms are now being added to JMdict](https://www.edrdg.org/wiki/index.php/Editorial_policy#Search-only_Forms). For example, 三蜜 is a typo that you normally wouldn't want to see in a dictionary (or in grouped-terms mode in yomichan), but you'd still like to be redirected to the appropriate entry when you scan it. These forms are being tagged as [sK] and [sk] (search-only forms for kanji and kana, respectively).

There are currently only ~100 terms with these tags (a very small fraction of the total database), but it might be a good idea to hold-off on updating the dictionary files until yomichan-import can handle these forms appropriately.

**Comment by salixor** [comment]
I'm closing this issue as it had been corrected.
