### ISSUE TITLE
Dictionaries branch

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#2220]
@FooSoft 
Since this has come up in #2218 (and I forget if I've brought this up before), I'd like to propose putting the dictionaries on a separate branch, in order to make the history easier to go through and decouple it from the development updates.

I've already set this up a bit, here are some links to check out:
* Orphan branch: https://github.com/FooSoft/yomichan/tree/dictionaries
* PR for updating download links: ~~#2219~~, #2221, #2222

And then going forward, dictionaries would just be updated on that branch; no other workflow changes.

This would hopefully also avoid any potential issues in the future in case a broken update is made, the history can just be rolled back without needing to rebase any commits that may have been made afterwards.

**Comment by FooSoft** [comment]
Yeah that makes sense to me -- I'll put updates there going forward :+1:

**Comment by toasted-nutbread** [comment]
The paths in the repository are updated, but the dictionary files are still present. This ensures that the links on https://foosoft.net/projects/yomichan/ will still work until you (@FooSoft) have a chance to update that, then #2222 can be merged.
