### ISSUE TITLE
Interferes with Copy+Paste with no modifier key

### ISSUE THREAD

**Issue by Tenpi** [FooSoft/yomichan#2225]
This extension interferes with copy+pasting when you set it to work with no modifier key, and it is pretty annoying. 

Whenever I make a selection of Japanese text to copy it, this extension will overwrite my selection so I'm unable to copy without disabling it. 

I recommend that you keep track of the text that is selected, and if the current selection doesn't match the last text that Yomi selected, then the extension will not activate. If there is no active selection, then the extension will activate regardless.

**Comment by toasted-nutbread** [comment]
This may be already resolved by #2186 (issue #2071), just not yet released. I plan on setting up a release later this week.

**Comment by Tenpi** [comment]
It appears like those changes were finally released, thank you!
