### ISSUE TITLE
MeCab integration does not work. "Could not connect to native MeCab component"

### ISSUE THREAD

**Issue by poteau** [FooSoft/yomichan#2228]
Platform: MacOS 12.5.1 (Apple Silicon)
Browser: Firefox

Related to this issue from the installer https://github.com/siikamiika/yomichan-mecab-installer/issues/3

I followed the instructions [here](https://github.com/siikamiika/yomichan-mecab-installer/blob/master/README.md) and I continue to get this error. I'm not sure if this is a Mac-specific bug since someone in the issue linked above mentioned getting the same error on Windows. I have `mecab` installed, the paths are all set up, and it works in the terminal. I'm just not sure why I'm getting this error.

**Comment by watatomo** [comment]
I have the same issue too, but on Windows 11 22H2 and Firefox Developer Edition.

**Comment by poteau** [comment]
This seems to be an issue with the installer and not Yomichan based on this comment which fixed the problem for me https://github.com/siikamiika/yomichan-mecab-installer/issues/3#issuecomment-1289877627, so I'm closing this issue.
