### ISSUE TITLE
[Feature Request] Make anki card screenshot file lighter

### ISSUE THREAD

**Issue by brainexcerpts** [FooSoft/yomichan#2230]
Anki integration is awesome. it would be even better if the screenshot were not using lossless png but jpg or something more memory efficient instead. A on the fly resizing option or something that allows the user to somewhat control the file size would be very welcome especially on high resolution screens.

**Comment by toasted-nutbread** [comment]
There is a _Quality (%)_ option that you can use when the format is _JPEG_. The lower the value, the lower the file size will be.

**Comment by brainexcerpts** [comment]
@toasted-nutbread unless I'm missing something yomichan will always produce a .png when using the {screenshot} tag to create an Anki card. There is no option *inside yomichan* to produce a .jpg.

(I'm well aware JPEG file format itself provides a quality parameter, for now I'm forced to batch convert all png produced by yomichan to jpg which works fine but is not ideal since it hands some extra manual labor)

**Comment by Mar2ck** [comment]
>There is no option inside yomichan to produce a .jpg.

Have you not seen this option?
![image](https://user-images.githubusercontent.com/6759254/192568307-0e6d96b1-a2fe-4476-9dc2-b79f48ec161b.png)

**Comment by brainexcerpts** [comment]
Oh, I see it now! 
I swear I searched for it before posting and again after @toasted-nutbread answered me, but like we say "the third time's the charm"... So on the third check I discovered that you need to toggle the "advanced" button on the bottom right corner. how embarrassing... Thank you so much! @Mar2ck and really yomichan has an impressive set of features.

**Comment by toasted-nutbread** [comment]
I had forgotten <span title="https://en.wikipedia.org/wiki/That_that_is_is_that_that_is_not_is_not_is_that_it_it_is">that that</span> option was behind the _Advanced_ flag, apologies for not pointing that out. Thanks @Mar2ck!
