### ISSUE TITLE
"Select matched text" stops working while cursor is being moved over text

### ISSUE THREAD

**Issue by fauu** [FooSoft/yomichan#2244]
**Description**
1. Enable "Select matched text"
2. Hold down the scan modifier key
3. Move cursor over text
4. At some point, the matched text stops being selected

Reproduction video: 

https://user-images.githubusercontent.com/4130634/194897631-16987d2c-7cb5-4e63-bba5-1cf9bb17cfb5.mp4

**Browser version**
Firefox 106.0b9

**Yomichan version**
Yomichan 22.9.9.2

**Exported settings file**
[yomichan-settings-2022-10-10-14-51-29.txt](https://github.com/FooSoft/yomichan/files/9747015/yomichan-settings-2022-10-10-14-51-29.txt)

**Comment by toasted-nutbread** [comment]
Have you seen this issue happen on any page, or does it only happen on specific webpages?

**Comment by fauu** [comment]
It happens everywhere. Resetting the settings doesn't have an effect. An earlier version (22.6.6.0) works fine in the same browser.
