### ISSUE TITLE
Updates/metadata branch

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#2261]
One thing that is currently done in this project is that the [updates.json](https://github.com/FooSoft/yomichan/blob/master/dl/updates.json) file for Firefox is stored and updated on the master branch. IMO this is not directly related to the main development, and the updates to this file add some unnecessary noise to the diff/commit log.

I'd propose doing something similar to what is done for the recently new [dictionaries](https://github.com/FooSoft/yomichan/tree/dictionaries) branch, where we move these updates that are related to deployment onto a separate branch.

For demonstration purposes, I have again set this up as a new branch, but not yet deleted the file from the master branch, as your website URL would need to be redirected:
* https://github.com/FooSoft/yomichan/tree/metadata

Line that would have to eventually be updated if we do this:
https://github.com/FooSoft/yomichan/blob/752d73418b23e8ec195a968b2c3ff064f0973357/dev/data/manifest-variants.json#L262

Related issue where I suggested this for the dictionaries branch: #2220.

Tagging @FooSoft

**Comment by FooSoft** [comment]
Sounds reasonable to me. We'll probably want to keep the existing URL for a little while since only new versions of the extension will know where to find updates. It will be a little bit annoying short-term since I statically generate the Yomichan homepage directly from the git repository but I can do something short-term for that on my end.

**Comment by FooSoft** [comment]
@toasted-nutbread switched to using updates.json from the metadata branch. I'll keep the updates file around on the website a bit longer (redundantly) so that folks running testing have a chance to "link up" to the new location.
