### ISSUE TITLE
Recursive popups don't work on Microsoft Edge 

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#231]
Recursive popups don't work on Microsoft Edge. The cause of this seems to be the following:
https://github.com/FooSoft/yomichan/blob/64eed33e8890df33e3c4acb47c96f0e3c674bd3b/ext/bg/js/api.js#L221-L224

```sender.frameId``` is undefined. I have looked briefly into this with little success. I will close this issue if I find a solution.

Documentation: [Chrome](https://developer.chrome.com/extensions/runtime#type-MessageSender), [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/MessageSender), [Edge](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-apis#runtime).

**Comment by thebasser123** [comment]
Assuming we're talking about the same thing, this no longer works in Chrome either. (I used to be able to click on words inside definitions, it was really handy with J-J dictionaries!)

**Comment by toasted-nutbread** [comment]
@thebasser123 I think that may be due to a different reason. That feature was (inadvertently) disabled by default when a setting was added to toggle it on/off.

I believe the option you are referencing is called "Enable search when clicking glossary entries", which is found under the "Popup Content Scanning Options" heading.

The feature I am referencing is the recursive popups, where multiple popups can be created. This feature can be enabled by changing "Maximum number of additional popups" to a value greater than 0. In action, this feature looks like the image below:
![image](https://user-images.githubusercontent.com/11037431/63235978-fad0e880-c209-11e9-942a-0772a907d127.png)

**Comment by sebastiaanvdm** [comment]
Silly me... Thank you!

**Comment by juanj** [comment]
I'm facing this issue. Don't have much experience with browser extensions, but will like to help.
@toasted-nutbread did you find any clue of why `sender.frameId` is undefined?

**Comment by toasted-nutbread** [comment]
Are you using Chromium-based Edge or Legacy Edge? Chromium-based Edge supports it, but you have to enable it in options by editing the option **Maximum number of additional popups**.

**Comment by juanj** [comment]
Oh. You are right. After increasing **Maximum number of additional popups** it works perfectly fine!

I was testing on Firefox and it worked out of the box, so I assumed it was a problem with Edge. But looking back into Firefox settings, **Maximum number of additional popups** was indeed different than 0. I should have changed it at some point.

Thanks!

**Comment by toasted-nutbread** [comment]
Closing as Legacy Edge is not planned on being supported anymore, since Chromium-based Edge supports the extension the same as Chrome.
