### ISSUE TITLE
Firefox automatically switches to the tab that has gmail open.

### ISSUE THREAD

**Issue by sDessens** [FooSoft/yomichan#241]
Since last night, I noticed that that firefox sometimes switches to the tab that has gmail open.

Steps to reproduce:
* Install yomichan, disable all other addons.
* Open gmail in a tab, go to inbox.
* Switch to a different tab.
* Right click on the gmail tab and refresh.
* After a few seconds, firefox will switch to the tab that has gmail open.

Alternatively, go to yomichan settings and change any setting (hit any checkbox or change the name of the current profile). The browser will immediately switch to tab that has gmail open.

Yomichan version 1.8.0. Firefox version 69.0.2 (64-bit)

**Comment by siikamiika** [comment]
Thanks for the report! I think this should be fixed in https://github.com/FooSoft/yomichan/pull/240, but it's not released yet. Let us know if this still happens after the update or on git master

**Comment by FooSoft** [comment]
The fix was pushed in an update (along with a bunch of other things), so hopefully this fixes the issue for you :+1:

**Comment by sDessens** [comment]
はやい。

I can confirm it is fixed.
