### ISSUE TITLE
Can't add words into anki with Yomichan

### ISSUE THREAD

**Issue by it0na72** [FooSoft/yomichan#244]
I installed yomichan today and made everything I was supposed to, I think. But can't seem to add new cards into Anki. I have Anki 2.1 and have ankiconnect properly functioning. 
![OpzZBoG](https://user-images.githubusercontent.com/56265972/66324110-ced60780-e91c-11e9-847b-7efd378d093d.png)
![p9KSasc](https://user-images.githubusercontent.com/56265972/66324205-ef05c680-e91c-11e9-877a-668322756ccf.png)
![OHRcA66](https://user-images.githubusercontent.com/56265972/66324209-f036f380-e91c-11e9-96f5-a134053590ec.png)
![BHlKy8Y](https://user-images.githubusercontent.com/56265972/66324212-f1682080-e91c-11e9-8ee9-c201a64909cc.png)
I am also using the latest version of Google Chrome, Windows 10 and I have tried changing the audio to disabled or the other types. Nothing seems to work :/

**Comment by toasted-nutbread** [comment]
Few questions:
1. Do you have any other extensions installed? Adblockers, etc.?
2. Can you share your JSON settings data? You can find this by doing the following:
   * Open the options page
   * Enable the "Show advanced options" option
   * Enable the "Show debug information" below it
   * Scroll to the bottom of the page and copy the code in the block under the donate button.

I've found where the error comes from ([here](https://github.com/FooSoft/yomichan/blob/master/ext/mixed/js/display.js#L389)), but it's not clear to me what would cause it.

**Comment by it0na72** [comment]
Thanks for the reply. This was fixed because the layout of my cards wasn't
set up properly due to me being careless lol. After that, I was able to
save cards and everything is perfect now.
Thanks!!
