### ISSUE TITLE
[Feature Request] search.html from the omnibar

### ISSUE THREAD

**Issue by grenzionky** [FooSoft/yomichan#247]
It would be very nice to be able to search for terms in search.html from outside of the webpage (example: im watching a show on my computer's video player, and i click on the subtitles to open up the search.html with the text already searched for).

Here's my proposed format: `search.html?なんでも`

Heres the bulk of the code needed to make this happen:
```
// get the search term (everything past the "?" in the omnibar)
var search = decodeURIComponent(location.href.match(/(?<=\?).*$/)[0])
undefined
// insert the search term into the search bar.
// if the search term is in abc's, convert it to kana first.
$("#query").value = wanakana.isRomaji(search) ? wanakana.toKana(search) : search
```

I didn't want to make my code click the search button like a person would cuz that doesnt make sense, what would make more sense is if the code did what clicking the search button does. But I'm not sure how yomichan does the searching, which is why im making the feature request instead of a pull request…

**Comment by toasted-nutbread** [comment]
This feature has been added in 1074c33f2074984fe5b21654e944d787408c0a93. The change will read the ```query``` parameter from the URL in the format of ```/bg/search.html?query=あ```. Rōmaji can also be input, meaning ```/bg/search.html?query=a``` will convert ```a``` to ```あ``` before searching. Changing the value in the input field will also cause the URL to replace its current state with an updated query parameter.

The remainder of the diff is visual differences related to animation, button state, etc.

**Comment by FooSoft** [comment]
Sweet!
