### ISSUE TITLE
Can't show more than one frequency list

### ISSUE THREAD

**Issue by Sidma99** [FooSoft/yomichan#248]
I used to use 4 different frequency list while looking up words, but suddenly it started to show only 1 frequency number. I switched to Firefox version to see if it has the same problem, and it also had the same problem.

**Comment by FooSoft** [comment]
Looks like a dupe of #245 . This is already fixed in code,  and I'll get this out to the stable release  later this wee 👍

**Comment by Geniusssmit** [comment]
Can you please implement the fix?

**Comment by FooSoft** [comment]
The fix is currently in the testing branch, and will be pushed to master this weekend.

**Comment by FooSoft** [comment]
Fixed
