### ISSUE TITLE
[Feature Request] Add option to search word that has been added in anki internal browser

### ISSUE THREAD

**Issue by huzerD** [FooSoft/yomichan#250]
Hi, I want to request a **shortcut key** or **button** to directly open and search the word detected by yomichan to anki browser using ankiconnet's "_guiBrowse_" action. 

The function is similar to how when word is first added, there is a shortcut to open it in anki, but if the word has been added the function is no longer there. I usually edit back word added to anki with more examples. Thank you.

**Comment by toasted-nutbread** [comment]
This feature has been added with 97f5b7139fcb69c68560d025f99418b0f697940c and 7ce54864f3fbaaeade2ebc20d80bcb084d9fa426.

**Comment by huzerD** [comment]
Thank you very much for promp response. It is perfect.
