### ISSUE TITLE
Persistent Storage doesn't activate

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#254]
After seeing the newly added persistent storage option, I tried turning it on and it didn't react to my click.

Google Chrome
バージョン: 77.0.3865.90（Official Build） （64 ビット）

macOS High Sierra
バージョン 10.13.6

**Comment by toasted-nutbread** [comment]
Honestly I'm not even sure if the option does anything on Chrome. Looks like I may need to add an option to enable the ```unlimitedStorage``` permission; unfortunately, this permission does not prevent Firefox from clearing the database under storage pressure, so both methods will likely have to be supported.

Looks like Yomichan is not alone in dealing with IndexdedDB eviction issues:
https://bugs.chromium.org/p/chromium/issues/detail?id=680392
https://github.com/mrcoles/test-chrome-extension-persist

**Comment by toasted-nutbread** [comment]
I've added some warnings about this behaviour in 099909287f23bbc9e2deee2e4cd8cf9b17c88618, but the ```unlimitedStorage``` permission can't be added as an optional permission and enabled after installation. I have opened #256 to address this.

**Comment by oudajosefu** [comment]
Ah, that makes more sense now, I appreciate the added warning.
