### ISSUE TITLE
Search page is classified as same popup level as first popup

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#255]
I would like to set a condition for a certain popup profile to work on the search page as the first popup but I can't find a condition to satisfy this. When I set the condition to work on a certain URL, both the first popup and search page start to use that profile, even though I want the search page to use another profile. When I set a condition to work on popup levels greater than 0, the same thing happens, both the search page and the first popup act as the 0th popup level, thus not allowing me to differentiate them in a condition.

In the given image below, I would like the first popup to use a different profile which I have set to only use Japanese-English dictionaries. However, this does not seem possible at the moment due to the reasons given above.

![image](https://user-images.githubusercontent.com/40701096/66803838-b003e200-eed5-11e9-9829-6bcc6689acd6.png)

**Comment by toasted-nutbread** [comment]
First popup on the search page is now assigned a depth of 1 instead of 0.

16521fec935845828b7e08baf1668657bb5a7cef
