### ISSUE TITLE
[Feature Request] Change language input of keyboard upon opening search page

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#257]
I am really curious to see if this is even possible. The idea is relatively simple: every time the search page is opened, whether that be by hotkey or the browser action search button, the input of my keyboard is changed to the chosen language of input in the settings. I honestly really doubt that browser extensions have the ability to do this, but I've seen it done in iOS with a specific Japanese dictionary app whenever I open it to the search screen. Please let me know if this is possible. I can't find any evidence that suggests so, but that could be because of bad search queries.

**Comment by siikamiika** [comment]
The closest to what I found was the [inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) attribute and [some sources](http://www.htmlcodes.ws/html-tags/input_inputmode.cfm) even claimed it supports the `kana` attribute, but it didn't seem to work at least for me.

Maybe you could use some automation software to both open the search page and set your active input method to Japanese, or if you don't have it already, add a keyboard shortcut for changing your input method: https://apple.stackexchange.com/a/135373

**Comment by oudajosefu** [comment]
Interestingly enough, I've discovered that even when typing with English input, any possible combination of letters that makes kana will turn into kana. This may be a bug, but even if it's not, I'd like to still be able to use Japanese input because of the ability to change kana into kanji when desired.

**Comment by siikamiika** [comment]
> Interestingly enough, I've discovered that even when typing with English input, any possible combination of letters that makes kana will turn into kana. This may be a bug, but even if it's not, I'd like to still be able to use Japanese input because of the ability to change kana into kanji when desired, which you lose when using this buggy English to kana input.

That uses https://wanakana.com/ and it's intended. It should work as long as you know how to type the entire word in kana.

> @siikamiika I do have the keyboard shortcut already, but in cases like this, my mind immediately goes to wondering how one can remove that extra step of switching inputs manually. I'll try the automation software, but that doesn't seem completely satisfying to be honest. I'll give it a shot and let you know.

Browsers can be quite limited when it comes to interacting with the OS, so unfortunately there's not much Yomichan can do to improve the situation. I don't know how often users find themselves in this situation, but if you find a way to automate setting the input method, maybe they could be added to the project wiki or a similar place where others can find it.

**Comment by oudajosefu** [comment]
> Browsers can be quite limited when it comes to interacting with the OS, so unfortunately there's not much Yomichan can do to improve the situation. I don't know how often users find themselves in this situation, but if you find a way to automate setting the input method, maybe they could be added to the project wiki or a similar place where others can find it.

Interesting... I wonder then if there is a way to take wanakana a step further and find a similar resource that lets one use kanji replacement. At the end of the day, the kana to kanji function is the one thing the search page lacks if it already utilizes English to kana.

**Comment by toasted-nutbread** [comment]
I don't think is possible to do this without a native application running on the host computer which could receive a signal and trigger the OS to change the keyboard. While it's possible to make Yomichan send a basic signal (much like how it communicates with AnkiConnect), the native application implementation would be highly dependent on the OS and keyboard software being used however, so that would fall outside the scope of this extension.

**Comment by oudajosefu** [comment]
Alright, that answers that. I appreciate the quick responses. I actually do want to make that native application but somehow make it cross-platform through Electron. This native application could actually be a huge upgrade to Yomichan, because its added capabilities could allow for the use of Yomichan outside of the browser, or at least I think.
