### ISSUE TITLE
Move focus to already opened search page when hotkey is pressed

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#260]
Instead of opening a whole new search page, Yomichan could check all tabs to see if the search page was already opened and shift the focus to that tab if it exists. I dislike having all these search pages open when I'm constantly searching words that I hear.

**Comment by oudajosefu** [comment]
Not really a feature request but more of a problem in my eyes that should be mended.

**Comment by siikamiika** [comment]
What if you had two search pages open next to each other when you wanted to compare the meanings of two words, or left one open to come back to it later after checking some other word?

I don't think the current behavior should be replaced, but focusing an already opened search page seems like a useful feature to me. I've already done something similar in the past if someone needs a starting point: https://github.com/siikamiika/firefox-tab-control

One thing that can limit how useful a feature like this is if an OS allows focus stealing (if the search page is in another window).

**Comment by toasted-nutbread** [comment]
>I don't think the current behavior should be replaced

Changing the search page to focus (one of) the existing search page(s) (if any) would make the button function the same as the options button, which does not open a new page if the options page is already open somewhere.

**Comment by siikamiika** [comment]
> Changing the search page to focus (one of) the existing search page(s) (if any) would make the button function the same as the options button, which does not open a new page if the options page is already open somewhere.

That's a good counterargument, but I don't think the options page is completely analogous to searching words although they are opened from the same menu, and the focusing is not implemented in Yomichan but in the browser. Actually now you could even want to have multiple options pages open because of recursive popups. :joy:

Anyway I mean that for the users who want to open a new search page the behavior could be the same, but there could be another hotkey that first checks if a search pages is already open.

**Comment by toasted-nutbread** [comment]
> Anyway I mean that for the users who want to open a new search page the behavior could be the same, but there could be another hotkey that first checks if a search pages is already open.

Perhaps something similar as when clicking a link, where middle click opens in a new tab, but standard click opens in the same tab? (In this case, the existing tab, if any, rather than the same tab.)

> Actually now you could even want to have multiple options pages open because of recursive popups. joy

Technically you can by just copying the link and pasting it into a new tab.

**Comment by siikamiika** [comment]
> Perhaps something similar as when clicking a link, where middle click opens in a new tab, but standard click opens in the same tab? (In this case, the existing tab, if any, rather than the same tab.)

I think that would be a great way to do it for mouse users. There should probably be a tooltip explaining each button because it changes the default click behavior.

**Comment by oudajosefu** [comment]
So to be clear, the search page hotkey would function the same as when opening the options page where it shifts the focus to an already opened tab of that page. And to open it intentionally in another tab, one would middle click ("Cmd + click" on macOS) to do so. Is this correct?

**Comment by siikamiika** [comment]
>So to be clear, the search page hotkey would function the same as when opening the options page where it shifts the focus to an already opened tab of that page. And to open it intentionally in another tab, one would middle click ("Cmd + click" on macOS) to do so. Is this correct?

Yeah, that's how the PR version currently works.

I was a bit concerned about removing existing functionality that some users could depend on, but on second thought it's quite easy to make the browser open the search page in a new tab or a window as a keyboard user even without a dedicated hotkey in Yomichan for it by opening the search page URL directly from the OS.

Which reminds me, now that https://github.com/FooSoft/yomichan/issues/247 exists, we are one step closer to https://github.com/FooSoft/yomichan/issues/146 (although probably won't ever get the same experience for desktop). At least for software that lets you copy text to the clipboard, it should be quite easy to make Yomichan search that text.

I'm actually going to open a new issue for APIs between Yomichan and the OS to keep this issue on topic.
