### ISSUE TITLE
{furigana-plain} has improper spacing for Anki

### ISSUE THREAD

**Issue by Rapptz** [FooSoft/yomichan#264]
The Anki furigana support both in AnkiMobile and desktop Anki (I assume iOS as well) require spaces between each segment to properly render the furigana.

For example, a word like お祝い will spit out お祝[いわ]い for the plain furigana. However, this renders incorrectly: 

![Incorrect Anki Furigana Render](https://user-images.githubusercontent.com/1695103/67284272-4e2e1400-f4a3-11e9-844d-6a085136b915.png)

To fix this requires a space between the お and the kanji: お 祝[いわ]い

![Correct Anki Furigana Render](https://user-images.githubusercontent.com/1695103/67284304-60a84d80-f4a3-11e9-8457-0670e36c6dd8.png)

**Comment by FooSoft** [comment]
How would you do furigana for 美味しい or other あてじ? The problem is that the term and reading are tied together, and it would be tricky (albeit not impossible), to try to match up parts of the reading to kanji in the term.

**Comment by FooSoft** [comment]
Ah, actually nevermind, thinking about this more, there was a code contribution many moons ago to make this work, so that just needs to be propagated to the Anki layer.

**Comment by Rapptz** [comment]
> How would you do furigana for 美味しい or other あてじ?

美味しい should be 美味[おい]しい. 

As far as I know this space requirement happens when there's kana between the kanji. So something like 食べ物 should be 食[た]べ 物[もの] and 試し切り would be 試[ため]し 切[ぎ]り

**Comment by siikamiika** [comment]
In this case all the required information is contained in お祝い and its reading おいわい and it's up to the implementation to use that information, but cases like 飼い犬・かいいぬ (https://github.com/FooSoft/yomichan/issues/94) are ambiguous unless you have definitive information about the possible readings for each kanji. Even then exceptions with あてじ such as the one @FooSoft mentioned can come and ruin the party, and at least misplace kana on top of the wrong kanji (for example when the あてじ has partial matches) if there's no other ambiguity.

**Comment by Rapptz** [comment]
Apologies. There might be some misunderstanding here.

I'm not really suggesting to correct the current segmentation (which is where the bug regarding かいいぬ being badly segmented for 飼い犬 comes from). I'm talking about the current segmentation results (i.e. the result of `jpDistributeFurigana`) being incorrect for the furigana-plain handlebars. I can open a PR to fix this rather than the segmentation which can be tackled later.
