### ISSUE TITLE
[Feature request] Import multiple dictionaries at once

### ISSUE THREAD

**Issue by Shadlock0133** [FooSoft/yomichan#269]
Importing and waiting for each dictionary to get added is really annoying. It also makes the process slower for users than adding them all at once.

**Comment by siikamiika** [comment]
Do you mean that you would like to queue more dictionaries to import while one is being imported, or actual parallel import? I think the former might be doable, but the latter feels too complex for the small benefit.

**Comment by Shadlock0133** [comment]
Former is more or less what I want. I was thinking that import file dialog would allow to choose multiple files and add them to something like an internal queue.

**Comment by FooSoft** [comment]
What is your use case? I imagine that for most users of Yomichan, you add the dictionaries once and then you don't think about it again. Furthermore, most people probably only use 2-3 dictionaries tops... I'm not the against the idea, but I worry about introducing complexity for an edge case.

**Comment by Shadlock0133** [comment]
Every so often (avg. 3 months) yomichan forgets the 5 dictionaries I use which I have to re-add. Since it takes a bit of time to add each one individually, I leave it in background to process and forget about it. It ends up taking few hours to make yomichan work again this way. Sometimes I don't even want to fix it because I know it will take too long.

**Comment by toasted-nutbread** [comment]
The dictionary clearing issue may be fixed when #256 is included in a release. See also: #254, #100.

**Comment by Shadlock0133** [comment]
Also, given that the only way to remove a dictionary is to purge them all and re-add all but the one, it would speed up this process.

**Comment by oudajosefu** [comment]
I agree with @Shadlock0133. Every time I want to get rid of a dictionary due to an upgrade of the version of the dictionary or just a personal change in tastes of which dictionary is better, I have to purge the whole database and re-add every dictionary, which is very annoying. I haven't had the dictionary fickleness issues like @Shadlock0133, but not having to tell my browser what to download next each time it finishes one would be less of a hassle.

**Comment by toasted-nutbread** [comment]
>the only way to remove a dictionary is to purge them all and re-add all but the one

I am looking into changing this so you can actually delete individual dictionaries. Current testing results on Chrome seem to indicate that the English KANJIDIC can be removed in under a second, and English JMdict can be removed in 25-30 seconds. These times are certainly non-trivial, so there is still a bit of wait involved, but the deletion times are faster than the import times. If a progress bar is shown during deletion, I think the speed is probably tolerable enough to warrant at least having the option to delete individual dictionaries.

**Comment by siikamiika** [comment]
@toasted-nutbread I'm not sure if this applies after 2 years (and after partly switching to raw IndexedDB), but apparently deleting rows caused problems in the past: https://github.com/FooSoft/yomichan/issues/86#issuecomment-332695915

**Comment by toasted-nutbread** [comment]
Thanks for the comment reference, it's useful to see some background on what some of the issues have been. I went ahead and opened up another bulk task tracking/discussion issue for various things related to the database, since there is a fairly broad range of topics. #270
