### ISSUE TITLE
[Feature Request] Regex formatting when adding cards to Anki

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#273]
Whenever I try to add a card from youtube with its subtitles as the sentence, the timestamps are sometimes added too. With some sort of regex matching similar to the conditions option to match urls with regex, I can add something like `[0-9]:[0-5][0-9].*$` to match the `1:50 / 1:06:07` part in this automatically generated subtitle `金井雅彦「無限と連続」ー高校生のための東京大学オープンキャンパス2018 模擬講義この位相という言葉なんだけれどもこれは物理で使ういそうと数学で使ういそうとは1:50 / 1:06:07` and replace it with a blank string.

It would be nice to have this ability so as to save time deleting parts of added sentences that occur for every part of a video.

**Comment by toasted-nutbread** [comment]
b59a5b8cdb9bf8cdc28701e16c3d581fb96f4ef8 You can now use regex in the handlebars templates. There are two options: one which replaces, and one which just returns the match(es).

```
{{#regexReplace "REGULAR_EXPRESSION" "REPLACEMENT_STRING" "REGEX_FLAGS"}}Whatever content or {{tag}} text{{/regexReplace}}

{{#regexMatch "REGULAR_EXPRESSION" "REGEX_FLAGS"}}Whatever content or {{tag}} text{{/regexReplace}}
```

REGULAR_EXPRESSION is the pattern passed to the [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) constructor.
REPLACEMENT_STRING is the [replacement text](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter).
REGEX_FLAGS are the [flags passed to the RegExp constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Parameters).

**Comment by toasted-nutbread** [comment]
FYI: You are now able to test templates on the settings page. Syntax errors will also show exception information that handlebars returns. Unfortunately, the sentence context is empty, so you can't directly test that value, but other placeholders can be used.

184cc4cf28594f3bef9e141a8cbf9d7eb7a39e88

---

![image](https://user-images.githubusercontent.com/11037431/68535352-2813cb00-030f-11ea-9942-8920dda86fb4.png)

**Comment by oudajosefu** [comment]
Thanks.
```
{{#regexReplace "REGULAR_EXPRESSION" "REPLACEMENT_STRING" "REGEX_FLAGS"}}Whatever content or {{tag}} text{{/regexReplace}}

{{#regexMatch "REGULAR_EXPRESSION" "REGEX_FLAGS"}}Whatever content or {{tag}} text{{/regexReplace}}
```
The closing tag you use for `{{#regexMatch}}` is `{{/regexReplace}}`. Was that on purpose or just a mistake?

**Comment by toasted-nutbread** [comment]
Indeed, that was a typo.

**Comment by toasted-nutbread** [comment]
> Whenever I try to add a card from youtube with its subtitles as the sentence, the timestamps are sometimes added too.

Do you have any examples of where this happens?

**Comment by oudajosefu** [comment]
Yes, if you go to any youtube video with captions turned on (doesn't matter if they're auto-captions) and click the (+) button after hovering over a word, the {sentence} place will most likely show time stamps.

Here's one example from a video on the Japan youtube's trending page:
![image](https://user-images.githubusercontent.com/40701096/69492548-6954c080-0e61-11ea-8518-ac864caea994.png)

**Comment by toasted-nutbread** [comment]
Thank you, it looks like #286 resolves this issue.

**Comment by oudajosefu** [comment]
When you say it resolves it, do you mean that Yomichan now automatically detects the timestamps and doesn't include them? Testing this has led me to believe otherwise, that it is still the same.
