### ISSUE TITLE
"Enable scanning of popup expressions" not working properly, and related improvements

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#275]
Some time ago the option started scanning a single character in popup expression instead of completely disabling it, which I tracked down to `TextSourceRange`. I added a workaround while working on query parser, but it really just hides the problem instead of fixing it: https://github.com/siikamiika/yomichan/commit/1cbb24b31eba781916429b4ca6e467109361c84e#diff-6559642516f798ca10f6693f70f1481eR485-R487

There's also the question if it should work automatically on search page despite saying "popup expressions". Another related question is whether custom CSS should also affect the search page, because currently it does not. My view is that they're just the same thing in a different place, but I'm open to ideas. I also added it there on the branch: https://github.com/siikamiika/yomichan/commit/1cbb24b31eba781916429b4ca6e467109361c84e#diff-0d2e54fd1ab25e9ab5fd6c04de9f8f75R28-R31

Then I'm thinking that it would be a related feature to also extend the scan blocking to the kanji definition page and prevent scanning the stroke order picture.

**Comment by toasted-nutbread** [comment]
fa963722a79c26c1642bbf81a2e153bd0c1a3fe8 fixes your first comment.

**Comment by toasted-nutbread** [comment]
> There's also the question if it should work automatically on search page despite saying "popup expressions".

I don't have any strong preference either way. "Enable scanning of expressions in search results" may clarify the intent if you decide to go that route. In general, I think a lot of the settings on the settings page could use some extra description, particularly some of the more advanced ones (e.g. "Deep DOM scan").

> Another related question is whether custom CSS should also affect the search page, because currently it does not. My view is that they're just the same thing in a different place, but I'm open to ideas.

I agree; the theme already works this way, so no reason why the custom CSS should work differently.

> Then I'm thinking that it would be a related feature to also extend the scan blocking to the kanji definition page and prevent scanning the stroke order picture.

Feel free to add as many selectors as you want that might be beneficial; the existing functionality should support adding things easily.

**Comment by siikamiika** [comment]
Resolved in 25af532ab7750a456f46b37825d8dbe876363d19, 177fad56b5d1d3165d0b8f755b935e8b953c7dff and cf0bb0a9e22bc5dee47d9a4d8b844c0ca67c0269.
