### ISSUE TITLE
[feature request] Mark target word in sentence

### ISSUE THREAD

**Issue by HelenFoster** [FooSoft/yomichan#28]
Hi, in this thread, people are talking about automatically finding and marking the target word in the sentence, for cards that are already made.
http://forum.koohii.com/thread-14276.html

But when Yomichan is making new cards, it already knows exactly where the target word is in the sentence, so would be able to mark it without any guessing.

I'd like to suggest using `<span class="targetword">` or similar, so the appearance is defined in the card CSS, and people can change their mind later about how and whether to display this marking.

**Comment by HelenFoster** [comment]
I may be wrong about using spans, as it's invisible in the Anki edit boxes.

**Comment by HelenFoster** [comment]
Using 3 fields is kind of messy, but probably the easiest to understand.

As xtreme1 just pointed out on the forum, using `<b>` tags still allows for the possibility of overriding the appearance with CSS. Bad but effective.

**Comment by FooSoft** [comment]
Fixed in 1.1.9

**Comment by morning-paradigm** [comment]
Sorry for reviving an old issue, but I don't see how this is fixed.
I've just checked the {sentence} field in HTML editor, it's just plaintext. Is there some option I'm missing?

**Comment by toasted-nutbread** [comment]
`{cloze-prefix}<b>{cloze-body}</b>{cloze-suffix}`

**Comment by morning-paradigm** [comment]
Oh, I see. Thank you!
