### ISSUE TITLE
Audio for many words is broken

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/yomichan#280]
Something weird with audio. Voices are different and not all words are correct.
For example 返答 - へんとう is pronounced like べんとう

Sometimes I also have that in audio field when exporting into anki:

[sound:1573493339.864842.mp3]https://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kanji=%E6%AD%A4%E3%82%8C%E3%81%A3%E3%81%BD%E3%81%A3%E3%81%A1&kana=%E3%81%93%E3%82%8C%E3%81%A3%E3%81%BD%E3%81%A3%E3%81%A1 download failed with error HTTPSConnectionPool(host='assets.languagepod101.com', port=443): Max retries exceeded with url: /dictionary/japanese/audiomp3.php?kanji=%E6%AD%A4%E3%82%8C%E3%81%A3%E3%81%BD%E3%81%A3%E3%81%A1&kana=%E3%81%93%E3%82%8C%E3%81%A3%E3%81%BD%E3%81%A3%E3%81%A1 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))

**Comment by siikamiika** [comment]
I noticed yesterday that their certificate has expired again (#180), so that's causing the error message. Which audio source are you using when you hear 返答 as べんとう? To me it sounds like へんとう when the audio source is https://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kanji=%E8%BF%94%E7%AD%94&kana=%E3%81%B8%E3%82%93%E3%81%A8%E3%81%86

**Comment by Geniusssmit** [comment]
> I noticed yesterday that their certificate has expired again (#180), so that's causing the error message. Which audio source are you using when you hear 返答 as べんとう? To me it sounds like へんとう when the audio source is https://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kanji=%E8%BF%94%E7%AD%94&kana=%E3%81%B8%E3%82%93%E3%81%A8%E3%81%86

That source is not working for me for some reason.
One that working is Japanesepod101 (alternative). Also this word 断片 pronounced たんぺん

**Comment by Geniusssmit** [comment]
It's ok now

**Comment by siikamiika** [comment]
Yeah, they renewed their certificate and now browsers download the audio normally again. I'll close the issue, but someone will probably get problems again three months from now when their current Let's Encrypt certificate expiress unless they managed to configure it to autorenew.
