### ISSUE TITLE
[Feature Request] Anki 2.1.x compatibility

### ISSUE THREAD

**Issue by Pogosaur** [FooSoft/yomichan#282]
Hello there, firstly great work on yomichan, it's the best. 

Not sure how easy or difficult this may be, most likely difficult, but Anki is no longer going to support syncing for Anki 2.0.x, which means that whoever wants to use Yomichan will no longer be able to easily sync to multiple devices. This, for me, is a very big issue seeing as I study almost exclusively with my phone. Is there any way to work towards having Anki 2.1.x compatibility? 

Otherwise the only way to be able to use Yomichan and study on mobile will be to constantly import and export one's collection after adding new cards which is obviously very troublesome. 

Sorry if this is in the wrong place but thanks for taking the time to read anyway.

**Comment by FooSoft** [comment]
I think you are probably talking about AnkiConnect, and not Yomichan specifically. AnkiConnect has supported Anki 2.1.x for a pretty long time now, so you should be able to use it just fine with the newest desktop version.

**Comment by Pogosaur** [comment]
I seemed to have confused this: https://ankiweb.net/shared/info/934748696 with AnkiConnect. I'm really relieved to hear that it works with 2.1.x, sorry for the useless feature request and thanks for such a prompt reply!
