### ISSUE TITLE
Getting 'TypeError: Cannot read property 'index' of undefined' from template

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#283]
Even after resetting the template, this error shows up for no apparent reason.

![image](https://user-images.githubusercontent.com/40701096/69108977-84739a80-0a33-11ea-93a1-ebbd5e7c286a.png)

**Comment by toasted-nutbread** [comment]
Fixed with baf0325f628d42f382370b82e33e4c1a810050f9.
