### ISSUE TITLE
.eslintrc file

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#289]
The [README.md](https://github.com/FooSoft/yomichan/blob/91c54e1853025c82b9f9e60c490c989ff7149d7d/README.md) file has a guideline under the development heading:

> Follow the [conventions and style](https://raw.githubusercontent.com/FooSoft/dotfiles/master/.eslintrc.json) of the existing code.

This URL is now 404'd due to the repository being hidden or deleted. @FooSoft: do you have a copy of this file available that could be added to this project? If not, I can make a new one.

I already have a linter enabled, but the settings I have may differ from others.

**Comment by FooSoft** [comment]
Whoops -- that file went away when I switched my dotfiles repository to private. I forgot that I had other things referencing it. I've re-added `.eslintrc.json` to the project root.

**Comment by FooSoft** [comment]
What kinds of things do you have in your lint config btw, @toasted-nutbread? We should add anything that can help keep the code qualify and consistency up.

**Comment by toasted-nutbread** [comment]
I have been using jshint rather than eslint, but it looks like eslint provides more options, which is good. Listed below is a list of some things I noticed after enabling eslint and scanning through the code. I can go through and update all of the code to be conformant after this.

* ```"curly": ["error", "all"]``` should be enabled. The current style already appears to be using this, but it's not technically enforced by the ruleset.
* ```"no-constant-condition": "off"``` should be added. Effectively this allows for ```while (true)``` statements, which are used (sparingly) at 5 locations in the code.
* ```"arrow-parens": ["error", "as-needed"]``` might not be the best option. It looks like the project currently has 142 occurrences of using a single-argument arrow functions, 88 of which include parentheses around the argument, and 54 of which don't (62% vs 38%). Should ```"as-needed"``` be changed to ```"always"```? IMO this would make the syntax of all arrow functions more consistent, and eslint's [arrow-parens docs](https://eslint.org/docs/rules/arrow-parens) even links to [Airbnb's JS Style Guide](https://github.com/airbnb/javascript#arrows--one-arg-parens), which has a similar rationale.
* Having [```require-atomic-updates```](https://eslint.org/docs/rules/require-atomic-updates) enabled affects the code in some weird ways. While some of the warnings are completely understandable, there are a few places where it warnings unexpectedly. Might be best to leave enabled but flag code with ```// eslint-disable-line require-atomic-updates```.
  For example, eslint complains about the assignment ```persisted = true;``` below:
  https://github.com/FooSoft/yomichan/blob/233a115ff9d470ad26aabb53226da5517bd34940/ext/bg/js/settings.js#L809-L830
