### ISSUE TITLE
WanaKana update

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#290]
There is at least one bug in the current version of WanaKana which can sometimes affect text input on the search page, specifically the issue noted in the [2.3.1 release notes](https://github.com/WaniKani/WanaKana/releases/tag/2.3.1).

* Would it be worth it to update?
* Would an update affect #279 at all? (@siikamiika)
* The latest version minified (v4.0.2) is about 5x larger than the current minified version included with Yomichan (v2.2.3) which may indicate that it has unnecessary bloat. If an upgrade is considered worthwhile, should the upgrade be done to the latest version ([v4.0.2 @ 83.8KB](https://unpkg.com/browse/wanakana@4.0.2/umd/)) or just a version which addresses the bug I mentioned ([v2.3.4 @ 17.3KB](https://unpkg.com/browse/wanakana@2.3.4/lib/))? (Current is [v2.2.3 @ 16.7KB](https://unpkg.com/browse/wanakana@2.2.3/lib/).)

**Comment by FooSoft** [comment]
If everything works properly in latest version, we should just use that. Size is not going to impact scanning perf, so it should be fine.

**Comment by siikamiika** [comment]
I did some testing with furigana conversion and IME input on the search page with 4.0.2, and didn't notice any issues.

It also seems to fix a bug where an uncommitted conversion on the OS level IME gets converted from alphabets to hiragana and causes the OS IME dropdown to disappear.
