### ISSUE TITLE
Full width popup not visible when pinch-zoomed in

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#318]
Pinch-zoom scaling came up in https://github.com/FooSoft/yomichan/pull/316, and it reminded me about this issue where full width popup isn't visible when you've zoomed in to some text. The popup is also very small when you zoom all the way out and the website is not "responsive" (`<meta name="viewport" content="width=device-width, initial-scale=1">` etc).

As it turns out, there's an API that could possibly be used to resolve this issue and the additional requirements for https://github.com/FooSoft/yomichan/issues/315:
https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API

The minimum requirements are Firefox for Android 68 and Chrome 62 for all the interesting events like `VisualViewport.onresize`.

**Comment by toasted-nutbread** [comment]
Was this fixed with #316?

**Comment by siikamiika** [comment]
Yeah, I forgot to close this one
