### ISSUE TITLE
[Feature Request] settings GUI improvement

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#319]
With the amount of settings there are now it sometimes takes quite a bit of scrolling to get to the desired section.
I think adding a sidebar with anchor links to each section would improve this process.

**Comment by toasted-nutbread** [comment]
I agree. There's actually several things that should be added at some point to improve the settings GUI, including better descriptions, but this can be added to that list as well. Something similar to Chrome's settings page might work well.

Added to the list in #296

**Comment by toasted-nutbread** [comment]
Resolving since the updated settings v2 page is in beta in the latest testing (soon stable) release.
