### ISSUE TITLE
Yomichan allowing duplicates to be created. 

### ISSUE THREAD

**Issue by NiceMaymay** [FooSoft/yomichan#321]
After an import of a different deck into my usual Yomichan mining deck, it seems that I can now import random words more than once. The deck I added did include some duplicates but I quickly amended and removed the duplicates that the new deck introduced. Some words are still working with the anti-duplicate checker function but a sizable amount are letting me add duplicates.

**Comment by toasted-nutbread** [comment]
How are you noticing this issue when using Yomichan? Is Yomichan showing the `+` buttons as green even when a term is already in the deck? or is it something else?

**Comment by NiceMaymay** [comment]
> 
> 
> How are you noticing this issue when using Yomichan? Is Yomichan showing the `+` buttons as green even when a term is already in the deck? or is it something else?

Yeah, it seems to be showing the green + on cards I definitely have.  I'm not sure what the criteria is but it hasn't been greying out those add buttons on certain cards.

**Comment by toasted-nutbread** [comment]
As far as I'm aware, the first field for the Anki card is supposed to be treated as a unique identifier. I'm not sure exactly how AnkiConnect/Anki handles it internally, @FooSoft may know more.

Can you share what your Yomichan Anki field values look like? And do you have any examples of a card + Yomichan term which can reproduce the issue?

**Comment by FooSoft** [comment]
Yes, @toasted-nutbread is correct, the first field is what must be unique when adding cards. I would double check your template settings in Yomichan and your model in Anki.

**Comment by toasted-nutbread** [comment]
Is there any more information for this issue? Is it still occurring or has it been resolved somehow?

**Comment by toasted-nutbread** [comment]
It's been a year, so I'm going to assume this issue was resolved.

**Comment by fello3** [comment]
I have an issue with cards not being recognized in the same deck. See here: https://imgur.com/a/lAuPOwx
