### ISSUE TITLE
Order of results

### ISSUE THREAD

**Issue by yakunitatanai** [FooSoft/yomichan#323]
It seems that there was some update recently as yomichan asked about new permissions. I've also noticed that the settings page has changed a bit since the last time I saw it. Almost all settings returned to default ones, but that isn't the very problem. 
The order of results has changed, and I don't know why and what to do. Let me give you a few examples. 
1. Before this, something like 経て would give the definition of exactly 経て first and only after that it would give the definitions of 経る and 経つ(their て-forms are 経て). But now the order is different: the first one is 経る, the second one is 経つ and the third one is 経て. It makes me look through lots of redundant results. 
2. If I try to find the definition of って, it will give me the definitions of 得, 居, 坐 and つ (because of old conjugation) and only after those redundant ones it will say that って is a casual quoting particle. 
I've spent some time trying to find settings for fixing that, but I couldn't find anything useful. 

So, can you help make it as it was before?

**Comment by toasted-nutbread** [comment]
> It seems that there was some update recently as yomichan asked about new permissions.

Just in case there's any worry about this, the extra permission was to try and prevent the dictionary from being deleted by the browser when running low on disk space.

1. I see this too. Version 1.8.1 listed them correctly, version 20.1.4.0 lists them out of order.
2. This is likely the same ordering issue, but what dictionaries do you have installed? Just so I have something to try to test against.

**Comment by toasted-nutbread** [comment]
I believe I found the culprit.

https://github.com/FooSoft/yomichan/commit/ae10bb7096fafc94ffb7227a16e13373c1c1c403#diff-dfe1a8edf9105e462dc9fb15e370b437R70-R71
This commit inadvertently reversed the `reason` sorting order.

This should be fixed with fe5e05f8aab195819339db5a8ce975a3733c0a6f. I haven't verified your 2. comment yet, but I think it's the same issue.

**Comment by yakunitatanai** [comment]
> 
> 
> > It seems that there was some update recently as yomichan asked about new permissions.
> 
> Just in case there's any worry about this, the extra permission was to try and prevent the dictionary from being deleted by the browser when running low on disk space.
> 
>     1. I see this too. Version 1.8.1 listed them correctly, version 20.1.4.0 lists them out of order.
> 
>     2. This is likely the same ordering issue, but what dictionaries do you have installed? Just so I have something to try to test against.

Speaking about #2, I have a few Japanese monolingual dictionaries installed as well (daijirin, daijisen, koujiten...). Definitions from them are usually shown after Japanese-English ones (JMdict, Kireicake) due to "result priority" configuration. But now they are shown in the very beginning. The reason of this is probably the same as in #1.

**Comment by FooSoft** [comment]
I'll post a new version with the change (20.1.12.0)

**Comment by yakunitatanai** [comment]
The new version fixes the aforementioned problem. However, another one probably occurs instead. As I remember(it may be wrong), proper names were usually shown after the main definitions in older versions. Now they are shown before them. Here are some examples to test it: 秋・本・物・水・風. I tried to find some screenshots to compare them. Compare the definitions list for 会:
This is what I found:
![2bd998709ef4b391bce9450b52c25f75edd9fe7e_2_517x364](https://user-images.githubusercontent.com/59809703/72327978-237ae280-36c3-11ea-875f-b5de879cffd3.png)
This is what I see now:
![image](https://user-images.githubusercontent.com/59809703/72328042-3f7e8400-36c3-11ea-9045-f1a9d5f51f9d.png)

**Comment by siikamiika** [comment]
@yakunitatanai You can adjust the dictionary priority in options after enabling advanced options under General Options. I guess the ordering might have been messed up when your settings were reset.

**Comment by yakunitatanai** [comment]
> 
> 
> @yakunitatanai You can adjust the dictionary priority in options after enabling advanced options under General Options. I guess the ordering might have been messed up when your settings were reset.

Thanks, it was because of settings after resetting.

**Comment by toasted-nutbread** [comment]
Closing as this seems to be resolved.
