### ISSUE TITLE
[Feature Request] Text spacing and furigana toggles 

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#324]
Add a toggle for text spacing in the search page and under text parsing options. 

Allow reading mode to be set to none
![image](https://user-images.githubusercontent.com/24824399/72444431-fe818f00-37ea-11ea-8314-cc70f1a95157.png)

**Comment by siikamiika** [comment]
Thanks for the ideas! I've also thought of adding part of speech highlighting with colors (underline, background or text color) so I'll include these requests in the next round of feature additions.
