### ISSUE TITLE
Too much padding above results

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/yomichan#325]
Why so much space here? on 1.8 everything was ok
![chrome_vH6odbXo24](https://user-images.githubusercontent.com/24941285/72537330-01cd5700-388d-11ea-8347-715c5460281e.jpg)

**Comment by siikamiika** [comment]
This has been fixed in https://github.com/FooSoft/yomichan/pull/317, but it's not merged yet. I'll see if there's something to fix before it can be merged.
