### ISSUE TITLE
"Automatically hide results" not working correctly on YouTube videos

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#328]
(Originally added for https://github.com/FooSoft/yomichan/issues/71)

Example: open https://www.youtube.com/watch?v=VK4vDfO_Ce8 and turn on the 日本語/English subtitles, scan Japanese text, and then scan the video outside of the dimmed area that's reserved for subtitles. The popup doesn't close. It will close if you scan an empty spot inside the dimmed area or outside of the video element.

I'm not sure if the video element somehow eats the `mousemove` events, but
```javascript
document.onmousemove = (e) => {console.log(e)}
```
will log the events even when the mouse cursor moves over the YouTube video element.

This started to happen some time during the latter half of 2019 due to a change in either Yomichan or YouTube.

**Comment by toasted-nutbread** [comment]
This appears to work for me. What are the settings you're using?

**Comment by siikamiika** [comment]
@toasted-nutbread Ah, it only seems to happen on Firefox

**Comment by toasted-nutbread** [comment]
```
SecurityError: The operation is insecure.
caretRangeFromPoint@fg/js/document.js:272:19
caretRangeFromPointExt@fg/js/document.js:288:46
docRangeFromPoint@fg/js/document.js:128:41
searchAt@mixed/js/text-scanner.js:301:49
async*search@mixed/js/text-scanner.js:72:24
onMouseMove@mixed/js/text-scanner.js:75:9
EventListener.handleEvent*addEventListener@mixed/js/text-scanner.js:271:14
hookEvents@mixed/js/text-scanner.js:245:18
setEnabled@mixed/js/text-scanner.js:226:22
setOptions@mixed/js/text-scanner.js:284:14
updateOptions@fg/js/frontend.js:93:14
async*prepare@fg/js/frontend.js:43:24
main@fg/js/frontend-initialize.js:32:20
async*@fg/js/frontend-initialize.js:35:1
```

**Comment by toasted-nutbread** [comment]
Issue was due to `caretPositionFromPoint` returning an element inside a closed `ShadowRoot`.

**Comment by siikamiika** [comment]
I recall seeing those SecurityErrors when opening the console on YouTube, but just glancing at them I thought it was something network related. Working perfectly now. Thanks!
