### ISSUE TITLE
Adding a card to Anki works only once per session

### ISSUE THREAD

**Issue by asakura42** [FooSoft/yomichan#329]
Adding a card to Anki works only once per session. Then the buttons with pluses become gray and it is not cured even by reloading the page. Only by restarting the browser.
I use Anki 2.1, Firefox and the latest version of Yomichan.

**Comment by toasted-nutbread** [comment]
* Is there a [book icon](https://github.com/FooSoft/yomichan/blob/master/ext/mixed/img/view-note.svg) button next to the gray buttons? If so, what happens if you click this?
* What do your Anki field templates look like in Yomichan?

**Comment by toasted-nutbread** [comment]
Is there any more information for this issue, or did the problem go away?

**Comment by toasted-nutbread** [comment]
Assuming this issue has been resolved since it's been open for nearly a year; closing.
