### ISSUE TITLE
Audio not working by clicking when resultOutputMode = 'merge' and result is kana only

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#336]
It works when using the keyboard shortcut `Alt+P`. Example word with JMDict: ようこそ

The problem is that the `kanji` and `kana` query string parameters are swapped when a word is kana only.

- With click: https://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kanji=%E3%82%88%E3%81%86%E3%81%93%E3%81%9D&kana=
- With hotkey: https://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kana=%E3%82%88%E3%81%86%E3%81%93%E3%81%9D

It happens regardless of the amount of results where some of them also have kanji, for example: ウケる

While debugging I also noticed that `expressionIndex` will be `-1` when clicking a single expression result like ようこそ, but it's 0 when using the hotkey. Not sure yet if that matters.

**Comment by siikamiika** [comment]
Found an example where one works but another doesn't: ごたごた
The katakana version is requested as `kanji` but the hiragana one as `kana`.

**Comment by siikamiika** [comment]
I'll try to look at this issue more closely the next week, starting from testing if it existed before https://github.com/FooSoft/yomichan/pull/317. If it didn't, it could be a simple fix.

**Comment by siikamiika** [comment]
There were two issues, one of which had existed for a very long time.

The first was caused by https://github.com/FooSoft/yomichan/pull/317/commits/be77544d77ba1f07955d76ebba1ab36286f0e52f in #317, and was fixed by https://github.com/FooSoft/yomichan/commit/dd019ecf687299b0d2238312de7c476b2a263107.

The second one caused katakana words to be queried as `kanji` from the `jpod101` audio source. I changed the check from hiragana to any kana in https://github.com/FooSoft/yomichan/commit/02e0e24153eb95b45057cfc92cadb6563b229cc1.

----------------

Offtopic, but I still try to click an audio button next to a single expression sometimes from old habit after https://github.com/FooSoft/yomichan/pull/317/commits/be77544d77ba1f07955d76ebba1ab36286f0e52f. There is already some discussion about touchscreen usability of the `.term-expression:hover` solution in https://github.com/FooSoft/yomichan/issues/292. I also think it would be nice if the behavior was consistent regardless of the number of results. Maybe it would be better if the audio button was next to a single expression but shown without `:hover` like the tags are now. It would also make https://github.com/FooSoft/yomichan/commit/dd019ecf687299b0d2238312de7c476b2a263107 unneeded. @toasted-nutbread

**Comment by toasted-nutbread** [comment]
You can undo be77544d77ba1f07955d76ebba1ab36286f0e52f if you think that would make more sense, I'm not tied to either option. I would leave the naming changes to display-generator.js in that commit, however, and adjust line 236 of display.css accordingly.

**Comment by siikamiika** [comment]
https://github.com/FooSoft/yomichan/commit/05bb4aef71c5c062b451dd04dcd55111f7ba7377

**Comment by siikamiika** [comment]
I think it would be fine if `.term-expression-details` was always visible when `[data-count="1"]`, but this looked a bit off sometimes:
```css
.term-expression-list[data-multi=true][data-count="1"] .term-expression-details {
    visibility: visible;
}
```

**Comment by toasted-nutbread** [comment]
I think the problem with permanent visibility is the overlap with other elements, including tags overlap term-reasons and frequencies overlapping the definitions.

![image](https://user-images.githubusercontent.com/11037431/73226539-741c2200-413e-11ea-84c2-9381915c8751.png)

**Comment by siikamiika** [comment]
Ah, that's true. Didn't remember the frequencies. I'll close this issue as it's solved but we can further discuss a better solution for displaying multi-expression `.term-expression-details` in #292.
