### ISSUE TITLE
FYI: Projects

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#347]
FYI: I have set up some projects to better track tasks and progress for some of the issues I have set up.

https://github.com/FooSoft/yomichan/projects

Currently using them to have better tracking for the content in #267, #270, #292, and #296. If any other collaborators else finds them useful, feel free to create any additional projects for anything which has a large enough scope (e.g. #262). The ones I created are set up using the default kanban configuration.

**Comment by siikamiika** [comment]
Thanks! I've found myself trying to find the ID's of larger issues that I want to mention when I see something related. This should make it easier. I agree that #262 qualifies as a project too, and I can try to organize my plans at some point.

**Comment by siikamiika** [comment]
I've added a new project: https://github.com/FooSoft/yomichan/projects/6

While it would technically also include things like Anki and audio sources, I've limited the scope to features that don't yet exist or were added after https://github.com/FooSoft/yomichan/issues/262 and can be solved in a general way.
