### ISSUE TITLE
Kanji information page dividers

### ISSUE THREAD

**Issue by psychodelicwasabi** [FooSoft/yomichan#349]
I thought about adding this to my previous submission, but I guess they're not so close to be dealt with in the same place, so I made a new one. 
 Ever since the built-in themes updates, the lines separating the kanji information vanished. More than an aesthetic issue, I guess that makes sorting the information a slightly harder, which is quite annoying.
 Speaking about aesthetics, though, I'd just like to put in words how much I disliked the change to the little "open book" you click to go forward or backwards on the pop-ups. I know that was a request by an user, but I'd just like to have it as it used to be, if possible.

**Comment by toasted-nutbread** [comment]
> Ever since the built-in themes updates, the lines separating the kanji information vanished. More than an aesthetic issue, I guess that makes sorting the information a slightly harder, which is quite annoying.

This has actually been fixed in #317, but it is not in a stable release yet. The testing release does include it.

> Speaking about aesthetics, though, I'd just like to put in words how much I disliked the change to the little "open book" you click to go forward or backwards on the pop-ups. I know that was a request by an user, but I'd just like to have it as it used to be, if possible.

This has also been changed such that the icons and the extra space are not shown if there is no history (also not in a stable release yet). Does that address your issue with it?

**Comment by psychodelicwasabi** [comment]
> This has actually been fixed in #317, but it is not in a stable release yet. The testing release does include it.

Great!

>This has also been changed such that the icons and the extra space are not shown if there is no history (also not in a stable release yet). Does that address your issue with it?

I'm not sure, my problem with it is how it appears above the rest of the icons, while I liked how it used to appear by their side in the past.

**Comment by siikamiika** [comment]
> I'm not sure, my problem with it is how it appears above the rest of the icons, while I liked how it used to appear by their side in the past.

I changed it to be a button that exists regardless of your scroll position to be consistent with how web browsers work. You can now use it even if you scroll the other icons related to single results out of view. So the changes were added from functional standpoint. I understand that it's hard to get used to something you've used differently for a long time, and it should be quite simple to add alternative display options for the history button(s) using the framework added in #317 if you don't like how it works in the current testing release.
