### ISSUE TITLE
[bug] Audio not working for many words

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#35]
I don't know if this is on the extension's end or the source of the audio, but most words are not producing audio. This includes common words like 日本.

Here is a sample word that _does_ work: 思い出.

**Comment by FooSoft** [comment]
It appears that something happened on languagepod101 (the host for the audio files). It is unknown if this is an accident or an intentional move to disable external usage of these audio assets.

There is a bit of discussion going on here: 
http://forum.koohii.com/thread-13742-page-15.html

**Comment by seanblue** [comment]
Is it possible to reach out to them and find out if they will allow a way to publicly access the files again?

**Comment by Ritvik1512** [comment]
Same issue. No audio playback.

Even the one @seanblue listed has gone down.

**Comment by FooSoft** [comment]
Fixed for 1.1.7 with massive hackery

**Comment by seanblue** [comment]
@FooSoft I'm not convinced that the fix worked for every word. Certainly many more words are working again. But there are still some very common words, like 日本, 日本語, and 私, that are not producing audio. These words definitely used to work.

**Comment by FooSoft** [comment]
You are totally right -- turns out I just had a typo in the code. Will be fixed for next release.

**Comment by FooSoft** [comment]
Fixed for good in 1.1.8

**Comment by noahastor** [comment]
Would you consider a possibility of adding Google Translate audio?

**Comment by FooSoft** [comment]
Yeah, assuming they have an easy enough to use API, that is something that I can hook up.

**Comment by noahastor** [comment]
@FooSoft That would be great. Did you get a chance to see if it's doable?
