### ISSUE TITLE
[BUG] Couldn`t save sentence to anki flashcards

### ISSUE THREAD

**Issue by YunofHD** [FooSoft/yomichan#351]
Dear developer
      thx for your develop,I found a bug when I want to save sentence to anki flashcards.
      In yomichan anki connection setting where the Terms is , I want to save {sentence} to my anki flashcards, but it failed.And also ,the {dictionary} failed. The {screenshoot} work well.
thx

**Comment by siikamiika** [comment]
Can you share your settings export for debugging? You can find in at the bottom of the settings where it says "Backup". It has to be renamed to `.txt` before it can be uploaded to GitHub.

**Comment by YunofHD** [comment]
> Can you share your settings export for debugging? You can find in at the bottom of the settings where it says "Backup". It has to be renamed to `.txt` before it can be uploaded to GitHub.

Hi
      the setting file as below
thanks for your help.

[yomichan-settings-2020-02-07-09-49-30.txt](https://github.com/FooSoft/yomichan/files/4170049/yomichan-settings-2020-02-07-09-49-30.txt)

**Comment by siikamiika** [comment]
I was able to reproduce the issue with your settings, but I haven't yet figured out what's causing it. The issue went away when I reset the settings to default.

**Comment by siikamiika** [comment]
You have **Sentence detection extent** in **Anki Options** set to 0. You should increase it to be able to extract sentences. The default value is 200. Do you remember if you've changed it manually before?

**Comment by YunofHD** [comment]
> You have **Sentence detection extent** in **Anki Options** set to 0. You should increase it to be able to extract sentences. The default value is 200. Do you remember if you've changed it manually before?

Hi siikamaiika
      very thanks for your help, but in Anki Option,  I couldn`t found Sentence detection extent option,
I haven`t changed it manually before.

![image](https://user-images.githubusercontent.com/17290044/74079430-5457f880-4a72-11ea-9990-e63ff26fa776.png)

**Comment by YunofHD** [comment]
> You have **Sentence detection extent** in **Anki Options** set to 0. You should increase it to be able to extract sentences. The default value is 200. Do you remember if you've changed it manually before?

I export the json file and setting "sentenceExt" to 200, save and import in yomichan ,but it still doesn`t work.

**Comment by YunofHD** [comment]
> You have **Sentence detection extent** in **Anki Options** set to 0. You should increase it to be able to extract sentences. The default value is 200. Do you remember if you've changed it manually before?

Yeah ,it works now , I change the sentenceExt in two place . I want to know why it is not in the anki option...

**Comment by siikamiika** [comment]
> in Anki Option, I couldnt found Sentence detection extent option

It will appear when you enable "Show advanced options" in **General Options**. Advanced options will also expose other options that can potentially break your config, and it can be disabled afterwards. Your other profiles also seemed to have this issue, so be sure to fix all the profiles you use.

>  I havent changed it manually before

Then there could be a bug somewhere in Yomichan like converting options between version upgrades, but your specific issue can be fixed by editing the sentence detection extent.

**Comment by YunofHD** [comment]
> > in Anki Option, I couldnt found Sentence detection extent option
> 
> It will appear when you enable "Show advanced options" in **General Options**. Advanced options will also expose other options that can potentially break your config, and it can be disabled afterwards. Your other profiles also seemed to have this issue, so be sure to fix all the profiles you use.
> 
> > I havent changed it manually before
> 
> Then there could be a bug somewhere in Yomichan like converting options between version upgrades, but your specific issue can be fixed by editing the sentence detection extent.

Much thanks for your help, I just think that anvance option is for general setting
