### ISSUE TITLE
Results tags display

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#354]
This came up while trying to determine how to present information in #61 due to a very small space to work with, but I wonder if results tags should be clickable to show additional information. This could something similar to a snackbar or popup footer which can show additional info. Of course it would also be closable with an "X" button or similar. This could also improve usability on Firefox for Android since the tags currently have hover text which cannot be seen.

**Comment by siikamiika** [comment]
Tag displaying could use some updates, especially for things that aren't strictly tags like pitch accent data or https://github.com/FooSoft/yomichan/pull/334.

However, it's problematic to map some of the data such as frequency or pitch accent directly to terms because the required information is not always there.

I've often seen Innocent Corpus frequencies mapped to the wrong terms, and it only uses a single string to do the matching.

The pitch accent data you used in https://github.com/FooSoft/yomichan/issues/61 seems to have part of speech, which I assume you got from the Rikaisama sqlite
![2020-02-11_23-04-15](https://user-images.githubusercontent.com/5602483/74279060-dff7b080-4d22-11ea-9cef-f8a15bd496d2.png)
but that can't be directly mapped to expressions at least in the format that JMdict uses. None of the EPWING dictionaries that I know of have part of speech tags parsed out of the dictionary format either.

So I guess what I'm trying to say is that it would be nice to display the additional data in a compact way, but it will be misleading at best without lots of human effort to match a dictionary with the other data source.

With JMdict you could use `definitionTags` and guess that if the part of speech tag matches you have the correct definition. The best option would be if the tags were specific to dictionaries such as 大辞林.

**Comment by siikamiika** [comment]
Regarding tag display on mobile devices, I think it would be cool if there was a button in merge mode when `data-browser=firefox-mobile`. I've also sometimes noticed that the popup width will overflow with the hidden tags. It's more frequent when the tags are wide such as when you have Innocent Corpus installed.

**Comment by toasted-nutbread** [comment]
> the required information is not always there.

Are you referring to part of speech, or something else? It's not surprising that data coming from different sources doesn't match up 100% of the time.

> I've often seen Innocent Corpus frequencies mapped to the wrong terms, and it only uses a single string to do the matching.

If you come across any examples, feel free to share them for documentation purposes.

> So I guess what I'm trying to say is that it would be nice to display the additional data in a compact way, but it will be misleading at best without lots of human effort to match a dictionary with the other data source.

For reference, something like this is all that I mean:
![test](https://user-images.githubusercontent.com/11037431/74295741-ef213300-4d0f-11ea-8973-f736ed4ea1bf.gif)

**Comment by siikamiika** [comment]
> Are you referring to part of speech, or something else? It's not surprising that data coming from different sources doesn't match up 100% of the time.

Part of speech, or in general something that can resolve the ambiguity when there are multiple pronunciations for a word depending on context.

> If you come across any examples, feel free to share them for documentation purposes.

端 lists all the readings はし はじ はな as having the same frequency. Similar examples include 
段階 and 階 where the incorrect mappings extend beyond different JMdict entries. Innocent Corpus was automatically generated and can also have other bias for example towards the verb form of a word such as 始める, 始め as a noun has zero hits but it can also be interpreted as the stem of 始める.

> For reference, something like this is all that I mean:

Ah, you weren't referring to the other change for touchscreens discussed earlier. Sorry for posting in the wrong issue. I think that looks good and should be added for touch devices, but might be too much for mouse devices together with regular tooltips unless you're planning to give them styles that can't be shown in a regular tooltip.

**Comment by siikamiika** [comment]
To improve Innocent Corpus, I'd show the information as-is and let the user figure out which readings or meanings the word maps to based on other data such as frequency reported by JMdict. Perhaps users will notice over time that the number is the same on different entries, but until then there's the risk of investing in learning obscure readings for a word just because the frequency is reported as higher than it actually is.

**Comment by toasted-nutbread** [comment]
Here's a quick demo of the issue you mentioned with 端. The pitch accent dataset does seem to work correctly for this example, as there is both an expression and a reading used as the key.
![test](https://user-images.githubusercontent.com/11037431/74387888-d5dbbd80-4dc7-11ea-82d2-30aa1a2ce604.gif)

**Comment by siikamiika** [comment]
Looks pretty good. I checked some possible error cases with a script, and looks like at least the ones related to parts of speech are quite rare (372/256928). The pitch accent dictionary part of speech tags appear pretty often in the results, and should resolve some of the ambiguity.

I think it would be ok to show these tags as `termTags`, but it would also be possible to have it as a separate dictionary that contains the tag. There can be multiple sources for them.

[possible_errors.txt](https://github.com/FooSoft/yomichan/files/4197641/possible_errors.txt)

```python
#!/usr/bin/env python3

import re
import copy

POS_TAGS = ["adj-i", "adj-ix", "adj-na", "adj-no", "adj-pn", "adj-t", "adj-f", "adv", "adv-to", "aux", "aux-v", "aux-adj", "conj", "cop-da", "ctr", "exp", "id", "int", "iv", "n", "n-adv", "n-suf", "n-pref", "n-t", "num", "on-mim", "pn", "pref", "prt", "suf", "unc", "v1", "v1-s", "v2a-s", "v4h", "v4r", "v5aru", "v5b", "v5g", "v5k", "v5k-s", "v5m", "v5n", "v5r", "v5r-i", "v5s", "v5t", "v5u", "v5u-s", "v5uru", "vz", "vi", "vk", "vn", "vr", "vs", "vs-c", "vs-s", "vs-i", "vt", "adj-kari", "adj-ku", "adj-shiku", "adj-nari", "n-pr", "v-unspec", "v4k", "v4g", "v4s", "v4t", "v4n", "v4b", "v4m", "v2k-k", "v2g-k", "v2t-k", "v2d-k", "v2h-k", "v2b-k", "v2m-k", "v2y-k", "v2r-k", "v2k-s", "v2g-s", "v2s-s", "v2z-s", "v2t-s", "v2d-s", "v2n-s", "v2h-s", "v2b-s", "v2m-s", "v2y-s", "v2r-s", "v2w-s"]
TAG_PATT = re.compile(r"\((.*?)\)")

def has_different_pos(row):
    tags_list = []
    for v in row:
        tags = get_tags_single(v)
        if tags:
            tags_list.append(tags)
    for i in range(len(tags_list)):
        pivot_tags = copy.deepcopy(tags_list[i])
        other_tags_list = copy.deepcopy(tags_list[:i] + tags_list[i + 1:])
        if len(other_tags_list) == 0:
            continue
        for other_tags in other_tags_list:
            for other_tag in other_tags:
                if other_tag in pivot_tags:
                    pivot_tags.remove(other_tag)
        if len(pivot_tags) > 1:
            return True

def get_tags_single(item):
    tags = []
    for match in TAG_PATT.findall(item):
        for tag in match.split(","):
            if tag not in POS_TAGS: continue
            tags.append(tag)
    return tags

def get_tags(row):
    tags = []
    for v in row:
        item_tags = get_tags_single(v)
        if len(item_tags) > 0:
            tags.append(item_tags)
    return tags

accent_data = {}
with open("accents.txt") as f:
    for row in f.read().splitlines():
        term, reading, accent = row.split("\t")
        key = f"{term} [{reading}]" if reading else term
        accent_data[key] = row

edict_data = {}
with open("edict.utf8") as f:
    for row_raw in f.read().splitlines():
        row = []
        for item in row_raw.split("/"):
            item_stripped = item.strip()
            if item_stripped:
                row.append(item_stripped)
        if len(row) > 0:
            key = row[0]
            if key not in edict_data:
                edict_data[key] = []
            edict_data[key].append(row)

for key, value in edict_data.items():
    edict_different_pos = any(has_different_pos(entry) for entry in value)
    accent_value = accent_data.get(key)
    possible_extra_accents = (
        accent_value is not None
        and ("," in accent_value and "(" in accent_value)
        and not edict_different_pos
    )

    messages = []
    if len(value) > 1:
        messages.append("term [reading] not unique")
    if edict_different_pos:
        messages.append("part of speech differs")
    if possible_extra_accents:
        messages.append("possible extra accents")

    if len(messages) == 0: continue
    for entry in value:
        pos_tags = get_tags(entry)
        if key in accent_data:
            accents = accent_data[key]
            if "," in accents.split("\t")[2]:
                print(
                    key,
                    "|".join([",".join(item_tags) for item_tags in pos_tags]),
                    accents.replace("\t", "|"),
                    "[ {} ]".format("; ".join(messages)),
                    sep="\t"
                )
```

**Comment by siikamiika** [comment]
Here's an example of what it could look like as a normal dictionary:
![pitch_accent_dictionary_sketch](https://user-images.githubusercontent.com/5602483/74560663-b2537700-4f6f-11ea-9db8-342e1f83f83f.png)
