### ISSUE TITLE
Navigation header mouse wheel events on search page

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#355]
There's an issue that when you click a word in query parser or a kanji in the results, it will push a history entry but the navigation header can appear in a place that the mouse cursor will sometimes move over if the scrolling step matches or scrolling is high resolution. When this happens, the current content can be replaced by something in the history.

This isn't a big problem in the popups because the navigation header will always be on top. I'm not sure if it would be simple to move the navigation header above everything on the search page.

The easy solution would be to delete this line, but I think the feature can be useful in many situations:

https://github.com/FooSoft/yomichan/blob/9ffd0cb441f9773651ed734d8bccce3667700ceb/ext/mixed/js/display.js#L301

Another solution would be to only make the area close to the buttons active, but accidents could still happen if the area moves when the results are scrolled.

I'm fine if this feature is temporarily removed before a better solution to unblock a release.

**Comment by toasted-nutbread** [comment]
Going to close this issue for now. #707 partially addresses mouse-based navigation of the popup (Chrome only), but IMO using the mouse wheel to navigate or change settings can be more annoying than helpful (I've seen this in other applications, and it's too easy to accidentally do).
