### ISSUE TITLE
Preferred callback style

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#359]
## Background
I am looking to change most of the static class callback maps into instance member callback maps for style consistency and to allow static analysis and automatic refactoring tools to have stronger type inferencing information.

For example, I am looking to convert these:
https://github.com/FooSoft/yomichan/blob/89cb98e4d14ad4980133f8e8e44b15d56c3ebea5/ext/bg/js/backend.js#L843-L868

Into something that looks more like this (without the `FrontendApiReceiver` constructor of course, just the `Map`):
https://github.com/FooSoft/yomichan/blob/89cb98e4d14ad4980133f8e8e44b15d56c3ebea5/ext/fg/js/popup-proxy-host.js#L36-L48

The intent is to replace `self` with `this`. `self` cannot be type-inferenced whereas `this` can be. In general, the overhead of having a per-instance `Map` rather than a global one should be very small since most of the classes that are using this pattern are instantiated only once or a very small number of times. I was also the one to initially change to the static `Map` pattern, but after using it for a while, I've found that having the `Map` as an instance member is probably better.

---

## Callback Style
That change will be simple enough to make, but as I was looking into it, I noticed something: there are two styles for callback functions, and I am wondering if we should pick one or the other for consistency and if it's worth it to do so.

The two styles are as follows:

### Type 1
`something.addCallback(this.someFunction.bind(this));`
https://github.com/FooSoft/yomichan/blob/89cb98e4d14ad4980133f8e8e44b15d56c3ebea5/ext/bg/js/backend.js#L71
https://github.com/FooSoft/yomichan/blob/89cb98e4d14ad4980133f8e8e44b15d56c3ebea5/ext/fg/js/frontend.js#L54-L55

### Type 2
`something.addCallback(() => this.someFunction());`
https://github.com/FooSoft/yomichan/blob/89cb98e4d14ad4980133f8e8e44b15d56c3ebea5/ext/bg/js/backend.js#L66
https://github.com/FooSoft/yomichan/blob/89cb98e4d14ad4980133f8e8e44b15d56c3ebea5/ext/fg/js/popup.js#L340
https://github.com/FooSoft/yomichan/blob/89cb98e4d14ad4980133f8e8e44b15d56c3ebea5/ext/fg/js/frontend.js#L58-L60

### Comparison
* `.bind` doesn't support overriding of functions, since the functions are bound in the constructor. Compared with `() => {}`, which binds at execution time. This could be seen as a pro or a con, but in practice it I don't think it will affect anything.
* I haven't tested, but I believe `.bind` is technically more efficient, since binding only occurs once. In practice, this overhead is likely negligible.
* `() => {}` supports more flexible arguments, such as omission, destructuring, etc. This is why arrow functions are used in a lot of callbacks currently, but there are situations where either could be used.

**Comment by siikamiika** [comment]
> I am looking to change most of the static class callback maps into instance member callback maps for style consistency and to allow static analysis and automatic refactoring tools to have stronger type inferencing information.

I kind of liked the way this made it easy to find all the callback maps at the bottom of each class, but disliked the extra step it added to the `onMessage` handlers when called.

> That change will be simple enough to make, but as I was looking into it, I noticed something: there are two styles for callback functions, and I am wondering if we should pick one or the other for consistency and if it's worth it to do so.

My main concerns about this are that `() => {}` requires maintaining the arguments in one more place as the method signature changes, but on the other hand it's more flexible and explicit about what it does. It would look out of place if a one of the callbacks was in the arrow function style and others used `bind`. An alternative way to handle custom arguments would be to use a wrapper method in the class.

**Comment by toasted-nutbread** [comment]
> I kind of liked the way this made it easy to find all the callback maps at the bottom of each class

Top of the class (constructor) should be equally as easy to find once accustomed to it.

Another example of something which already does this:
https://github.com/FooSoft/yomichan/blob/89cb98e4d14ad4980133f8e8e44b15d56c3ebea5/ext/mixed/js/core.js#L249-L253

> but disliked the extra step it added to the `onMessage` handlers when called.

Do you mean having to do something like `DisplaySearch._runtimeMessageHandlers.get(action)` instead of `this._runtimeMessageHandlers.get(action)`? or something else?
https://github.com/FooSoft/yomichan/blob/89cb98e4d14ad4980133f8e8e44b15d56c3ebea5/ext/bg/js/search.js#L177

> My main concerns about this are that `() => {}` requires maintaining the arguments in one more place as the method signature changes, but on the other hand it's more flexible and explicit about what it does.

`(...args) => func(...args)` is certainly a possibility for this, which is already used in backend.js. Additionally, it looks like a lot of places that use `.bind`, the argument format is already strictly defined by what is being subscribed to. In most cases it's a standard event, so the args would just be `(e) => func(e)`.

I agree that there is potentially more maintenance involved, but it should be marginal and rare, and I don't think it's a huge issue in the current code. There are many places where callbacks are already defined like `({arg1, arg2}) => func(arg1, arg2)`, which is dependent on function signature, and I don't think that's proven to be a big issue (yet).

> It would look out of place if a one of the callbacks was in the arrow function style and others used `bind`.

Yeah, there are already several places in the codebase where both `() => {}` and `.bind` are used in the same function, which is why I noticed this.

> An alternative way to handle custom arguments would be to use a wrapper method in the class.

Not sure exactly what you mean by this; example?

**Comment by siikamiika** [comment]
> Do you mean having to do something like `DisplaySearch._runtimeMessageHandlers.get(action)` instead of `this._runtimeMessageHandlers.get(action)`? or something else?

Hmm, I was probably thinking of the difference between adding a DOM event listener and getting a `handler` from a `Map` in `onMessage`, but this change doesn't affect it. Some kind of abstraction such `EventDispatcher` in `core.js` could reduce the amount of duplicate code for each class that has callbacks.

> `(...args) => func(...args)` is certainly a possibility for this, which is already used in backend.js. Additionally, it looks like a lot of places that use `.bind`, the argument format is already strictly defined by what is being subscribed to. In most cases it's a standard event, so the args would just be `(e) => func(e)`.
> 
> I agree that there is potentially more maintenance involved, but it should be marginal and rare, and I don't think it's a huge issue in the current code. There are many places where callbacks are already defined like `({arg1, arg2}) => func(arg1, arg2)`, which is dependent on function signature, and I don't think that's proven to be a big issue (yet).

This is actually something I realized while reviewing https://github.com/FooSoft/yomichan/pull/358/commits/e3c871bc004d9ca612d908f0f3848cdcfc286cd3, but the callback convention is closely related. It's not always obvious that everything has been updated to the new signature even though the diff looks ok if somewhere in the chain you forget to add or remove an argument. Adding new settings also suffers from a similar issue because everything has to be explicitly added. I think `(...args) => func(...args)` is equally good.

> > An alternative way to handle custom arguments would be to use a wrapper method in the class.
> 
> Not sure exactly what you mean by this; example?

```javascript
method(_arg1, _arg2) {
    throw new Error('Override me');
}

methodWrapper(arg1) {
    return this.method(arg1, 'foo');
}
// -------------------------------------------
this._messageHandlers = new Map([ 
    ['method', this.methodWrapper.bind(this)], 
    ['otherMethod', this.otherMethod.bind(this)]
]); 
```

**Comment by toasted-nutbread** [comment]
81fbe60da9c4cd7de27ef68c39805b96680bc24d...fdfc2d33bbcd32f2984e74bd58a518fcc50705d2 takes care of most of the things I was concerned with. I went with `.bind` where possible since it's the least redundant and shortest of the options.

**Comment by siikamiika** [comment]
> [81fbe60...fdfc2d3](https://github.com/FooSoft/yomichan/compare/81fbe60da9c4cd7de27ef68c39805b96680bc24d...fdfc2d33bbcd32f2984e74bd58a518fcc50705d2) takes care of most of the things I was concerned with. I went with `.bind` where possible since it's the least redundant and shortest of the options.

Looks good! Maybe the ones using object destructuring like https://github.com/FooSoft/yomichan/commit/03ba1b633e2230435f6baeeaa4b6009de2932452 should be switched to arrays in the next refactoring round.
