### ISSUE TITLE
[bug] Alt + End opens Yomichan extension options

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#36]
If I understand correctly, Alt + End should go to the last entry in the popup. Instead it opens the Yomichan options in the chrome://extensions tab.

**Comment by FooSoft** [comment]
Yeah, I realized this shortly after publishing 1.1.8. It's a hotkey conflict and it's already fixed on dev. Will be included in the next release.

**Comment by FooSoft** [comment]
Fixed in 1.1.9
