### ISSUE TITLE
setDisplayInitialized failing due to iframes

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#360]
Getting this error when iframes are on the page:

```
Error in event handler: Error: Override me
    at Popup.setDisplayInitialized (/fg/js/popup.js:128:15)
    at /fg/js/frontend.js:248:59
    at Frontend.onRuntimeMessage (/fg/js/frontend.js:85:24)
```

**Comment by siikamiika** [comment]
I can reproduce this on the Amazon page linked in https://github.com/FooSoft/yomichan/issues/29. Interestingly, Firefox logs this error but the popup will still work while Chrome shows it a few times before completely stopping to display the errors.

**Comment by siikamiika** [comment]
I found that `Backend._onApiForward` was missing `frameId` from the `sendMessage` call and same with `BackendApiForwarder`, but adding those in didn't fix the issue.
