### ISSUE TITLE
"Cannot parent popup to another popup which already has a child" when making iframe video fullscreen

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#365]
Example: [random tweet with embedded youtube video](https://twitter.com/miemongful/status/1228238051572207616)

Open the video, make it fullscreen and observe the error happen in browser console.

After this has happened once, nested popups will stop working.

Noticed while working on https://github.com/FooSoft/yomichan/pull/364

**Comment by toasted-nutbread** [comment]
I am guessing this is not including 912d59d3dfefde5738b4244d74d944795edcc02c, because I am seeing a different but still erroneous behaviour with that merged. Apparently when the ancestor hierarchy of the iframe is changed, it is reset to the empty about:blank page. I'll look into both issues.

**Comment by siikamiika** [comment]
First I thought it was something about #364, but then I installed the current stable release alongside and it reproduced on that as well. I had not rebased on https://github.com/FooSoft/yomichan/commit/912d59d3dfefde5738b4244d74d944795edcc02c at the time of testing.

**Comment by siikamiika** [comment]
I can confirm that the popup currently becomes `about:blank` instead.

**Comment by siikamiika** [comment]
Actually it's now `about:blank` even on non-iframe fullscreen pages.

**Comment by toasted-nutbread** [comment]
Yes, it's because the DOM element is moved, which causes the content to be cleared. The iframe part is irrelevant for that issue, but this is where I noticed it since it's the only occasion that Yomichan moves the iframe.

**Comment by toasted-nutbread** [comment]
Okay so I'm reverting in 36605f74c3d48a98500d198636112454b36063f6 because the issue is significantly more complex if the goal is to have the iframe be more secure and less susceptible to hijacking. There are some timing issues which make it tricky.

While I was working on it, there was an issue with how popup proxies work if the iframe is unloaded which triggered the issue that you mentioned here because existing popups weren't being reused. This is updated in dcd243c9e9f3af3fedb0bb0db9795f377f175587. I am not sure if this fixes the issue or not; I wasn't seeing the issue after the revert mentioned above.

**Comment by siikamiika** [comment]
> Okay so I'm reverting in [`36605f7`](https://github.com/FooSoft/yomichan/commit/36605f74c3d48a98500d198636112454b36063f6) because the issue is significantly more complex if the goal is to have the iframe be more secure and less susceptible to hijacking. There are some timing issues which make it tricky.

We can try the data URL or srcdoc approach next if browsers don't like setting the URL to `contentDocument`.

> While I was working on it, there was an issue with how popup proxies work if the iframe is unloaded which triggered the issue that you mentioned here because existing popups weren't being reused. This is updated in [dcd243c](https://github.com/FooSoft/yomichan/commit/dcd243c9e9f3af3fedb0bb0db9795f377f175587). I am not sure if this fixes the issue or not; I wasn't seeing the issue after the revert mentioned above.

It seems to work on current master, thanks for the fix. :+1: The only issue I see now is that there will be a blank popup left over if you press Esc in full screen while a popup is open. Everything will work afterwards, though.

I'm still able to reproduce the issue in 36605f74c3d48a98500d198636112454b36063f6 (**not current master**):
![ezgif-2-1743bdffedea](https://user-images.githubusercontent.com/5602483/74616130-d0b3a100-512e-11ea-9b4f-0558bfd2185a.gif)

**Comment by toasted-nutbread** [comment]
> We can try the data URL or srcdoc approach next if browsers don't like setting the URL to `contentDocument`.

I don't think we will have to go that far. The main issue I have encountered is multiple `load` events that should be handled in a certain order, which adds complexity. So I'm trying to determine the most effective way of doing so.

While making this update, I'm also trying to detect if the iframe is hijacked during the process and to stop sending messages to the frame if that occurs. This can happen if the src or srcdoc is reassigned from an external source, and there might be a very small timing window where this could potentially happen between the two `load` events.

**Comment by siikamiika** [comment]
@toasted-nutbread I'm closing this issue since it's resolved, but do you think everything else here is the same as https://github.com/FooSoft/yomichan/issues/441 or do we need a new issue?

**Comment by toasted-nutbread** [comment]
Yes, I think #441 captures everything.
