### ISSUE TITLE
Query tab Frontend instance structure from Backend for communication

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#368]
There are many ways to communicate between windows: you can `postMessage` to a window, `chrome.runtime.sendMessage/onMessage`, connect to port with `chrome.runtime.connect`, maybe I forgot something else.

They all work a bit differently, but especially window communication can be very confusing when used with multiple frames or nested frames. I've seen `apiForward` used instead probably because it only sends the message to the extension in the current tab, but that doesn't solve the issue of sending to the correct frame of the extension.

After seeing where https://github.com/FooSoft/yomichan/issues/353 is going, I'm thinking if it would be helpful to make `Backend` manage all the different instances of `Frontend` and their types (root page instance, nested proxies, iframe proxy https://github.com/FooSoft/yomichan/pull/364) along with a unique ID so that you could send messages to specific `Frontend` instances. For one, it would solve the issue I mentioned in https://github.com/FooSoft/yomichan/issues/353#issuecomment-587116442. I think it would also make debugging easier if you had to target a specific ID with every call.

Example structure (123 is tab ID but you could query the current tab):
```json
{
  "123": [
    {"id": "581ce391b4c19ef5e2adc8745e343820", "type": "root", "parent": null},
    {"id": "555c5664b055b58d551b4e04d6847454", "type": "iframe", "parent": null},
    {"id": "cf3187af33d0055b6355b811fedc73e9", "type": "nested", "parent": "581ce391b4c19ef5e2adc8745e343820"},
    {"id": "569dfb2c6043c90f12b04487ba14f830", "type": "nested", "parent": "cf3187af33d0055b6355b811fedc73e9"}
  ]
}
```

**Comment by toasted-nutbread** [comment]
I have thought of this a few times, and the main issue that comes up is the added complexity and permissions requirements. The background now has to know about all tabs and frames and to assign IDs. In order to not have memory leaks, the backend also needs to observe for when frames are removed in order to clean up data. This requires the [webNavigation](https://developer.chrome.com/extensions/webNavigation) permission, which is otherwise not needed (so far).

**Comment by siikamiika** [comment]
I agree it would make things more complicated. Would be nicer if this could be handled within a tab, but I remember seeing in https://github.com/FooSoft/yomichan/issues/29#issuecomment-568207279 that frames can load before the root page, so either the frames in one tab have to share their state in a peer-to-peer way or there has to be a master that's up before the frames.

Maybe a garbage collection approach would work to prevent memory leaks without additional permissions. The backend would periodically (in a throttled way) query all tabs that have their structure stored, and the ones that don't respond in time would have their data dropped. But that would be even more complex.

**Comment by toasted-nutbread** [comment]
> I remember seeing in [#29 (comment)](https://github.com/FooSoft/yomichan/issues/29#issuecomment-568207279) that frames can load before the root page

This was also the reason why I considered exactly what you have mentioned in this issue, but ultimately I just postponed my efforts on that task.

**Comment by siikamiika** [comment]
I just got a horrible idea to work around the permission issue, you could use busy wait combined with onbeforeunload. I might test it at some point.

**Comment by siikamiika** [comment]
This issue has been obsoleted by `yomichan.getTemporaryListenerResult` and Popup unique ID.
