### ISSUE TITLE
[bug] Alt + ESC doesn't work

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#37]
I'm using Windows 10 and it looks like Alt + ESC is a system level key combination. Because of that, it doesn't clear the search as it should.

**Comment by FooSoft** [comment]
Do you mean using escape to close the search popup window? It doesn't actually require the alt modifier.

**Comment by seanblue** [comment]
Ah, I didn't notice that that one didn't require the Alt key. Nevermind then.

**Comment by FooSoft** [comment]
Good deal, closing :+1:
