### ISSUE TITLE
[Feature Request] expose sentence extent detection logic in settings

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#370]
Or add some other sets of detection method for user to choose from.
https://github.com/FooSoft/yomichan/blob/af89659751f72ae282f2c81d797cc224d1077b0a/ext/fg/js/document.js#L148-L150

In some use cases having a full line filled into anki card produce better results, such as VN text hooking or novels with many intrasentential quotes.
I want to be able to set these pages to a different profile where only line breaks are used to slice sentences.

**Comment by toasted-nutbread** [comment]
So in your case, are you just looking to have an option to entirely disable quote and punctuation termination? Or would you need a subset of the existing quotes/terminators, or perhaps an entirely custom set?

Related: #286

**Comment by Pintliz** [comment]
> So in your case, are you just looking to have an option to entirely disable quote and punctuation termination?
I think this is enough for my use cases
