### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#376]
This issue is intended to document high-level changes since the last stable/testing release.

## [Changes since 20.4.18.0](https://github.com/FooSoft/yomichan/compare/20.4.18.0...master)

* Added support for frequency data with readings. (#382, #450)
* Added support for dictionaries with images. (#322, #446)
* Fixed some edge cases where root popup positioning didn't work correctly from &lt;iframe&gt; elements. (#432, #460)
* Improve status indicators on the extension badge. (#448)
* Source structuring and refactoring. (#442, #447, #453, #463, #466, #467)
* Fixed custom Anki templates not being used. (#473, #474)
* Fixed an issue with pitch accents not presenting the data correctly. (#469, #472)

**Comment by FooSoft** [comment]
Awesome, this helps a lot -- thanks for creating this list. I'll create a new release.

**Comment by siikamiika** [comment]
I'll remove the mouse wheel feature for now as mentioned in https://github.com/FooSoft/yomichan/issues/355

**Comment by toasted-nutbread** [comment]
Moving this content to https://github.com/FooSoft/yomichan/wiki/Changelog, where it will continue to be maintained.
