### ISSUE TITLE
Cannot add Anki cards in merge mode for terms from non-primary dictionaries

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#377]
**Steps to reproduce:**
* Install JMdict
* Install JMnedict
* Change setting **Result grouping** to "Group results by main entry"
* Change **Main dictionary for merged mode** to "JMdict"
* Enable Anki, ensure set up to be able to add cards. Use `{expression}` as the primary field.
* Scan "りが"

**Results:**
Results for JMnedict definitions will have the + buttons grayed out and no book will appear. Results for definitions contained in JMdict will have green buttons.

The issue is coming from a discrepancy in the data format returned from the lookup backend, as initially noted in #337. Non-primary dictionaries return data in a different format; in this case the template system is expecting `expressions` to be an array, but it is a string for non-primary dictionaries.

This could potentially be the cause of some other Anki issues like #329 if someone has their settings configured incorrectly. There was also a bug in AnkiConnect which affected Yomichan, but I have fixed that https://github.com/FooSoft/anki-connect/pull/133.

**Comment by siikamiika** [comment]
Thanks for finding the issue. The PR will fix non-primary dictionary definitions when using `{expression}` or `{reading}`.
