### ISSUE TITLE
Export from a single dictionary

### ISSUE THREAD

**Issue by psychodelicwasabi** [FooSoft/yomichan#378]
Would there be a way to generate the Anki cards with the definitions of a single dictionary only? I have multiple dictionaries, but don't need all those definitions in the card. So, in the end, I have to erase the other definitions when making cards using Yomichan, which becomes time consuming. Is there a way to play with handlebars or something to make that happen? Also, please, when answering, make it extremely simple, I really can't code at all.

Ideally, I'd also like to get rid of the reading and etc that comes with the definition, but I'm not sure that can be done. Here's an image with all the information I don't need and end up cleaning in the card-making process underlined. Thank you for the attention.
![image](https://user-images.githubusercontent.com/39304471/75307483-32a49280-5822-11ea-9c39-98eaaab0eee0.png)

**Comment by toasted-nutbread** [comment]
Answer to first half: this is not possible in the current version of Yomichan, but this ability to could be added. Taking your idea of using the Handlebars templates, this would require the ability to include definitions based on a condition, in this case the condition would be checking to see if the name of the dictionary is `"三省堂　スーパー大辞林"` for the definitions. Unfortunately, it seems that Handlebars doesn't have built-in functionality for this comparison, so this would have to be added.

Answer to second half: this would likely be difficult to consistently do in a handlebars template since there doesn't seem to be a good pattern for what you want to remove. Consider another definition for `"口"`:
![image](https://user-images.githubusercontent.com/11037431/75498091-3f48f800-5994-11ea-9b6d-a29643573037.png)
The pattern in this case is different.

This is honestly more of a problem with the dictionary data than with what Yomichan's doing with it; I think a few of the Japanese=>Japanese dictionaries have similar formatting issues.

**Comment by Geniusssmit** [comment]
I'm dealing with the same issue, is there any way to only export from 1 dictionary now?

**Comment by toasted-nutbread** [comment]
You are now able to do these comparison! The trick is finding the right place to put them, and what field to compare against, but here is an example:

```handlebars
{{#*inline "test"}}
    {{~#if (op "===" definition.dictionary "JMdict (English)")~}}
        Matches
    {{~#else~}}
        Doesn't match
    {{~/if~}}
{{/inline}}
```

Note: the example above is not using per-definition dictionary checks, which may be necessary depending on which presentation mode is being used. You would likely need to modify the `glossary` inline definition and add these checks to it.

There is also some basic documentation for the Handlebars helpers now:
https://github.com/FooSoft/yomichan/blob/master/docs/templates.md

**Comment by Geniusssmit** [comment]
That didn't help that much. 1 more issue, for example word 虞 won't come up in 三省堂　スーパー大辞林 but it is in 新明解国語辞典 第五版 . So how I can export definitions from the first dictionary that come up, no matter which one it is?

**Comment by toasted-nutbread** [comment]
```handlebars
{{#*inline "test"}}
    {{~#scope~}}
        {{~#set "first-dictionary" null}}{{/set~}}
        {{~#if modeKanji~}}
            ...
        {{~else if (op "||" group merge)~}}
            <ol>
            {{~#each definition.definitions~}}
                {{~#if (op "===" null (get "first-dictionary"))~}}
                    {{~#set "first-dictionary" dictionary~}}{{~/set~}}
                {{~/if~}}
                {{~#if (op "===" dictionary (get "first-dictionary"))~}}
                    {{> glossary-single brief=../brief compactGlossaries=../compactGlossaries}}
                {{~/if~}}
            {{~/each~}}
            </ol>
        {{~else~}}
            {{~> glossary-single definition brief=brief compactGlossaries=compactGlossaries~}}
        {{~/if~}}
    {{~/scope~}}
{{/inline}}
```

**Comment by Geniusssmit** [comment]
> ```
> {{#*inline "test"}}
>     {{~#scope~}}
>         {{~#set "first-dictionary" null}}{{/set~}}
>         {{~#if modeKanji~}}
>             ...
>         {{~else if (op "||" group merge)~}}
>             <ol>
>             {{~#each definition.definitions~}}
>                 {{~#if (op "===" null (get "first-dictionary"))~}}
>                     {{~#set "first-dictionary" dictionary~}}{{~/set~}}
>                 {{~/if~}}
>                 {{~#if (op "===" dictionary (get "first-dictionary"))~}}
>                     {{> glossary-single brief=../brief compactGlossaries=../compactGlossaries}}
>                 {{~/if~}}
>             {{~/each~}}
>             </ol>
>         {{~else~}}
>             {{~> glossary-single definition brief=brief compactGlossaries=compactGlossaries~}}
>         {{~/if~}}
>     {{~/scope~}}
> {{/inline}}
> ```

Thanks! Where should add that?

**Comment by toasted-nutbread** [comment]
Add to the handlebars templates, then you can use the `{test}` marker in this case (determined by the first `inline` part). You can extend and modify it as necessary.

Note that what I posted is incomplete (placeholder used for kanji, but can be copied from elsewhere if needed)

**Comment by Geniusssmit** [comment]
I added it before everything else and set terms like that 
![image](https://user-images.githubusercontent.com/24941285/90339434-791cc200-dff9-11ea-8783-299fcb1382df.png)
but no results in expected anki field. What I did wrong?

```{{#*inline "test"}}
    {{~#scope~}}
        {{~#set "first-dictionary" null}}{{/set~}}
        {{~#if modeKanji~}}
            ...
        {{~else if (op "||" group merge)~}}
            <ol>
            {{~#each definition.definitions~}}
                {{~#if (op "===" null (get "first-dictionary"))~}}
                    {{~#set "first-dictionary" dictionary~}}{{~/set~}}
                {{~/if~}}
                {{~#if (op "===" dictionary (get "first-dictionary"))~}}
                    {{> glossary-single brief=../brief compactGlossaries=../compactGlossaries}}
                {{~/if~}}
            {{~/each~}}
            </ol>
        {{~else~}}
            {{~> glossary-single definition brief=brief compactGlossaries=compactGlossaries~}}
        {{~/if~}}
    {{~/scope~}}
{{/inline}}

{{#*inline "glossary-single"}}
    {{~#unless brief~}}
        {{~#if definitionTags~}}<i>({{#each definitionTags}}{{name}}{{#unless @last}}, {{/unless}}{{/each}})</i> {{/if~}}
        {{~#if only~}}({{#each only}}{{{.}}}{{#unless @last}}, {{/unless}}{{/each}} only) {{/if~}}
    {{~/unless~}}
    {{~#if glossary.[1]~}}
        {{~#if compactGlossaries~}}
            {{#each glossary}}{{#multiLine}}{{.}}{{/multiLine}}{{#unless @last}} | {{/unless}}{{/each}}
        {{~else~}}
            <ul>{{#each glossary}}<li>{{#multiLine}}{{.}}{{/multiLine}}</li>{{/each}}</ul>
        {{~/if~}}
    {{~else~}}
        {{~#multiLine}}{{glossary.[0]}}{{/multiLine~}}
    {{~/if~}}
{{/inline}}

{{#*inline "audio"}}
    {{~#if definition.audioFileName~}}
        [sound:{{definition.audioFileName}}]
    {{~/if~}}
{{/inline}}

{{#*inline "character"}}
    {{~definition.character~}}
{{/inline}}

{{#*inline "dictionary"}}
    {{~definition.dictionary~}}
{{/inline}}

{{#*inline "expression"}}
    {{~#if merge~}}
        {{~#if modeTermKana~}}
            {{~#each definition.reading~}}
                {{{.}}}
                {{~#unless @last}}、{{/unless~}}
            {{~else~}}
                {{~#each definition.expression~}}
                    {{{.}}}
                    {{~#unless @last}}、{{/unless~}}
                {{~/each~}}
            {{~/each~}}
        {{~else~}}
            {{~#each definition.expression~}}
                {{{.}}}
                {{~#unless @last}}、{{/unless~}}
            {{~/each~}}
        {{~/if~}}
    {{~else~}}
        {{~#if modeTermKana~}}
            {{~#if definition.reading~}}
                {{definition.reading}}
            {{~else~}}
                {{definition.expression}}
            {{~/if~}}
        {{~else~}}
            {{definition.expression}}
        {{~/if~}}
    {{~/if~}}
{{/inline}}

{{#*inline "furigana"}}
    {{~#if merge~}}
        {{~#each definition.expressions~}}
            <span class="expression-{{termFrequency}}">{{~#furigana}}{{{.}}}{{/furigana~}}</span>
            {{~#unless @last}}、{{/unless~}}
        {{~/each~}}
    {{~else~}}
        {{#furigana}}{{{definition}}}{{/furigana}}
    {{~/if~}}
{{/inline}}

{{#*inline "furigana-plain"}}
    {{~#if merge~}}
        {{~#each definition.expressions~}}
            <span class="expression-{{termFrequency}}">{{~#furiganaPlain}}{{{.}}}{{/furiganaPlain~}}</span>
            {{~#unless @last}}、{{/unless~}}
        {{~/each~}}
    {{~else~}}
        {{#furiganaPlain}}{{{definition}}}{{/furiganaPlain}}
    {{~/if~}}
{{/inline}}

{{#*inline "glossary"}}
    <div style="text-align: left;">
    {{~#if modeKanji~}}
        {{~#if definition.glossary.[1]~}}
            <ol>{{#each definition.glossary}}<li>{{.}}</li>{{/each}}</ol>
        {{~else~}}
            {{definition.glossary.[0]}}
        {{~/if~}}
    {{~else~}}
        {{~#if group~}}
            {{~#if definition.definitions.[1]~}}
                <ol>{{#each definition.definitions}}<li>{{> glossary-single brief=../brief compactGlossaries=../compactGlossaries}}</li>{{/each}}</ol>
            {{~else~}}
                {{~> glossary-single definition.definitions.[0] brief=brief compactGlossaries=compactGlossaries~}}
            {{~/if~}}
        {{~else if merge~}}
            {{~#if definition.definitions.[1]~}}
                <ol>{{#each definition.definitions}}<li>{{> glossary-single brief=../brief compactGlossaries=../compactGlossaries}}</li>{{/each}}</ol>
            {{~else~}}
                {{~> glossary-single definition.definitions.[0] brief=brief compactGlossaries=compactGlossaries~}}
            {{~/if~}}
        {{~else~}}
            {{~> glossary-single definition brief=brief compactGlossaries=compactGlossaries~}}
        {{~/if~}}
    {{~/if~}}
    </div>
{{/inline}}

{{#*inline "glossary-brief"}}
    {{~> glossary brief=true ~}}
{{/inline}}

{{#*inline "kunyomi"}}
    {{~#each definition.kunyomi}}{{.}}{{#unless @last}}, {{/unless}}{{/each~}}
{{/inline}}

{{#*inline "onyomi"}}
    {{~#each definition.onyomi}}{{.}}{{#unless @last}}, {{/unless}}{{/each~}}
{{/inline}}

{{#*inline "reading"}}
    {{~#unless modeTermKana~}}
        {{~#if merge~}}
            {{~#each definition.reading~}}
                {{{.}}}
                {{~#unless @last}}、{{/unless~}}
            {{~/each~}}
        {{~else~}}
            {{~definition.reading~}}
        {{~/if~}}
    {{~/unless~}}
{{/inline}}

{{#*inline "sentence"}}
    {{~#if definition.cloze}}{{definition.cloze.sentence}}{{/if~}}
{{/inline}}

{{#*inline "cloze-prefix"}}
    {{~#if definition.cloze}}{{definition.cloze.prefix}}{{/if~}}
{{/inline}}

{{#*inline "cloze-body"}}
    {{~#if definition.cloze}}{{definition.cloze.body}}{{/if~}}
{{/inline}}

{{#*inline "cloze-suffix"}}
    {{~#if definition.cloze}}{{definition.cloze.suffix}}{{/if~}}
{{/inline}}

{{#*inline "tags"}}
    {{~#mergeTags definition group merge}}{{this}}{{/mergeTags~}}
{{/inline}}

{{#*inline "url"}}
    <a href="{{definition.url}}">{{definition.url}}</a>
{{/inline}}

{{#*inline "screenshot"}}
    <img src="{{definition.screenshotFileName}}" />
{{/inline}}

{{#*inline "document-title"}}
    {{~context.document.title~}}
{{/inline}}

{{~> (lookup . "marker") ~}}```

**Comment by Geniusssmit** [comment]
```{{#*inline "test"}}
    {{~#scope~}}
        {{~#set "first-dictionary" null}}{{/set~}}
        {{~#if modeKanji~}}
            ...
        {{~else if (op "||" group merge)~}}
            <ol>
            {{~#each definition.definitions~}}
                {{~#if (op "===" null (get "first-dictionary"))~}}
                    {{~#set "first-dictionary" dictionary~}}{{~/set~}}
                {{~/if~}}
                {{~#if (op "===" dictionary (get "first-dictionary"))~}}
                    {{> glossary-single brief=../brief compactGlossaries=../compactGlossaries}}
                {{~/if~}}
            {{~/each~}}
            </ol>
        {{~else~}}
            {{~> glossary-single definition brief=brief compactGlossaries=compactGlossaries~}}
        {{~/if~}}
    {{~/scope~}}
{{/inline}}

{{#*inline "glossary-single"}}
    {{~#unless brief~}}
```
etc

**Comment by Geniusssmit** [comment]
![image](https://user-images.githubusercontent.com/24941285/90339548-1b3caa00-dffa-11ea-9539-ea0c1b287b63.png)
etc

**Comment by toasted-nutbread** [comment]
Are you on the latest release, version 20.8.3.0? It looks like it's available on Firefox, but not yet on the Chrome web store.

**Comment by Geniusssmit** [comment]
> Are you on the latest release, version 20.8.3.0? It looks like it's available on Firefox, but not yet on the Chrome web store.

thanks, that worked!

**Comment by psychodelicwasabi** [comment]
Seems to work for me, but I also want to get rid of the format, since that center-aligns the text. This is how I have it:

`{{#*inline "glossary"}}
    <div style="text-align: left;">
    {{~#if modeKanji~}}
        {{~#if definition.glossary.[1]~}}
            <ol>{{#each definition.glossary}}<li>{{.}}</li>{{/each}}</ol>
        {{~else~}}
            {{definition.glossary.[0]}}
        {{~/if~}}
    {{~else~}}
        {{~#if group~}}
            {{~#if definition.definitions.[1]~}}
                <ol>{{#each definition.definitions}}<li>{{> glossary-single brief=../brief compactGlossaries=../compactGlossaries}}</li>{{/each}}</ol>
            {{~else~}}
                {{~> glossary-single definition.definitions.[0] brief=brief compactGlossaries=compactGlossaries~}}
            {{~/if~}}
        {{~else if merge~}}
            {{~#if definition.definitions.[1]~}}
                <ol>{{#each definition.definitions}}<li>{{> glossary-single brief=../brief compactGlossaries=../compactGlossaries}}</li>{{/each}}</ol>
            {{~else~}}
                {{~> glossary-single definition.definitions.[0] brief=brief compactGlossaries=compactGlossaries~}}
            {{~/if~}}
        {{~else~}}
            {{~> glossary-single definition brief=brief compactGlossaries=compactGlossaries~}}
        {{~/if~}}
    {{~/if~}}
    </div>
{{/inline}}`

I wish to add the "single dictionary" piece on this code, or at least get the {test} one to works as it does.

**Comment by toasted-nutbread** [comment]
Basically just wrap the content of the post above with your `<div>`:

```handlebars
{{#*inline "glossary"}}
    <div style="text-align: left;">
    {{~#scope~}}
        {{~#set "first-dictionary" null}}{{/set~}}
        {{~#if modeKanji~}}
            ...
        {{~else if (op "||" group merge)~}}
            <ol>
            {{~#each definition.definitions~}}
                {{~#if (op "===" null (get "first-dictionary"))~}}
                    {{~#set "first-dictionary" dictionary~}}{{~/set~}}
                {{~/if~}}
                {{~#if (op "===" dictionary (get "first-dictionary"))~}}
                    {{> glossary-single brief=../brief compactGlossaries=../compactGlossaries}}
                {{~/if~}}
            {{~/each~}}
            </ol>
        {{~else~}}
            {{~> glossary-single definition brief=brief compactGlossaries=compactGlossaries~}}
        {{~/if~}}
    {{~/scope~}}
    </div>
{{/inline}}
```

**Comment by toasted-nutbread** [comment]
What do you mean by "doesn't seem to work"?

**Comment by psychodelicwasabi** [comment]
Sorry for the lack of clarity. What I meant to say is, adding the `<div>` does not seem to change anything.

![image](https://user-images.githubusercontent.com/39304471/92419752-63ed0c00-f13d-11ea-93d4-08b39254df9c.png)

I also tried to add a word using that configuration, but the card itself was still center-aligned.

**Comment by toasted-nutbread** [comment]
Are you referring to the indentation?

![image](https://user-images.githubusercontent.com/11037431/92420797-52a6fe00-f143-11ea-9441-b6cee0703904.png)

If that's the case, there were some `~` markers missing which was adding extra spacing.

```handlebars
{{#*inline "glossary"}}
    <div style="text-align: left;">
    {{~#scope~}}
        {{~#set "first-dictionary" null}}{{/set~}}
        {{~#if modeKanji~}}
            ...
        {{~else if (op "||" group merge)~}}
            <ol>
            {{~#each definition.definitions~}}
                {{~#if (op "===" null (get "first-dictionary"))~}}
                    {{~#set "first-dictionary" dictionary~}}{{~/set~}}
                {{~/if~}}
                {{~#if (op "===" dictionary (get "first-dictionary"))~}}
                    {{~> glossary-single brief=../brief compactGlossaries=../compactGlossaries~}}
                {{~/if~}}
            {{~/each~}}
            </ol>
        {{~else~}}
            {{~> glossary-single definition brief=brief compactGlossaries=compactGlossaries~}}
        {{~/if~}}
    {{~/scope~}}
    </div>
{{/inline}}
```

**Comment by psychodelicwasabi** [comment]
Oh, I see. Great, it works perfectly now. Unless you guys plan to make an actual feature out of this, I guess this issue can be closed now.

**Comment by ntvkhoasgt** [comment]
@toasted-nutbread 
I had a same issue: https://github.com/FooSoft/yomichan/issues/378#issue-571035543
I want to get specified dictionary.
Difference: I wanna get red brick text too. 🙇 What should i need to do ?
https://user-images.githubusercontent.com/39304471/75307483-32a49280-5822-11ea-9c39-98eaaab0eee0.png

**Comment by toasted-nutbread** [comment]
If you're trying to export definitions from a specific dictionary, check #1345; #1735 has requested this as an easier feature.

If you want to get rid of the text underlined in red, that's not something that is as easily done, since that is more of an issue with the format of the dictionary data. The best that could currently be done is a complex regular expression in the handlebars template, but even that is unlikely to catch everything correctly.

**Comment by BlenderUser** [comment]
Sorry to revive the thread, but I get a "The partial glossary-single could not be found" on the settings page and {glossary-render-error} on the anki note itself. How do i fix this?

**Comment by toasted-nutbread** [comment]
Open a new issue and include an export of your settings file.
