### ISSUE TITLE
[bug] cannot copy selected text

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#38]
I believe some of the recent changes broke behavior related to highlighting text. I have the option “Select matched text” turned on, so when I scan and a match is found, the text is highlighted. Previously, the highlighted text was focused on, so doing Ctrl+C would copy the selected text. In version 1.1.8 (not sure about 1.1.7), this functionality no longer works, perhaps because the popover is being focused on instead.

I personally use this to copy text and paste it into jisho.org to see secondary information that may not be included in yomichan.

**Comment by seanblue** [comment]
If focusing on the popover is required for the shortcuts to work (and if no solution allows for both to work), perhaps adding a setting to allow _either_ "Select matched text" _or_ "Allow popover shortcuts" would be an appropriate solution.

**Comment by FooSoft** [comment]
My reasoning is that if you are having to use Jisho for secondary information then Yomichan probably needs to include this information to begin with. While I might be able to hack special case behavior for copy paste, I don't want to have to make people choose keyboard shortcuts vs. some other behavior. Could you provide what information you are using from Jisho for reference?

**Comment by seanblue** [comment]
Additional word information from jisho.org:
* JLPT information.
* WaniKani level information.
* Additional audio that is originally from WaniKani.
* Some words have sample sentences to provide more context.
* Some words/definitions have a "see also", "synonym", or "antonym" link to another word. (e.g. 上手)
* Other spellings for the same word (including information about if that spelling is outdated or ateji.

Additional kanji information from jisho.org:
* Interactive stroke order drawings.
* Frequency information for a kanji.
* Variants for the kanji.
* Radicals and parts for the kanji.
* (While building this list I noticed that your kanji JLPT information may be based on the outdated 4-level system)

In addition to jisho.org, I also paste these words directly into WaniKani.

**Comment by seanblue** [comment]
@FooSoft Have you come to any decision about this?

**Comment by FooSoft** [comment]
As it looks like a lot of things would need to be added, I will probably just catch <kbd>Ctrl + C </kbd> in the IFRAME and pass the message along to the parent window so it can catch it and manually do a copy to clipboard operation. It's totally a hack and I hate it, but it's the easiest short-term solution.

**Comment by FooSoft** [comment]
Fixed for 1.1.10
