### ISSUE TITLE
For some reason I can't import a frequency list

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/yomichan#383]
[UNIDIC 3011 fixed.zip](https://github.com/FooSoft/yomichan/files/4272163/UNIDIC.3011.fixed.zip)
I'm pretty sure it's a correct format but for some reason I can't import it

**Comment by toasted-nutbread** [comment]
I think the issue is that there is a byte order mark at the start of one of the files. This character is invisible and is usually used for auto-detection of UTF encodings, but `JSON.parse` doesn't seem to like it.

```js
JSON.parse('\ufeff{}')
// ...
// SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Comment by toasted-nutbread** [comment]
FYI there is also a script in the project that can validate dictionary files:

https://github.com/FooSoft/yomichan/blob/master/test/dictionary-validate.js

Can test ZIP files using:

```sh
node test/dictionary-validate.js path/to/dictionary.zip
```

**Comment by Geniusssmit** [comment]
how can I fix it?

**Comment by toasted-nutbread** [comment]
Depends on what you created/modified the files with. If you have a script which created the data, there may be an encoding option for the file writer. Alternatively, code text editors often have a way to change it. For example VSCode has options to save with an encoding, Notepad++ has options to change the encoding (UTF-8 vs UTF-8-BOM), etc.

**Comment by Geniusssmit** [comment]
thanks, changing the encoding to UTF-8 worked!
