### ISSUE TITLE
quick way to switch between profiles

### ISSUE THREAD

**Issue by radonmiser** [FooSoft/yomichan#388]
Is there a quick way to switch between profiles? For example some sort of hotkey 
I have two profiles each for a different anki template, I go to settings and switch up the profile whenever I want to make a different type of card.
It would be helpful if there's a way to do this faster.

**Comment by siikamiika** [comment]
I'm currently working on it in this branch https://github.com/siikamiika/yomichan/tree/switch-matching-profiles, but it requires some changes to how the text scanning component identifies the popup and popup content that belong to it. I have a draft of the required changes, but it's unreliable sometimes and I'll have to investigate why.

**Comment by toasted-nutbread** [comment]
This is something I thought of while adding the profiles feature but chose not to add at the time, but would it be useful to be able to change profiles from the popup window using the extension button? I don't know if that can be resized after opening however.
