### ISSUE TITLE
Usability proposals

### ISSUE THREAD

**Issue by felixvd** [FooSoft/yomichan#4]
I just picked this up and thought that these things could make the first uses a bit easier. I'll just drop these as comments:

- Make the main text box editable (saving to a .txt file first is inconvenient, especially when reading websites or emails). 
- Add "Paste text here or open a .txt file you want to read!" as initial text into the main text box.
- Add tooltips for the buttons in the Vocabulary/Kanji widgets
- Display a message on first start to set up the card export in the preferences (this feature is easy to overlook)

Lastly, a digital currency donation address would be appropriate somewhere :)

Thanks!

**Comment by FooSoft** [comment]
These are good ideas. About having the text box editable -- do you want to actually be able to edit it, or is being able to paste text to it sufficient? I don't want to create a situation where users can accidentally make edits to the text file they are reading, if you know what I mean.

**Comment by felixvd** [comment]
I think I'd do both. Editing the field would be useful for treating notes I take during presentations or classes. My workflow at the moment involves a browser window, Rikaichan and lots of copy-pasting.

You are right in saying that overwriting an opened file would be unintuitive and might be destructive. As a user I wouldn't expect the text box to save edits to a file, unless it's a temp file to keep the box persistent between sessions. If it worked like that, making the field completely editable would pose no risk, I think. 

Afterwards, a separate save option for the field may be desirable to some, but I wouldn't sweat it.

Thanks for the response, looking forward to your changes :)

**Comment by felixvd** [comment]
I might have misunderstood what you meant - if the text box is editable you might edit it by accident, yes. Most users will know to undo via hotkey, and for the rest you could put in an Undo button. Making the box lockable is another option, but I'd vote for leaving it editable by default - I wouldn't think to look for a button to unlock it as a new user.

Cheers!

**Comment by FooSoft** [comment]
All done with the exception of having tool tips for the buttons. 
The HTML widget in Qt4 is primitive and doesn't allow this to be done through HTML : (

New version pushed out.
