### ISSUE TITLE
Compound Verbs

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#410]
![image](https://user-images.githubusercontent.com/24824399/76618018-7e657480-6562-11ea-9477-a77ef06195f7.png)
I've encountered a lot of these compound verbs that's partially in kanji. 
Is there currently a way to incorporate the main entry（擦り合わせ）into the main lookup?

**Comment by siikamiika** [comment]
Do you need the dictionaries separately in your use case? The feature to group your results by main dictionary entry could solve your problem if you don't.
![2020-03-14_01-52-55](https://user-images.githubusercontent.com/5602483/76669933-91923780-6596-11ea-8c1d-3e784e51e0d2.png)
![2020-03-14_01-54-24](https://user-images.githubusercontent.com/5602483/76669981-ca321100-6596-11ea-8057-099ad30bbeeb.png)

**Comment by Pintliz** [comment]
There's no problem when scanning 擦り合わせ or すりあわせ. the problem arises when scanning compound verbs that's only partly in kanji.
I tried grouping the results, but the definition from 擦り合わせ still doesn't show up when scanning すり合わせ.

(dajirin as the main dictionary)
![image](https://user-images.githubusercontent.com/24824399/76676574-f33abc00-65ff-11ea-826d-a3ca4c5cfc50.png)

(jmdict as the main dictionary)
![image](https://user-images.githubusercontent.com/24824399/76676534-6e4fa280-65ff-11ea-837a-6c165d37e907.png)

**Comment by siikamiika** [comment]
Oh yeah, I forgot one thing. You should make JMdict the main dictionary, but also enable "secondary searches" for 大辞林 in advanced settings.
![2020-03-14_12-51-16](https://user-images.githubusercontent.com/5602483/76680605-8cfb6c80-65f2-11ea-80ee-dbdb163f7951.png)

**Comment by siikamiika** [comment]
Here's an explanation of what it does: https://github.com/FooSoft/yomichan/issues/167#issuecomment-515806486

**Comment by Pintliz** [comment]
It worked, thank you!
