### ISSUE TITLE
anki cloze note /{audio} problem

### ISSUE THREAD

**Issue by FireKingY** [FooSoft/yomichan#419]
I'd like fill my fied like `{{c1::{expression}}} {{c2::{audio}}}`, but the result is `{{c2::教師}}{{c1::}}[sound:yomichan_きょうし_教師.mp3]`. 

It semms the {audio} will always be appended at end. Is there any way let it work as I need?

**Comment by toasted-nutbread** [comment]
The audio is appended at the end as part of anki-connect.

https://github.com/FooSoft/anki-connect/blob/9ba5c08c965885222613ebf45c0edf38ab50b3ac/plugin/__init__.py#L495-L499

What is the use case of putting the {audio} tag at a specific location? My understanding is that it's hidden anyways.

**Comment by FireKingY** [comment]
> The audio is appended at the end as part of anki-connect.
> 
> https://github.com/FooSoft/anki-connect/blob/9ba5c08c965885222613ebf45c0edf38ab50b3ac/plugin/__init__.py#L495-L499
> 
> What is the use case of putting the {audio} tag at a specific location? My understanding is that it's hidden anyways.

Cloze deletion.
I want to fill "Question" filed like`{{c1::車}}{{c2::[sound:車.mp3]}}`,  so that I can use `{{cloze:Question}}` at the front side of the card. 
[https://docs.ankiweb.net/#/editing?id=cloze-deletion](url)

**Comment by toasted-nutbread** [comment]
I see. I'm working on some changes to how audio is injected into cards, so it might be able to be done as part of that. #427

**Comment by FireKingY** [comment]
> I see. I'm working on some changes to how audio is injected into cards, so it might be able to be done as part of that. #427

Thank you.

**Comment by toasted-nutbread** [comment]
@FooSoft I'm looking through some of the audio code, and when loading an `Audio` object, there are two durations which cause the audio to be ignored: `5.694694` and `5.720718`. The first one corresponds to [invalid audio from the jpod101 source](https://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kana=invalid) and the MD5 hash `7e2c2f954ef6051373ba916f000168dc`, but I'm not sure what the second one corresponds to. Do you know what the second one is/was for?

Originally added here: https://github.com/FooSoft/yomichan/commit/c8eb77cfd9e30625ae33739b7de5a86f59d0457c#diff-d5a318d27e03a2960299ccc82727e376R186
