### ISSUE TITLE
[bug] Search breaks double consonant when using IME

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#42]
I tend to use an IME in the search, even though it converts romaji to hiragana. This generally works, but not when the word has a double consonant. For example, when I try to type 学校, when I get to 「がｋｋ」 in the IME, it is converted to 「がっk」from the romaji replacement. Because of this, the IME can't detect the rest of the word as being associated with the first part, and it can't convert the word to 学校.

**Comment by FooSoft** [comment]
What IME are you using? I'm using IBus on Linux and everything appears to work properly.

**Comment by seanblue** [comment]
I'm using the Microsoft IME on Windows 10.

**Comment by FooSoft** [comment]
I'm using WanaKana for the built-in IME. Can you go to http://wanakana.com/ and see if you can replicate the issue by typing in the demo textbox that is just under the "Download" button? I'm getting the feeling that this is a bug in their library as opposed to Yomichan itself.

**Comment by seanblue** [comment]
Yep, the issue happens there as well.

**Comment by DJTB** [comment]
Fixed in `Wanakana 2.2.2` ^^

**Comment by FooSoft** [comment]
Awesome, I will make sure that the next release of Yomichan uses this version.

**Comment by seanblue** [comment]
@FooSoft Just so you know, they found an issue in `WanaKana 2.2.2` on mobile devices. While it won't impact your extension since it doesn't run on mobile, it seems like they will come out with a new version soon.

**Comment by seanblue** [comment]
Version `2.2.3` is now live.
