### ISSUE TITLE
Question: Yomichan on Brave

### ISSUE THREAD

**Issue by fsmiamoto** [FooSoft/yomichan#422]
I have not been able to get Yomichan properly working on the Brave Browser and I've wondered if anyone has the same issue.

Since Brave is based on Chromium, I guess it is possible for it to work.

The same set of dictionaries I used on Brave works perfectly on Firefox.

### Problem:
Popup doesn't show after pressing the scan modifier key

### Expected behavior:
The popup should appear after pressing the key

### Attempts to solve the issue:
 - Disabling all other extensions except Yomichan

### Description:
- Brave: Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) unknown (64-bit)
- OS: Arch Linux x86_64 5.5.11-arch1-1
- Yomichan: v20.2.24.0

**Comment by siikamiika** [comment]
Are you using the default settings? It works for me both on Arch (https://aur.archlinux.org/packages/brave-bin/) and Windows (1.8.52/81.0.4044.83). Check that you have the correct dictionaries enabled and you're not accidentally using the wrong profile. If there's a bug, you might see it in the developer console.

**Comment by fsmiamoto** [comment]
It indeed seems like it was a mistake on my part, sorry!

But since this might be useful for another users, I'm gonna leave it here:
Check if the current page is allowed, it looks like you have to authorize the extension on every page by clicking on the extension icon.

Thanks @siikamiika  and closing the issue

**Comment by siikamiika** [comment]
I wasn't aware of this feature in chromium based browsers before, but it seems that you can allow site access on "all sites" instead of "on click" at brave://extensions?id=ogmnaimimemjmbakcfefmnahgdfhfami.

**Comment by fsmiamoto** [comment]
Yes it is!
Thanks for the useful heads up
