### ISSUE TITLE
[Feature request] Add option to keep native popups always on top

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#425]
When watching shows fullscreen in external apps, I use Yomichan's native popup feature to look up words when copying the subs with a hotkey. However, whenever I do this on macOS, the Yomichan window opens outside of the fullscreen window, shifting the view away from the video. The ability to enable the option, "Keep native popups always on top," would fix this. That way the view won't be shifted and I can look up words while staying on the video, making the whole lookup process faster for external applications.

**Comment by siikamiika** [comment]
I'm not sure if this is supported by extension APIs, but for mac specifically there seems to be an app that could achieve what you need: https://github.com/rwu823/afloat

I didn't test it, so hopefully there's a way to make it persist after the popup is closed.

**Comment by oudajosefu** [comment]
I saw afloat while researching a solution for this, but then realized it hasn't been updated in 5 years and installation requires one to "reboot into recovery mode and disable SIP." I'd rather not do that as much as possible (speaking from experience).

I'll try the stretching solution but I like watching videos in real full screen so it's not my favorite solution. Thanks anyways.

**Comment by toasted-nutbread** [comment]
I looked into this a while ago for Windows and was similarly disappointed that there is no browser API, although maybe it's an understandable choice. One thing I did find in my search was the following, which seems to be an implementation of a helper Windows native extension:
https://addons.mozilla.org/en-US/firefox/addon/always-on-top/
https://vm-devr.github.io/aot/
https://github.com/vm-devr/aot

**Comment by siikamiika** [comment]
> I'll try the stretching solution, but honestly, I like watching videos in real full screen so it's not my favorite solution. Thanks anyways.

Yeah, it's not perfect. Maybe it's possible to make your clipboard copy hotkey first disable fullscreen and then perform the copy. However, this might not play nicely with macOS animation delays. For stretched windows, hiding dock, taskbar or player toolbars (for any OS or player in general) will improve the results.

**Comment by oudajosefu** [comment]
Update: I discovered in my media player that there exists something called "legacy full screen." Pretty much does exactly what I was looking for while keeping that full screen feel, allowing me to use the copy hotkey to look up any word in the native popup. The media player I use btw is [IINA](https://iina.io/), highly recommend it as you can customize it to your heart's content with mpv scripts since it is based off libmpv.

**Comment by siikamiika** [comment]
@oudajosefu Nice that you found a solution! I haven't tried IINA, but the legacy full screen option sounds like it could be something similar to borderless full screen that's common with Windows games. I mainly use Linux/Windows where I have mpv installed as well, and I agree that it's pretty good and customizable. I do have the regular mpv installed on my work MacBook too, but I don't usually watch videos on it :smile:

I'll close the issue since it's resolved for you and edit the title a bit since I'm pretty convinced that it's not possible to do this with browsers at the moment.
