### ISSUE TITLE
Multiple pop-up not working in some pages

### ISSUE THREAD

**Issue by MarcusAseth** [FooSoft/yomichan#426]
Hi, I'm using firefox and the yomi-chan scan with multiple pop-up is not working on some pages, like it works on wikipedia but doesn't work on this one https://www3.nhk.or.jp/news/easy/k10012353791000/k10012353791000.html

Meanwhile another user with firefox is not having any problem in that link, so for some reason I am the only one affected by this problem it seems.

**Comment by MarcusAseth** [comment]
also if really is only a problem on my side, I would really appreciate some help in troubleshooting and fixing this ^_^'

**Comment by MarcusAseth** [comment]
nevermind I've found a solution, apparently after the setting change all that was needed for it to work properly on every page was to restart Firefox.
This issue can be deleted :)

**Comment by siikamiika** [comment]
It usually helps if you refresh the page after changing settings. There's also an update on the testing version where more settings are updated without a need to refresh, but it might not help in this case because popup initialization is only done on page load.
