### ISSUE TITLE
Can't create card to Anki ver 2.1.22

### ISSUE THREAD

**Issue by SecretArmy** [FooSoft/yomichan#428]
Just updating to Anki ver 2.1.22 on Win 10 Pro 64-bit. Then the error appear, reinstall / downgrading anki or yomichan is a no go, still got the error. 
http://localhost:8765/ return AnkiConnect v.6.
On the settings page there is an error :
Error: Failed to connect
Error: Failed to connect
at XMLHttpRequest. (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/bg/js/request.js:25:52)

**Comment by toasted-nutbread** [comment]
Have you verified that your Windows Firewall isn't blocking Anki?

**Comment by SecretArmy** [comment]
never change anything on firewall, also do you mean these ? https://i.imgur.com/xjJFhvY.png

**Comment by toasted-nutbread** [comment]
The settings look correct, so it's unclear what exactly is happening... I think we might have to do some debugging in the web console to see what is happening, similar to what we have had to do for a similar issue https://github.com/FooSoft/yomichan/issues/327#issuecomment-576368773.

If you can open the dev console (F12) on Yomichan's settings page, run the following script, and screenshot/copy the results in a comment, that might help diagnose the issue.

```js
(async () => {
  function requestJson(url, action, params) {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.overrideMimeType('application/json');
      xhr.addEventListener('load', () => resolve(xhr.responseText));
      xhr.addEventListener('error', (e) => { reject(new Error('Failed to connect')); console.log(xhr, e); });
      xhr.open(action, url);
      if (params) {
        xhr.send(JSON.stringify(params));
      } else {
        xhr.send();
      }
    });
  }

  const results = [];
  for (const action of ['version', 'deckNames', 'modelNames']) {
    const text = await requestJson('http://127.0.0.1:8765', 'POST', {action, version: 2});
    try { JSON.parse(text); } catch (e) { console.log(action, e); }
    results.push(text);
  }
  console.log(JSON.stringify(results, null, 4));
})();
```

Here is an example of what the results look like:
![image](https://user-images.githubusercontent.com/11037431/78414277-6759f580-75e9-11ea-980c-685f77666302.png)

**Comment by SecretArmy** [comment]
Here the results https://i.imgur.com/mQPqgZa.png

**Comment by toasted-nutbread** [comment]
This may be related to this:
https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

So I think in order to fix this, you have to edit the settings of AnkiConnect from inside Anki. Try adding `"chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami"` to the `"webCorsOriginList"` list; don't forget to add a comma to the line above. The result should look something like this:

```jsonc
{
    "apiKey": null,
    "apiLogPath": null,
    "webBindAddress": "127.0.0.1",
    "webBindPort": 8765,
    "webCorsOrigin": "http://localhost",
    "webCorsOriginList": [
        "http://localhost",
        "chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami"
    ]
}
```

**Comment by SecretArmy** [comment]
Well, It works, the error is gone and anki is accepting new cards. Thanks for the help.

**Comment by toasted-nutbread** [comment]
Good to hear! It's still unclear why this happened however; even the link that I posted isn't something that should affect this extension. Can you check what version of Chrome are you using, and are there any settings you have modified in it?

**Comment by SecretArmy** [comment]
Version 80.0.3987.163 (Official Build) (64-bit), for settings what settings? browser, exts, or yomichan?

**Comment by toasted-nutbread** [comment]
Nothing in Yomichan should affect it, but are there any browser settings that you modified, or any extensions (like an adblocker) which have specialized settings? I wasn't able to reproduce the same behaviour your had, so I'm wondering if there was some sort of change which may have caused it. We may just have to add an additional info message for the cases when Yomichan cannot connect.

**Comment by SecretArmy** [comment]
For exts: 

- Avira Browser Safety 2.8.4.2056
- Anti Miner - No 1 Coin Minerblock 1.1.5
- HTTPS Everywhere 2020.3.16
- No Coin - Block miners on the web! 0.4.14
- Twitter Media Assist 3.0.2
- uBlock Origin 1.24.4

and yomichan on change to site access on click, everything is working before with all the settings and exts, but most likely due to chrome update, since I play GBF, I tend to update chrome to the latest ver.

**Comment by toasted-nutbread** [comment]
Alright, thanks for your help. I'll try out some things in case other users have the same issue in the future.
