### ISSUE TITLE
[bug] Wrong audio for some words

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#43]
I just encountered this today. I don't know if the audio source is simply wrong if it this has to do with how the audio is being retrieved.
Take the following word: 留守番電話
For 留守番電話, the audio for 留守録 plays.
This also gives the result 留守番, which actually plays the audio expected for 留守番電話.
And when searching for 留守録 (the wrong audio from the first one), it plays とめどない.

**Comment by FooSoft** [comment]
This appears to be a problem with the audio source. Check out the audio results from https://www.japanesepod101.com/japanese-dictionary/ , it also plays the wrong audio. Bizarre and broken, but unfortunately there is nothing that can be done on Yomichan's end.
