### ISSUE TITLE
Improve Yomichan popup iframe security

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#441]
Related: #353

This is a reminder issue to update the iframe to be dynamically loaded rather than using a `src` URL.

Old in-progress branch: https://github.com/toasted-nutbread/yomichan/tree/iframe-url-security

**Comment by siikamiika** [comment]
I actually thought this was resolved earlier, but a while ago I tested that it's still possible to get the iframe `src` from the page. Were there some issues with getting blank popups?

**Comment by toasted-nutbread** [comment]
There were some issues which weren't handled which made me have to revert it.

36605f74c3d48a98500d198636112454b36063f6
