### ISSUE TITLE
Failed to import Kanjium zip downloaded from official Yomichan webpage

### ISSUE THREAD

**Issue by mbdevpl** [FooSoft/yomichan#457]
## Steps to reproduce

1. Install latest Yomichan addon in Firefox.
2. Download pitch accent dictionary from https://foosoft.net/projects/yomichan/ (exact URL: https://foosoft.net/projects/yomichan/dl/dict/kanjium_pitch_accents.zip)
3. Import it to Yomichan.

### Expected

It imports normally, as other dictionaries do.

### Actual

Following error appears in Yomichan:

```
Error: Dictionary has invalid data in 'term_meta_bank_1.json'
for value 'dictionary[0][1]', validated against 'schema.additionalItems.items[1]':
Invalid enum value
```

**Comment by siikamiika** [comment]
The version available at AMO doesn't have support for pitch accents yet. The testing version at https://foosoft.net/projects/yomichan/index.html#installation works already, though. Maybe we should add this information to the website until the test version is released as stable because this has caused confusion before too.

Related: https://github.com/FooSoft/yomichan/issues/451

**Comment by FooSoft** [comment]
Yup, I will update the website to reflect that this is only available in the latest release.

**Comment by mbdevpl** [comment]
I see. Thank you. Not sure what exactly AMO acronym stands for, even after googling... But basically the latest stable version available now seems to be 20.2.24.0. Could you specify what is the version number in which the pitch accents dictionary is expected to work? I'll keep an eye on updates.

**Comment by mbdevpl** [comment]
And, BTW, there is a discussion in JMdict about including pitch accents. See: https://www.edrdg.org/wiki/index.php/JMdict:_Next_Generation#Pitch_Accent_Elements Would you also be willing to support their data format (if it gets released)?

**Comment by siikamiika** [comment]
> I see. Thank you. Not sure what exactly AMO acronym stands for, even after googling...

Sorry for being unclear, it's the [acronym](https://wiki.mozilla.org/Add-ons#What) of [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/), but I guess it's mainly used by Mozilla iternally.

> But basically the latest stable version available now seems to be 20.2.24.0. Could you specify what is the version number in which the pitch accents dictionary is expected to work? I'll keep an eye on updates.

The feature was released in [20.4.10.0](https://github.com/FooSoft/yomichan/releases/tag/20.4.10.0) which is now in testing.

> And, BTW, there is a discussion in JMdict about including pitch accents. See: https://www.edrdg.org/wiki/index.php/JMdict:_Next_Generation#Pitch_Accent_Elements Would you also be willing to support their data format (if it gets released)?

There's some discussion about the feature in https://github.com/FooSoft/yomichan/issues/61 and https://github.com/FooSoft/yomichan/pull/385. Basically it supports multiple pitch accent dictionaries simultaneously as long as they're converted into the format specified in [the schema](https://github.com/FooSoft/yomichan/blob/master/ext/bg/data/dictionary-term-meta-bank-v3-schema.json). Creating the framework was the hardest part, and it should be relatively simple to do the format conversion. The dictionary was created with this tool: https://github.com/toasted-nutbread/yomichan-pitch-accent-dictionary

**Comment by FooSoft** [comment]
As @siikamiika mentioned, 20.4.10.0 is already in testing, and has been queued to go to master (as soon as the update is reviewed and accepted). It happens pretty quickly for AMO, but for Play Store it can take several days...

**Comment by mbdevpl** [comment]
Thanks again - just wanted to report that my Yomichan settings at the bottom today says "v20.4.10.0" and I was able to import the pitch accent dictionary, and they show up in the lookup results. Very nice feature :)
