### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by andrearicci** [FooSoft/yomichan#459]
Hello, I installed yomichan, some dictionaties etcetera as per instruction but nothing happens: with the middle mouse button I have the scrolling arrows, with SHIFT absolutely nothing. Of course it's ON.
Is there any setting I can check? Maybe an extension conflict?
Win10 V 1909
FF 75.0 (64)
FF active extensions:
Amazon.it	1.1	true	amazon@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
Context Search	3.72	true	olivier.debroqueville@gmail.com
Decentraleyes	2.0.14	true	jid1-BoFifL9Vbdl2zQ@jetpack
Disable HTML5 Autoplay	2018.10.3	true	disable-html5-autoplay@afnankhan
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Facebook Container	2.1.1	true	@contain-facebook
Google	1.0	true	google@search.mozilla.org
Google search link fix	1.6.9	true	jid0-XWJxt5VvCXkKzQK99PhZqAn7Xbg@jetpack
No Coin - Block miners on the web!	0.4.13	true	{5657c026-efc3-4860-b43b-16e4eaa8a9aa}
Print Edit WE	26.1	true	printedit-we@DW-dev
Privacy Badger	2020.2.19	true	jid1-MnnxcxisBPnSXQ@jetpack
TinEye Reverse Image Search	1.4.1	true	tineye@ideeinc.com
uBlock Origin	1.26.0	true	uBlock0@raymondhill.net
Wikipedia (it)	1.0	true	wikipedia@search.mozilla.org
Worldwide Radio	3.4	true	worldwide@radio
Yomichan	20.2.24.0	true	alex@foosoft.net
Thank you

**Comment by siikamiika** [comment]
Do you happen to have "Never remember history" or "Always use private mode" enabled in Firefox settings? I can't test that now, but there's been some problems with that and the Yomichan database engine IndexedDB.

After checking that, you could try creating a fresh profile and seeing if this problem still exists. If it does, please export and share your profile settings from the bottom of the page where you import dictionaries so it's easier to reproduce the issue. I think you'll have to rename the `.json` into something else like `.txt` to upload it to Github.

**Comment by toasted-nutbread** [comment]
I set up a fresh profile and installed all of the addons in the list and installed two Yomichan dictionaries and everything seemed to work. I didn't change any settings of any addons or the 
browser though.

| Name | Version | Enabled | ID |
|---|---|---|---|
| Amazon.com | 1.1 | true | amazondotcom@<wbr>search.mozilla.org |
| Bing | 1.1 | true | bing@<wbr>search.mozilla.org |
| Context Search | 3.8.4 | true | olivier.debroqueville@<wbr>gmail.com |
| Decentraleyes | 2.0.14 | true | jid1-BoFifL9Vbdl2zQ@<wbr>jetpack |
| Disable HTML5 Autoplay | 2018.10.3 | true | disable-html5-autoplay@<wbr>afnankhan |
| DuckDuckGo | 1.0 | true | ddg@<wbr>search.mozilla.org |
| eBay | 1.0 | true | ebay@<wbr>search.mozilla.org |
| Facebook Container | 2.1.1 | true | @<wbr>contain-facebook |
| Google | 1.0 | true | google@<wbr>search.mozilla.org |
| Google search link fix | 1.6.9 | true | jid0-XWJxt5VvCXkKzQK99PhZqAn7Xbg@<wbr>jetpack |
| No Coin - Block miners on the web! | 0.4.13 | true | {5657c026-efc3-4860-b43b-16e4eaa8a9aa} |
| Print Edit WE | 26.1 | true | printedit-we@<wbr>DW-dev |
| Privacy Badger | 2020.2.19 | true | jid1-MnnxcxisBPnSXQ@<wbr>jetpack |
| TinEye Reverse Image Search | 1.4.1 | true | tineye@<wbr>ideeinc.com |
| Twitter | 1.0 | true | twitter@<wbr>search.mozilla.org |
| uBlock Origin | 1.26.0 | true | uBlock0@<wbr>raymondhill.net |
| Wikipedia (en) | 1.0 | true | wikipedia@<wbr>search.mozilla.org |
| Worldwide Radio | 3.4 | true | worldwide@<wbr>radio |
| Yomichan | 20.2.24.0 | true | alex@<wbr>foosoft.net |

**Comment by andrearicci** [comment]
> Do you happen to have "Never remember history" or "Always use private mode" enabled in Firefox settings?

Hi, and thank you all for your reply.
The two options are not enabled.
I made a new profile, installed it and two dicts but still nothing happens. 
In the default profile I have:
Mdict (English) 
JMnedict 
KANJIDIC

Thank you

**Comment by toasted-nutbread** [comment]
Can you export your settings and share the resulting file here? It's under the "Backup" section, near the bottom on the settings page.

![image](https://user-images.githubusercontent.com/11037431/79640814-a9df0e80-8161-11ea-8bea-e3dc3f0716a8.png)

**Comment by andrearicci** [comment]
Here it is, thank you. (this is from my default profile, not the fresh new one)
[yomichan-settings-2020-04-18-15-32-46.txt](https://github.com/FooSoft/yomichan/files/4496898/yomichan-settings-2020-04-18-15-32-46.txt)

**Comment by toasted-nutbread** [comment]
Nothing looks to be wrong in your settings file, and when I tried importing it, everything seemed to work. I changed the browser language to Italian also (which I think is what you're using), and that didn't seem to break anything either. Would you be able to look at some of the developer tools and share some screenshots?

1. Background dev tools => Console tab. Open `about:devtools-toolbox?type=extension&id=alex%40foosoft.net` in a new tab; should look [something like this](https://user-images.githubusercontent.com/11037431/79642542-0f37fd00-816c-11ea-9da1-ff9356b8b7c2.png), maybe white themed.
2. Dev tools => Console tab on a standard web page after trying to scan some Japanese text using shift key + mouseover. You can try it here: `こんにちは`. Again, this should look similar to the one above: [something like this](https://user-images.githubusercontent.com/11037431/79642601-8a99ae80-816c-11ea-8486-96d5369d14c2.png).
3. Dev tools => Inspector tab on a standard web page after trying to scan some Japanese text. This time, checking the web page to see if the Yomichan `<iframe>` is present. It would be at the very bottom, and should look [something like this](https://user-images.githubusercontent.com/11037431/79642687-098ee700-816d-11ea-8a10-ceadd2f9db8a.png).

**Comment by andrearicci** [comment]
I'm sorry (but happy!),
it's working now. I donnow what happened (well, i rebooted, but I didn't think I had to).
Thank you very much for your help and time.

**Comment by toasted-nutbread** [comment]
Nice, cheers.
