### ISSUE TITLE
japanesepod101 certificate expired

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#471]
This seems to happen periodically, so I'm pinning the issue. It's usually fixed in a day or two.

https://github.com/FooSoft/yomichan/issues/180, https://github.com/FooSoft/yomichan/issues/280

**Comment by zdzislaw-s** [comment]
As a workaround I'm using this:
![Screenshot from 2020-04-23 13-14-12](https://user-images.githubusercontent.com/34413043/80055194-7129a580-8564-11ea-95bd-eed1de6b0b3f.png)
