### ISSUE TITLE
Field templates are not honoured

### ISSUE THREAD

**Issue by zdzislaw-s** [FooSoft/yomichan#473]
My field template for `"glossary"` has:
```js
    {{#*inline "glossary"}}
        <div style="text-align: center;">
        .
        .
        .
```

After creating a note with Yomichan/AnkiConnect, where the mapping is `"Meaning"` -> `"{glossary-brief}"`, the `"Meaning"` field in the created note has:
```html
    <div style="text-align: left;">...</div>
```

My current woraround is the following in `2055492159/__init__.py` (AnkiConnect):
```py
    class AnkiConnect:
        .
        .
        .
        for name, value in note['fields'].items():
            if name in ankiNote:
                # zdz@23/4/20: Workaround for field templates not working in Yomichan
                if name == "Meaning":
                    value = re.sub("style=\"text-align: left;\"", "style=\"text-align: center;\"", value)
                ankiNote[name] = value
```

My configuration:
- Ubuntu 16.02
- Anki 2.1.22 (0ecc189a)
- Yomichan 20.4.10.0
- meta.json from AnkiConnect has:
    {"name": "AnkiConnect", "mod": 1587556086}

**Comment by siikamiika** [comment]
Thanks for noticing. I think it was caused by this change: https://github.com/FooSoft/yomichan/pull/380/files#diff-eb13a5f4fa49d25c9785f6af244c9d59L451
