### ISSUE TITLE
Default option values review

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#479]
Expanding upon #462, I think there may be a few default values for options that we should consider reviewing:

* Changing `showIframePopupsInRootFrame` from `false` to `true`. (#462)
  This feature should be stable enough to support being enabled by default.
* Changing `scanning.middleMouse` from `true` to `false`.
  I don't know how many people use this, but its implementation currently feels a bit odd to use since it doesn't prevent the default behaviour of middle mouse click. This results in the page being scrolled while trying to move the mouse over text.
* Changing `scanning.delay` from `20` to `0` (or `1`).
  It feels sluggish to have delay enabled when scanning text. Again, not sure how many people use this, or what their preferences are for it, but IMO 0 feels better than 20, since lookups are near instantaneous on some setups.
  * Aside: whenever we get to addressing additional functionality for modifier keys, it may be good to have a key that you can hold to _not_ scan text under the cursor, or hide the popup. (Added to #267)
* Changing `popupNestingMaxDepth` from `0` to `1`.
  Not sure if this would confuse people or not, but this feature is probably stable enough to allow having it on by default.
* Changing `enablePopupSearch` from `false` to `true`.
  Same motivation as above, potentially a stronger case to enable since it's only a specific page.

We should consider how we want to handle updating these. For something like `showIframePopupsInRootFrame`, it _might_ actually be fine to change existing user setting value, since it could be seen as simply an added/improved feature, not a behaviour change. For others, we would definitely want to not touch user settings and only change the installation defaults.

We should also try to determine when to do this. In #462, it was mentioned that we might want to wait a bit before merging. Since I'm working on some updates to the settings page in general, I'm wondering if we want to update that and any other settings as part of that effort.

**Comment by siikamiika** [comment]
>   * Changing `scanning.delay` from `20` to `0` (or `1`).
>     It feels sluggish to have delay enabled when scanning text. Again, not sure how many people use this, or what their preferences are for it, but IMO 0 feels better than 20, since lookups are near instantaneous on some setups.

It's only enabled when scanning modifier is set to None. I think it could be more obvious from the setting, though. I've also seen some discussion among Yomichan users that those who like a mouse only rikaichan style setup will also set popup offset to 0 to be able to move mouse from the page to the popup without accidentally scanning some other text. I personally keep the delay there when I have the modifer None, for example when I'm watching Netflix (also using this [script](https://github.com/siikamiika/scripts/blob/master/netflix/netflix-extra-keybinds.user.js) and [Subadub](https://github.com/rsimmons/subadub)) or YouTube.

> * Changing `popupNestingMaxDepth` from `0` to `1`.
>   Not sure if this would confuse people or not, but this feature is probably stable enough to allow having it on by default.
> 
> * Changing `enablePopupSearch` from `false` to `true`.
>   Same motivation as above, potentially a stronger case to enable since it's only a specific page.

Agreed, together with "Enable scanning of expressions in search results" this should be fine. I think it should be probably extended to the "only" disambiguation and other non-dictionary content too.

**Comment by siikamiika** [comment]
More discussion in this issue: https://github.com/FooSoft/yomichan/issues/71

**Comment by siikamiika** [comment]
>   * Changing `scanning.middleMouse` from `true` to `false`.
>       I don't know how many people use this, but its implementation currently feels a bit odd to use since it doesn't prevent the default behaviour of middle mouse click. This results in the page being scrolled while trying to move the mouse over text.

I believe this comes from @FooSoft being a Linux user where it's not the norm that middle click activates auto-scroll. It's possible to enable it for Firefox in settings, but for Chrome you'll need an [extension](https://chrome.google.com/webstore/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan?hl=en). It would be possible to disable this option by default on Windows, or make the defaults work without issues on all target platforms (thus making this `false` by default).

> We should consider how we want to handle updating these. For something like `showIframePopupsInRootFrame`, it _might_ actually be fine to change existing user setting value, since it could be seen as simply an added/improved feature, not a behaviour change. For others, we would definitely want to not touch user settings and only change the installation defaults.

Yeah, I was originally considering making it always on without a switch, but then stuff like shadow DOM came along. I'd still keep the option there in case users find places where they can still break it.

> We should also try to determine when to do this. In #462, it was mentioned that we might want to wait a bit before merging. Since I'm working on some updates to the settings page in general, I'm wondering if we want to update that and any other settings as part of that effort.

I'm not in a hurry with that, and I think the transition would be more smooth if it was enabled as opt-in and for new users by default. Changing existing values would also add some complexity.

**Comment by siikamiika** [comment]
Other possible default value changes:
-  `general.compactTags` from `false` to `true`.
    Mainly applies to JMdict, but I think they are quite noisy when you don't compress them. Not sure if this could cause some issues with long entries.
- `general.popupHeight` from 250 to 400.
   The small height affects layout design. https://github.com/FooSoft/yomichan/issues/402
- `general.popupTheme` to the value that the browser or OS uses.
   Available as the CSS selector [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), but not sure what's the most effective way to get it using JS.
- `scanning.alphanumeric` from `true` to `false`.
  This can be annoying when you have scanning modifier set to none. Numbers and alphabets are currently also difficult to scan due to JMdict having them as full width and Japanese text using a mix of full and half width. The issue is partly solved by translation options, but I think it's a deeper issue. https://github.com/FooSoft/yomichan/issues/461
- `scanning.autoHideResults` from `false` to `true`.
  When using a scanning modifier, the popup would still stay open if you don't keep it pressed. The only issue I can see from having this on is that you can accidentally close the popup when adding a note or doing other things inside the popup with scanning modifier as none.

**Comment by FooSoft** [comment]
> I believe this comes from @FooSoft being a Linux user where it's not the norm that middle click activates auto-scroll. It's possible to enable it for Firefox in settings, but for Chrome you'll need an extension. It would be possible to disable this option by default on Windows, or make the defaults work without issues on all target platforms (thus making this false by default).

That pretty much sums it up -- we should just disable that by default IMO. I've been using `Shift` for scanning for a pretty long time now myself, and I don't think it makes sense to have such fundamental things be different across platforms; just makes things confusing.

**Comment by byjtje** [comment]
I have no idea how much it would affect weaker hardware, but `scanning.length` being `10` by default causes Yomichan to miss out on a lot of longer sayings, e.g. `山椒は小粒でもぴりりと辛い`. So far I've had no problems with it being set to `20`.

**Comment by toasted-nutbread** [comment]
Closing this issue as numerous of these settings changes have been addressed. Other changes in the future will be largely subject to user feedback.
