### ISSUE TITLE
Sanseido support

### ISSUE THREAD

**Issue by CureDolly** [FooSoft/yomichan#48]
It now seems that the online Sanseido dictionary is not going down.

I am wondering if it would be possible to include Sanseido definitions in the same way Rikaisama does.

This is an important issue to me and perhaps to other readers. For convenience I am pasting here a post I made on the Kanji Koohii forums explaining why the issue matters.

>>With Rikaisama/Sanseido back in action, at least for the present, I thought It might be helpful to FooSoftさん to tell him whether we would be switching back to RIkaisama and if so why.

In my case I will and for one simple reason. Sanseido. I like the brevity of the definitions. With Yomichan currently I get a big definition with a lot of dictionary-esque text plus bits of English I don't want (even using the Japanese EPwing dictionary exclusively). Of course I can edit this but it all adds time and complication to the card-making process. And I still miss Sanseido's concise, boiled-down definitions.

As it happens I just explained in this thread why I need very concise definitions.

The problem is the dictionary, not the plugin, so if it were possible for Yomichan to have the same arrangement with Sanseido that Rikai has, it would be solved.

In addition to this of course, the means of obtaining an EPwing Japanese dictionary are complex, dubious (obviously I can't recommend it on KawaJapa for example), and may not last. It also doesn't work on 32-bit systems.

I don't know if it is possible, but I will open an issue on GitHub because to me it is not quite make-or-break but certainly enough to make me return to Rikai.

**Comment by FooSoft** [comment]
I hear what you are saying, but I don't think this will be happening. I take pride in writing high-quality, reliable software and I have (and will continue to) prioritize code quality over feature quantity (quality over quality I guess). Rikai implements Sanseido support with web page scraping. Basically it loads the website (which is down half the time I look at it by the way), and tries to extract useful bits out of the HTML and display them to the user. 

There are several problems:
* Reliability: when the site stops working, it looks like the extension is broken.
* Accuracy: just like the rest of EPWING support in Rikai, Sanseido is implemented in a half-assed way that does not support deinflection. Proper deinflection support requires numerous search queries to execute. When you look at how slow that site already is and multiply it by a factor of magnitude *for every single possible term*, you can imagine how slow things would be.
* Sanseido is already available in EPWING (as you pointed out). I've always thought of J-J dictionary support as a feature for the most hardcore learners of Japanese; those users are probably resourceful enough to obtain whatever files they want. It is true that 32-bit systems are not directly supported, but there are other ways of getting EPWING dictionaries into Yomichan, which I will document later.

I truly appreciate and value your (and everyone else's) suggestions, but this one is getting closed as it is (in my opinion) orthogonal to Yomichan's design philosophy.
