### ISSUE TITLE
Merge strategy for pull requests

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#480]
One thing I've noticed as I make the changelog update notes is that the history that Github shows for commits is not very easy to read. The reason for this is that we currently do merge commits for features, and Github displays commits in more or less chronological order. This means that all the individual commits can appear jumbled up, making it difficult to understand exactly what changes were made. Here is an [example](https://github.com/FooSoft/yomichan/compare/20.4.10.0...20.4.18.0).

I'm wondering if we should switch to the "Squash and merge" strategy instead. This would make PR commits show up as a single commit, and there would be much less branching, if any, on the master branch. The history of that branch and the PR would still be available in the PR itself, even if the branch is deleted. The only downside is that it might make it harder to bisect exactly which part of a feature caused a break when we encounter a bug, but can still check out a PR's history directly.

This article summarizes it nicely:
https://medium.com/@brunoluiz/still-using-gitflow-what-about-a-simpler-alternative-74aa9a46b9a3

**Comment by FooSoft** [comment]
I think it makes a lot of sense. I think an ideal PR encompasses some basic feature or improvement, and there is limited value in going finer-grained than that. Doing squash also makes it easier to revert changes if/when things don't work out the way that they were intended to.

**Comment by siikamiika** [comment]
I have kind of mixed feelings about this. I agree that commits made during a pull request review to address issues in the PR are mostly useless in the future, but some larger features will be a lot easier to understand when you keep the different parts where you first refactor the code and then add the new feature.

I think it would be ideal for the commit history if we first had a draft that can be reviewed, and after review there would be another pull request with clean commits. This would probably be too much hassle for small changes, but something worth considering in larger updates or features in my opinion.

For small pull requests where some fixes have to be done during review I agree that squash could be a better option than a merge commit.

I've also noticed that if you do a rebase locally and force push before a merge commit, the commit history seems to stay logical but not chronological. The merge commit will have a reference to the GitHub issue.

**Comment by FooSoft** [comment]
Maybe this is just a situation where there is no hard and fast rule? Do squash by default, but keep history in cases where it is meaningful?

Nice thing about squash is that if you are getting a contribution from a developer who does not have good discipline about writing descriptive commit messages (I am definitely guilty of this), you just end up getting a bunch of garbage in your history that just adds noise for anyone trying to get useful info out of it.

I also think that it is nice to think about every commit in a project's history as a place you could go back to and reasonably expect to have things functional. This would imply that before doing every single commit, there is some sort of testing pass to ensure that there is some basic level of functionality (which would be kind of annoying to do). For my workflow at least, I like to commit at logical points in development "added stub for X", "removed Y", etc... if that history was preserved, and someone tried to jump into a random spot in it, things could be beyond broken.

**Comment by siikamiika** [comment]
Sounds good, I'm also curious to see how this works compared to the previous style. I agree that it's good to have commits where things aren't broken in the master branch so that you can bisect and find the breaking commit easily without having to deal with commits that were never tested. Reviewed pull requests are easier for this purpose except when they're huge themselves. I wish git had an abstraction for squashes that could be treated like a commit but would still contain the commits that were there pre-squash. GitHub kind of is one, but yeah.

**Comment by toasted-nutbread** [comment]
> but some larger features will be a lot easier to understand when you keep the different parts where you first refactor the code and then add the new feature.

This is perhaps motivation to try to make as small and isolated PRs as possible. For example, #467 => #481 => #(not done). Various other things I've worked on recently have not been a complete feature (#406, #458, #483, etc.) and have relied on future commits to actually use it.

> Nice thing about squash is that if you are getting a contribution from a developer who does not have good discipline about writing descriptive commit messages (I am definitely guilty of this), you just end up getting a bunch of garbage in your history that just adds noise for anyone trying to get useful info out of it.

Not only that, but in a completely valid use of PRs, there will be feedback commits which may fix or tweak minor things that typically shouldn't be relevant when looking through the history. IMO it just adds noise. 

> I also think that it is nice to think about every commit in a project's history as a place you could go back to and reasonably expect to have things functional.

This is also a very strong argument for the workflow.

> Sounds good, I'm also curious to see how this works compared to the previous style.

I've made this switch on a few projects before, and I have been quite satisfied with it and have not had any major issues. Whenever it becomes necessary to dive into a specific PR commit with more granularity, the PR's branch can be checked out from the repository site.

> I wish git had an abstraction for squashes that could be treated like a commit but would still contain the commits that were there pre-squash.

That would be nice, but alas ¯\\_(ツ)\_/¯ 

---

Something like [this particular chain of changes](https://github.com/FooSoft/yomichan/compare/0e31139734efd51799efcb6357c074059c78858d...fdfc2d33bbcd32f2984e74bd58a518fcc50705d2
) is an example of something that I am primarily referring to. A lot of it is noise, and should really be considered a single PR commit. There are also other PR merges mixed in due to how github orders them.

This also kind of ties in to how/when commits are made to the master branch. I know @FooSoft mentioned that it's fine to do so, but for larger features, it's probably best to do changes as PRs, [even if they are trivial](https://github.com/FooSoft/yomichan/pull/466). All collaborators are already following this pattern, but I just want to point out that it might be good form even if there was only one developer, since it makes feature tracking easier by looking at the history. (The basic standalone changes like release commits and other ones @FooSoft has made recently are fine too.)

**Comment by siikamiika** [comment]
Did the first squash merge: https://github.com/FooSoft/yomichan/pull/464

Follow-up: should we edit the squash commit messages to include some of the discussion that's in the thread or just go with a list of commit messages?

> Something like [this particular chain of changes](https://github.com/FooSoft/yomichan/compare/0e31139734efd51799efcb6357c074059c78858d...fdfc2d33bbcd32f2984e74bd58a518fcc50705d2) is an example of something that I am primarily referring to. A lot of it is noise, and should really be considered a single PR commit. There are also other PR merges mixed in due to how github orders them.

I haven't looked into this much, but do you think this would solve the issue?
> I've also noticed that if you do a rebase locally and force push before a merge commit, the commit history seems to stay logical but not chronological. The merge commit will have a reference to the GitHub issue.

**Comment by siikamiika** [comment]
> This is perhaps motivation to try to make as small and isolated PRs as possible. For example, #467 => #481 => #(not done). Various other things I've worked on recently have not been a complete feature (#406, #458, #483, etc.) and have relied on future commits to actually use it.

I also hope this style will push me to plan the required steps for a feature better before opening a pull request. I think I've picked up some habits from this but there's still a lot to learn.

> This also kind of ties in to how/when commits are made to the master branch. I know @FooSoft mentioned that it's fine to do so, but for larger features, it's probably best to do changes as PRs, [even if they are trivial](https://github.com/FooSoft/yomichan/pull/466). All collaborators are already following this pattern, but I just want to point out that it might be good form even if there was only one developer, since it makes feature tracking easier by looking at the history. (The basic standalone changes like release commits and other ones @FooSoft has made recently are fine too.)

I think this could have probably been a single commit, but at least the PR notified me about it and I remembered something: https://github.com/FooSoft/yomichan/pull/449

**Comment by toasted-nutbread** [comment]
> I've also noticed that if you do a rebase locally and force push before a merge commit, the commit history seems to stay logical but not chronological. The merge commit will have a reference to the GitHub issue.

I actually was doing that at some point in this project, but then stopped. The main issue is that you lose information about what PR the commits correspond to (no merge commit with #XXX in the name), and it still has the issue of commit noise.

I don't think it even solved the chronology issue when looking at the commits in github. I have seen the issue in feature branches I've worked on where I have rebased and reordered commits. The timestamp on the commits is then out of order, but following the order of those changes is more logical. However, I think github will _sometimes_ display them in chronological order rather than parent-child order. I say "_sometimes_" because I think it may also depend on how much time was between the commits. Github likes to group commits by "these 4 commits were done on date XX, YY, ZZZZ", and the only way for that to work is to use the timestamp of the commit, rather than the true commit order. Hence the ordering issue that I have noticed.

**Comment by siikamiika** [comment]
> I actually was doing that at some point in this project, but then stopped. The main issue is that you lose information about what PR the commits correspond to (no merge commit with #XXX in the name), and it still has the issue of commit noise.

I think it should be there as long as you tell GitHub to do a merge commit after you've rebased (could be wrong), but I agree that this doesn't help with commit noise when you do lots of "fix X and Y". Those commits could probably be squashed within the PR though but that's confusing if done during review.

> I don't think it even solved the chronology issue when looking at the commits in github.

That's a shame, I guess it's better to avoid it then.

**Comment by toasted-nutbread** [comment]
> I think this could have probably been a single commit, but at least the PR notified me about it and I remembered something: #449

True; I guess in this case it adds a more easily visible venue for discussion, and also allows us to make sure CI passes (which I guess could be done locally too) before merging. Similar could be said for #474. And if it's something like a very obvious bug fix which needs a hotfix, I'm fine with skipping the review process if it takes too long due to nobody being available at the time, and just merge it in quickly.

**Comment by toasted-nutbread** [comment]
> Follow-up: should we edit the squash commit messages to include some of the discussion that's in the thread or just go with a list of commit messages?

Just the commit messages should be fine. If PRs contain details about potential future tasks, at some point they should just be extracted into new issues.

**Comment by toasted-nutbread** [comment]
Closing as this workflow is now being used.
