### ISSUE TITLE
Yomichan sometimes stops popping up(?) / "Search alphanumeric text"

### ISSUE THREAD

**Issue by sumirina** [FooSoft/yomichan#49]
Some info in advance: I'm using Firefox 53.0 with Yomichan 1.1.14 under Windows 10

Basically, I went through this process a few times:
1) I was getting annoyed at yomichan popping up on English text, 
2) I'd go into the options and uncheck "Search alphanumeric text"
3) yomichan would stop popping up AT ALL, 
4) I'd go into the options again to reenable the option, 
5) but yomichan still wouldn't show up at all
6) I'd live with that for the time being
--- later on
7) I'd restart firefox and yomichan would work again

This process repeated itself a few times as the "Search alphanumeric text" option was always checked when I restarted... Just recently I figured Yomichan works as I want it to if I have the option unchecked when I restart. Before making this issue I tried to reproduce the problem a few times and... I couldn't do it consistently. I was able to reproduce it once deliberately and then I couldn't anymore. I'm unsure if there are other reasons as well why yomichan could stop popping up (could that happen with other options as well?), but this is what I've done so far and what I'm aware of.

**Comment by FooSoft** [comment]
Thanks for the bug report. The Firefox specific issue was being caused by setting options, and then trying to use Yomichan after closing the options page (it doesn't matter what options were modified). I released version 1.1.15 which has the fix for this problem.
