### ISSUE TITLE
Autofill anki model in fields that have the same name as the marker

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#495]
![image](https://user-images.githubusercontent.com/24824399/80867034-91740580-8cc4-11ea-8b66-2d2e04b0602d.png)

This would save a lot of time, I'm not sure when the autofill should be triggered though.
Maybe whenever a new model is selected or manually with an autofill button.

**Comment by toasted-nutbread** [comment]
I suppose it's possible to do this, but it's not straightforward. You personally may have field names which match the Yomichan markers, but this is not necessarily the case for all users.

However, there is probably some heuristic methods that can be used to autofill some of the fields. For example, there is already a recommendation that the first field is `{expression}` or `{character}`. Additionally, there are some assumptions that could be made about some field names with common words. I.e. a field with "audio" or "sound" in the name is assigned to `{audio}`.
