### ISSUE TITLE
[bug] Words with furigana and okurigana cannot be detected

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#50]
Right now, yomichan has trouble detecting some words with furigana in ruby tags. When there is no okurigana, this seems to works fine. For example, <ruby>東京<rt>とうきょう</rt></ruby> can be detected. However, when there is okurigana, it does not work. For example, <ruby>起<rt>お</rt></ruby>きます cannot be detected.

EDIT: Apparently this happens whenever the entire word isn't together, not just with okurigana. For example, trying to put the furigana above specific kanji such as <ruby>漢<rt>かん</rt></ruby><ruby>字<rt>じ</rt></ruby> causes it not to be detectable by yomichan.

**Comment by seanblue** [comment]
This change does work, but it looks like there is a small oddity with the highlighting. Though if I recall correctly, I also saw this happen before this update, so it may be unrelated. Image attached:

---

![image](https://cloud.githubusercontent.com/assets/5884067/26280700/dc7cb76c-3dac-11e7-8a91-abd653c4a30a.png)

**Comment by FooSoft** [comment]
Try selecting 漢字 without じ in your example with your mouse. It's not possible to do because of the way the elements for the furigana are placed within the word itself.

**Comment by seanblue** [comment]
I see. I have seen other cases of entire paragraphs being highlighted. If I see that again, I'll be sure to open a separate bug for it.

**Comment by FooSoft** [comment]
Yeah, you should definitely not see entire paragraphs being highlighted, that would definitely be a bug.
