### ISSUE TITLE
Give platform specific names and icons to modifier keys

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#504]
- `event.shiftKey`: ⇧ Shift (universal)
- `event.metaKey`: ⊞ Windows (Windows); ⌘ Command (macOS); ◆ Super (Linux)
- `event.altKey`: ⎇ Alt (Windows, Linux); ⌥ Option (macOS)
- `event.ctrlKey`: ⎈ Ctrl (Windows, Linux); ⌃ Control (macOS)

Related: https://github.com/FooSoft/yomichan/pull/487, https://github.com/FooSoft/yomichan/pull/502, https://github.com/FooSoft/yomichan/issues/503

**Comment by siikamiika** [comment]
The Ctrl symbol ⎈ and Alt symbol ⎇ are a bit obscure, but they seem like the most "official" ones I can find.

**Comment by toasted-nutbread** [comment]
I would just go with the text names; most of the keyboard key selection inputs I've seen don't use any icons.

**Comment by siikamiika** [comment]
Ok, that's a less confusing option for sure except maybe for macOS users because they have all the symbols printed on their keyboards.

**Comment by toasted-nutbread** [comment]
I mean the Windows key doesn't literally say "Windows" on it, but I think people should generally understand what it is. Similar thing for OSs which are using a keyboard with icons for a different OS.

**Comment by siikamiika** [comment]
Some examples from Firefox addon keyboard shortcuts:

Windows:
![firefox_L2ewoItiS3](https://user-images.githubusercontent.com/5602483/80924614-98694980-8d92-11ea-8b0d-bf392012f436.png)

macOS:
<img width="610" alt="Screen Shot 2020-05-03 at 22 59 18" src="https://user-images.githubusercontent.com/5602483/80924504-02cdba00-8d92-11ea-8fd4-ed816f73899e.png">

Linux:
![2020-05-03_22-58-24](https://user-images.githubusercontent.com/5602483/80924507-0a8d5e80-8d92-11ea-9bee-f252dd6d3dc4.png)

It seems that Windows and Linux use the same way to show the keys, but macOS uses the icons. I don't use mac enough to know how common this is, but could be worth checking Chrome at least (don't have it installed now).

> I mean the Windows key doesn't literally say "Windows" on it, but I think people should generally understand what it is. Similar thing for OSs which are using a keyboard with icons for a different OS.

Yeah Windows is so common that almost all keyboards except some enthusiast ones or mac specific ones use the Windows logo to represent the Windows key. Mine has it too. I think it's best to go by the OS convention, and I brought up this issue because I'm sure "Meta" will sound weird to many. I'm fine with text names only even for macOS if that's a convention in addition to the symbols.

**Comment by siikamiika** [comment]
Something I found along with a picture of key remapping on macOS: https://www.nngroup.com/articles/ui-copy/

Could be useful for https://github.com/FooSoft/yomichan/issues/465.
