### ISSUE TITLE
[request] Group furigana with their respective kanji

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#51]
Currently you are displaying furigana across the entire word like <ruby>漢字<rt>かんじ</rt></ruby>.
If possible, it would be better to display them like <ruby>漢<rt>かん</rt></ruby><ruby>字<rt>じ</rt></ruby>, where it's clear which furigana belong with each kanji. Related to that, okurigana probably shouldn't get furigana. This is very obvious with the work 必ずしも.
The popover currently shows <ruby>必ずしも<rt>かならずしも</rt></ruby>.
Instead, it should probably show <ruby>必<rt>かなら</rt>ずしも</ruby>.

I know this may not be possible depending on what the data you get looks like, but I figured I'd put in the request it case it was possible.

**Comment by FooSoft** [comment]
Good idea, but we will also have to figure out what to do for ateji (like 美味しい).

**Comment by seanblue** [comment]
美味しい doesn't seem to be ateji, and for whatever reason it is done like this on jisho.org: <ruby>美<rt>おい</rt>味しい</ruby>. Maybe that is just the proper way for that word, but I have no idea.
Here are some that are ateji:
<ruby>寿司<rt>すし</rt></ruby>
<ruby>布団<rt>ふとん</rt></ruby>
<ruby>可愛<rt>かわい</rt>い</ruby>

They all seem to have the furigana across the entire word's kanji, but still not the okurigana. I'm not sure why jisho.org does it that way and I don't know if that is standard or just what they did.

**Comment by erasedff** [comment]
I have a semi-related issue with the scan logic. If you try to scan the first 漢字 from the OP, it scans normally, but for a second 漢字 scan breaks down and displays each word separately. Or try scanning 可愛い from the post above for example (the kanji, not furigana).
This is extremely annoying and borderline unusable on imabi.net for example. 
Rikaichan in Firefox doesn't have any issues with it and properly scans kanji with furigana.

**Comment by seanblue** [comment]
@erasedff I already opened an issue for this as well. See #50

**Comment by FooSoft** [comment]
@erasedff the issue that you mentioned has been fixed in 1.1.16

**Comment by FooSoft** [comment]
Fixed in 1.3.4
