### ISSUE TITLE
forum.koohii.com no more

### ISSUE THREAD

**Issue by zdzislaw-s** [FooSoft/yomichan#543]
Hi Guys, just a heads up issue.

You seem to have some links to forum.koohii.com in your files (I've just seen one in README.md, 
https://forum.koohii.com/post-168613.html#pid168613) but the sad news is that forum.koohii.com has been closed down by Fabrice [some year ago](https://kanji.koohii.com/news/id/372).

The fact of the closure saddens me muchly, :cry:

**Comment by toasted-nutbread** [comment]
I noticed this a while ago as well. I have an eventual task of doing some revisions to the README file to update links, grammar, descriptions, etc. at some point, and I'll likely address this issue as part of that.

Thanks for the heads up; you can leave this issue open if you like and I'll close it once I do the revisions.

**Comment by toasted-nutbread** [comment]
Archive URL:
https://web.archive.org/web/20190309073023/https://forum.koohii.com/thread-9459.html#pid168613

**Comment by zdzislaw-s** [comment]
素晴らしいよ。:+1:
