### ISSUE TITLE
Select from multiple audio URLs

### ISSUE THREAD

**Issue by Rapptz** [FooSoft/yomichan#544]
Yomichan has the ability to allow users to set a custom audio source which allows them to retrieve audio. I've written one for [Forvo](https://forvo.com/). However, the very nature of the site being made up of amateur users who want to help each other means that at times there are many results that show up, for example [this word](https://forvo.com/word/なるほど/#ja) has multiple results and a user might be inclined to pick a specific one that suits their needs (best pronunciation, matching gender, etc.).

While this is easy to implement from the custom audio source, making Yomichan use it is another matter. Since Yomichan requires you to send only one audio without allowing the user to preview them it makes it hard to know which audio is the best one to use.

It would be nice if the server could return a JSON array comprised of some metadata like so:

```js
[
  {
    "author": "strawberrybrown",
    "url": "https://audio00.forvo.com/mp3/9478059/76/9478059_76_1424232.mp3",
    "filename": "yomichan_\u306a\u308b\u307b\u3069_3613655_strawberrybrown.mp3"
  },
  {
    "author": "Jun_Japan",
    "url": "https://audio00.forvo.com/mp3/9129797/76/9129797_76_1424232_1.mp3",
    "filename": "yomichan_\u306a\u308b\u307b\u3069_1170320_Jun_Japan.mp3"
  },
  {
    "author": "kaoring",
    "url": "https://audio00.forvo.com/mp3/9221075/76/9221075_76_1424232.mp3",
    "filename": "yomichan_\u306a\u308b\u307b\u3069_3617248_kaoring.mp3"
  },
  {
    "author": "Junchan",
    "url": "https://audio00.forvo.com/mp3/9233170/76/9233170_76_1424232_1217591.mp3",
    "filename": "yomichan_\u306a\u308b\u307b\u3069_1801927_Junchan.mp3"
  },
  {
    "author": "hardstone",
    "url": "https://audio00.forvo.com/mp3/9461106/76/9461106_76_1424232.mp3",
    "filename": "yomichan_\u306a\u308b\u307b\u3069_4051131_hardstone.mp3"
  }
]
```

Which would allow for the user to select a specific audio with an author for display purposes along with the resulting filename that Yomichan would use when generating the audio file on the anki side.

Unfortunately such a request requires a bit too many moving parts and some UI design. I'm not too familiar with the code base to do it myself but I hope the idea proposed here at least sounds interesting enough to tackle.

**Comment by siikamiika** [comment]
If this was the only use case, I'd go with a server between Forvo and Yomichan in localhost that spawned popups asking which audio to play, but there's also another when you have result grouping by main dictionary and add cards with `{audio}`. Not exactly the same issue, but the UI code could be reused.

**Comment by weirdalsuperfan** [comment]
How do you even designate a custom URL??? All I see is a dropdown menu where you can select "Custom," but I have no idea what to do after that, and this has bothered me for a year. Is my extension just broken?? Because I thought I was able to specify this before on a different computer...

**Comment by weirdalsuperfan** [comment]
@Rapptz Can you share the URL scheme you made for forvo?

**Comment by Rapptz** [comment]
> @Rapptz Can you share the URL scheme you made for forvo?

It's a closed source custom server I wrote that runs locally on the computer.

**Comment by weirdalsuperfan** [comment]
Well then, nevermind. So much for a custom audio source for Forvo.
