### ISSUE TITLE
Unclear sentence and a broken link in the FAQ

### ISSUE THREAD

**Issue by snoyes** [FooSoft/yomichan#546]
https://github.com/FooSoft/yomichan/blame/master/README.md#L290-L292

> the number field of templates

I imagine this is supposed to be one of:

- the number of field templates
- the number of fields
- the number of templates

but I don't know which.

Further, the link `<a href="dl/fields.txt">` leads to a 404, at least here on GitHub. Perhaps you'd like to add the file to GitHub, or change the link to point to the file at foosoft.net?

**Comment by toasted-nutbread** [comment]
> I imagine this is supposed to be one of:

Probably `the number of field templates`

> Further, the link `<a href="dl/fields.txt">` leads to a 404, at least here on GitHub. Perhaps you'd like to add the file to GitHub, or change the link to point to the file at foosoft.net?

I think the reason why it's not added to the repository is probably to avoid having to maintain it. Some of the new changes have definitely not been added to that file. I don't know how relevant that section is these days either. The easiest solution would be to change the URL to https://foosoft.net/projects/yomichan/dl/fields.txt, but maybe it can be removed altogether.
