### ISSUE TITLE
[feature request] Highlight Known Words

### ISSUE THREAD

**Issue by Pcsl** [FooSoft/yomichan#55]
Why don't you add a feature to highlight known words? Something like this [Chrome add-on](https://chrome.google.com/webstore/detail/highlight-known-chinese-w/gbpllapimjcpljegefoblbmjdaoahglm) would help us a lot when reading websites. I have a list of words that I am supposed to know and I like to check if I remember them on real context so if you add a feature like this that could toggle highlight on words we are supposed to know, it would save us a lot of time so we could focus on words we don't know or that we know depending on we what to review words or add words we don't know.

So please consider adding this feature.
Thanks!

**Comment by Pcsl** [comment]
@FooSoft Did you have time to check this? Thanks!

**Comment by FooSoft** [comment]
Hey Pcsl, I agree that this would be a pretty useful feature to have (and it has been suggested in the past), but I don't know about a meaningful way to implement it at this time. The problem lies in the fact that there are no spaces in Japanese, so there is no way to definitively parse text into its components. 

For example, ねこ: is it 猫 or 根 followed by 子? etc.

**Comment by Pcsl** [comment]
> Hey Pcsl, I agree that this would be a pretty useful feature to have (and it has been suggested in the past), but I don't know about a meaningful way to implement it at this time. The problem lies in the fact that there are no spaces in Japanese, so there is no way to definitively parse text into its components.
For example, ねこ: is it 猫 or 根 followed by 子? etc.

I think we are speaking about something a little bit different. Let me explain it better using an example. At this moment I am using an add-on called [Multi-highlight](https://chrome.google.com/webstore/detail/multi-highlight/pfgfgjlejbbpfmcfjhdmikihihddeeji). As you can see on the attached screenshot I added a list of words I am supposed to know and the add-on highlights them. The issue with that add-on is that it can't highlight inflected form such as verbs, adjectives...
![Yahoo screenshot](http://i.imgur.com/hzC4Wsu.png "Yahoo screenshot with Multi-highlight")

Anyway I can understand that problem to parse them but please if you find a workaround consider adding it as many people would find it useful.

**Comment by HelenFoster** [comment]
Why should this be a Yomichan feature, and not a separate Chrome extension? There doesn't seem to be much overlap really.

**Comment by Pcsl** [comment]
There isn't so much overlap but there is some as it helps you to view easily the unknown words (those that are not highlighted) so you can add them easily to Anki.

**Comment by FooSoft** [comment]
Closing since this is out of scope. Would make a good addon though.
