### ISSUE TITLE
Chrome Web Store policy update regarding "repetitive" extensions

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#557]
FYI @FooSoft: Google has apparently set up some new policies regarding extensions on their storefront which may affect Yomichan, since it has both a testing release and a stable release. It appears to still be permitted to have a test and production version, so long as it is clearly indicated.

> * Developers or their affiliates should not publish multiple extensions that provide duplicate experiences or functionality on the Chrome Web Store. 
>
> ...
>
> Developers must comply with this policy by August 27th 2020. After that date, extensions that violate the updated policy may be taken down and disabled.

> The description of any non-production variants should include the URL of the production variant, so that users can find it.

https://blog.chromium.org/2020/04/keeping-spam-off-chrome-web-store.html
https://developer.chrome.com/webstore/program_policies#spam
https://developer.chrome.com/webstore/spam-faq (See **Can I have both a test version and a production version of my extension?** section)

**Comment by FooSoft** [comment]
Thanks for catching this. Sounds like "testing" is fine, but I will update the wording to exactly match the FAQ to make extra sure that we are covered.
