### ISSUE TITLE
[request] Order of senses in JMDict

### ISSUE THREAD

**Issue by HelenFoster** [FooSoft/yomichan#57]
Hi, I brought this up on the forum a while back, but it's well buried now. I wasn't sure if you really didn't agree, or if I just hadn't explained well enough. (Also I don't really know how it works, so it's possble this should be a yomichan-import ticket instead.)

In JMDict, the order of &lt;sense&gt; tags within an entry is significant, with the most important senses placed first. I think Yomichan should respect this order.

Especially in Anki, I'm just going to glance at the definition most of the time, and having the most useful senses hidden down the bottom is not very helpful.

Using Yomichan 1.1.18. I purged my dictionaries and re-imported today.
On the forum, I mentioned 宜しく, but that seems to be correct now.
手 - first in JMDict is "hand, arm" but Yomichan gives "forepaw, foreleg".
隙間 - first in JMDict is "crevice, crack..." but Yomichan gives "chink (in ones armor)...".
かじる (噛る) - first in JMDict is "to chew..." but Yomichan gives "to dabble in..." - strangely, looking up the kanji form does show "to chew" first.

**Comment by HelenFoster** [comment]
On the forum, you said "I'm sorting the senses based on tags (for example items marked 'P' go on top)". The problem is that senses don't carry priority tags such as 'P' (those tags go into &lt;keb&gt; and &lt;reb&gt;), so all the senses in an entry effectively have the same priority tags.

It would make sense to sort entries based on priority tags. E.g. I would expect かじる (噛る) to come before かじる (齧る) - and it doesn't, but that's a different issue.

**Comment by FooSoft** [comment]
I'm doing some work now on updating dictionary formats, so this should be fixed for the next release.

**Comment by FooSoft** [comment]
Had a bunch of big changes for current release, so punting till next :+1:

**Comment by seanblue** [comment]
Any update on this one?

**Comment by FooSoft** [comment]
Next version for sure :smirk:

**Comment by FooSoft** [comment]
So yay, I got around to fixing this! The fix was made to `yomichan-import` and not the extension itself, so there is no new version associated with this fix. Just go to the Yomichan homepage and download the new EDICT dictionary and you should be set. Reopen this issue if there are still problems (there shouldn't be any though).
