### ISSUE TITLE
Error: Message length exceeded maximum allowed length.

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/yomichan#586]
I get that message when I try to import 広辞苑第六版 • 付属資料 dictionary
How can I fix that?

**Comment by toasted-nutbread** [comment]
This seems to be due to an undocumented limit on the size of messages that Chrome extensions can use to communicate. There doesn't appear to be an easy workaround in the current release, so I'll try to implement a fix.

**Comment by Geniusssmit** [comment]
Thanks, looking forward to it!

**Comment by toasted-nutbread** [comment]
@FooSoft I have pushed the change from #587 into a hotfix release, [20.5.22.1](https://github.com/FooSoft/yomichan/commits/20.5.22.1).
