### ISSUE TITLE
Options view does not show state in Firefox Nightly

### ISSUE THREAD

**Issue by SimonPilkington** [FooSoft/yomichan#589]
I noticed this while investigating #588. On first opening the options, the view will be empty. I must click the Yomichan button for the view to actually show the current state.

**Comment by siikamiika** [comment]
Ooh, missed this. That's interesting. I might have an idea what's causing this.

**Comment by siikamiika** [comment]
I was able to make the options show up immediately when I added `chrome.runtime.sendMessage(data, callback)` to https://github.com/FooSoft/yomichan/blob/2c58b1c1091355e5e4f2a2c20d96051863549b8d/ext/bg/js/backend.js#L446 so probably there's an issue in Firefox that prevents `chrome.tabs.sendMessage` from working correctly. Tried adding `tabs` to permissions, but didn't help.

**Comment by SimonPilkington** [comment]
Could I bother you to report this to Mozilla? I am not an add-on developer so my report will almost certainly be inferior to yours.

**Comment by siikamiika** [comment]
I can do that on their Matrix server or bugzilla later, but I think it should be enough for them to know how to reproduce it (install Yomichan and go to Options), and that `chrome.tabs.sendMessage` behaves weirdly. It would probably help them if the issue was reduced to a minimal test case though.

**Comment by toasted-nutbread** [comment]
The issue is also detectable by checking if `chrome.runtime.lastError` has a message of `"Could not establish connection. Receiving end does not exist."` in the `chrome.tabs.sendMessage` callback.

**Comment by SimonPilkington** [comment]
Fixed by  https://bugzilla.mozilla.org/show_bug.cgi?id=1642967.
