### ISSUE TITLE
Yomichan doesn't work on plain HTML files

### ISSUE THREAD

**Issue by plusfuture** [FooSoft/yomichan#59]
As title. I've attached the sample I'm using. I had a clever idea (at least I thought so) to add some basic HTML tags to text files so I could use the updated plugin instead of the one for Anki. But it doesn't seem to work... is this a fixable problem? Is it even a bug?

I'm using Chrome v58 64-bit and the latest Chrome store version of Yomichan.

**Steps to reproduce:**

1. Open attached HTML file.
2. Try to press shift and observe that nothing occurs.
3. Try to press the middle mouse button and get the four-direction scroll function instead of highlighting text.

[japanese_sample.zip](https://github.com/FooSoft/yomichan/files/1096563/japanese_sample.zip)

**Comment by FooSoft** [comment]
Works for me. Did you enable local file access support in chrome://extensions ?

**Comment by plusfuture** [comment]
Didn't catch that. Thanks for the tip.

**Comment by FooSoft** [comment]
Glad you got it working :+1:
