### ISSUE TITLE
Support for custom frequency list per profile

### ISSUE THREAD

**Issue by Cupbox** [FooSoft/yomichan#593]
Hi. 
Support for files from analysis tools like [Japanese Text Analysis Tool](https://sourceforge.net/projects/japanesetextana/) and their assignment to specific profiles would be appreciated. 
Rationale
Per novel text analysis would allow the user to more intelligently mine cards. Assigning them per profile would be useful in case the user is reading multiple novels.

**Comment by toasted-nutbread** [comment]
This is technically already supported, albeit maybe not the exact file format that the tool exports. Dictionaries can be enabled on a per-profile basis, and frequency dictionaries are supported. The only missing piece would be a tool to convert Japanese Text Analysis Tool's output format to Yomichan's dictionary format. That conversion is probably outside the scope of what the Yomichan extension should be doing, but depending on what the format JTAT exports to, it's probably easy to make a converter.

**Comment by Cupbox** [comment]
Here's the format JTAT outputs
● Format of Word Frequency Report:
    Field 1: Number of times word was encountered
    Field 2: Word
    Field 3: Frequency Group
    Field 4: Frequency Rank
    Field 5: Percentage (Field 1 / Total number of words)
    Field 6: Cumulative percentage
    Field 7: Part-of-speech
Here's a sample file
[word_freq_report.txt](https://github.com/FooSoft/yomichan/files/4743682/word_freq_report.txt)

**Comment by toasted-nutbread** [comment]
Here is a conversion script.
https://github.com/toasted-nutbread/jtat-to-yomichan-frequency-dictionary

**Comment by Cupbox** [comment]
Working perfectly on my end. Thank you for working on this.

**Comment by CrAZONE0** [comment]
@toasted-nutbread 
How can I create a yomichan frequency dictionary with a different format?
It's pretty simply, there's an ordered list of vocab and nothing else. Something like:

```
は
の
が
私
僕
俺
```

**Comment by toasted-nutbread** [comment]
You would have to convert it to the format Yomichan expects, which is a fairly simple JSON format. Check the [schema files](https://github.com/FooSoft/yomichan/tree/master/ext/data/schemas) for details and/or just extract and reference an existing frequency dictionary to see how it's set up.
