### ISSUE TITLE
Database not initialized google chrome

### ISSUE THREAD

**Issue by 1nderian** [FooSoft/yomichan#598]
Since yesterday I am not able to use yomichan anymore, which is probably due to the error under the dictionary section stating "Database not initialized". I am not very technical so if I am asking something that is easy to solve or an obvious mistake from my side, then you have my apologies in advance.

**Comment by 1nderian** [comment]
Excuse me for the tardiness in my reply.
* I'm on version 20.5.22.1
* Yes I'm seeing the icon with the two exclamation marks.
* Here is the information from the "Console" tab:
Unchecked runtime.lastError: No current window
background.html:1 A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
background.html:1 A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
core.js:422 Yomichan v20.5.22.1 has encountered a problem.
Originating URL: chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/bg/settings.html
Error: Dictionary is already imported
    at DictionaryImporter.import (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/bg/js/dictionary-importer.js:64:19)
    at async Backend._onApiImportDictionaryArchive (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/bg/js/backend.js:782:16)
    at async onMessageComplete (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/bg/js/backend.js:860:40)

Issues can be reported at https://github.com/FooSoft/yomichan/issues
log @ core.js:422

Thank you in again for your help!

**Comment by toasted-nutbread** [comment]
Are you still seeing the "Database not initialized" message when you see that log message? It looks like it's logging "Dictionary is already imported" now.

You can also try completely removing the extension and reinstalling it + the dictionaries and see if that helps any.

**Comment by 1nderian** [comment]
Reinstalling the extension as well as the dictionaries seems to have worked! Thank you for the help!

**Comment by toasted-nutbread** [comment]
Sure thing. It's unclear why your issue was happening; the only reason I know of that the "Database not initialized" error would occur is due to rolling back versions, which doesn't seem to be what happened to you. In case that error ever occurs again in the future, I have made an update to make the dictionary database able to be deleted even if it has an error (#600). This fix will be available in a future version, and that way you won't have to lose all of your settings by reinstalling if the database breaks.
