### ISSUE TITLE
{furigana-brackets} for Anki Japanese Support Plugin

### ISSUE THREAD

**Issue by Profpatsch** [FooSoft/yomichan#60]
The Anki [Japanese Support Plugin](https://ankiweb.net/shared/info/3918629684) uses a syntax with brackets to populate the `Reading` field, e.g. `昨日[きのう]すき 焼[や]きを 食[た]べました` where furigana in brackets follow consecutive kanji (or kanji belonging to single words, haven’t figured that out yet).
It looks like AnkiDroid also supports correctly rendering these `Reading` fields.

It would be nice if yomichan could support directly rendering this syntax, e.g. by introducing a `{furigana-brackets}` template.

**Comment by FooSoft** [comment]
This is similar to #51 in that it has the problem of requiring knowledge of which part of the reading corresponds to which Kanji. The dictionaries I use don't have this information (I just have the Kanji expression + combined reading). It could conceivably be possible to try to get at this information, by looking up readings for individual characters and trying to match them up to the reading as a whole... I would need to figure out some sort of accurate way of doing this.

**Comment by kmltml** [comment]
I implemented an algorithm doing that based on just the word and it's reading in kana for my fork of chiitrans (https://github.com/kmltml/chiitrans/commit/416175fdc34a22a4fdc614d410c26ed8dc8dd4c9), and would be happy to port it here, would you accept this kind of solution @FooSoft ? If so i could use a few pointers on where this would go.

**Comment by FooSoft** [comment]
@kmltml how does your algorithm deal with words with readings which do not correspond to that of the Kanji (for example terms  like 美味しい). Also, does it handle changes in reading based on character position (such as 時々 (toki**d**oki) or 合併 (ga**p**ei))? If it is robust enough to handle such cases it would be awesome to get it hooked up into Yomichan.

**Comment by kmltml** [comment]
@FooSoft My solution just looks at a word in kanji form and it's reading in kana. It then splits the word into kanji clusters and kana clusters and tries to distribute kana so that the kana clusters match. So for example in 美味しい it splits it up into [美味][しい] and then, sees, that for the [しい] part to match [美味] has to get [おい] as furigana. I think it should work in most cases, though some could be ambigous. Only 物の怪 comes to mind, which could be either 物[も]の 怪[のけ] or (correctly) 物[もの]の 怪[け].
Also, if i were to start working on that, should i branch off of dev, or master?

**Comment by FooSoft** [comment]
You should branch off of `master`. Normally you would do it off of `dev` but it's kind of a mess right now since I'm doing a fairly large overhaul. If you create a member class for the `Translator` object, things should be fairly easy to adapt when `dev` is merged into `master`.

**Comment by FooSoft** [comment]
Fixed in 1.3.4, use the new `{furigana-plain}` marker.
