### ISSUE TITLE
Anki integration stopped working

### ISSUE THREAD

**Issue by sirati97** [FooSoft/yomichan#613]
I recently updated anki and ankiconnect and now yomichan does not connect anymore and gives me the following error:

requestText/</<@moz-extension://bb9830c5-dfa6-4203-b47c-0c24b6a6bfc0/bg/js/request.js:24:52

**Comment by toasted-nutbread** [comment]
* Open Anki and then open http://127.0.0.1:8765/, check if it shows some text saying `AnkiConnect v.6`.
* Open Yomichan's settings page, enable "Show advanced options", and then check what the value of the "Interface server" setting is (under the Anki Options heading).

Share what you see for those two.

**Comment by sirati97** [comment]
idk what the issue was, it fixed itself. even though i had the same problem multiple times before. shrug
