### ISSUE TITLE
Text-to-speech issue

### ISSUE THREAD

**Issue by grospoulpe** [FooSoft/yomichan#616]
Hi,
I don't know if it is related to a chrome update or something, but, only Text-to-speech sources (Google text to speech) seems to work, now (it worked before)

If I try both Japanesepod or Jisho.org, I have no sound (bu I have with Google Text to speech voice)
Chrome : Version 83.0.4103.106 (Official Build) (64-bit)
Yomichan v20.5.22.1

Thanks for you help!

Have a nice day.

Here two configuration (one which is working with google because I remove the other sources)
[yomichan settings.zip](https://github.com/FooSoft/yomichan/files/4807581/yomichan.settings.zip)

**Comment by toasted-nutbread** [comment]
Check the "Audio playback volume" option; the value is set to 200. You are getting an error because the browser doesn't like the value being outside the range of [0, 100]. I will implement a safe-guard to limit the value if it's out of range.

**Comment by grospoulpe** [comment]
OK, thank you for your answer (I messed up with the volume level but: I usually use chrome extension like Volume Booster (some pronunciations have pretty low volume, especially with Jisho.org; meanwhile some words like 市外局番 were only speak using text-to-speech/google, but the volume is not modified by that extension (the extension works with the other sources like JapanesePod/Jisho)
Anyway, meanwhile, I rebooted my PC (+CCleaner), and now the Audio Option works again :) )
Thanks again for you answer! :)

**Comment by toasted-nutbread** [comment]
Text-to-speech audio is generated using a different method than the other audio methods, so it's not surprising that Volume Booster doesn't work for that. And as far as I can tell in my testing, trying to set Yomichan's volume above 100% won't affect how Volume Booster works.

Thanks for finding and reporting the issue; the out-of-range volume issue will be fixed in the next release.
