### ISSUE TITLE
[Bug] No Audio

### ISSUE THREAD

**Issue by JohnIngles** [FooSoft/yomichan#62]
The playback feature is not working.  I tried turning both my system's audio and the extension's audio up but I still get no sound.  Do I need to download audio files?  I can hear the click on the less common words but the common words have no sound at all even though the little animation plays to indicate a playback.

**Comment by FooSoft** [comment]
Can you let me know if you are using Firefox or Chrome, and what operating system you are on? 

I just tried it and the sound works for me. This may sound like a stupid question, but do you have a reliable internet connection? The audio files are downloaded on demand (when you click on the audio links), and will not play if you are not connected to the internet. You can also try switching the audio source from JPOD101 to JPOD101 Alternate.

**Comment by JohnIngles** [comment]
Yeah, I'm on Firefox and windows 7 and my internet is never down.  There is a delay when I click a specific word for the first time before the short spinning animation, which I guess is the clip being downloaded.  It seems to be getting downloaded and played but it isn't audible.

**Comment by JohnIngles** [comment]
I resolved the issue.  I realized that NoScript was blocking the downloads.

**Comment by FooSoft** [comment]
Thanks for the heads up about what was causing it -- I didn't even consider that another extension could be breaking audio.
