### ISSUE TITLE
{glossary} without tags?

### ISSUE THREAD

**Issue by dequis** [FooSoft/yomichan#64]
Hey, thanks for yomichan. Is there any tag to have the definitions for a word without adding the tags like "(P, ichi, news, v1, vt, JMDICT (English))" before it?

My anki card template has a huge font so it's a bit uncomfortable to have both in the same field.

![screen](https://user-images.githubusercontent.com/94108/28035753-16ded2c6-658c-11e7-9d40-c0b432d02b7d.png)

If there's no such thing, I'd like to try implementing it myself (sounds reasonably easy), and would appreciate some directions on how you would prefer to have it done.

**Comment by FooSoft** [comment]
This makes sense to me. This is something that is reasonably easy to hook up. You will want to:
1. Update the card field templates: `tmpl/fields.html`
2. Regenerate `ext/bg/js/templates.js` using Handlebars
3. Update `ext/bg/js/options.js` to include `glossary-brief` (or whatever you want to call it) to the dropdown menu.
4. Update `README.md` with description of your new marker.

**Comment by FooSoft** [comment]
Fixed

**Comment by makosear** [comment]
This solution looks outdated. Is there any way to do that still? 
![image](https://user-images.githubusercontent.com/80222853/110254107-7caf7080-7f6c-11eb-8251-e24a81b3e387.png)

**Comment by toasted-nutbread** [comment]
Modify the Anki field templates, remove these lines from the `glossary-single` definition:

https://github.com/FooSoft/yomichan/blob/7793e14e57639426cb9ca64c82004151f9eaba05/ext/data/templates/default-anki-field-templates.handlebars#L3-L20

**Comment by toasted-nutbread** [comment]
However, I am still seeing that `{glossary-brief}` works.
