### ISSUE TITLE
[Question / Feature Request?] Native window for mouseover text

### ISSUE THREAD

**Issue by 4a** [FooSoft/yomichan#664]
Apologies in advance if this is a duplicate question.

I think yomichan's native window feature for text added to the clipboard is great. Is it possible to have the native window show up for mouseover text?

**Comment by toasted-nutbread** [comment]
It's probably doable, but may have some odd edge cases, such as popup nesting. Do you want the native window to be positioned just like the embedded popup? Or just open a window anywhere, and update content on scanning without updating position?

**Comment by 4a** [comment]
In my head I was imagining it like the second option, where the window has a static position. One of the things I love about the native window is I can just have it on a second monitor and not have the popup block any of the text in the browser. Thanks for the reply!
