### ISSUE TITLE
The red "off" part of the icon looks too much like a pending notification

### ISSUE THREAD

**Issue by dequis** [FooSoft/yomichan#67]
I also had the terrible idea of placing it in the toolbar right next to where the facebook notifications are  (well, it was a coincidence)

![scrot](https://user-images.githubusercontent.com/94108/28702350-b508c5ca-7332-11e7-82bf-d428cc40ed36.png)

Regardless of the position that's some attention-grabbing red for a default state.

**Comment by FooSoft** [comment]
"Off" is actually not the default state -- you have the extension installed but it is not being used; this is meant to be an exceptional case.

**Comment by dequis** [comment]
Well, the thing is that I still haven't gotten rid of rikaichan while it works, and I'm trying to imitate the rikaichan experience as closely as possible. Aside from things that need code changes that I'll bring up later, setting "scan modifier key" to none and just hovering over words without using the keyboard is one important part of it. So I really prefer having it as a toggleable thing that is off most of the time.

**Comment by dequis** [comment]
Suggestion:

![states](https://user-images.githubusercontent.com/94108/29053928-521e131c-7bc9-11e7-8620-b361f61d2624.gif)

(https://github.com/dequis/yomichan/commit/dc91c9e94fa1a3e7d5de8ec9368a4b52ac4f6c9f)

**Comment by FooSoft** [comment]
I'm fine with switching the color to gray, that is an easy change.

**Comment by dequis** [comment]
Thanks!
