### ISSUE TITLE
JapanesePod101 Audio Broken?

### ISSUE THREAD

**Issue by Rahey94** [FooSoft/yomichan#675]
Hi,

A couple hours ago, I noticed that audio from JapanesePod101 no longer works in Yomichan. If I hover over a word and click the speaker button, instead of audio I just get the clicking sound. This happens for even the simplest of words.

However, if I switch the audio to Jisho.org (under Audio playback sources in the Yomichan settings) the audio playback does work. To summarize:

JapanesePod101: Audio doesn't work, just the clicking sound
JapanesePod101 (Alternate): Audio doesn't work, just the clicking sound
Jisho.org: Audio works
Text-to-speech: Audio doesn't work, just the clicking sound
Text-to-speech (custom): Audio doesn't work, just a clicking sound

I'm not sure if this is an issue with Yomichan or JapanesePod101, but I thought I would bring up the issue just in case. 

Thanks for your help.

**Comment by arbieo** [comment]
Ah, looks like we posted at the same time. I opened an issue with some more info and local workarounds here:
https://github.com/FooSoft/yomichan/issues/676

Note for text to speech you need to configure a specific provider.

**Comment by Rahey94** [comment]
Ah, thank you for this! It's good to know it's not just me. It seems like there's not a great fix around right now, hopefully this gets fixed soon since like you said in your Jisho's audio library is tiny compared to JapanesePod101's.

I also didn't know that about text-to-speech, thanks for the information.
