### ISSUE TITLE
Japanpod101 audio currently non-functional due to cert issue, manifests as missing audio

### ISSUE THREAD

**Issue by arbieo** [FooSoft/yomichan#676]
So, this isn't an issue with Yomichan directly but I'm putting this here in part because others experiencing this problem are going to look here. 

Seems like JapanesePod allowed their cert to expire. Reproducible here: 

https://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kanji=%E8%8A%B1%E7%81%AB&kana=%E3%81%AF%E3%81%AA%E3%81%B3

(expected behaviour at time of writing this is cert warning)

Three local work arounds exist. 

1. You can disable the cert check for JapanesePod101 however I'm not going to provide detailed instructions for this as there are security concerns and I don't really want to enable people to do this without knowing the possible side effects.
2. Set your computer clock back. Cert expired about 2 hours earlier than this post. If you set your computer clock back before this time it should begin to function again.
3. Enable other audio sources in Yomichan settings. Note that these libraries are currently much smaller.

As for handling this from the side of Yomichan, i'm not sure. However it might be good to handle the case of a permanent or technical failure different from the case where the audio is not present.

**Comment by toasted-nutbread** [comment]
JPod really needs to get it together, this seems to happen every few months.
#180, #280, #471

**Comment by arbieo** [comment]
It's resolved now but... I checked and they only renewed for 2 months.... Seems like a fairly poor life choice.

Next tentative date for them to break the audio integration is October 18th (Japan time). That is when the current cert expires.

Maybe we need a retry on http:// if and only if  encountering a cert failure? All http:// all the time is a really bad idea not only for security but also because internet providers will often intercept random web requests with webpages for sign-ins or data usage warnings. So that's not a valid option even discounting the security concerns.

**Comment by arbieo** [comment]
Quick bump as this is due to break again in under 7 days. (October 18 5:30 AM JST)

Maybe the best resolution is to email jpod101? To make sure their cert doesn't expire. ahaha.

**Comment by kuri7** [comment]
I am already having this issue as pretty much every single word doesn't give me audio right now. Did someone end up emailing them?

**Comment by arbieo** [comment]
@kuri7 if you are having audio issues right now it is likely unrelated as the cert is still valid (and has even been updated to January 10th!)

I'm gonna close this for now under the assumption that jpod101 has their shit together for now.

**Comment by toasted-nutbread** [comment]
Even if it happens again in the future, I'm not sure if it's something that Yomichan should even worry about handling, seeing as how infrequent it is, and how it's a server-error anyways.

**Comment by arbieo** [comment]
Yeah, I respect that. But at the end of the day from an end user perspective it's still a poor experience. The actionable item from yomichan's perspective is better handling of the error case as this error (or any error) is indistinguishable from missing audio. But if Jpod can keep this down to at most once a year it's probably not worth the time.
