### ISSUE TITLE
[bug] Audio is not working

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#68]
For the past 2-3 days, the audio has not been working. It doesn't even make that clicking sound that happens when audio can't be found. Sound works for other things on my computer, and I double checked that the extension settings have the audio playback source and volume set correctly. Also, the backup source for JapanesePod101 doesn't work either.

**Comment by FooSoft** [comment]
The JPOD101 file server used to host audio is currently down. This means that it doesn't work for anyone else who is using these MP3s, including JPOD101 itself.

**Comment by seanblue** [comment]
Okay, thanks for the explanation. Seems to be working again.
