### ISSUE TITLE
Font changed by itself and cannot be adjusted

### ISSUE THREAD

**Issue by Arctagon** [FooSoft/yomichan#688]
Recently, the font in the popup window changed on its own to something rather ugly and annoying to read. The hiragana characters are fine, but the kanji characters are low-res -- it's like I'm reading on a Windows 98 system. I have no idea why the font suddenly changed, but I'm unable to change it back to the way it was. I've tried to change the font through CSS, and reset to default settings. Nothing works.

**Comment by toasted-nutbread** [comment]
Can you share a screenshot of it? I think another user has had this issue in the past and didn't really provide any details.

**Comment by Arctagon** [comment]
https://i.imgur.com/i3dEYUi.png

Windows 10, Chrome. Seems to be limited to Chrome. It looks okay in Firefox. I did delete some extensions and reset my Chrome settings recently, so it could be related to that.

(Just realised you can attach files. Was looking for a way to upload pictures earlier.)

**Comment by toasted-nutbread** [comment]
I assume you're expecting it to look something more like this?
![image](https://user-images.githubusercontent.com/11037431/88465849-60a30700-ce94-11ea-9b15-ca87ba955fd4.png)

I've seen this issue before, although maybe not with the exact font. I believe it stems from Windows changing some fonts or some font settings, perhaps during an update, and then Chrome detects a "more suitable" font for Kanji.

**Comment by Arctagon** [comment]
Yes, that's right, and that's how it currently looks in Firefox. It seems like Chrome is overriding anything I try to change inside Yomichan in that case.

**Comment by toasted-nutbread** [comment]
Check this link out for a potential solution:
https://japanese.meta.stackexchange.com/questions/1141/chrome-kanji-renderings-murdering-my-eyes-how-to-fix

I am guessing this is the issue, as the "yo" character looks like this font. Note the how there is a vertical stroke on the left component using this font, vs 4 horizontal strokes on the correct one, which is probably due to it being a Chinese font.
![image](https://user-images.githubusercontent.com/11037431/88466135-546c7900-ce97-11ea-8409-2643df147733.png)

I have never been able to fully reproduce having the "ugly" font due to not knowing what fonts users have installed. Would you be able to open up a powershell prompt and running these commands and copying the output here? (If not familiar with powershell, you can select text from the console and then right click to copy it.)
```ps
[System.Reflection.Assembly]::LoadWithPartialName("System.Drawing")
(New-Object System.Drawing.Text.InstalledFontCollection).Families
```
(Command from [here](https://superuser.com/questions/760627/how-to-list-installed-font-families/760632#760632))

**Comment by Arctagon** [comment]
Thanks for the link. I'll check it out.

`Name : Arial


Name : Arial Black


Name : Arimo


Name : Bahnschrift


Name : Bahnschrift Condensed


Name : Bahnschrift Light


Name : Bahnschrift Light Condensed


Name : Bahnschrift Light SemiCondensed


Name : Bahnschrift SemiBold


Name : Bahnschrift SemiBold Condensed


Name : Bahnschrift SemiBold SemiConden


Name : Bahnschrift SemiCondensed


Name : Bahnschrift SemiLight


Name : Bahnschrift SemiLight Condensed


Name : Bahnschrift SemiLight SemiConde


Name : BIZ UDGothic


Name : BIZ UDMincho Medium


Name : BIZ UDPGothic


Name : BIZ UDPMincho Medium


Name : Calibri


Name : Calibri Light


Name : Cambria


Name : Cambria Math


Name : Candara


Name : Candara Light


Name : Comic Sans MS


Name : Consolas


Name : Constantia


Name : Corbel


Name : Corbel Light


Name : Courier New


Name : DejaVu Sans


Name : DejaVu Sans Condensed


Name : DejaVu Sans Light


Name : DejaVu Sans Mono


Name : DejaVu Serif


Name : DejaVu Serif Condensed


Name : Ebrima


Name : Franklin Gothic Medium


Name : Gabriola


Name : Gadugi


Name : Gentium Basic


Name : Gentium Book Basic


Name : Georgia


Name : HoloLens MDL2 Assets


Name : Impact


Name : Ink Free


Name : Javanese Text


Name : Lato


Name : Lato Light


Name : Lato Semibold


Name : Leelawadee UI


Name : Leelawadee UI Semilight


Name : Lucida Console


Name : Lucida Sans Unicode


Name : Malgun Gothic


Name : Malgun Gothic Semilight


Name : Marlett


Name : Meiryo


Name : Meiryo UI


Name : Microsoft Himalaya


Name : Microsoft JhengHei


Name : Microsoft JhengHei Light


Name : Microsoft JhengHei UI


Name : Microsoft JhengHei UI Light


Name : Microsoft New Tai Lue


Name : Microsoft PhagsPa


Name : Microsoft Sans Serif


Name : Microsoft Tai Le


Name : Microsoft YaHei


Name : Microsoft YaHei Light


Name : Microsoft YaHei UI


Name : Microsoft YaHei UI Light


Name : Microsoft Yi Baiti


Name : MingLiU-ExtB


Name : MingLiU_HKSCS-ExtB


Name : Mongolian Baiti


Name : MS Gothic


Name : MS Mincho


Name : MS PGothic


Name : MS PMincho


Name : MS UI Gothic


Name : MV Boli


Name : Myanmar Text


Name : Nirmala UI


Name : Nirmala UI Semilight


Name : NSimSun


Name : OpenSymbol


Name : Palatino Linotype


Name : PMingLiU-ExtB


Name : Segoe MDL2 Assets


Name : Segoe Print


Name : Segoe Script


Name : Segoe UI


Name : Segoe UI Black


Name : Segoe UI Emoji


Name : Segoe UI Historic


Name : Segoe UI Light


Name : Segoe UI Semibold


Name : Segoe UI Semilight


Name : Segoe UI Symbol


Name : SimSun


Name : SimSun-ExtB


Name : Sitka Banner


Name : Sitka Display


Name : Sitka Heading


Name : Sitka Small


Name : Sitka Subheading


Name : Sitka Text


Name : Sylfaen


Name : Symbol


Name : Tahoma


Name : Times New Roman


Name : Trebuchet MS


Name : UD Digi Kyokasho N-B


Name : UD Digi Kyokasho N-R


Name : UD Digi Kyokasho NK-B


Name : UD Digi Kyokasho NK-R


Name : UD Digi Kyokasho NP-B


Name : UD Digi Kyokasho NP-R


Name : Unispace


Name : Verdana


Name : Webdings


Name : Wingdings


Name : Yu Gothic


Name : Yu Gothic Light


Name : Yu Gothic Medium


Name : Yu Gothic UI


Name : Yu Gothic UI Light


Name : Yu Gothic UI Semibold


Name : Yu Gothic UI Semilight


Name : Yu Mincho


Name : Yu Mincho Demibold


Name : Yu Mincho Light`

**Comment by toasted-nutbread** [comment]
Thanks for the feedback. For some websites, the fonts may look correct if they manually specify different fonts. Yomichan's fonts may not be working because Chrome/Windows doesn't have those and is trying to use a default fallback. May be worth it at some point for Yomichan to have a font debugging/information page included to have some info about this.
