### ISSUE TITLE
[Feature Request] Add box for Register Helper functions

### ISSUE THREAD

**Issue by machtgelust** [FooSoft/yomichan#689]
In the Anki Integration section I'd like to register a function in handlebars such as 

```
Handlebars.registerHelper('each_upto', function(ary, max, options) {
    if(!ary || ary.length == 0)
        return options.inverse(this);

    var result = [ ];
    for(var i = 0; i < max && i < ary.length; ++i)
        result.push(options.fn(ary[i]));
    return result.join('');
});
```

But it doesn't seem that Yomichan allows it through the settings page.

**Comment by toasted-nutbread** [comment]
Yomichan does not currently support custom handlebars helpers, and probably won't because it presents an extension security/integrity opening. The helper you wrote could be added to the list of built-in helpers if that suits your needs.

**Comment by machtgelust** [comment]
That makes sense, thanks for the consideration. I'd be happy to get the function added if you're willing.

**Comment by toasted-nutbread** [comment]
See #690
