### ISSUE TITLE
Anki cards with text-align: left in {glossary} look weird

### ISSUE THREAD

**Issue by dequis** [FooSoft/yomichan#69]
Hi.

Text in anki cards is centered by default. For some reason glossary was sent to the left. I think it's easier to read the flashcards if they are centered. Is it okay to just change this behavior?

A card aligned to the left

![screen1](https://user-images.githubusercontent.com/94108/29052996-ba42a9ea-7bc3-11e7-939c-fd29a1dfe83f.png)

Removing the alignment:

![screen2](https://user-images.githubusercontent.com/94108/29052869-1b07e890-7bc3-11e7-8627-7f86eac192c9.png)

Adding `list-style-position: inside`

![screen3](https://user-images.githubusercontent.com/94108/29052982-abd44a08-7bc3-11e7-9892-be700b41b8c0.png)

**Comment by dequis** [comment]
Quoting https://github.com/FooSoft/yomichan/pull/70#issuecomment-321007669

> There are a couple of concerns I have with this change:
> 
> * Single entry, long definitions (like the ones that come out of EPWING) objectively make sense to left-justify otherwise you are reading paragraphs of centered text which is kind of gross. Having the text left-justified in some cases and
> center-aligned in others creates undesired inconsistency in cards.
> * People generally don't like when styling is changed on them because it makes existing cards look different from new ones produced by Yomichan.
> * Putting things behind option flags is definitely a possibility but it will not scale when you think about all of the different parameters that can be tweaked about card creation.
> 
> I think the only real solution is to allow people to edit the templates used for card generation within the options dialog. This way everyone wins and I don't have to maintain lots of branching and options management for making things look the way people want.
> 

So this is now about allowing users to edit templates.

**Comment by FooSoft** [comment]
@dequis yup. The tricky thing is that handlebars is implemented in such a way that it uses `eval`, and that function is banned in extensions (this is one of the reasons as to why I bake my templates out). There is a workaround though, where you basically create a sandboxed frame just for rendering templates. It's super gross and requires additional message passing but it's probably the only way this will work.

**Comment by FooSoft** [comment]
@dequis user templates have been added. You can now generate Anki cards with whatever formatting you desire.

**Comment by dequis** [comment]
Nice, thanks!
