### ISSUE TITLE
[bug] Whitespace Issue?

### ISSUE THREAD

**Issue by SamuelFoster** [FooSoft/yomichan#72]
I'm encountering a strange issue. (Yomichan 1.3, Firefox 55.0.2)

Steps to reproduce:

First, here are my Anki input settings:
![1](https://user-images.githubusercontent.com/5395381/29455627-c5256054-83c6-11e7-952f-0b66a7aa0843.png)

And here is a word that was previously input into Anki using Yomichan
![2](https://user-images.githubusercontent.com/5395381/29455637-c9e65f30-83c6-11e7-8452-7d4343bfcdf0.png)

Yet, Yomichan thinks the word is not in Anki.
![3](https://user-images.githubusercontent.com/5395381/29455638-cb837f9e-83c6-11e7-8b0f-8f60e63321cc.png)

If I add it to Anki, a strange whitespace appears.
![4](https://user-images.githubusercontent.com/5395381/29455640-ccd1f506-83c6-11e7-9504-18f090df3d11.png)

(Strangely, the whitespace does not appear in a separate test field...)
![5](https://user-images.githubusercontent.com/5395381/29455641-ce1e489c-83c6-11e7-8b61-3f4ebf6a2e02.png)

Now Yomichan recognizes that the word is in Anki.
![6](https://user-images.githubusercontent.com/5395381/29455643-cfd69e50-83c6-11e7-8de8-cb116a6df695.png)

**Comment by SamuelFoster** [comment]
In addition, the Anki input settings appear to reset when the settings page is closed.
![7](https://user-images.githubusercontent.com/5395381/29456612-5185cb3e-83cb-11e7-945f-3113cb7405c8.png)

**Comment by HelenFoster** [comment]
I'm having similar problems in Chrome since today's update. Basically, some of the Anki fields are being filled with a lot of extra whitespace. And the expression field is one of them, which breaks the duplicate detection.

**Comment by FooSoft** [comment]
This appears to be a problem with the latest version of handlebars (library I'm using to render templates). It is supposed to trim spaces but it is not doing it. I'll have a fix out shortly.

**Comment by FooSoft** [comment]
@SamuelFoster I cannot reproduce the issue you are having. Can you provide more info?

**Comment by FooSoft** [comment]
@SamuelFoster the problem that was the basis for creating this issue has been resolved. The problem you are describing with the Anki settings being reset is unrelated, so you should open a new issue for it if you are still running into it as of 1.3.1.
