### ISSUE TITLE
[feature request] Add the option to make the full furigana line visible, like it used to be.

### ISSUE THREAD

**Issue by Mikemikemike14** [FooSoft/yomichan#74]
As it is right now, the missing portions of the furigana line make copy pasting more time consuming than desirable in two ways:

1. the extra characters it grabs from the top row while highlighting a word require extra cleanup afterwards 

![fddfd](https://user-images.githubusercontent.com/31386582/29750264-15b013f4-8b45-11e7-987e-00098ad20390.png)

Like, in the instance shown above you'd get 肩かたの力ちからを抜ぬく instead of 肩の力を抜く.

2. the gaps in the furigana line require you to assemble a word from multiple pieces, should you want to copy it as kana only

As someone who likes to likes to manually make his Anki cards so that they only include certain definitions, this certainly makes the experiences a lot less pleasant.

**Comment by FooSoft** [comment]
You realize that you can create an Anki setup that does not automatically add a glossary and that when new cards are created you get a button to instantly open them in the deck browser right? I guess that given these features I don't understand the necessity to copy paste anything from the popup.

**Comment by siikamiika** [comment]
Isn't this a browser issue instead? `<ruby>` tags are used on many other sites as well and I agree that copying text from them is a pain on Chrome. Working around the copy-paste issue by restoring furigana that is harder to read sounds borderline "keyboard heating" but of course sometimes you have to adapt to the OS/browser/etc. you're working with.

Anyway, I suggest opening an issue [here](https://bugs.chromium.org/p/chromium/issues/list) requesting that Chrome would behave like Firefox and not copy furigana along with text.

**Comment by FooSoft** [comment]
Closing due to lack of feedback. Feel free to reopen this with requested info.
