### ISSUE TITLE
feature request 2

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/yomichan#740]
Using that code https://github.com/FooSoft/yomichan/issues/378 I was able to create cards that look like this in just 1 click, imho header is not necessary and takes a lot of space. I would like to have an option to skip headers when exporting to anki.
![anki_DUW3JBY88D](https://user-images.githubusercontent.com/24941285/90615547-f4a68b00-e214-11ea-8586-606ecaa56d29.jpg)

**Comment by toasted-nutbread** [comment]
I don't think that's a "header" that Yomichan generates; it's part of the definition. Some of the Japanese dictionaries don't have great formatting and are rather messy, so this may be what you are seeing. You may be able to strip it with a custom regular expression in the handlebars templates, but ultimately it's an issue with the dictionaries themselves.

**Comment by Geniusssmit** [comment]
> I don't think that's a "header" that Yomichan generates

I see. MIA dictionary addon can strip that, it's just removing the first line on every dictionary basically. How can I do that using handlebars?

> You may be able to strip it with a custom regular expression in the handlebars templates

or that.

**Comment by toasted-nutbread** [comment]
```handlebars
{{#regexReplace "^[^\n]*\n" ""}}(content where the first line is to be removed){{/regexReplace}}
```

**Comment by Geniusssmit** [comment]
> ```
> {{#regexReplace "^[^\n]*\n" ""}}(content where the first line is to be removed){{/regexReplace}}
> ```

Thanks! can you give an example?
For example I have that
```
{{#*inline "test"}}
    {{~#scope~}}
        {{~#set "first-dictionary" null}}{{/set~}}
        {{~#if modeKanji~}}
            ...
        {{~else if (op "||" group merge)~}}
            {{~#each definition.definitions~}}
                {{~#if (op "===" null (get "first-dictionary"))~}}
{{~#set "first-dictionary" dictionary~}}{{~/set~}}
                {{~/if~}}
                {{~#if (op "===" dictionary (get "first-dictionary"))~}}
{{> glossary-single brief=../brief compactGlossaries=../compactGlossaries}}
                {{~/if~}}
            {{~/each~}}
        {{~else~}}
            {{~> glossary-single definition brief=brief compactGlossaries=compactGlossaries~}}
        {{~/if~}}
    {{~/scope~}}
{{/inline}}
```

**Comment by toasted-nutbread** [comment]
You will want to modify the `glossary-single` definition, wrapping the `{{.}}` and `{{glossary.[0]}}` with `regexReplace`.
(This whole thing could now be rewritten to be a bit cleaner, but this is based on the default.)

```handlebars
{{#*inline "glossary-single"}}
    {{~#unless brief~}}
        {{~#if definitionTags~}}<i>({{#each definitionTags}}{{name}}{{#unless @last}}, {{/unless}}{{/each}})</i> {{/if~}}
        {{~#if only~}}({{#each only}}{{{.}}}{{#unless @last}}, {{/unless}}{{/each}} only) {{/if~}}
    {{~/unless~}}
    {{~#if glossary.[1]~}}
        {{~#if compactGlossaries~}}
            {{#each glossary}}{{#multiLine}}{{#regexReplace "^[^\n]*\n" ""}}{{.}}{{/regexReplace}}{{/multiLine}}{{#unless @last}} | {{/unless}}{{/each}}
        {{~else~}}
            <ul>{{#each glossary}}<li>{{#multiLine}}{{#regexReplace "^[^\n]*\n" ""}}{{.}}{{/regexReplace}}{{/multiLine}}</li>{{/each}}</ul>
        {{~/if~}}
    {{~else~}}
        {{~#multiLine}}{{#regexReplace "^[^\n]*\n" ""}}{{glossary.[0]}}{{/regexReplace}}{{/multiLine~}}
    {{~/if~}}
{{/inline}}
```

**Comment by Geniusssmit** [comment]
> You will want to modify the `glossary-single` definition, wrapping the `{{.}}` and `{{glossary.[0]}}` with `regexReplace`.
> (This whole thing could now be rewritten to be a bit cleaner, but this is based on the default.)
> 
> ```
> {{#*inline "glossary-single"}}
>     {{~#unless brief~}}
>         {{~#if definitionTags~}}<i>({{#each definitionTags}}{{name}}{{#unless @last}}, {{/unless}}{{/each}})</i> {{/if~}}
>         {{~#if only~}}({{#each only}}{{{.}}}{{#unless @last}}, {{/unless}}{{/each}} only) {{/if~}}
>     {{~/unless~}}
>     {{~#if glossary.[1]~}}
>         {{~#if compactGlossaries~}}
>             {{#each glossary}}{{#multiLine}}{{#regexReplace "^[^\n]*\n" ""}}{{.}}{{/regexReplace}}{{/multiLine}}{{#unless @last}} | {{/unless}}{{/each}}
>         {{~else~}}
>             <ul>{{#each glossary}}<li>{{#multiLine}}{{#regexReplace "^[^\n]*\n" ""}}{{.}}{{/regexReplace}}{{/multiLine}}</li>{{/each}}</ul>
>         {{~/if~}}
>     {{~else~}}
>         {{~#multiLine}}{{#regexReplace "^[^\n]*\n" ""}}{{glossary.[0]}}{{/regexReplace}}{{/multiLine~}}
>     {{~/if~}}
> {{/inline}}
> ```

Thank you very much, that helped!
