### ISSUE TITLE
Screenshot with yomichan popup

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/yomichan#741]
Sometimes(1 out of 10 times) screenshot exported to anki with yomichan popup. As I understand, a little bit more latency will solve it
![image](https://user-images.githubusercontent.com/24941285/90621873-ff651e00-e21c-11ea-914d-0c9afd4bd4ac.png)

**Comment by nonetrix** [comment]
Still having this issue

**Comment by toasted-nutbread** [comment]
@nonetrix Please create a new issue with your details for visibility, the implementation has changed sufficiently, so the underlying issue is probably different.
