### ISSUE TITLE
[feature request] Anki functionality within the Yomichan search

### ISSUE THREAD

**Issue by jsnowk** [FooSoft/yomichan#75]
I don't know if this is possible but I'd like the ability to use the anki feature inside yomichan's search.
Oftentimes the Kenkyusha dictionary is full of example sentences with words I've never seen before and it'd be convenient to be able to create cards from them on the same page.

Thanks.

**Comment by FooSoft** [comment]
You should already be able to do this assuming you have Anki stuff configured on the options page. Do the add buttons not show up on the search page even though they show up on the normal popup?

**Comment by jsnowk** [comment]
Ah, sorry. I meant that I'd like to highlight the words in the sentences on that page and have the pop-up appear so I can make cards.

**Comment by siikamiika** [comment]
I've also been thinking of something similar. Inside the popup (and search) there could be a mini version of Yomichan that would have a separately enabled set of dictionaries and a more compact layout without kanji links, for example. But if this is not what you meant @jsnowk I have no intention to hijack this issue :D

**Comment by FooSoft** [comment]
It's pretty simple to add Yomichan functionality to the standalone search page (where you type in the text to search for) by manually injecting the CSS and JS that the browser does not want to recursively inject into the extension. I tried this as a hack and everything worked aside from Anki integration (it would just need to be updated to be sure to use the correct messaging format depending on if it is running in the foreground or background context).

If this were to be implemented on the actual search popup, I think maybe there could be a thing where you could just click on beginning on text where you want to scan, and Yomichan would display those definitions. You could then use the "back" button to go back to the source definition (just like the way Kanji search works).

**Comment by Aakasan** [comment]
> It's pretty simple to add Yomichan functionality to the standalone search page (where you type in the text to search for) by manually injecting the CSS and JS that the browser does not want to recursively inject into the extension. I tried this as a hack and everything worked aside from Anki integration (it would just need to be updated to be sure to use the correct messaging format depending on if it is running in the foreground or background context).
> 
> If this were to be implemented on the actual search popup, I think maybe there could be a thing where you could just click on beginning on text where you want to scan, and Yomichan would display those definitions. You could then use the "back" button to go back to the source definition (just like the way Kanji search works).

Can anybody explain how to do this in plain terms? I have no clue how to manually inject CSS and JS,etc. I think having a search definitions, inside definitions would save a great deal of time when using J-J dictionaries
