### ISSUE TITLE
Firefox error "Yomichan could not be verified for use in Firefox and has been disabled."

### ISSUE THREAD

**Issue by yaycupcake** [FooSoft/yomichan#750]
This just started happening out of seemingly nowhere. Can it be addressed so it's usable again?

**Comment by toasted-nutbread** [comment]
Closing as the issue is resolved for this case. The underlying cause is still unknown; I've never experienced this error myself (outside the time Mozilla broke everything), and no other users have reported a similar issue thus far. Hopefully it was a fluke and the issue does not happen again.
