### ISSUE TITLE
[bug] Cannot load any dictionaries

### ISSUE THREAD

**Issue by Piranhaplant** [FooSoft/yomichan#76]
Upon a new install of the extension, this message is shown on the settings page under "Dictionaries":
> **Error:** OpenFailedError: UnknownError The operation failed for reasons unrelated to the database itself and not covered by any other error code.

Purging the database doesn't do anything and no dictionaries can be imported.

Using version 1.3.5 in Firefox Nightly 57.0a1 on Windows 7.

**Comment by FooSoft** [comment]
Some versions of Firefox appear to have a buggy implementation of IndexedDb ... will investigate. Thank you for the report.

**Comment by FooSoft** [comment]
@Piranhaplant so it looks like I'm unable to reproduce the problem in the 64-bit build of 57.0a1 nightly (2017-09-11). Could you check to see that your nightly is up to date, and if it isn't, what is the date on it. 

Also, did you get the error before you even attempted to import any dictionaries?

**Comment by Piranhaplant** [comment]
@FooSoft I am using the latest 64-bit nightly (2017-09-11). The error shows up on a clean install of the extension before importing any dictionaries.

If you don't have any other ideas, I will try a fresh profile/install of Firefox and see if that helps.

**Comment by FooSoft** [comment]
@Piranhaplant so it appears then that you must be getting the error on the initial database open (before Yomichan even does anything interesting with it). I've seen a similar issue in Firefox 53. Some relevant threads about people running into the same problem:

* https://github.com/dfahlander/Dexie.js/issues/298
* https://bugzilla.mozilla.org/show_bug.cgi?id=1217257 (do you have other installs of Firefox?)
* https://bugzilla.mozilla.org/show_bug.cgi?id=1310616
* https://greasyfork.org/en/forum/discussion/6663/state-of-denial

It just seems like the underlying support for IndexedDb is pretty spotty. If you could try wiping your profile and/or reinstalling FF I would be very interested in seeing if the problem goes away.

**Comment by Piranhaplant** [comment]
I tried it on a new profile and that fixed the issue, then I went back to my original profile and used the "Refresh Firefox" feature, which also fixed it. I've restored my settings and other extensions and Yomichan is still working, so I'm not sure what the problem was. Sorry to waste your time!

**Comment by FooSoft** [comment]
@Piranhaplant thanks for the info, it's good to know that this is indeed related to a (likely) corrupt profile. I will other users to try the "Refresh Firefox" feature if they encounter similar problems. Out of curiosity, do you have multiple installs of Firefox on your machine or are you using the nightly build exclusively? Trying to narrow down list of possibilities for what can be causing IndexedDB corruption.

**Comment by Piranhaplant** [comment]
I do have multiple installs (the standard release and nightly), but it has been quite some time since I last ran the standard release. It looks like I have version 32.0.3 installed which puts it at almost 3 years old.
