### ISSUE TITLE
Inconsistent behavior with mixed kanji/hiragana

### ISSUE THREAD

**Issue by Ceiyne** [FooSoft/yomichan#766]
I'm not sure if this is really a bug or just the way the dictionaries work.   But, from a user perspective, Yomichan can't always find words that exist in the dictionary, depending on hiragana and kanji usage.  This is easier to explain with an example.

If I am trying to look up the word すいこむ in all hiragana, Yomichan will find it and display the correct definition.

If it is written as 吸い込む or 吸いこむ, Yomichan will still find it and display the correct definition.

However, if it is written as すい込む, then Yomichan does not find it, and instead displays the dictionary entry for just すい.

I'm guessing the problem is that すい込む is a non-standard spelling.  I think I have a tendency to run into this because some of my Japanese reading assignments are aimed at students who might not know all the required kanji yet, and so hiragana is used sometimes when it normally wouldn't be.

**Comment by toasted-nutbread** [comment]
It's an issue with non-standard kana representations not being stored in the dictionary, therefore Yomichan can't find a matching result. The extension is working as expected when it can't find `すい込む`, because there is no raw dictionary entry matching that string.

**Comment by Ceiyne** [comment]
Thanks for letting me know.  You want me to close the issue?
