### ISSUE TITLE
Yomichan stopped working on kiwi browser (mobile) after latest update (v20.8.24.0)

### ISSUE THREAD

**Issue by HansKlokkenspel** [FooSoft/yomichan#775]
Yesterday everything worked fine, today I can't get it to show the pop ups anymore. I have reinstalled it just to be sure, but to no avail. Anyone with the same problem? 

In the past I used firefox on mobile, but after the revamp they had for the mobile app about 1.5 months ago it said that yomichan wasn't compatible. With Kiwi now out of the question as well, does anyone have any suggestions on what to use in the meantime?

**Comment by toasted-nutbread** [comment]
I believe #772 is the issue. @FooSoft hotfix time?

**Comment by FooSoft** [comment]
Done!

**Comment by Panda-Sama** [comment]
I also use kiwi, and mine is broken too. But in my case is just the single touch, i can search words if i make a long touch, probably that could help you. 
I miss my single touch searching. :c

**Comment by Panda-Sama** [comment]
I also use kiwi, and mine is broken too. But in my case is just the single touch, i can search words if i make a long touch, probably that could help you.
I miss my single touch searching. :c

**Comment by HansKlokkenspel** [comment]
It seems to be working again on 20.8.24.1, thanks guys :) I'll be closing the issue now. @Panda-Sama If you still have trouble on your end, I think it would be best to open a separate issue.
