### ISSUE TITLE
Shift key to preview broken in OS X High Sierra

### ISSUE THREAD

**Issue by Cryocubed** [FooSoft/yomichan#78]
After testing yomichan on OS X High Sierra, I've found that it doesn't appear to register holding the shift key to get information. Holding the middle mouse button works like normal. I tried different keyboard modifiers as well, but they also didn't seem to register.

**Comment by FooSoft** [comment]
Hmm, that's bizarre; I would not expect that a new version of an operating system would change browser behavior. 

Couple of things:
* Have you tried installing Yomichan before on Sierra? If so, did that work properly for you?
* Are you running the Firefox or Chrome version? Could you tell me the version number?

**Comment by Cryocubed** [comment]
Yeah, I thought it was odd too since I had yomichan previously installed and working on Chrome before I updated. 

Yes, it was working normally up until I updated, but I'm unaware if Chrome also updated at the same time.
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

I also tried restarting my browser and computer, neither of which worked.

**Comment by Cryocubed** [comment]
I just retested it, and it seems to be working as normal again. Unsure of what changed, as I haven't done anything worth noting.

**Comment by FooSoft** [comment]
Well I guess it's good that it fixed itself since I don't have a OS X High Sierra machine to test it on (just a hacked OS X VirtualBox image). If this happens again, please reopen this.
