### ISSUE TITLE
If "Middle mouse button scans" is enabled, disable auto scroll

### ISSUE THREAD

**Issue by psychodelicwasabi** [FooSoft/yomichan#781]
As is known (#479), the "middle button scan" ends up enabling the auto-scroll. In Firefox, you can disable the auto-scrolling altogether in the browser settings and that fixes it, however, Chrome lacks that feature. As a workaround, I use an extension that disables the auto-scrolling on Chrome, but that only works for sites. So, I can use the middle button to scan a word in first instance, but not words inside the Yomichan pop-up, since the middle button still enables the auto-scrolling there. What I'm looking for is a way to disable auto-scrolling inside the Yomichan pop-ups or search page, since none of the extensions and scripts I tried seem to work.

**Comment by toasted-nutbread** [comment]
What Chrome extension are you using to disable the feature?

**Comment by psychodelicwasabi** [comment]
Sorry, I thought about adding it to the issue but ended up deciding not to. This is it: https://chrome.google.com/webstore/detail/no-smooth-scroll-2/hmnphcnjmmddnocmhmdmlgbdkabcccho
