### ISSUE TITLE
[feature request] Add a shortcut to see the kanji dictionary entry for the kanji you are pointing to.

### ISSUE THREAD

**Issue by non-e-moose** [FooSoft/yomichan#79]
We already have Alt + b  to go back to source term. I'd love a shortcut (maybe the same alt + b combination, seems logical to use it to switch between dictionary and kanji dictionary modes) to do the opposite.

**Comment by FooSoft** [comment]
From your other request, know that you are coming from Rikai* where the only way to see Kanji definitions is to switch to an entirely different mode, but in Yomichan I think the process works a little bit simpler since you can just click on the characters in the term results window. I'm curious is to what your usage scenario is where you wish to see the Kanji before the actual terms. Or is it that you want to go from the term result back to the Kanji you were just viewing?

**Comment by non-e-moose** [comment]
My usage would be mouse over word, read definition, hit shortcut and see the kanji info.
I know I could use mouse to click on the kanji within the definition, but I would just want a shortcut for this, since it's both faster and easier to use a shortcut. (Just like I COULD go from kanji back to the definition by clicking the return button, but I vastly prefer to use the shortcut you kindly provided for that.) 
Obviously it's a non-issue for somebody who doesn't like checking the kanji info or for somebody who is so advanced that he rarely checks new kanji, but still I don't think it's all that user-specific, at least among the beginners. Since you have a fair amount of shortcuts already I believe you also see the benefits of shortcuts vs GUI in some cases, so I'm hopeful you will see some sense into adding another one.

**Comment by FooSoft** [comment]
So let's say you mouse over a word and you get 10 results back. Each term in the results window has multiple Kanji in it. You hit the hotkey to switch to Kanji view -- which Kanji is selected for view?

**Comment by non-e-moose** [comment]
I would say the kanji you are pointing to (the same behavior as when you only have kanji dictionary installed) would be the best and seems to be the easiest to implement.

E.g. if you don't know the word and the second kanji of the word you mouse over, read definition, move mouse to the next character and hit shortcut.

Another way would be showing all kanji from the string selected in text (in this case the kanji number would be less than 10, 4 character jukugo seem to be the longest ones that appear regularly.)

Both approaches have some disadvantages (second may require scrolling while first may require moving cursor to the appropriate character), but I would prefer the first one.

**Comment by FooSoft** [comment]
Would a "show me Kanji results only" modifier key work? E.g. mousing over with Ctrl pressed only shows Kanji results.

**Comment by non-e-moose** [comment]
If you mean something like: modifier key makes yomichan work as it does when only kanji dictionary is installed, then yes, it would be perfect.

**Comment by FooSoft** [comment]
Cool, will do it that way. Will just have to make some sort of system for making sure modifier keys don't collide for the purposes of normal scanning.

**Comment by non-e-moose** [comment]
Thanks.

**Comment by siikamiika** [comment]
To increase the modifier space, you could make each modifier a tuple of modifiers. That makes a total of 8 modifiers if no modifiers is included.
