### ISSUE TITLE
[bug] Error: IndexSizeError: Index or size is negative or greater than the allowed amount

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#80]
**Summary:**
On some sites I get the alert `Error: IndexSizeError: Index or size is negative or greater than the allowed amount` when scanning.

**Steps to reproduce:**
1. Open this test case (Firefox 55, Linux or Windows):
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>IndexSizeError</title>
    </head>
    <body>
        <form method="get" action="https://test"><div><input name="test" value="123" type="hidden"><input value="test" type="submit"></div></form>
    </body>
</html>
```
2. Scan anywhere on the page.

**Expected results:**
Nothing should happen because there is no text under the mouse cursor.

**Actual results:**
You get an alert with the text  `Error: IndexSizeError: Index or size is negative or greater than the allowed amount`.

---

**More info:**
- The error in this case has something to do with the `<form>` being an one-liner. If I add newlines between `<form>` and `<div>`, there are no errors.
- On dev branch, the error appears to originate from https://github.com/FooSoft/yomichan/blob/5476c100467e31d7dac02a4b1c14e62a4e9b34d0/ext/fg/js/frontend.js#L176 or a corresponding line on current master https://github.com/FooSoft/yomichan/blob/0c650dac828b7ab9641396268a66d3a7410d4000/ext/fg/js/frontend.js#L180 (`textSource.containsPoint(point)`)
- I don't think that there are bad consequences from silently ignoring this error unless it can be reproduced with something that actually contains text.
- I cannot reproduce it on Chrome/Chromium.

**Comment by FooSoft** [comment]
Thanks for the report and the nice repro, will investigate. Simply killing this error would be the easy thing to do, but I want to figure out the underlying problem because this is just weird.
