### ISSUE TITLE
Feature Request: Make profile dependent on modifier key

### ISSUE THREAD

**Issue by roryfree** [FooSoft/yomichan#816]
Example: 
If scanning with Shift, use default profile
If scanning with CTRL, use modified profile

**Comment by toasted-nutbread** [comment]
This should already be doable using profile conditions. You would have to add the following condition to the alternate profile:
![image](https://user-images.githubusercontent.com/11037431/93006839-40580600-f52f-11ea-8bdb-95b5e6be8712.png)

**Comment by roryfree** [comment]
I tried this and only had the option to choose URL and Popup Level. Turns out my Yomichan wasn't set to auto-update and the option is there after updating. Sorry to bother you and thanks for all your work.
