### ISSUE TITLE
Add support for auto-updating of Firefox testing builds

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#830]
https://stackoverflow.com/questions/40541561/firefox-web-extension-auto-update-unlisted-and-self-hosted-extension

**Comment by toasted-nutbread** [comment]
@FooSoft This would likely require doing one of the following:

1. Maintaining an `updates.json` file on [https://github.com/FooSoft/foosoft.github.io](https://github.com/FooSoft/foosoft.github.io).
   E.g. [https://foosoft.github.io/projects/yomichan/updates.json](#) or [https://foosoft.net/projects/yomichan/updates.json](#).

2. Maintaining an `updates.json` file on an orphan branch of this repository which is visible as a gh-pages URL.
   E.g. [https://foosoft.github.io/yomichan/updates.json](#) or [https://foosoft.net/yomichan/updates.json](#).

The release process would be:
* Upload releases to AMO and Chrome Store as usual.
* Upload the release files to the release [GitHub release page](https://github.com/FooSoft/yomichan/releases).
* Update the `updates.json` file with the URL from the GitHub release page.

We could have a checklist template that is pasted into the release issue to help remember what the process is.

### Authoring security concerns

* If the `updates.json` file would be located in this repository, that would likely mean that any collaborators have the ability to modify it without going through a PR.
* Additionally, it may mean that other files on the gh-pages branch could be created on [https://foosoft.net/projects/yomichan/](#).
* For the release files hosted on the [GitHub release page](https://github.com/FooSoft/yomichan/releases), these files can be uploaded/deleted/replaced by collaborators.

So I guess the takeaway is that supporting auto-updating using this repository directly assumes that collaborators are trustworthy and won't "secretly" change the update URLs or download links.

**Comment by FooSoft** [comment]
I think that hosting it on foosoft.net is probably the most straightforward way to go (option 1). 

I'd change the URL to https://foosoft.net/projects/yomichan/dl/updates-testing.json, however as the files in the `yomichan` directory are mainly resources for the HTML there. Explicitly calling out the "testing" also seems like good idea, since Mozilla has already kicked Yomichan off their store once, and I would not be that surprised if at some point the extension has to be hosted outside of their ecosystem.

Speaking of testing releases, are we in a good state to queue up a new one?

**Comment by toasted-nutbread** [comment]
Sounds good to me.

> Explicitly calling out the "testing" also seems like good idea ...

You can also use one updates.json file for multiple extension IDs.

> Speaking of testing releases, are we in a good state to queue up a new one?

Most of the features are done for the release, and I'll be doing mostly testing for the next several days. I may do a bit of documentation updates/file organization as well. Right now a lot of new stuff is just dumped in /fg/, /bg/, or /mixed/, and there are probably some ways to clarify the organization.

**Comment by FooSoft** [comment]
Cool, did not know that you can put multiple extensions in one `updates.json`, I guess that solves that issue.
