### ISSUE TITLE
Popups stopped showing up

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#838]
I use the most current master branch version of Yomichan and I noticed that when the scan inputs part of settings was added, my scanning just stopped working altogether on any Japanese text. I assume it's because you have to mess with scan inputs now, which I don't really understand the purpose of, btw. I will add my current Yomichan settings for anyone to check out.
[yomichan-settings-2020-09-15-09-48-46.json.zip](https://github.com/FooSoft/yomichan/files/5243007/yomichan-settings-2020-09-15-09-48-46.json.zip)

**Comment by toasted-nutbread** [comment]
The master branch doesn't upgrade settings properly between each commit, only between major releases. There have been several changes to how scanning inputs are set up which have likely not been upgraded properly for your setup. You will have to set up the scanning inputs to your liking. These are the defaults:

![image](https://user-images.githubusercontent.com/11037431/93548850-2014b680-f936-11ea-8a4d-8d7db1779c9d.png)

Note that this upgrade should work properly for users of testing/stable releases.

**Comment by toasted-nutbread** [comment]
@oudajosefu Do you have any further issues related to this? The reason this was changed is to make it more flexible, allowing more custom inputs to be specified for scanning (e.g. shift+ctrl scans, or holding alt prevents scanning), and support for multiple different actions based on scanning inputs (scan terms/expressions and/or scan kanji definitions).

I may add a simplified UI for this in the future which is more similar to the previous UI, but that will come with the v2 settings page updates.

**Comment by toasted-nutbread** [comment]
Closing due to lack of feedback, and also due to the revert/addition of the old simplified UI.
