### ISSUE TITLE
September 2020 Release

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#869]
I am going to start creating issues when releases are nearly ready, to serve as a heads-up, use as a forum for testing notes, release notes, etc. The release frequency is roughly monthly, so I'm going to title the issues by month, but if the version number rolls over to the next month due to any delays, that's fine.

The features for this next release should be mostly ready, I'll be doing some final testing over the next few days to verify it's good to go.

@FooSoft Did you ever get any info about the Firefox release issues, as per https://github.com/FooSoft/yomichan/issues/828#issuecomment-693147251? This release doesn't have #830 implemented yet, but I can work towards that for the next major release if necessary. I'm hoping I don't have to go and [implement an `eval`-less handlebars replacement](https://github.com/FooSoft/yomichan/pull/311#issuecomment-565827090), but I won't be surprised if it comes to that.

**Comment by toasted-nutbread** [comment]
## [Changes since 20.8.24.1](https://github.com/FooSoft/yomichan/compare/20.8.24.0...master)

### Features
* Added support for more flexible scanning inputs, including mouse, touch, pen, and keyboard inputs. (#79; #783, #784, #785, #789, #805, #806, #808, #810, #811, #812, #813, #814, #815, #817, #818, #819, #820, #821, #822, #823, #824, #866, #872)
* Added support for `{clipboard-image}` Anki marker. (#776; #780)
* Added support for `{clipboard-text}` Anki marker. (#862; #863)
* Added support for using a native window for the standard scanning popup. (#664; #763, #773, #865)
* Added support for a "delay hide" option. (#742; #774, #836)
* Added support for preventing the default behavior of the middle mouse button on different pages. (#781; #868)
* Added support for controlling scanning and scrolling from touch events. (#870; #871)
* Enabled sandboxing on Chrome browsers for Anki template generation, which should improve extension security. (#612, #841)

### Fixes
* Fixed an issue preventing touch input from being enabled. (#775; #772)
* Fixed an issue causing Yomichan to throw an error when a custom logo is displayed on the Chrome's new tab page. (#760)
* Fixed error log messages not including the correct URL. (#761)
* Fixed an issue in Chrome where opening the settings page would cause a long-running database integrity check that could block scanning in other tabs. (#302; #831)
* Fixed an issue where importing certain settings backup files could fail. (#843)
* Fixed the "Enable scanning on search page" setting not being obeyed correctly. (#867)

### Internal Changes
* Improved internal handling of profile conditions. (#758, #768, #769, #782, #786)
* Refactored dictionary operations on the settings page. (#759, #844)
* Refactored Anki template system. (#762, #770, #790, #791, #792, #793, #795, #796, #801, #802, #803, #804, #833, #849)
* Fixed some internal messaging issues. (#765)
* Refactored code in preparation of support for Manifest v3. (#798, #825, #831, #832, #845)
* Refactored and simplified audio system classes. (#799, #800, #858)
* Refactored options upgrade process. (#807, #829, #850, #851, #852)
* Added and organized tests and validation. (#827, #846, #848, #852, #861)
* Added documentation. (#835, #837)
* Added icons in preparation for future changes to the settings page. (#860)
* Build system and build target updates. (#839, #840)
* General refactoring and organization. (#764, #767, #771, #777,  #778, #779, #787, #788, #794, #809, #826, #842, #847, #853,  #854, #856, #857, #859, #864, #873)

**Comment by FooSoft** [comment]
Sweet, this helps a ton. I'll get a new testing release queued up later today or tomorrow :tada: 

The situation with the Firefox listing is not good; I have no idea where this all came from, and why a certain range of versions was arbitrarily disabled. Handlebars have been used for a really long time, so who knows why the reviewer did not just take down the extension in its entirety. My requests for clarification as to why this is happening now have thus far been ignored...

I think we have two (not necessarily mutually exclusive) things we can do regarding Firefox users:
1. Switch to eval-less Handlebars
2. Self-host the Firefox extension

Considering how dysfunctional the review process appears to be, #2 is looking pretty appealing. I think our users are pretty technically capable in general, and would not have a problem making the switch.

**Comment by toasted-nutbread** [comment]
@FooSoft Can you upload the testing release builds here https://github.com/FooSoft/yomichan/releases/tag/20.9.28.0? That will give me some testing files for experimenting with self-hosted releases.

**Comment by FooSoft** [comment]
@toasted-nutbread it should already be available here:
https://chrome.google.com/webstore/detail/yomichan-development-buil/bcknnfebhefllbjhagijobjklocakpdm

Or are you referring to something else?

**Comment by toasted-nutbread** [comment]
I mean by attaching them as files to the release tag:
https://github.com/FooSoft/yomichan/releases/edit/20.9.28.0

> Attach binaries by dropping them here or selecting them.

**Comment by FooSoft** [comment]
Done! I am not actually that saavy when it comes to release management on GitHub, but easy enough :+1:
