### ISSUE TITLE
Is it possible to disable pop ups on mobile when dragging?

### ISSUE THREAD

**Issue by HansKlokkenspel** [FooSoft/yomichan#870]
To scroll on mobile by dragging, you have to find an empty spot on the page where you can drag. This can be an absolute challenge on certain cluttered websites. Is it possible to only activate pop ups by tapping the text? So no activation when you "hold" text.

**Comment by toasted-nutbread** [comment]
This is technically split up into two different parts: disabling touch move scanning and disabling scroll prevention. This should be possible using the new customizable input system which will be available in the next release. The options look like this, with the top box being the default touch options, and the bottom being the settings for the behaviour you are asking for.

![image](https://user-images.githubusercontent.com/11037431/94369020-56300400-00b5-11eb-9b74-d949664507dc.png)

**Comment by HansKlokkenspel** [comment]
Thanks! I'll keep an eye on it.
