### ISSUE TITLE
Using Kenkyusha, Yomichan detects all spaces as "minimally invasive surgery"

### ISSUE THREAD

**Issue by eiennosihaisya** [FooSoft/yomichan#88]
See example:
[https://imgur.com/a/lJPZz](https://imgur.com/a/lJPZz)

I used Yomichan Import to import Kenkyusha (研究社　新和英大辞典　第５版) EPWING. But all spaces seem to be detected as 低侵襲. It's annoying to have Yomichan popup while moving the cursor around an English page. Is this a bug in Yomichan, Yomichan Import, or the EPWING files? Is there a way to manually delete this entry? Thanks!

**Comment by FooSoft** [comment]
Thanks for the report. I just tried importing this dictionary and everything appears to work fine (no false matches for spaces). If you email me at alex@foosoft.net, I can give you a locally converted version, which you can see if it works.

**Comment by guidocella** [comment]
I have the same problem, you can manually delete the space's definitions by removing
`,[" ","","","",0,["低侵襲手術　minimally invasive surgery.\n"],173720,""]`
and
`,[" ","","","",0,["低侵襲治療　minimally invasive treatment.\nていしんしょう【逓信省】 [ローマ字](teishinshō)\n"],173722,""],[" ","","","",0,["◧低侵襲医療　minimally invasive medical treatment.\n"],173723,""]`
from term_bank_18.json in the kenykusha.zip generated by yomichan-import.

**Comment by FooSoft** [comment]
This has been fixed in the latest release of Yomichan-Import.
