### ISSUE TITLE
Alert for IndexError pops up due to weird interaction with CSS scale

### ISSUE THREAD

**Issue by RodericDay** [FooSoft/yomichan#89]
This issue may be just too niche and bizarre and self-inflicted to merit fixing, but I have a little [webapp](https://roderic.ca/apps/jgap/) that I usually zoom into for viewing comfort. If the zoom is set inappropriately, the yomichan widget zooms-in too, but this is fine. 

The problem is that, depending on the cursor motion, sometimes an annoying alert pops up. I narrowed it down to the following setup, with Firefox Nightly and OSX, and I can trigger it consistently.

```
<meta charset="utf-8">

<style>
input {
    display:block;
    transform-origin: 0 0;
}
input:nth-child(2) {
    transform: translateX(100px);
}
input:nth-child(3) {
    transform: scale(2);
}
.yomichan-imposter {
    opacity: 0.5 !important;
}
</style>

<input value="犬か猫か猿か馬か亀か豚か鬼"/>
<input value="犬か猫か猿か馬か亀か豚か鬼"/>
<input value="犬か猫か猿か馬か亀か豚か鬼"/>
```

![screen shot 2017-10-12 at 00 24 53](https://user-images.githubusercontent.com/6867226/31479256-e274227e-aee3-11e7-9578-fd0cd911b680.png)

The alert happens when I interact with the lower border of the input while pressing shift, where I can see Yomichan overlaying its own detector box if I open the DOM inspector panel. The left, top, and right borders seem to be fine.

I would love to fix this myself and thus become a contributor to this project. If you want me to spelunk and fix this, I would be happy too.

**Comment by FooSoft** [comment]
Thanks for the report -- if you want to dive in and figure fix this up, I would appreciate the help! A good place to look is the `docRangeFromPoint` function in `document.js`.

**Comment by RodericDay** [comment]
So, removing the opacity on the imposter, the problem becomes clear.

Under a CSS transformation, it's not overlaid over the original input element like it should be. In fact, under very large scales, there's no overlap whatsoever, and the alert can be triggered reliably.

I'm looking into various ways of ensuring that the offset is correct.

One thing I'm doing very stupidly right now, though, is reloading the code for testing. I just change a file, recreate the zip file, reinstall it in firefox, and test. It's not clear to me (first extension I work on) if I can make the reload automatic somehow.

**Comment by FooSoft** [comment]
@RodericDay sounds like there are two problems then (breaking under transformation and error triggering). There should be some sort of early out somewhere to make sure that the error doesn't trigger under any condition (even after the imposter position is fixed).

As for debugging the extension, there is a much simpler way! Just go to `about:debugging` and use the `Load Temporary Add-on` feature, using the reload feature as necessary.

**Comment by RodericDay** [comment]
Fantastic, much more ergonomic. Thanks!

**Comment by RodericDay** [comment]
I'm trying to fix the alert first. These are the offending lines:

    const range = document.createRange();
    range.setStart(position.offsetNode, position.offset);
    range.setEnd(position.offsetNode, position.offset);

I haven't exhaustively checked, but it seems that under normal circumstances, the `offsetNode` is a Text node (via `constructor.name` which returns `Text`). Under a transform, sometimes the "offsetNode" as determined by `caretPositionFromPoint` is something else, such as `<body>`.

So, a try/catch around those lines, or a more explicit check, would both squelch the error.

**Comment by RodericDay** [comment]
Come think of it, this problem is not restricted to just input boxes / the impostor. Transforming the body element also makes regular text highlighting/scanning break.

**Comment by FooSoft** [comment]
Would it be possible to detect this condition by examining the returned `range` object? I like to think of a `try` / `catch` approach as the nuclear option that you use when there is absolutely no way to detect the specific problem (as it could possibly squelch other legitimate error conditions).

**Comment by RodericDay** [comment]
`position.offsetNode.constructor.name === "Text"`, from my testing, seems like it would work. not sure if there's a better way to "type check"

**Comment by FooSoft** [comment]
The `offsetNode` returned inside of `position` should have a `nodeType` [according to the docs](https://developer.mozilla.org/en-US/docs/Web/API/Node). You should be able to just perform the check as soon as you get the position back:

```
            if (position && position.offsetNode && position.offsetNode.nodeType === 3) { ...
```

Then you should be able to remove the checks in the code below (Chrome never had any issues with this)

```
    const range = document.caretRangeFromPoint(point.x, point.y);
    if (range && range.startContainer.nodeType === 3 && range.endContainer.nodeType === 3) {
        return new TextSourceRange(range);
    }
```

**Comment by FooSoft** [comment]
After the code from the bottom is removed, it would make sense to make sure that #80 continues to remain fixed.

**Comment by RodericDay** [comment]
New update:

I was testing on a different website, and I saw a bug, that I narrowed down and reproduced with

```
<meta charset="utf-8"/>
<textarea style="margin:5px">海　よみちゃん</textarea>
```

The problem here is the `margin` property. It is applied to the textarea, but then, via ` window.getComputedStyle(element);`, it gets applied one extra time when the overlay is being positioned, so it ends up being offset.

I think it's the same family of bug: it's hard to position the impostor.

**Comment by FooSoft** [comment]
Yeah, the whole thing of having to used the impostor is kind of a hack. Not sure if there are any good solutions to making text controls work regardless of style applied to them. Seems to work okay-ish in Chrome?

**Comment by toasted-nutbread** [comment]
Closing since improvements to the imposter element should have resolved these issues. The recent a5d7de8e97400f63c328ccde9b313a127cef0611 also fixed an issue with CSS ```transform``` which was present in the example in the opening post.
