### ISSUE TITLE
{furigana-plain-render-error}

### ISSUE THREAD

**Issue by Shibasaki175** [FooSoft/yomichan#915]
Yomichan, after its update, stopped copying the {furigana-plain} field for Anki.

This problem only occurs with words that contain hiragana together with kanji

![image](https://user-images.githubusercontent.com/72839565/95927965-991cf780-0d96-11eb-9aef-4d1dfa5f8abb.png)

![image](https://user-images.githubusercontent.com/72839565/95927906-6f63d080-0d96-11eb-829c-80398149346e.png)

**Comment by toasted-nutbread** [comment]
Thanks for reporting; I have fixed this with #916. There's another similar issue which was reported today (#914), which I suspect is something else, but I will give some time for a reply. I'll set up a patch release tomorrow; heads up @FooSoft.
