### ISSUE TITLE
{furigana-render-error}

### ISSUE THREAD

**Issue by blackmen2x** [FooSoft/yomichan#917]
This problem came up today when I tried to add new words to my Anki using the Anki integration, especially with words that come with both kanji and kana.
![image](https://user-images.githubusercontent.com/45961624/95977420-130aba80-0e43-11eb-8cee-aee2f4385993.png)

At first I was unaware of the new update and thought it was on my end but upon checking this github there are also people having similar problems so I thought it might be good to report to you as well.

And also old exported setting files don't seem to work on this new version.

**Comment by M-Yori** [comment]
I have the same problem as yours, and even if i downgraded it to a previous version, it still doesn't work.

**Comment by toasted-nutbread** [comment]
The first issue is the same as #915, which has been fixed and will be patched soon. The second issue was a separate issue that has also just been fixed, to be patched soon as well.
