### ISSUE TITLE
[bug] Incorrect furigana distribution

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#94]
The result for 飼い犬 and possibly other words as well shows incorrectly placed furigana:
![2017-10-17_15-24-08](https://user-images.githubusercontent.com/5602483/31664727-51828f7e-b34f-11e7-80bf-55d693e40bee.png)
The correct way would be 飼[か]い犬[いぬ].

Because you can't know which い is the one written without kanji, you will need to use a dictionary like KANJIDIC to decide how the furigana should be distributed. For 飼, there is the kun reading か.う that could be used to rule out 飼[かい]. With the performance concerns mentioned in #82 in mind, maybe the readings could be prefetched from IndexedDB (assuming memory doesn't become an issue) or furigana distribution could be done when the dictionary is imported. Finally, if you can't narrow the possibilities down to 1 (or if everything gets eliminated), the full furigana could be shown as fallback.

**Comment by FooSoft** [comment]
Given the performance and software complexity requirements of doing this correctly for all cases, I would prefer to just fall back to full furigana when there there are multiple possibilities. I'm a big fan of [Worse is Better](https://en.wikipedia.org/wiki/Worse_is_better), for both hobby and professional development, and this falls strictly inline with "it is slightly better to be simple than correct". I'm pretty convinced that even if performance were not an issue, supporting this for all cases would be pretty major feature.

**Comment by siikamiika** [comment]
That's actually a really good compromise. The cases like 飼い犬 are rare (first and only I've noticed) and even using KANJIDIC wouldn't necessarily cover all the cases, although now I'm wondering if there's something in the way how kanji in Japanese words and the current furigana function work that makes it go right most of the time even with many possible ways of doing it.
