### ISSUE TITLE
Select Anki deck without going to options menu

### ISSUE THREAD

**Issue by rogershijin** [FooSoft/yomichan#944]
Anki integration feature is really lifechanging.  I think it would also be nice if users could select the Anki deck they want the next Yomichan card to be sent to quickly.  For example, from the Yomichan button in the browser toolbar or from the hover popup.

**Comment by toasted-nutbread** [comment]
There are some plans to update the UI of the popup to support additional buttons in a non-cluttered manner, this might fit into that design. #402

**Comment by Radmir2015** [comment]
I also wanted to mention it in the previous issue. It would be nice not to go into the settings every time to change the deck.

**Comment by toasted-nutbread** [comment]
A new feature is in progress which allows profile changing from the extension popup menu, which looks like the following:

![image](https://user-images.githubusercontent.com/11037431/99199216-89b11580-276b-11eb-9852-f3a8240723b9.png)

Using this, you could set up multiple profiles to select the target deck for Anki cards. Let me know if that is sufficient for either of your needs.

**Comment by rogershijin** [comment]
Thanks! Might be even better than what I described because would allow different card formatting for different decks too.
