### ISSUE TITLE
Set a negative "Horizontal popup offset" value

### ISSUE THREAD

**Issue by Hiwo21400** [FooSoft/yomichan#959]
It will be nice if we can set a negative value for horizontal popup offset to be like the google traduction popup
![image](https://user-images.githubusercontent.com/35316996/97339320-b8ca1a80-1882-11eb-8558-1c62f506ac44.png)

**Comment by toasted-nutbread** [comment]
I didn't even realize there was a limit for those values. Created #960 to fix.

For a quick workaround, if you are familiar with the ability to "inspect element" in web browsers, you can actually remove the `min="0"` attribute manually.

![image](https://user-images.githubusercontent.com/11037431/97364681-c7143880-187a-11eb-912d-95add97ef8c2.png)
