### ISSUE TITLE
Auto-hide delay doens't seem to be working

### ISSUE THREAD

**Issue by Joel-Hjerten** [FooSoft/yomichan#969]
Coming from Rikaikun, I've disabled shift for scanning on the pages so I only need to hover the mouse over the text, very convenient, but wen I move my mouse away from scanning Japanese text, the Yomichan window stays there on the last scanned text. I always have to click some where on the page or esc to make the popup disappear. I doesn't matter what value I put in to Auto-hide delay. This makes me always go back to Rikaikun after a while as I get tired of clicking way the popup. Is this a bug or by design, if so what does the Auto-hide delay do?

**Comment by toasted-nutbread** [comment]
Do you have the option *Automatically hide results* enabled?

**Comment by Joel-Hjerten** [comment]
I did not, didn't notice it, just thought increasing the Auto-hide delay above zero would be enough. It works as desired now. Thank you!

**Comment by toasted-nutbread** [comment]
I think part of the issue is that it is not clear what some of the options do, as in your case, and in an older issue #120. I'm working on an update to the settings page to make it more clear what the various options do and better organization.
