### ISSUE TITLE
Can't import JMdict

### ISSUE THREAD

**Issue by pockethook** [FooSoft/yomichan#98]
Once I download https://foosoft.net/projects/yomichan/dl/dict/jmdict_english.zip and choose it from Options->Dictionaries->'Choose File' I get following error/warning alerts:

    No dictionaries have been installed
    AbortError: Transaction aborted

**Comment by FooSoft** [comment]
Thanks for reporting the issue. Could you let me know your browser name and version? Do you have any other extensions installed? Could you also check to see that you have sufficient space on your hard drive? This error appears to sometimes come up when you are running low on disk space. If you are using Firefox, I don't believe it will allow extensions to use more than 10% of remaining disk space for persistent storage.

**Comment by pockethook** [comment]
I'm using Chromium 62.0.3202.94. I had a ~2GB(<1%) space left, increasing this to 16GB(3%) solved the problem. Thanks.

**Comment by nicolas-raoul** [comment]
Same problem on Chromium. I have 8.2 GB free.
