### ISSUE TITLE
October 2020 Release

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#980]
https://github.com/FooSoft/yomichan/releases/tag/20.11.1.0

Feature #955/#926 depends on https://github.com/FooSoft/anki-connect/pull/203.

@FooSoft

**Comment by toasted-nutbread** [comment]
Kind of an aside, but I did notice that the latest Firefox release (20.9.28.1) was actually released on AMO properly, despite the previous issues. Hopefully that's a good thing? I'll still plan to add support for automatic updates for testing installations and such, but for now, at least it looks like updates can still go through.

**Comment by FooSoft** [comment]
Halloween release :jack_o_lantern: 

Yeah, I think they just have reviewers that troll through extensions and suspend ones that they don't like for for whatever reason. I have started adding a disclaimer about the use of "eval" in the "notes to reviewer" field, so hopefully this will keep them off our back for the time being.

**Comment by toasted-nutbread** [comment]
If you haven't started the release yet, I'm working through an issue related to displaying pitch accents which I should have finished today. I'll update the tags/branch/etc once that's done, let me know if I need to update the version or anything due to already updating the testing release.

**Comment by toasted-nutbread** [comment]
Looks like the testing release was already pushed, so here's a new version with the fixes.
https://github.com/FooSoft/yomichan/releases/tag/20.11.1.0

**Comment by toasted-nutbread** [comment]
Haven't noticed any blocking issues for the stable release so far since 20.11.1.0.

I did notice that there was an issue with displaying the storage stats on the current settings page, #998, but I would defer that until a patch release (maybe in a week or so) since it's a cosmetic issue. Gives time to gather any other reported issues that require a patch.

**Comment by toasted-nutbread** [comment]
ping @FooSoft

**Comment by FooSoft** [comment]
Ack, been a crazy couple of weeks. Putting up new version now :+1:

**Comment by toasted-nutbread** [comment]
No worries, I don't want to be too naggy so I'm not that worried about a strict schedule.

While I'm at it, if you find some time, could you take a quick look at https://github.com/FooSoft/yomichan/pull/606#issuecomment-723386456? (comment hidden by commit list for some reason; expand if not visible)

**Comment by toasted-nutbread** [comment]
Also a patch release for #1058: [20.11.1.1](https://github.com/FooSoft/yomichan/tree/20.11.1.1)
