### ISSUE TITLE
Capturing Yomichan Conjugation Data For Anki?

### ISSUE THREAD

**Issue by christopherball** [FooSoft/yomichan#983]
Recently set up the full Yomichan Anki integration through Chrome, but one thing I can't seem to find a flashcard "marker" for, as Yomichan refers to them, is for capturing the _conjugation_ data.

Extreme Example: **食べさせられたくなかった**
In Yomichan, before the definitions kick in, it shows a very useful chunk of information as follows: **causative << potential or passive << -tai << adv**

While this conjugation flow doesn't capture all of the example, it helps a tremendous amount for learning / decrypting the presented form. Am I missing something obvious or is this data simply not available for persistence through to Anki?  Can this be put on the list to expose for Anki?

**Comment by toasted-nutbread** [comment]
The data is available for the Handlebars templates, but there is no marker template included by default. I'll look into adding a default marker for this, and paste it here once it's set up so you can configure it yourself.

**Comment by christopherball** [comment]
Awesome - I'll wait for your guidance - cheers.

**Comment by toasted-nutbread** [comment]
If you add the following to the handlebars templates (under the Anki fields when the _Show advanced options_ option is enabled), you should then be able to use the `{conjugation}` marker to get what you want.

```handlebars
{{#*inline "conjugation"}}
    {{~#if definition.reasons~}}
        {{~#each definition.reasons~}}
            {{~#if (op ">" @index 0)}} « {{/if~}}
            {{.}}
        {{~/each~}}
    {{~/if~}}
{{/inline}}
```

**Comment by christopherball** [comment]
Lookin' good with the changes.  Thanks for the quick turnaround - the plugin is highly useful.  Between this and Morphman, studies are golden.

![image](https://user-images.githubusercontent.com/5790394/98192505-002e5780-1ed0-11eb-907f-3a0a85b9d0fc.png)
