### ISSUE TITLE
Hello from LLN

### ISSUE THREAD

**Issue by hobodrifterdavid** [FooSoft/yomichan#989]
Hello,

Not an issue, but a message. I am really impressed by the quality and thoughtfulness of this project. We develop a browser extension for language learning with Netflix (https://chrome.google.com/webstore/detail/language-learning-with-ne/hoombieeljmmljlkjmnheibnpciblicm). I was considering adding support for anki-connect. Anyway, if you'd like to be in contact, please us on LanguageLearningExtension@gmail.com
Also there's this :) :
https://forum.languagelearningwithnetflix.com/t/hey-developers-we-need-help/1668

**Comment by Thermospore** [comment]
+1 for this extension; it's awesome. Thanks!

**Comment by triqster1** [comment]
Advertising your closed source project with paid subscription plan on here is kinda rude imo. You could have just emailed them.
