### ISSUE TITLE
Issues when basic dynamic values are used in field

### ISSUE THREAD

**Issue by kanjieater** [FooSoft/yomichan#992]
Here is my setup:
![image](https://user-images.githubusercontent.com/32607317/98414103-62a66580-2040-11eb-99f8-3095df4929f6.png)

I want to add the word to anki:
![image](https://user-images.githubusercontent.com/32607317/98414234-997c7b80-2040-11eb-8f31-7b41cfbee46d.png)

The green buttons are disabled. If I replace {expression} with static text "something static", the green button does work again. 

Yomichan v20.9.28.1
Latest AnkiConnect

**Comment by toasted-nutbread** [comment]
Does this happen for all terms, including any that you are 100% sure does not exist anywhere in your collection?

Also might be helpful to test the templates, just to make sure nothing is breaking there. On the settings page, enable advanced options, then near the bottom of the Anki options, test the `{expression}` (or other) marker.

![image](https://user-images.githubusercontent.com/11037431/98418102-35fa4a00-2050-11eb-8880-5425987954ed.png)

**Comment by toasted-nutbread** [comment]
Additionally: can you export your settings file and share that here? Sometimes something else in there causes this problem.

**Comment by toasted-nutbread** [comment]
And what version of Anki (not AnkiConnect) are you using? While looking into #993, I noticed an issue that could potentially cause this problem.

**Comment by kanjieater** [comment]
> And what version of Anki (not AnkiConnect) are you using? While looking into #993, I noticed an issue that could potentially cause this problem.

I'm on:
Version 2.1.22 (0ecc189a)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Windows 10





> Does this happen for all terms, including any that you are 100% sure does not exist anywhere in your collection?
> 
> Also might be helpful to test the templates, just to make sure nothing is breaking there. On the settings page, enable advanced options, then near the bottom of the Anki options, test the `{expression}` (or other) marker.
> 
> ![image](https://user-images.githubusercontent.com/11037431/98418102-35fa4a00-2050-11eb-8880-5425987954ed.png)

![image](https://user-images.githubusercontent.com/32607317/98421965-34308680-2050-11eb-8e89-fab1f4719613.png)
It won't generate for me currently when I press play.



> Additionally: can you export your settings file and share that here? Sometimes something else in there causes this problem.


<details>
<summary>Details</summary>

{
    "version": 0,
    "date": "2020-11-06 22:50:59",
    "url": "chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/",
    "manifest": {
        "author": "Alex Yatskov",
        "background": {
            "page": "bg/background.html",
            "persistent": true
        },
        "browser_action": {
            "default_icon": {
                "16": "mixed/img/icon16.png",
                "19": "mixed/img/icon19.png",
                "32": "mixed/img/icon32.png",
                "38": "mixed/img/icon38.png",
                "48": "mixed/img/icon48.png",
                "64": "mixed/img/icon64.png",
                "128": "mixed/img/icon128.png"
            },
            "default_popup": "bg/context.html",
            "default_title": "Yomichan"
        },
        "commands": {
            "search": {
                "description": "Open search window",
                "suggested_key": {
                    "default": "Alt+Insert"
                }
            },
            "toggle": {
                "description": "Toggle text scanning",
                "suggested_key": {
                    "default": "Alt+Delete"
                }
            }
        },
        "content_scripts": [
            {
                "all_frames": true,
                "js": [
                    "mixed/js/core.js",
                    "mixed/js/yomichan.js",
                    "mixed/js/comm.js",
                    "mixed/js/api.js",
                    "mixed/js/dynamic-loader.js",
                    "mixed/js/frame-client.js",
                    "mixed/js/text-scanner.js",
                    "mixed/js/document-util.js",
                    "fg/js/dom-text-scanner.js",
                    "fg/js/popup.js",
                    "fg/js/source.js",
                    "fg/js/popup-factory.js",
                    "fg/js/frame-offset-forwarder.js",
                    "fg/js/popup-proxy.js",
                    "fg/js/popup-window.js",
                    "fg/js/frontend.js",
                    "fg/js/content-script-main.js"
                ],
                "match_about_blank": true,
                "matches": [
                    "http://*/*",
                    "https://*/*",
                    "file://*/*"
                ]
            }
        ],
        "content_security_policy": "script-src 'self'; object-src 'self'",
        "description": "Japanese dictionary with Anki integration",
        "differential_fingerprint": "1.dd1644869c3c607db1254ebb0f204d23976a525d1b33d2ab445ee09e96768fc5",
        "icons": {
            "16": "mixed/img/icon16.png",
            "19": "mixed/img/icon19.png",
            "32": "mixed/img/icon32.png",
            "38": "mixed/img/icon38.png",
            "48": "mixed/img/icon48.png",
            "64": "mixed/img/icon64.png",
            "128": "mixed/img/icon128.png"
        },
        "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAug/0Wtc35jGyy+Jkf4Kt9DUAzvziCJbhwlwzdro0cPnN+2K6Y2rCBVgAJln7SffCKVWa0k6BM3D7m7yydAECgSo8VUn2zUgInXpfQAuI2dG+6OEi0SOu2SkXJFvvAMjM/JAXY0zQRofnxeDRqvT7EtHW9lLwtgLTBuJObuq5zCHAPFa3PZ5ZORvUEmQZ2HDxUxaUZzsFW4kZ/rxPaNXTWe+qM30wqvlk79DBUJVq9zlzsDGM6G5qWcCk3vT5MEGuZVK7IPi6w9dPfOA3myicuywhDxumteg6wFraarMMAR2Stc80Yb9pCZT5Jav9e7eG97DuBAh97IOKrfI6mU8CkwIDAQAB",
        "manifest_version": 2,
        "minimum_chrome_version": "57.0.0.0",
        "name": "Yomichan",
        "optional_permissions": [
            "clipboardRead"
        ],
        "options_ui": {
            "open_in_tab": true,
            "page": "bg/settings.html"
        },
        "permissions": [
            "<all_urls>",
            "storage",
            "clipboardWrite",
            "unlimitedStorage",
            "nativeMessaging",
            "webRequest",
            "webRequestBlocking"
        ],
        "sandbox": {
            "content_security_policy": "sandbox allow-scripts; script-src 'self' 'unsafe-eval'; object-src 'self'",
            "pages": [
                "bg/template-renderer.html"
            ]
        },
        "update_url": "https://clients2.google.com/service/update2/crx",
        "version": "20.9.28.1",
        "web_accessible_resources": [
            "fg/float.html",
            "bg/template-renderer.html"
        ]
    },
    "environment": {
        "browser": "chrome",
        "platform": {
            "os": "win"
        }
    },
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",
    "options": {
        "profiles": [
            {
                "name": "Default",
                "options": {
                    "general": {
                        "enable": true,
                        "enableClipboardPopups": false,
                        "resultOutputMode": "group",
                        "debugInfo": false,
                        "maxResults": 32,
                        "showAdvanced": true,
                        "popupDisplayMode": "default",
                        "popupWidth": 400,
                        "popupHeight": 250,
                        "popupHorizontalOffset": 0,
                        "popupVerticalOffset": 10,
                        "popupHorizontalOffset2": 10,
                        "popupVerticalOffset2": 0,
                        "popupHorizontalTextPosition": "below",
                        "popupVerticalTextPosition": "before",
                        "popupScalingFactor": 1,
                        "popupScaleRelativeToPageZoom": false,
                        "popupScaleRelativeToVisualViewport": true,
                        "showGuide": false,
                        "compactTags": false,
                        "compactGlossaries": false,
                        "mainDictionary": "ヨガ日本語アクセント辞典",
                        "popupTheme": "dark",
                        "popupOuterTheme": "dark",
                        "customPopupCss": "",
                        "customPopupOuterCss": "",
                        "enableWanakana": true,
                        "enableClipboardMonitor": false,
                        "showPitchAccentDownstepNotation": true,
                        "showPitchAccentPositionNotation": true,
                        "showPitchAccentGraph": false,
                        "showIframePopupsInRootFrame": false,
                        "useSecurePopupFrameUrl": true,
                        "usePopupShadowDom": true,
                        "usePopupWindow": false
                    },
                    "audio": {
                        "enabled": true,
                        "sources": [
                            "jpod101"
                        ],
                        "volume": 100,
                        "autoPlay": true,
                        "customSourceUrl": "",
                        "textToSpeechVoice": ""
                    },
                    "scanning": {
                        "touchInputEnabled": true,
                        "selectText": true,
                        "alphanumeric": true,
                        "autoHideResults": false,
                        "delay": 20,
                        "length": 10,
                        "deepDomScan": false,
                        "popupNestingMaxDepth": 2,
                        "enablePopupSearch": false,
                        "enableOnPopupExpressions": false,
                        "enableOnSearchPage": true,
                        "enableSearchTags": false,
                        "layoutAwareScan": false,
                        "hideDelay": 0,
                        "pointerEventsEnabled": false,
                        "preventMiddleMouse": {
                            "onWebPages": false,
                            "onPopupPages": false,
                            "onSearchPages": false,
                            "onSearchQuery": false
                        },
                        "inputs": [
                            {
                                "include": "shift",
                                "exclude": "mouse0",
                                "types": {
                                    "mouse": true,
                                    "touch": false,
                                    "pen": false
                                },
                                "options": {
                                    "showAdvanced": false,
                                    "searchTerms": true,
                                    "searchKanji": true,
                                    "scanOnTouchMove": true,
                                    "scanOnPenHover": true,
                                    "scanOnPenPress": true,
                                    "scanOnPenRelease": false,
                                    "preventTouchScrolling": true
                                }
                            },
                            {
                                "include": "mouse2",
                                "exclude": "",
                                "types": {
                                    "mouse": true,
                                    "touch": false,
                                    "pen": false
                                },
                                "options": {
                                    "showAdvanced": false,
                                    "searchTerms": true,
                                    "searchKanji": true,
                                    "scanOnTouchMove": true,
                                    "scanOnPenHover": true,
                                    "scanOnPenPress": true,
                                    "scanOnPenRelease": false,
                                    "preventTouchScrolling": true
                                }
                            },
                            {
                                "include": "",
                                "exclude": "",
                                "types": {
                                    "mouse": false,
                                    "touch": true,
                                    "pen": true
                                },
                                "options": {
                                    "showAdvanced": false,
                                    "searchTerms": true,
                                    "searchKanji": true,
                                    "scanOnTouchMove": true,
                                    "scanOnPenHover": true,
                                    "scanOnPenPress": true,
                                    "scanOnPenRelease": false,
                                    "preventTouchScrolling": true
                                }
                            }
                        ]
                    },
                    "translation": {
                        "convertHalfWidthCharacters": "false",
                        "convertNumericCharacters": "false",
                        "convertAlphabeticCharacters": "false",
                        "convertHiraganaToKatakana": "false",
                        "convertKatakanaToHiragana": "variant",
                        "collapseEmphaticSequences": "false"
                    },
                    "dictionaries": {
                        "ヨガ日本語アクセント辞典": {
                            "priority": 1,
                            "enabled": true,
                            "allowSecondarySearches": false
                        },
                        "JMdict (English)": {
                            "priority": 0,
                            "enabled": true,
                            "allowSecondarySearches": false
                        },
                        "JMnedict": {
                            "priority": 0,
                            "enabled": true,
                            "allowSecondarySearches": false
                        },
                        "KANJIDIC (English)": {
                            "priority": 0,
                            "enabled": true,
                            "allowSecondarySearches": false
                        },
                        "新明解国語辞典 第五版": {
                            "priority": 2,
                            "enabled": true,
                            "allowSecondarySearches": false
                        },
                        "三省堂　スーパー大辞林": {
                            "priority": 3,
                            "enabled": true,
                            "allowSecondarySearches": false
                        },
                        "大辞泉": {
                            "priority": 1,
                            "enabled": true,
                            "allowSecondarySearches": false
                        }
                    },
                    "parsing": {
                        "enableScanningParser": true,
                        "enableMecabParser": false,
                        "selectedParser": "scan",
                        "termSpacing": true,
                        "readingMode": "hiragana"
                    },
                    "anki": {
                        "enable": true,
                        "server": "http://127.0.0.1:8765",
                        "tags": [
                            "yc"
                        ],
                        "sentenceExt": 200,
                        "screenshot": {
                            "format": "jpeg",
                            "quality": 92
                        },
                        "terms": {
                            "deck": "!優先::2 自分::ヨミちゃん",
                            "model": "MIA Japanese",
                            "fields": {
                                "Expression": "{expression}",
                                "Meaning": "",
                                "Audio": "",
                                "Audio on Front": ""
                            }
                        },
                        "kanji": {
                            "deck": "",
                            "model": "",
                            "fields": {}
                        },
                        "duplicateScope": "deck"
                    },
                    "version": 14
                },
                "conditionGroups": []
            }
        ],
        "profileCurrent": 0,
        "version": 4,
        "global": {
            "database": {
                "prefixWildcardsSupported": false
            }
        }
    }
}

</details>

**Comment by kanjieater** [comment]
It looks like the issue was on my end. My template was blank, so I reset it, and now it generates on play, and the popup shows green buttons.
