### ISSUE TITLE
Account for TB-sized drives.

### ISSUE THREAD

**Issue by trueFragment** [FooSoft/yomichan#997]
My Yomichan settings page states that `Yomichan is using approximately 125.9MB of 1.9undefined.` I have a terabyte sized hard drive, so I looked into it and saw that `TB` wasn't in the `_bytesToLabeledString(size)` array that tracks size constants. This method is located under `ext/bg/js/settings/storage-controller.js`.

I would appreciate it you updated it, would be a very simple one-line fix. Thanks for Yomichan and your continued work!

**Comment by trueFragment** [comment]
There appears to be different behavior on Firefox 82.0.2, as it incorrectly reports the `GB` constant.  Could it involve different underlying implementations of `navigator.storage` between the browsers? 

The array constant is being downshifted by one due to a seeming one-off error, and erroneously reports as `GB` (3 in the array). However, it should return a null value similar to Chrome's behavior according to how `_storageEstimate` is implemented.

**Comment by toasted-nutbread** [comment]
Firefox and Chrome have radically different implementations for how much available storage space they report, so that part is expected. Created a PR to fix the label issue.
